Analysis Software: genfit::HMatrixU Class Reference
genfit::HMatrixU Class Reference
AbsHMatrix implementation for one-dimensional MeasurementOnPlane and RKTrackRep parameterization.
#include <GenFit/blob/master/measurements/include/HMatrixU.h>
Public Member Functions
HMatrixU ()
const TMatrixD & getMatrix () const override
Get the actual matrix representation.
TVectorD Hv (const TVectorD &v) const override
H*v.
TMatrixD MHt (const TMatrixDSym &M) const override
M*H^t.
TMatrixD MHt (const TMatrixD &M) const override
void HMHt (TMatrixDSym &M) const override
similarity: H*M*H^t
virtual HMatrixU * clone () const override
virtual bool isEqual (const AbsHMatrix &other) const override
virtual void Print (const Option_t *="") const override
Public Member Functions inherited from genfit::AbsHMatrix
AbsHMatrix ()
virtual ~AbsHMatrix ()
bool operator== (const AbsHMatrix &other) const
bool operator!= (const AbsHMatrix &other) const
Additional Inherited Members
Protected Member Functions inherited from genfit::AbsHMatrix
AbsHMatrix (const AbsHMatrix &o)
AbsHMatrix & operator= (const AbsHMatrix &)
Detailed Description
AbsHMatrix implementation for one-dimensional MeasurementOnPlane and RKTrackRep parameterization.
This projects out u. H = (0, 0, 0, 1, 0)
Definition at line 37 of file HMatrixU.h.
View newest version in sPHENIX GitHub at line 37 of file HMatrixU.h
Constructor & Destructor Documentation
genfit::HMatrixU::HMatrixU () inline
Definition at line 41 of file HMatrixU.h.
View newest version in sPHENIX GitHub at line 41 of file HMatrixU.h
Referenced by clone().
Member Function Documentation
virtual HMatrixU* genfit::HMatrixU::clone () const inline override virtual
Implements genfit::AbsHMatrix.
Definition at line 52 of file HMatrixU.h.
View newest version in sPHENIX GitHub at line 52 of file HMatrixU.h
References HMatrixU().
const TMatrixD & genfit::HMatrixU::getMatrix () const override virtual
Get the actual matrix representation.
Implements genfit::AbsHMatrix.
Definition at line 33 of file HMatrixU.cc.
View newest version in sPHENIX GitHub at line 33 of file HMatrixU.cc
Referenced by genfit::GblFitterInfo::constructGblPoint().
void genfit::HMatrixU::HMHt (TMatrixDSym & M) const override virtual
similarity: H*M*H^t
Reimplemented from genfit::AbsHMatrix.
Definition at line 81 of file HMatrixU.cc.
View newest version in sPHENIX GitHub at line 81 of file HMatrixU.cc
References assert.
TVectorD genfit::HMatrixU::Hv (const TVectorD & v) const override virtual
H*v.
Reimplemented from genfit::AbsHMatrix.
Definition at line 42 of file HMatrixU.cc.
View newest version in sPHENIX GitHub at line 42 of file HMatrixU.cc
References assert, and v.
virtual bool genfit::HMatrixU::isEqual (const AbsHMatrix & other) const inline override virtual
Implements genfit::AbsHMatrix.
Definition at line 54 of file HMatrixU.h.
View newest version in sPHENIX GitHub at line 54 of file HMatrixU.h
TMatrixD genfit::HMatrixU::MHt (const TMatrixDSym & M) const override virtual
M*H^t.
Reimplemented from genfit::AbsHMatrix.
Definition at line 53 of file HMatrixU.cc.
View newest version in sPHENIX GitHub at line 53 of file HMatrixU.cc
References assert, and i.
TMatrixD genfit::HMatrixU::MHt (const TMatrixD & M) const override virtual
Reimplemented from genfit::AbsHMatrix.
Definition at line 67 of file HMatrixU.cc.
View newest version in sPHENIX GitHub at line 67 of file HMatrixU.cc
References assert, and i.
void genfit::HMatrixU::Print (const Option_t * = "") const override virtual
Reimplemented from genfit::AbsHMatrix.
Definition at line 90 of file HMatrixU.cc.
View newest version in sPHENIX GitHub at line 90 of file HMatrixU.cc
References genfit::printOut.
The documentation for this class was generated from the following files:
GenFit/blob/master/measurements/include/HMatrixU.h
GenFit/blob/master/measurements/src/HMatrixU.cc