Analysis Software: genfit::StateOnPlane Class Reference
genfit::StateOnPlane Class Reference
A state with arbitrary dimension defined in a DetPlane.
#include <GenFit/blob/master/core/include/StateOnPlane.h>
Public Member Functions
StateOnPlane (const AbsTrackRep *rep=nullptr)
StateOnPlane (const TVectorD &state, const SharedPlanePtr &plane, const AbsTrackRep *rep)
state is defined by the TrackReps parameterization
StateOnPlane (const TVectorD &state, const SharedPlanePtr &plane, const AbsTrackRep *rep, const TVectorD &auxInfo)
StateOnPlane & operator= (StateOnPlane other)
void swap (StateOnPlane &other)
virtual ~StateOnPlane ()
virtual StateOnPlane * clone () const
const TVectorD & getState () const
TVectorD & getState ()
const TVectorD & getAuxInfo () const
TVectorD & getAuxInfo ()
const SharedPlanePtr & getPlane () const
const AbsTrackRep * getRep () const
void setState (const TVectorD &state)
void setPlane (const SharedPlanePtr &plane)
void setStatePlane (const TVectorD &state, const SharedPlanePtr &plane)
void setAuxInfo (const TVectorD &auxInfo)
void setRep (const AbsTrackRep *rep)
double extrapolateToPlane (const SharedPlanePtr &plane, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToLine (const TVector3 &linePoint, const TVector3 &lineDirection, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToPoint (const TVector3 &point, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToPoint (const TVector3 &point, const TMatrixDSym &G, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToCylinder (double radius, const TVector3 &linePoint=TVector3(0., 0., 0.), const TVector3 &lineDirection=TVector3(0., 0., 1.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToCone (double openingAngle, const TVector3 &conePoint=TVector3(0., 0., 0.), const TVector3 &coneDirection=TVector3(0., 0., 1.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToSphere (double radius, const TVector3 &point=TVector3(0., 0., 0.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateBy (double step, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToMeasurement (const AbsMeasurement *measurement, bool stopAtBoundary=false, bool calcJacobianNoise=false)
TVector3 getPos () const
TVector3 getMom () const
TVector3 getDir () const
void getPosMom (TVector3 &pos, TVector3 &mom) const
void getPosDir (TVector3 &pos, TVector3 &dir) const
TVectorD get6DState () const
double getMomMag () const
int getPDG () const
double getCharge () const
double getQop () const
double getMass () const
double getTime () const
void setPosMom (const TVector3 &pos, const TVector3 &mom)
void setPosMom (const TVectorD &state6)
void setChargeSign (double charge)
void setQop (double qop)
void setTime (double time)
virtual void Print (Option_t *option="") const
Protected Attributes
TVectorD state_
TVectorD auxInfo_
SharedPlanePtr sharedPlane_
Private Attributes
const AbsTrackRep * rep_
Shared ownership. '!' in order to silence ROOT, custom streamer writes and reads this.
Detailed Description
A state with arbitrary dimension defined in a DetPlane.
The dimension and meaning of the state_ vector are defined by the track parameterization of the rep_. sharedPlane_ is a shared_pointer, the ownership over that plane is shared between all StateOnPlane objects defined in that plane. The definition of the state is bound to the TrackRep rep_. Therefore, the StateOnPlane contains a pointer to a AbsTrackRep. It will provide functionality to extrapolate it and translate the state it into cartesian coordinates. Shortcuts to all functions of the AbsTrackRep which use this StateOnPlane are also provided here.
Definition at line 47 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 47 of file StateOnPlane.h
Constructor & Destructor Documentation
genfit::StateOnPlane::StateOnPlane (const AbsTrackRep * rep = nullptr) inline
Definition at line 155 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 155 of file StateOnPlane.h
References genfit::AbsTrackRep::getDim(), and state_.
Referenced by clone().
genfit::StateOnPlane::StateOnPlane (const TVectorD & state, const SharedPlanePtr & plane, const AbsTrackRep * rep) inline
state is defined by the TrackReps parameterization
Definition at line 163 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 163 of file StateOnPlane.h
References assert, and sharedPlane_.
genfit::StateOnPlane::StateOnPlane (const TVectorD & state, const SharedPlanePtr & plane, const AbsTrackRep * rep, const TVectorD & auxInfo) inline
Definition at line 170 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 170 of file StateOnPlane.h
References assert, and sharedPlane_.
virtual genfit::StateOnPlane::~StateOnPlane () inline virtual
Definition at line 60 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 60 of file StateOnPlane.h
Member Function Documentation
virtual StateOnPlane* genfit::StateOnPlane::clone () const inline virtual
Reimplemented in genfit::MeasuredStateOnPlane.
Definition at line 61 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 61 of file StateOnPlane.h
References StateOnPlane().
double genfit::StateOnPlane::extrapolateBy (double step, bool stopAtBoundary = false, bool calcJacobianNoise = false) inline
Definition at line 105 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 105 of file StateOnPlane.h
References genfit::AbsTrackRep::extrapolateBy(), and rep_.
Referenced by genfit::EventDisplay::drawEvent().
double genfit::StateOnPlane::extrapolateToCone (double openingAngle, const TVector3 & conePoint = TVector3(0.,0.,0.), const TVector3 & coneDirection = TVector3(0.,0.,1.), bool stopAtBoundary = false, bool calcJacobianNoise = false) inline
Definition at line 96 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 96 of file StateOnPlane.h
References genfit::AbsTrackRep::extrapolateToCone(), and rep_.
double genfit::StateOnPlane::extrapolateToCylinder (double radius, const TVector3 & linePoint = TVector3(0.,0.,0.), const TVector3 & lineDirection = TVector3(0.,0.,1.), bool stopAtBoundary = false, bool calcJacobianNoise = false) inline
Definition at line 91 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 91 of file StateOnPlane.h
References genfit::AbsTrackRep::extrapolateToCylinder(), and rep_.
double genfit::StateOnPlane::extrapolateToLine (const TVector3 & linePoint, const TVector3 & lineDirection, bool stopAtBoundary = false, bool calcJacobianNoise = false) inline
Definition at line 80 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 80 of file StateOnPlane.h
References genfit::AbsTrackRep::extrapolateToLine(), and rep_.
double genfit::StateOnPlane::extrapolateToMeasurement (const AbsMeasurement * measurement, bool stopAtBoundary = false, bool calcJacobianNoise = false) inline
Definition at line 108 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 108 of file StateOnPlane.h
References genfit::AbsTrackRep::extrapolateToMeasurement(), and rep_.
double genfit::StateOnPlane::extrapolateToPlane (const SharedPlanePtr & plane, bool stopAtBoundary = false, bool calcJacobianNoise = false) inline
Definition at line 77 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 77 of file StateOnPlane.h
References genfit::AbsTrackRep::extrapolateToPlane(), and rep_.
Referenced by genfit::GblFitter::constructGblInfo(), and genfit::GblFitter::sortHits().
double genfit::StateOnPlane::extrapolateToPoint (const TVector3 & point, bool stopAtBoundary = false, bool calcJacobianNoise = false) inline
Definition at line 84 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 84 of file StateOnPlane.h
References genfit::AbsTrackRep::extrapolateToPoint(), and rep_.
Referenced by genfit::SpacepointMeasurement::constructPlane(), PHGenFitTrkFitter::MakeSvtxTrack(), and TpcPrototypeGenFitTrkFitter::MakeSvtxTrack().
double genfit::StateOnPlane::extrapolateToPoint (const TVector3 & point, const TMatrixDSym & G, bool stopAtBoundary = false, bool calcJacobianNoise = false) inline
Definition at line 87 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 87 of file StateOnPlane.h
References genfit::AbsTrackRep::extrapolateToPoint(), and rep_.
double genfit::StateOnPlane::extrapolateToSphere (double radius, const TVector3 & point = TVector3(0.,0.,0.), bool stopAtBoundary = false, bool calcJacobianNoise = false) inline
Definition at line 101 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 101 of file StateOnPlane.h
References genfit::AbsTrackRep::extrapolateToSphere(), and rep_.
TVectorD genfit::StateOnPlane::get6DState () const inline
Definition at line 118 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 118 of file StateOnPlane.h
References genfit::AbsTrackRep::get6DState(), and rep_.
Referenced by genfit::Track::udpateSeed().
const TVectorD& genfit::StateOnPlane::getAuxInfo () const inline
Definition at line 65 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 65 of file StateOnPlane.h
References auxInfo_.
Referenced by genfit::calcAverageState(), genfit::RKTrackRep::extrapolateBy(), genfit::RKTrackRep::extrapolateToCone(), genfit::RKTrackRep::extrapolateToCylinder(), genfit::RKTrackRep::extrapolateToLine(), genfit::RKTrackRep::extrapolateToSphere(), genfit::RKTrackRep::extrapToPoint(), genfit::RKTrackRep::getSpu(), genfit::RKTrackRep::getTime(), genfit::RKTrackRep::initArrays(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitter::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::GblFitterInfo::recalculateJacobian(), genfit::RKTrackRep::setPosMom(), genfit::GblFitterInfo::setReferenceState(), genfit::RKTrackRep::setSpu(), genfit::RKTrackRep::setTime(), and PHGenFit::Track::updateOneMeasurementKalman().
TVectorD& genfit::StateOnPlane::getAuxInfo () inline
Definition at line 66 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 66 of file StateOnPlane.h
References auxInfo_.
double genfit::StateOnPlane::getCharge () const inline
Definition at line 121 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 121 of file StateOnPlane.h
References genfit::AbsTrackRep::getCharge(), and rep_.
Referenced by genfit::EventDisplay::drawEvent(), genfit::GblFitter::processTrackWithRep(), and genfit::Track::udpateSeed().
TVector3 genfit::StateOnPlane::getDir () const inline
Definition at line 115 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 115 of file StateOnPlane.h
References genfit::AbsTrackRep::getDir(), and rep_.
Referenced by genfit::GblFitterInfo::constructGblPoint().
double genfit::StateOnPlane::getMass () const inline
Definition at line 123 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 123 of file StateOnPlane.h
References genfit::AbsTrackRep::getMass(), and rep_.
TVector3 genfit::StateOnPlane::getMom () const inline
Definition at line 114 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 114 of file StateOnPlane.h
References genfit::AbsTrackRep::getMom(), and rep_.
Referenced by PHGenFit::Track::get_mom(), main(), PHG4TrackFastSim::MakeSvtxTrack(), and PHGenFitTrkProp::OutputPHGenFitTrack().
double genfit::StateOnPlane::getMomMag () const inline
Definition at line 119 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 119 of file StateOnPlane.h
References genfit::AbsTrackRep::getMomMag(), and rep_.
int genfit::StateOnPlane::getPDG () const inline
Definition at line 120 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 120 of file StateOnPlane.h
References genfit::AbsTrackRep::getPDG(), and rep_.
const SharedPlanePtr& genfit::StateOnPlane::getPlane () const inline
Definition at line 67 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 67 of file StateOnPlane.h
References sharedPlane_.
Referenced by genfit::KalmanFitterInfo::addMeasurementOnPlane(), genfit::calcAverageState(), genfit::RKTrackRep::checkCache(), checkErrorPropagation(), checkExtrapolateBy(), checkExtrapolateToCylinder(), checkExtrapolateToLine(), checkExtrapolateToPoint(), checkExtrapolateToSphere(), checkSetGetPosMom(), checkStopAtBoundary(), genfit::GblFitter::constructGblInfo(), genfit::GblFitterInfo::constructGblPoint(), genfit::FullMeasurement::constructMeasurementsOnPlane(), genfit::PlanarMeasurement::constructMeasurementsOnPlane(), genfit::WirePointMeasurement::constructMeasurementsOnPlane(), genfit::SpacepointMeasurement::constructMeasurementsOnPlane(), genfit::WireMeasurement::constructMeasurementsOnPlane(), genfit::WireMeasurementNew::constructMeasurementsOnPlane(), genfit::SpacepointMeasurement::constructPlane(), genfit::EventDisplay::drawEvent(), genfit::RKTrackRep::extrapolateBy(), genfit::RKTrackRep::extrapolateToCone(), genfit::RKTrackRep::extrapolateToCylinder(), genfit::RKTrackRep::extrapolateToLine(), genfit::RKTrackRep::extrapolateToPlane(), genfit::RKTrackRep::extrapolateToSphere(), genfit::RKTrackRep::extrapToPoint(), genfit::KalmanFitterInfo::getResidual(), genfit::RKTrackRep::getState5(), genfit::RKTrackRep::getState7(), genfit::Track::getTrackLen(), main(), genfit::EventDisplay::makeLines(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::RKTrackRep::setPosMom(), genfit::RKTrackRep::setPosMomErr(), genfit::RKTrackRep::transformM6P(), genfit::RKTrackRep::transformPM6(), and genfit::GblFitterInfo::updateMeasurementAndPlane().
TVector3 genfit::StateOnPlane::getPos () const inline
Definition at line 113 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 113 of file StateOnPlane.h
References genfit::AbsTrackRep::getPos(), and rep_.
Referenced by checkExtrapolateBy(), genfit::GblFitter::constructGblInfo(), genfit::EventDisplay::drawEvent(), GenFitTrackProp::fill_tree(), PHG4TrackFastSim::MakeSvtxTrack(), PHGenFitTrkProp::OutputPHGenFitTrack(), and PHGenFitTrkProp::TrackPropPatRec().
void genfit::StateOnPlane::getPosDir (TVector3 & pos, TVector3 & dir) const inline
Definition at line 117 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 117 of file StateOnPlane.h
References genfit::AbsTrackRep::getPosDir(), and rep_.
void genfit::StateOnPlane::getPosMom (TVector3 & pos, TVector3 & mom) const inline
Definition at line 116 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 116 of file StateOnPlane.h
References genfit::AbsTrackRep::getPosMom(), and rep_.
double genfit::StateOnPlane::getQop () const inline
Definition at line 122 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 122 of file StateOnPlane.h
References genfit::AbsTrackRep::getQop(), and rep_.
const AbsTrackRep* genfit::StateOnPlane::getRep () const inline
Definition at line 68 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 68 of file StateOnPlane.h
References rep_.
Referenced by genfit::calcAverageState(), genfit::RKTrackRep::checkCache(), genfit::FullMeasurement::constructMeasurementsOnPlane(), genfit::PlanarMeasurement::constructMeasurementsOnPlane(), genfit::WirePointMeasurement::constructMeasurementsOnPlane(), genfit::SpacepointMeasurement::constructMeasurementsOnPlane(), genfit::WireMeasurement::constructMeasurementsOnPlane(), genfit::WireMeasurementNew::constructMeasurementsOnPlane(), genfit::ProlateSpacepointMeasurement::constructPlane(), genfit::WirePointMeasurement::constructPlane(), genfit::WireMeasurement::constructPlane(), genfit::WireMeasurementNew::constructPlane(), genfit::FullMeasurement::FullMeasurement(), genfit::MeasuredStateOnPlane::get6DCov(), genfit::MeasuredStateOnPlane::get6DStateCov(), genfit::MeasuredStateOnPlane::getMomVar(), genfit::MeasuredStateOnPlane::getPosMomCov(), genfit::KalmanFitterInfo::getResidual(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::MeasuredStateOnPlane::Print(), Print(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::RKTrackRep::setPosMom(), genfit::MeasuredStateOnPlane::setPosMomCov(), and genfit::MeasuredStateOnPlane::setPosMomErr().
const TVectorD& genfit::StateOnPlane::getState () const inline
Definition at line 63 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 63 of file StateOnPlane.h
References state_.
Referenced by genfit::calcAverageState(), genfit::AbsTrackRep::calcJacobianNumerically(), genfit::DAF::calcWeights(), genfit::RKTrackRep::checkCache(), compareForthBackJacNoise(), genfit::GblFitterInfo::constructGblPoint(), genfit::WirePointMeasurement::constructMeasurementsOnPlane(), genfit::SpacepointMeasurement::constructMeasurementsOnPlane(), genfit::EventDisplay::drawEvent(), genfit::KalmanFitterInfo::getAvgWeightedMeasurementOnPlane(), genfit::RKTrackRep::getBackwardJacobianAndNoise(), genfit::RKTrackRep::getCharge(), genfit::KalmanFitterInfo::getClosestMeasurementOnPlane(), genfit::RKTrackRep::getForwardJacobianAndNoise(), genfit::RKTrackRep::getMomMag(), genfit::RKTrackRep::getMomVar(), genfit::RKTrackRep::getQop(), genfit::KalmanFitterInfo::getResidual(), genfit::KalmanFitterInfo::getSmoothedChi2(), genfit::RKTrackRep::getState5(), genfit::RKTrackRep::getState7(), main(), PHG4TrackFastSim::MakeSvtxTrack(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::GblFitterInfo::Print(), genfit::KalmanFitter::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::GFGbl::processTrackWithRep(), genfit::GblFitterInfo::recalculateJacobian(), genfit::KalmanFitterRefTrack::removeOutdated(), genfit::RKTrackRep::setChargeSign(), genfit::RKTrackRep::setPosMom(), genfit::RKTrackRep::setQop(), genfit::GblFitterInfo::setReferenceState(), genfit::TEST_F(), genfit::RKTrackRep::transformPM6(), and PHGenFit::Track::updateOneMeasurementKalman().
TVectorD& genfit::StateOnPlane::getState () inline
Definition at line 64 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 64 of file StateOnPlane.h
References state_.
double genfit::StateOnPlane::getTime () const inline
Definition at line 124 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 124 of file StateOnPlane.h
References genfit::AbsTrackRep::getTime(), and rep_.
Referenced by genfit::Track::udpateSeed().
StateOnPlane & genfit::StateOnPlane::operator= (StateOnPlane other) inline
Definition at line 177 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 177 of file StateOnPlane.h
References swap().
void genfit::StateOnPlane::Print (Option_t * option = "") const virtual
Reimplemented in genfit::ReferenceStateOnPlane, genfit::MeasuredStateOnPlane, and genfit::MeasurementOnPlane.
Definition at line 30 of file StateOnPlane.cc.
View newest version in sPHENIX GitHub at line 30 of file StateOnPlane.cc
References genfit::AbsTrackRep::getPosMom(), getRep(), pos, genfit::printOut, sharedPlane_, and state_.
Referenced by checkExtrapolateBy(), checkExtrapolateToCylinder(), checkExtrapolateToLine(), checkExtrapolateToPoint(), checkExtrapolateToSphere(), checkSetGetPosMom(), checkStopAtBoundary(), compareForthBackExtrapolation(), and genfit::ReferenceStateOnPlane::Print().
void genfit::StateOnPlane::setAuxInfo (const TVectorD & auxInfo) inline
Definition at line 73 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 73 of file StateOnPlane.h
References auxInfo_.
Referenced by genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), and PHGenFit::Track::updateOneMeasurementKalman().
void genfit::StateOnPlane::setChargeSign (double charge) inline
Definition at line 128 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 128 of file StateOnPlane.h
References rep_, and genfit::AbsTrackRep::setChargeSign().
void genfit::StateOnPlane::setPlane (const SharedPlanePtr & plane) inline
Definition at line 71 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 71 of file StateOnPlane.h
References sharedPlane_.
Referenced by genfit::RKTrackRep::extrapolateBy(), genfit::RKTrackRep::extrapolateToCone(), genfit::RKTrackRep::extrapolateToCylinder(), genfit::RKTrackRep::extrapolateToLine(), genfit::RKTrackRep::extrapolateToPlane(), genfit::RKTrackRep::extrapolateToSphere(), genfit::RKTrackRep::extrapToPoint(), and genfit::RKTrackRep::setPosMom().
void genfit::StateOnPlane::setPosMom (const TVector3 & pos, const TVector3 & mom) inline
Definition at line 126 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 126 of file StateOnPlane.h
References rep_, and genfit::AbsTrackRep::setPosMom().
void genfit::StateOnPlane::setPosMom (const TVectorD & state6) inline
Definition at line 127 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 127 of file StateOnPlane.h
References rep_, and genfit::AbsTrackRep::setPosMom().
void genfit::StateOnPlane::setQop (double qop) inline
Definition at line 129 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 129 of file StateOnPlane.h
References rep_, and genfit::AbsTrackRep::setQop().
void genfit::StateOnPlane::setRep (const AbsTrackRep * rep) inline
Definition at line 74 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 74 of file StateOnPlane.h
References rep_.
Referenced by PHGenFit::extrapolateToCylinder(), and genfit::KalmanFitterRefTrack::prepareTrack().
void genfit::StateOnPlane::setState (const TVectorD & state) inline
Definition at line 70 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 70 of file StateOnPlane.h
References state_.
Referenced by genfit::calcAverageState(), and genfit::MeasuredStateOnPlane::setStateCov().
void genfit::StateOnPlane::setStatePlane (const TVectorD & state, const SharedPlanePtr & plane) inline
Definition at line 72 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 72 of file StateOnPlane.h
References sharedPlane_, and state_.
Referenced by genfit::RKTrackRep::checkCache(), and genfit::MeasuredStateOnPlane::setStateCovPlane().
void genfit::StateOnPlane::setTime (double time) inline
Definition at line 130 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 130 of file StateOnPlane.h
References rep_, and genfit::AbsTrackRep::setTime().
void genfit::StateOnPlane::swap (StateOnPlane & other) inline
Definition at line 182 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 182 of file StateOnPlane.h
References auxInfo_, rep_, sharedPlane_, state_, and boost::swap().
Referenced by operator=(), genfit::MeasuredStateOnPlane::swap(), and genfit::ReferenceStateOnPlane::swap().
Member Data Documentation
TVectorD genfit::StateOnPlane::auxInfo_ protected
Definition at line 138 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 138 of file StateOnPlane.h
Referenced by getAuxInfo(), setAuxInfo(), and swap().
const AbsTrackRep* genfit::StateOnPlane::rep_ private
Shared ownership. '!' in order to silence ROOT, custom streamer writes and reads this.
Pointer to TrackRep with respect to which StateOnPlane is defined
Definition at line 145 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 145 of file StateOnPlane.h
Referenced by extrapolateBy(), extrapolateToCone(), extrapolateToCylinder(), extrapolateToLine(), extrapolateToMeasurement(), extrapolateToPlane(), extrapolateToPoint(), extrapolateToSphere(), get6DState(), getCharge(), getDir(), getMass(), getMom(), getMomMag(), getPDG(), getPos(), getPosDir(), getPosMom(), getQop(), getRep(), getTime(), setChargeSign(), setPosMom(), setQop(), setRep(), setTime(), and swap().
SharedPlanePtr genfit::StateOnPlane::sharedPlane_ protected
Definition at line 139 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 139 of file StateOnPlane.h
Referenced by getPlane(), genfit::MeasurementOnPlane::Print(), genfit::MeasuredStateOnPlane::Print(), Print(), setPlane(), setStatePlane(), StateOnPlane(), and swap().
TVectorD genfit::StateOnPlane::state_ protected
Definition at line 137 of file StateOnPlane.h.
View newest version in sPHENIX GitHub at line 137 of file StateOnPlane.h
Referenced by getState(), genfit::MeasurementOnPlane::Print(), genfit::MeasuredStateOnPlane::Print(), Print(), setState(), setStatePlane(), StateOnPlane(), and swap().
The documentation for this class was generated from the following files:
GenFit/blob/master/core/include/StateOnPlane.h
GenFit/blob/master/core/src/StateOnPlane.cc