Analysis Software: genfit::RKMatrix< nRows, nCols > Struct Template Reference
genfit::RKMatrix< nRows, nCols > Struct Template Reference
#include <GenFit/blob/master/trackReps/include/RKTools.h>
Public Member Functions
double & operator() (size_t iRow, size_t iCol)
double & operator[] (size_t n)
const double & operator[] (size_t n) const
double * begin ()
double * end ()
const double * begin () const
const double * end () const
RKMatrix< nRows, nCols > & operator= (const RKMatrix< nRows, nCols > &o)
void print ()
Public Attributes
double vals [nRows *nCols]
Detailed Description
template<size_t nRows, size_t nCols>
struct genfit::RKMatrix< nRows, nCols >
Definition at line 33 of file RKTools.h.
View newest version in sPHENIX GitHub at line 33 of file RKTools.h
Member Function Documentation
template<size_t nRows, size_t nCols> double* genfit::RKMatrix< nRows, nCols >::begin () inline
Definition at line 45 of file RKTools.h.
View newest version in sPHENIX GitHub at line 45 of file RKTools.h
Referenced by genfit::RKTrackRep::calcJ_Mp_7x5(), genfit::RKTrackRep::calcJ_pM_5x7(), genfit::RKTrackRep::Extrap(), genfit::ExtrapStep::ExtrapStep(), genfit::RKTrackRep::initArrays(), genfit::MaterialEffects::noiseCoulomb(), genfit::RKMatrix< 7, 7 >::operator=(), genfit::RKStep::RKStep(), genfit::RKTrackRep::RKutta(), genfit::RKTrackRep::transformM6P(), and genfit::RKTrackRep::transformPM6().
template<size_t nRows, size_t nCols> const double* genfit::RKMatrix< nRows, nCols >::begin () const inline
Definition at line 47 of file RKTools.h.
View newest version in sPHENIX GitHub at line 47 of file RKTools.h
template<size_t nRows, size_t nCols> double* genfit::RKMatrix< nRows, nCols >::end () inline
Definition at line 46 of file RKTools.h.
View newest version in sPHENIX GitHub at line 46 of file RKTools.h
Referenced by genfit::RKTrackRep::calcJ_Mp_7x5(), genfit::RKTrackRep::calcJ_pM_5x7(), genfit::ExtrapStep::ExtrapStep(), genfit::RKTrackRep::initArrays(), genfit::MaterialEffects::noiseCoulomb(), genfit::RKMatrix< 7, 7 >::operator=(), genfit::RKStep::RKStep(), genfit::RKTrackRep::transformM6P(), and genfit::RKTrackRep::transformPM6().
template<size_t nRows, size_t nCols> const double* genfit::RKMatrix< nRows, nCols >::end () const inline
Definition at line 48 of file RKTools.h.
View newest version in sPHENIX GitHub at line 48 of file RKTools.h
template<size_t nRows, size_t nCols> double& genfit::RKMatrix< nRows, nCols >::operator() (size_t iRow, size_t iCol) inline
Definition at line 36 of file RKTools.h.
View newest version in sPHENIX GitHub at line 36 of file RKTools.h
template<size_t nRows, size_t nCols> RKMatrix<nRows, nCols>& genfit::RKMatrix< nRows, nCols >::operator= (const RKMatrix< nRows, nCols > & o) inline
Definition at line 49 of file RKTools.h.
View newest version in sPHENIX GitHub at line 49 of file RKTools.h
template<size_t nRows, size_t nCols> double& genfit::RKMatrix< nRows, nCols >::operator[] (size_t n) inline
Definition at line 39 of file RKTools.h.
View newest version in sPHENIX GitHub at line 39 of file RKTools.h
template<size_t nRows, size_t nCols> const double& genfit::RKMatrix< nRows, nCols >::operator[] (size_t n) const inline
Definition at line 42 of file RKTools.h.
View newest version in sPHENIX GitHub at line 42 of file RKTools.h
template<size_t nRows, size_t nCols> void genfit::RKMatrix< nRows, nCols >::print () inline
Definition at line 89 of file RKTools.h.
View newest version in sPHENIX GitHub at line 89 of file RKTools.h
References genfit::RKTools::printDim().
Member Data Documentation
template<size_t nRows, size_t nCols> double genfit::RKMatrix< nRows, nCols >::vals[nRows *nCols]
Definition at line 34 of file RKTools.h.
View newest version in sPHENIX GitHub at line 34 of file RKTools.h
Referenced by genfit::RKMatrix< 7, 7 >::begin(), genfit::RKMatrix< 7, 7 >::end(), genfit::RKMatrix< 7, 7 >::operator()(), genfit::RKMatrix< 7, 7 >::operator[](), and genfit::TEST_F().
The documentation for this struct was generated from the following file:
GenFit/blob/master/trackReps/include/RKTools.h