Analysis Software: genfit::GFRaveVertex Class Reference
genfit::GFRaveVertex Class Reference
GFRaveVertex class.
#include <GenFit/blob/master/GFRave/include/GFRaveVertex.h>
Public Member Functions
GFRaveVertex ()
GFRaveVertex (const TVector3 &pos, const TMatrixDSym &cov, const std::vector< genfit::GFRaveTrackParameters * > &smoothedTracks, double ndf, double chi2, int id=-1)
GFRaveVertex (const GFRaveVertex &)
GFRaveVertex & operator= (GFRaveVertex)
void swap (GFRaveVertex &)
~GFRaveVertex ()
TVector3 getPos () const
get Position
TMatrixDSym getCov () const
get 3x3 covariance (error) of position.
double getNdf () const
double getChi2 () const
unsigned int getNTracks () const
Number of tracks the vertex is made of.
GFRaveTrackParameters * getParameters (unsigned int i) const
int getId () const
void Print (const Option_t *="") const
Private Attributes
TVector3 pos_
TMatrixDSym cov_
double ndf_
double chi2_
int id_
std::vector
< genfit::GFRaveTrackParameters * > smoothedTracks_
Detailed Description
GFRaveVertex class.
A Vertex contains information about its position and covariance. The tracks the vertex is consisting of are stored in smoothedTracks_. These GFRaveTrackParameters contain the weight of the corresponding track in the vertex, smoothed track parameters and a pointer to the original unaltered genfit::Track.
Definition at line 48 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 48 of file GFRaveVertex.h
Constructor & Destructor Documentation
genfit::GFRaveVertex::GFRaveVertex ()
Definition at line 35 of file GFRaveVertex.cc.
View newest version in sPHENIX GitHub at line 35 of file GFRaveVertex.cc
genfit::GFRaveVertex::GFRaveVertex (const TVector3 & pos, const TMatrixDSym & cov, const std::vector< genfit::GFRaveTrackParameters * > & smoothedTracks, double ndf, double chi2, int id = -1)
Definition at line 47 of file GFRaveVertex.cc.
View newest version in sPHENIX GitHub at line 47 of file GFRaveVertex.cc
References cov_.
genfit::GFRaveVertex::GFRaveVertex (const GFRaveVertex & vertex)
Definition at line 68 of file GFRaveVertex.cc.
View newest version in sPHENIX GitHub at line 68 of file GFRaveVertex.cc
References i, and smoothedTracks_.
genfit::GFRaveVertex::~GFRaveVertex ()
Definition at line 105 of file GFRaveVertex.cc.
View newest version in sPHENIX GitHub at line 105 of file GFRaveVertex.cc
References i, and smoothedTracks_.
Member Function Documentation
double genfit::GFRaveVertex::getChi2 () const inline
Definition at line 73 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 73 of file GFRaveVertex.h
References chi2_.
Referenced by RecoConversionEval::correctSecondaryVertex(), Conversion::correctSecondaryVertex(), PHGenFitTrkFitter::FillSvtxVertexMap(), TpcPrototypeGenFitTrkFitter::FillSvtxVertexMap(), SVReco::GFRVVtxToSvtxVertex(), VtxTest::numUnique(), Print(), VtxTest::process_event(), VtxTest::processBackground(), TruthConversionEval::processTrackBackground(), and TruthConversionEval::recordConversion().
TMatrixDSym genfit::GFRaveVertex::getCov () const inline
get 3x3 covariance (error) of position.
Definition at line 70 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 70 of file GFRaveVertex.h
References cov_.
Referenced by RecoConversionEval::correctSecondaryVertex(), Conversion::correctSecondaryVertex(), PHGenFitTrkFitter::FillSvtxVertexMap(), TpcPrototypeGenFitTrkFitter::FillSvtxVertexMap(), BDiJetModule::FillVertexMap(), SVReco::GFRVVtxToSvtxVertex(), SVReco::MakeGenFitTrack(), Print(), and BDiJetModule::process_event().
int genfit::GFRaveVertex::getId () const inline
Definition at line 79 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 79 of file GFRaveVertex.h
References id_.
Referenced by RecoConversionEval::correctSecondaryVertex(), Conversion::correctSecondaryVertex(), and Print().
double genfit::GFRaveVertex::getNdf () const inline
Definition at line 72 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 72 of file GFRaveVertex.h
References ndf_.
Referenced by RecoConversionEval::correctSecondaryVertex(), Conversion::correctSecondaryVertex(), PHGenFitTrkFitter::FillSvtxVertexMap(), TpcPrototypeGenFitTrkFitter::FillSvtxVertexMap(), SVReco::GFRVVtxToSvtxVertex(), and Print().
unsigned int genfit::GFRaveVertex::getNTracks () const inline
Number of tracks the vertex is made of.
Definition at line 76 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 76 of file GFRaveVertex.h
References smoothedTracks_.
Referenced by RecoConversionEval::correctSecondaryVertex(), Conversion::correctSecondaryVertex(), PHGenFitTrkFitter::FillSvtxVertexMap(), TpcPrototypeGenFitTrkFitter::FillSvtxVertexMap(), BDiJetModule::FillVertexMap(), SVReco::FillVertexMap(), BDiJetModule::GetSVMass_mom(), SVReco::GetSVMass_mom(), SVReco::GFRVVtxToSvtxVertex(), main(), SVReco::MakeGenFitTrack(), Print(), and BDiJetModule::process_event().
GFRaveTrackParameters* genfit::GFRaveVertex::getParameters (unsigned int i) const inline
Definition at line 77 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 77 of file GFRaveVertex.h
References i, and smoothedTracks_.
Referenced by RecoConversionEval::correctSecondaryVertex(), Conversion::correctSecondaryVertex(), PHGenFitTrkFitter::FillSvtxVertexMap(), TpcPrototypeGenFitTrkFitter::FillSvtxVertexMap(), SVReco::FillVertexMap(), BDiJetModule::GetSVMass_mom(), SVReco::GetSVMass_mom(), SVReco::GFRVVtxToSvtxVertex(), main(), and Print().
TVector3 genfit::GFRaveVertex::getPos () const inline
get Position
Definition at line 67 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 67 of file GFRaveVertex.h
References pos_.
Referenced by RecoConversionEval::correctSecondaryVertex(), Conversion::correctSecondaryVertex(), PHGenFitTrkFitter::FillSvtxVertexMap(), TpcPrototypeGenFitTrkFitter::FillSvtxVertexMap(), BDiJetModule::FillVertexMap(), SVReco::GFRVVtxToSvtxVertex(), SVReco::MakeGenFitTrack(), VtxTest::numUnique(), Print(), VtxTest::process_event(), BDiJetModule::process_event(), VtxTest::processBackground(), TruthConversionEval::processTrackBackground(), TruthConversionEval::recordConversion(), VtxRegressor::regress(), and RecoConversionEval::vtxCuts().
GFRaveVertex & genfit::GFRaveVertex::operator= (GFRaveVertex other)
Definition at line 88 of file GFRaveVertex.cc.
View newest version in sPHENIX GitHub at line 88 of file GFRaveVertex.cc
References swap().
void genfit::GFRaveVertex::Print (const Option_t * = "") const
Definition at line 118 of file GFRaveVertex.cc.
View newest version in sPHENIX GitHub at line 118 of file GFRaveVertex.cc
References getChi2(), getCov(), getId(), getNdf(), getNTracks(), getParameters(), getPos(), i, and genfit::GFRaveTrackParameters::Print().
Referenced by Conversion::printTruth().
void genfit::GFRaveVertex::swap (GFRaveVertex & other)
Definition at line 94 of file GFRaveVertex.cc.
View newest version in sPHENIX GitHub at line 94 of file GFRaveVertex.cc
References chi2_, cov_, id_, ndf_, pos_, smoothedTracks_, and boost::swap().
Referenced by operator=().
Member Data Documentation
double genfit::GFRaveVertex::chi2_ private
Definition at line 89 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 89 of file GFRaveVertex.h
Referenced by getChi2(), and swap().
TMatrixDSym genfit::GFRaveVertex::cov_ private
Definition at line 87 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 87 of file GFRaveVertex.h
Referenced by getCov(), GFRaveVertex(), and swap().
int genfit::GFRaveVertex::id_ private
Definition at line 90 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 90 of file GFRaveVertex.h
Referenced by getId(), and swap().
double genfit::GFRaveVertex::ndf_ private
Definition at line 88 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 88 of file GFRaveVertex.h
Referenced by getNdf(), and swap().
TVector3 genfit::GFRaveVertex::pos_ private
Definition at line 86 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 86 of file GFRaveVertex.h
Referenced by getPos(), and swap().
std::vector< genfit::GFRaveTrackParameters* > genfit::GFRaveVertex::smoothedTracks_ private
Definition at line 92 of file GFRaveVertex.h.
View newest version in sPHENIX GitHub at line 92 of file GFRaveVertex.h
Referenced by getNTracks(), getParameters(), GFRaveVertex(), swap(), and ~GFRaveVertex().
The documentation for this class was generated from the following files:
GenFit/blob/master/GFRave/include/GFRaveVertex.h
GenFit/blob/master/GFRave/src/GFRaveVertex.cc