Analysis Software: GPUTPCBaseTrackParam Class Reference
GPUTPCBaseTrackParam Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/GPUTPCBaseTrackParam.h>
Public Member Functions
float X () const
float Y () const
float Z () const
float SinPhi () const
float DzDs () const
float QPt () const
float ZOffset () const
float GetX () const
float GetY () const
float GetZ () const
float GetSinPhi () const
float GetDzDs () const
float GetQPt () const
float GetZOffset () const
float GetKappa (float Bz) const
const float * Par () const
const float * GetPar () const
float GetPar (int i) const
void SetPar (int i, float v)
void SetX (float v)
void SetY (float v)
void SetZ (float v)
void SetSinPhi (float v)
void SetDzDs (float v)
void SetQPt (float v)
void SetZOffset (float v)
Private Attributes
float mX
float mZOffset
float mP [5]
Detailed Description
GPUTPCBaseTrackParam class contains track parameters used in output of the GPUTPCTracker slice tracker. This class is used for transfer between tracker and merger and does not contain the covariance matrice
Definition at line 28 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 28 of file GPUTPCBaseTrackParam.h
Member Function Documentation
float GPUTPCBaseTrackParam::DzDs () const inline
Definition at line 35 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 35 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::DzDs().
float GPUTPCBaseTrackParam::GetDzDs () const inline
Definition at line 43 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 43 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::GetDzDs().
float GPUTPCBaseTrackParam::GetKappa (float Bz) const inline
Definition at line 47 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 47 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::GetKappa().
const float* GPUTPCBaseTrackParam::GetPar () const inline
Definition at line 50 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 50 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::GetPar().
float GPUTPCBaseTrackParam::GetPar (int i) const inline
Definition at line 51 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 51 of file GPUTPCBaseTrackParam.h
References mP.
float GPUTPCBaseTrackParam::GetQPt () const inline
Definition at line 44 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 44 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::GetQPt().
float GPUTPCBaseTrackParam::GetSinPhi () const inline
Definition at line 42 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 42 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::GetSinPhi().
float GPUTPCBaseTrackParam::GetX () const inline
Definition at line 39 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 39 of file GPUTPCBaseTrackParam.h
References mX.
Referenced by GPUTPCTrackParam::GetX().
float GPUTPCBaseTrackParam::GetY () const inline
Definition at line 40 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 40 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::GetY().
float GPUTPCBaseTrackParam::GetZ () const inline
Definition at line 41 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 41 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::GetZ().
float GPUTPCBaseTrackParam::GetZOffset () const inline
Definition at line 45 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 45 of file GPUTPCBaseTrackParam.h
References mZOffset.
const float* GPUTPCBaseTrackParam::Par () const inline
Definition at line 49 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 49 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::Par().
float GPUTPCBaseTrackParam::QPt () const inline
Definition at line 36 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 36 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::QPt().
void GPUTPCBaseTrackParam::SetDzDs (float v) inline
Definition at line 59 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 59 of file GPUTPCBaseTrackParam.h
References mP, and v.
Referenced by GPUTPCTrackParam::SetDzDs().
void GPUTPCBaseTrackParam::SetPar (int i, float v) inline
Definition at line 53 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 53 of file GPUTPCBaseTrackParam.h
References i, mP, and v.
Referenced by GPUTPCTrackParam::SetPar().
void GPUTPCBaseTrackParam::SetQPt (float v) inline
Definition at line 60 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 60 of file GPUTPCBaseTrackParam.h
References mP, and v.
Referenced by GPUTPCTrackParam::SetQPt().
void GPUTPCBaseTrackParam::SetSinPhi (float v) inline
Definition at line 58 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 58 of file GPUTPCBaseTrackParam.h
References mP, and v.
Referenced by GPUTPCTrackParam::SetSinPhi().
void GPUTPCBaseTrackParam::SetX (float v) inline
Definition at line 55 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 55 of file GPUTPCBaseTrackParam.h
References mX, and v.
Referenced by GPUTPCTrackParam::SetX().
void GPUTPCBaseTrackParam::SetY (float v) inline
Definition at line 56 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 56 of file GPUTPCBaseTrackParam.h
References mP, and v.
Referenced by GPUTPCTrackParam::SetY().
void GPUTPCBaseTrackParam::SetZ (float v) inline
Definition at line 57 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 57 of file GPUTPCBaseTrackParam.h
References mP, and v.
Referenced by GPUTPCTrackParam::SetZ().
void GPUTPCBaseTrackParam::SetZOffset (float v) inline
Definition at line 61 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 61 of file GPUTPCBaseTrackParam.h
References mZOffset, and v.
Referenced by GPUTPCTrackParam::SetZOffset().
float GPUTPCBaseTrackParam::SinPhi () const inline
Definition at line 34 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 34 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::SinPhi().
float GPUTPCBaseTrackParam::X () const inline
Definition at line 31 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 31 of file GPUTPCBaseTrackParam.h
References mX.
Referenced by GPUTPCTrackParam::X().
float GPUTPCBaseTrackParam::Y () const inline
Definition at line 32 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 32 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::Y().
float GPUTPCBaseTrackParam::Z () const inline
Definition at line 33 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 33 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::Z().
float GPUTPCBaseTrackParam::ZOffset () const inline
Definition at line 37 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 37 of file GPUTPCBaseTrackParam.h
References mZOffset.
Referenced by GPUTPCTrackParam::ZOffset().
Member Data Documentation
float GPUTPCBaseTrackParam::mP[5] private
Definition at line 69 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 69 of file GPUTPCBaseTrackParam.h
Referenced by DzDs(), GetDzDs(), GetKappa(), GetPar(), GetQPt(), GetSinPhi(), GetY(), GetZ(), Par(), QPt(), SetDzDs(), SetPar(), SetQPt(), SetSinPhi(), SetY(), SetZ(), SinPhi(), Y(), and Z().
float GPUTPCBaseTrackParam::mX private
Definition at line 67 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 67 of file GPUTPCBaseTrackParam.h
Referenced by GetX(), SetX(), and X().
float GPUTPCBaseTrackParam::mZOffset private
Definition at line 68 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 68 of file GPUTPCBaseTrackParam.h
Referenced by GetZOffset(), SetZOffset(), and ZOffset().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackreco/GPUTPCBaseTrackParam.h