Analysis Software: genfit::MeasurementCreator Class Reference
genfit::MeasurementCreator Class Reference
Create different measurement types along a HelixTrackModel for testing purposes.
#include <GenFit/blob/master/utilities/include/MeasurementCreator.h>
Public Member Functions
MeasurementCreator ()
~MeasurementCreator ()
void setTrackModel (const HelixTrackModel *model)
Takes ownership!
void setResolution (double resolution)
void setResolutionWire (double resolutionWire)
void setOutlierProb (double outlierProb)
void setOutlierRange (double outlierRange)
void setThetaDetPlane (double thetaDetPlane)
void setPhiDetPlane (double phiDetPlane)
void setWireDir (const TVector3 wireDir)
void setMinDrift (double minDrift)
void setMaxDrift (double maxDrift)
void setIdealLRResolution (bool idealLRResolution)
void setUseSkew (bool useSkew)
void setSkewAngle (double skewAngle)
void setNSuperLayer (int nSuperLayer)
void setDebug (bool debug)
std::vector
< genfit::AbsMeasurement * > create (eMeasurementType, double tracklength, bool &outlier, int &lr)
std::vector
< genfit::AbsMeasurement * > create (eMeasurementType type, double tracklength)
void reset ()
Private Attributes
const HelixTrackModel * trackModel_
double resolution_
double resolutionWire_
double outlierProb_
double outlierRange_
double thetaDetPlane_
double phiDetPlane_
int wireCounter_
TVector3 wireDir_
double minDrift_
double maxDrift_
bool idealLRResolution_
bool useSkew_
double skewAngle_
int nSuperLayer_
int measurementCounter_
bool debug_
Detailed Description
Create different measurement types along a HelixTrackModel for testing purposes.
Definition at line 57 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 57 of file MeasurementCreator.h
Constructor & Destructor Documentation
genfit::MeasurementCreator::MeasurementCreator ()
Definition at line 38 of file MeasurementCreator.cc.
View newest version in sPHENIX GitHub at line 38 of file MeasurementCreator.cc
genfit::MeasurementCreator::~MeasurementCreator () inline
Definition at line 65 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 65 of file MeasurementCreator.h
References trackModel_.
Member Function Documentation
std::vector< genfit::AbsMeasurement * > genfit::MeasurementCreator::create (eMeasurementType type, double tracklength, bool & outlier, int & lr)
Definition at line 61 of file MeasurementCreator.cc.
View newest version in sPHENIX GitHub at line 61 of file MeasurementCreator.cc
References debug_, double(), genfit::HelixTrackModel::getPosDir(), idealLRResolution_, maxDrift_, measurementCounter_, minDrift_, nSuperLayer_, outlierProb_, outlierRange_, phiDetPlane_, genfit::Pixel, genfit::ProlateSpacepoint, resolution_, resolutionWire_, skewAngle_, genfit::Spacepoint, genfit::StripU, genfit::StripUV, genfit::StripV, thetaDetPlane_, trackModel_, useSkew_, genfit::Wire, wireCounter_, wireDir_, genfit::WirePoint, TauVsDIS_MachineLearning_Differentiation::X, x, TauVsDIS_MachineLearning_Differentiation::Y, SVM_v1::Z, and z.
Referenced by create(), and main().
std::vector<genfit::AbsMeasurement*> genfit::MeasurementCreator::create (eMeasurementType type, double tracklength) inline
Definition at line 86 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 86 of file MeasurementCreator.h
References create().
void genfit::MeasurementCreator::reset ()
Definition at line 339 of file MeasurementCreator.cc.
View newest version in sPHENIX GitHub at line 339 of file MeasurementCreator.cc
References measurementCounter_, and wireCounter_.
void genfit::MeasurementCreator::setDebug (bool debug) inline
Definition at line 82 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 82 of file MeasurementCreator.h
References debug_.
Referenced by main().
void genfit::MeasurementCreator::setIdealLRResolution (bool idealLRResolution) inline
Definition at line 78 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 78 of file MeasurementCreator.h
References idealLRResolution_.
Referenced by main().
void genfit::MeasurementCreator::setMaxDrift (double maxDrift) inline
Definition at line 77 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 77 of file MeasurementCreator.h
References maxDrift_.
Referenced by main().
void genfit::MeasurementCreator::setMinDrift (double minDrift) inline
Definition at line 76 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 76 of file MeasurementCreator.h
References minDrift_.
Referenced by main().
void genfit::MeasurementCreator::setNSuperLayer (int nSuperLayer) inline
Definition at line 81 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 81 of file MeasurementCreator.h
References nSuperLayer_.
Referenced by main().
void genfit::MeasurementCreator::setOutlierProb (double outlierProb) inline
Definition at line 71 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 71 of file MeasurementCreator.h
References outlierProb_.
Referenced by main().
void genfit::MeasurementCreator::setOutlierRange (double outlierRange) inline
Definition at line 72 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 72 of file MeasurementCreator.h
References outlierRange_.
Referenced by main().
void genfit::MeasurementCreator::setPhiDetPlane (double phiDetPlane) inline
Definition at line 74 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 74 of file MeasurementCreator.h
References phiDetPlane_.
Referenced by main().
void genfit::MeasurementCreator::setResolution (double resolution) inline
Definition at line 69 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 69 of file MeasurementCreator.h
References resolution_.
Referenced by main().
void genfit::MeasurementCreator::setResolutionWire (double resolutionWire) inline
Definition at line 70 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 70 of file MeasurementCreator.h
References resolutionWire_.
Referenced by main().
void genfit::MeasurementCreator::setSkewAngle (double skewAngle) inline
Definition at line 80 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 80 of file MeasurementCreator.h
References skewAngle_.
Referenced by main().
void genfit::MeasurementCreator::setThetaDetPlane (double thetaDetPlane) inline
Definition at line 73 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 73 of file MeasurementCreator.h
References thetaDetPlane_.
Referenced by main().
void genfit::MeasurementCreator::setTrackModel (const HelixTrackModel * model) inline
Takes ownership!
Definition at line 68 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 68 of file MeasurementCreator.h
References trackModel_.
Referenced by main().
void genfit::MeasurementCreator::setUseSkew (bool useSkew) inline
Definition at line 79 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 79 of file MeasurementCreator.h
References useSkew_.
Referenced by main().
void genfit::MeasurementCreator::setWireDir (const TVector3 wireDir) inline
Definition at line 75 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 75 of file MeasurementCreator.h
References wireDir_.
Referenced by main().
Member Data Documentation
bool genfit::MeasurementCreator::debug_ private
Definition at line 120 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 120 of file MeasurementCreator.h
Referenced by create(), and setDebug().
bool genfit::MeasurementCreator::idealLRResolution_ private
Definition at line 113 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 113 of file MeasurementCreator.h
Referenced by create(), and setIdealLRResolution().
double genfit::MeasurementCreator::maxDrift_ private
Definition at line 112 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 112 of file MeasurementCreator.h
Referenced by create(), and setMaxDrift().
int genfit::MeasurementCreator::measurementCounter_ private
Definition at line 119 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 119 of file MeasurementCreator.h
Referenced by create(), and reset().
double genfit::MeasurementCreator::minDrift_ private
Definition at line 111 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 111 of file MeasurementCreator.h
Referenced by create(), and setMinDrift().
int genfit::MeasurementCreator::nSuperLayer_ private
Definition at line 116 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 116 of file MeasurementCreator.h
Referenced by create(), and setNSuperLayer().
double genfit::MeasurementCreator::outlierProb_ private
Definition at line 101 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 101 of file MeasurementCreator.h
Referenced by create(), and setOutlierProb().
double genfit::MeasurementCreator::outlierRange_ private
Definition at line 102 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 102 of file MeasurementCreator.h
Referenced by create(), and setOutlierRange().
double genfit::MeasurementCreator::phiDetPlane_ private
Definition at line 106 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 106 of file MeasurementCreator.h
Referenced by create(), and setPhiDetPlane().
double genfit::MeasurementCreator::resolution_ private
Definition at line 98 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 98 of file MeasurementCreator.h
Referenced by create(), and setResolution().
double genfit::MeasurementCreator::resolutionWire_ private
Definition at line 99 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 99 of file MeasurementCreator.h
Referenced by create(), and setResolutionWire().
double genfit::MeasurementCreator::skewAngle_ private
Definition at line 115 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 115 of file MeasurementCreator.h
Referenced by create(), and setSkewAngle().
double genfit::MeasurementCreator::thetaDetPlane_ private
Definition at line 105 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 105 of file MeasurementCreator.h
Referenced by create(), and setThetaDetPlane().
const HelixTrackModel* genfit::MeasurementCreator::trackModel_ private
Definition at line 96 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 96 of file MeasurementCreator.h
Referenced by create(), setTrackModel(), and ~MeasurementCreator().
bool genfit::MeasurementCreator::useSkew_ private
Definition at line 114 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 114 of file MeasurementCreator.h
Referenced by create(), and setUseSkew().
int genfit::MeasurementCreator::wireCounter_ private
Definition at line 109 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 109 of file MeasurementCreator.h
Referenced by create(), and reset().
TVector3 genfit::MeasurementCreator::wireDir_ private
Definition at line 110 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 110 of file MeasurementCreator.h
Referenced by create(), and setWireDir().
The documentation for this class was generated from the following files:
GenFit/blob/master/utilities/include/MeasurementCreator.h
GenFit/blob/master/utilities/src/MeasurementCreator.cc