Analysis Software: KFParticle Class Reference
KFParticle Class Reference
The main scalar class of KF Particle package, describes particle objects.
#include <KFParticle/blob/master/KFParticle/KFParticle.h>
Public Member Functions
KFParticle ()
~KFParticle ()
KFParticle (const KFParticle &d1, const KFParticle &d2)
KFParticle (const KFParticle &d1, const KFParticle &d2, const KFParticle &d3)
KFParticle (const KFParticle &d1, const KFParticle &d2, const KFParticle &d3, const KFParticle &d4)
void Create (const float Param[], const float Cov[], Int_t Charge, float mass)
void Create (const Double_t Param[], const Double_t Cov[], Int_t Charge, float mass)
KFParticle (const KFPTrack &track, const int PID)
KFParticle (const KFPVertex &vertex)
void Initialize ()
float GetX () const
Retruns X coordinate of the particle, fP[0].
float GetY () const
Retruns Y coordinate of the particle, fP[1].
float GetZ () const
Retruns Z coordinate of the particle, fP[2].
float GetPx () const
Retruns X component of the momentum, fP[3].
float GetPy () const
Retruns Y component of the momentum, fP[4].
float GetPz () const
Retruns Z component of the momentum, fP[5].
float GetE () const
Returns energy of the particle, fP[6].
float GetS () const
Returns dS=l/p, l - decay length, fP[7], defined if production vertex is set.
char GetQ () const
Returns charge of the particle.
float GetChi2 () const
Returns Chi2 of the fit.
Int_t GetNDF () const
Returns number of decrease of freedom.
Bool_t GetAtProductionVertex () const
Returns a flag which shows if the particle is located at the production point.
void SetAtProductionVertex (Bool_t b)
Set a flag that particle is at the production point.
const float & X () const
Retruns X coordinate of the particle, fP[0].
const float & Y () const
Retruns Y coordinate of the particle, fP[1].
const float & Z () const
Retruns Z coordinate of the particle, fP[2].
const float & Px () const
Retruns X component of the momentum, fP[3].
const float & Py () const
Retruns Y component of the momentum, fP[4].
const float & Pz () const
Retruns Z component of the momentum, fP[5].
const float & E () const
Returns energy of the particle, fP[6].
const float & S () const
Returns dS=l/p, l - decay length, fP[7], defined if production vertex is set.
const char & Q () const
Returns charge of the particle.
const float & Chi2 () const
Returns Chi2 of the fit.
const Int_t & NDF () const
Returns number of decrease of freedom.
float GetParameter (int i) const
Returns P[i] parameter.
float GetCovariance (int i) const
Returns C[i] element of the covariance matrix in the lower triangular form.
float GetCovariance (int i, int j) const
Returns C[i,j] element of the covariance matrix.
float GetP () const
Returns momentum.
float GetPt () const
Returns transverse momentum.
float GetEta () const
Returns pseudorapidity.
float GetPhi () const
Returns the azimuthal angle phi.
float GetMomentum () const
Returns momentum.
float GetMass () const
Returns mass.
float GetDecayLength () const
Returns decay length.
float GetDecayLengthXY () const
Returns decay length in XY.
float GetLifeTime () const
Returns life time ctau [cm].
float GetR () const
Returns distance to the origin of the coordinate system {0,0,0}.
float GetErrX () const
Returns the error of X of current position.
float GetErrY () const
Returns the error of Y of current position.
float GetErrZ () const
Returns the error of Z of current position.
float GetErrPx () const
Returns the error of X-compoment of the particle momentum.
float GetErrPy () const
Returns the error of Y-compoment of the particle momentum.
float GetErrPz () const
Returns the error of Z-compoment of the particle momentum.
float GetErrE () const
Returns the error of energy.
float GetErrS () const
Returns the error of decay length / momentum.
float GetErrP () const
Returns the error of momentum.
float GetErrPt () const
Returns the error of transverse momentum.
float GetErrEta () const
Returns the error of pseudorapidity.
float GetErrPhi () const
Returns the error of the azimuthal angle phi.
float GetErrMomentum () const
Returns the error of momentum.
float GetErrMass () const
Returns the error of mass.
float GetErrDecayLength () const
Returns the error of decay length.
float GetErrDecayLengthXY () const
Returns the error of decay length in XY.
float GetErrLifeTime () const
Returns the error of life time.
float GetErrR () const
Returns the error of distance to the origin of the coordinate system {0,0,0}.
int GetP (float &P, float &SigmaP) const
int GetPt (float &Pt, float &SigmaPt) const
int GetEta (float &Eta, float &SigmaEta) const
int GetPhi (float &Phi, float &SigmaPhi) const
int GetMomentum (float &P, float &SigmaP) const
int GetMass (float &M, float &SigmaM) const
int GetDecayLength (float &L, float &SigmaL) const
int GetDecayLengthXY (float &L, float &SigmaL) const
int GetLifeTime (float &T, float &SigmaT) const
int GetR (float &R, float &SigmaR) const
float GetRapidity () const
Returns rapidity of the particle.
float GetTheta () const
Returns the polar angle in RZ.
float & X ()
Modifier of X coordinate of the particle, fP[0].
float & Y ()
Modifier of Y coordinate of the particle, fP[1].
float & Z ()
Modifier of Z coordinate of the particle, fP[2].
float & Px ()
Modifier of X component of the momentum, fP[3].
float & Py ()
Modifier of Y component of the momentum, fP[4].
float & Pz ()
Modifier of Z component of the momentum, fP[5].
float & E ()
Modifier of energy of the particle, fP[6].
float & S ()
Modifier of dS=l/p, l - decay length, fP[7], defined if production vertex is set.
char & Q ()
Modifier of charge of the particle.
float & Chi2 ()
Modifier of Chi2 of the fit.
Int_t & NDF ()
Modifier of number of decrease of freedom.
float & Parameter (int i)
Modifier of P[i] parameter.
float & Covariance (int i)
Modifier of C[i] element of the covariance matrix in the lower triangular form.
float & Covariance (int i, int j)
Modifier of C[i,j] element of the covariance matrix.
float * Parameters ()
Returns pointer to the parameters fP.
float * CovarianceMatrix ()
Returns pointer to the covariance matrix fC.
void AddDaughter (const KFParticle &Daughter)
void operator+= (const KFParticle &Daughter)
void Construct (const KFParticle *vDaughters[], int nDaughters, const KFParticle *ProdVtx=0, float Mass=-1)
void TransportToPoint (const float xyz[])
void TransportToParticle (const KFParticle &p)
float GetDStoPoint (const float xyz[3], float dsdr[6]) const
void GetDStoParticle (const KFParticleBase &p, float dS[2], float dsdr[4][6]) const
Bool_t GetDistanceFromVertexXY (const float vtx[], float &val, float &err) const
Bool_t GetDistanceFromVertexXY (const float vtx[], const float Cv[], float &val, float &err) const
Bool_t GetDistanceFromVertexXY (const KFParticle &Vtx, float &val, float &err) const
float GetDistanceFromVertexXY (const float vtx[]) const
float GetDistanceFromVertexXY (const KFParticle &Vtx) const
float GetDistanceFromParticleXY (const KFParticle &p) const
float GetDeviationFromVertexXY (const float v[], const float Cv[]=0) const
float GetDeviationFromVertexXY (const KFParticle &Vtx) const
float GetDeviationFromParticleXY (const KFParticle &p) const
void GetParametersAtPoint (const float *point, const float *pointCov, float *m, float *mV)
float GetAngle (const KFParticle &p) const
float GetAngleXY (const KFParticle &p) const
float GetAngleRZ (const KFParticle &p) const
float GetPseudoProperDecayTime (const KFParticle &primVertex, const float &mass, float *timeErr2=0) const
void GetFieldValue (const float xyz[], float B[]) const
void Transport (float dS, const float *dsdr, float P[], float C[], float *dsdr1=0, float *F=0, float *F1=0) const
Public Member Functions inherited from KFParticleBase
float GetDStoPointLine (const float xyz[3], float dsdr[6]) const
float GetDStoPointBz (float B, const float xyz[3], float dsdr[6], const float *param=0) const
float GetDStoPointBy (float By, const float xyz[3], float dsdr[6]) const
float GetDStoPointB (const float *B, const float xyz[3], float dsdr[6]) const
float GetDStoPointCBM (const float xyz[3], float dsdr[6]) const
void GetDStoParticleLine (const KFParticleBase &p, float dS[2], float dsdr[4][6]) const
void GetDStoParticleBz (float Bz, const KFParticleBase &p, float dS[2], float dsdr[4][6], const float *param1=0, const float *param2=0) const
void GetDStoParticleBy (float B, const KFParticleBase &p, float dS[2], float dsdr[4][6]) const
void GetDStoParticleCBM (const KFParticleBase &p, float dS[2], float dsdr[4][6]) const
virtual void Transport (float dS, const float dsdr[6], float P[], float C[], float *dsdr1=0, float *F=0, float *F1=0) const =0
KFParticleBase ()
virtual ~KFParticleBase ()
The default destructor.
void Initialize (const float Param[], const float Cov[], Int_t Charge, float Mass)
void Initialize ()
void SetConstructMethod (Int_t m)
Defines the construction method for the current particle (see description of fConstructMethod).
void SetMassHypo (float m)
Sets the mass hypothesis to the particle, is used when fConstructMethod = 2.
const float & GetMassHypo () const
Returns the mass hypothesis.
const float & GetSumDaughterMass () const
Returns the sum of masses of the daughters.
float GetX () const
Retruns X coordinate of the particle, fP[0].
float GetY () const
Retruns Y coordinate of the particle, fP[1].
float GetZ () const
Retruns Z coordinate of the particle, fP[2].
float GetPx () const
Retruns X component of the momentum, fP[3].
float GetPy () const
Retruns Y component of the momentum, fP[4].
float GetPz () const
Retruns Z component of the momentum, fP[5].
float GetE () const
Returns energy of the particle, fP[6].
float GetS () const
Returns dS=l/p, l - decay length, fP[7], defined if production vertex is set.
char GetQ () const
Returns charge of the particle.
float GetChi2 () const
Returns Chi2 of the fit.
Int_t GetNDF () const
Returns number of decrease of freedom.
const float & X () const
Retruns X coordinate of the particle, fP[0].
const float & Y () const
Retruns Y coordinate of the particle, fP[1].
const float & Z () const
Retruns Z coordinate of the particle, fP[2].
const float & Px () const
Retruns X component of the momentum, fP[3].
const float & Py () const
Retruns Y component of the momentum, fP[4].
const float & Pz () const
Retruns Z component of the momentum, fP[5].
const float & E () const
Returns energy of the particle, fP[6].
const float & S () const
Returns dS=l/p, l - decay length, fP[7], defined if production vertex is set.
const char & Q () const
Returns charge of the particle.
const float & Chi2 () const
Returns Chi2 of the fit.
const Int_t & NDF () const
Returns number of decrease of freedom.
float GetParameter (Int_t i) const
Returns P[i] parameter.
float GetCovariance (Int_t i) const
Returns C[i] element of the covariance matrix in the lower triangular form.
float GetCovariance (Int_t i, Int_t j) const
Returns C[i,j] element of the covariance matrix.
Int_t GetMomentum (float &p, float &error) const
Int_t GetPt (float &pt, float &error) const
Int_t GetEta (float &eta, float &error) const
Int_t GetPhi (float &phi, float &error) const
Int_t GetMass (float &m, float &error) const
Int_t GetDecayLength (float &l, float &error) const
Int_t GetDecayLengthXY (float &l, float &error) const
Int_t GetLifeTime (float &ctau, float &error) const
Int_t GetR (float &r, float &error) const
float & X ()
Modifier of X coordinate of the particle, fP[0].
float & Y ()
Modifier of Y coordinate of the particle, fP[1].
float & Z ()
Modifier of Z coordinate of the particle, fP[2].
float & Px ()
Modifier of X component of the momentum, fP[3].
float & Py ()
Modifier of Y component of the momentum, fP[4].
float & Pz ()
Modifier of Z component of the momentum, fP[5].
float & E ()
Modifier of energy of the particle, fP[6].
float & S ()
Modifier of dS=l/p, l - decay length, fP[7], defined if production vertex is set.
char & Q ()
Modifier of charge of the particle.
float & Chi2 ()
Modifier of Chi2 of the fit.
Int_t & NDF ()
Modifier of number of decrease of freedom.
float & Parameter (Int_t i)
Modifier of P[i] parameter.
float & Covariance (Int_t i)
Modifier of C[i] element of the covariance matrix in the lower triangular form.
float & Covariance (Int_t i, Int_t j)
Modifier of C[i,j] element of the covariance matrix.
void operator+= (const KFParticleBase &Daughter)
void AddDaughter (const KFParticleBase &Daughter)
void SubtractDaughter (const KFParticleBase &Daughter)
void AddDaughterWithEnergyFit (const KFParticleBase &Daughter)
void AddDaughterWithEnergyFitMC (const KFParticleBase &Daughter)
void SetProductionVertex (const KFParticleBase &Vtx)
void SetNonlinearMassConstraint (float Mass)
void SetMassConstraint (float Mass, float SigmaMass=0)
void SetNoDecayLength ()
void Construct (const KFParticleBase *vDaughters[], Int_t nDaughters, const KFParticleBase *ProdVtx=0, float Mass=-1)
void TransportToDecayVertex ()
void TransportToProductionVertex ()
void TransportToDS (float dS, const float *dsdr)
void TransportBz (float Bz, float dS, const float *dsdr, float P[], float C[], float *dsdr1=0, float *F=0, float *F1=0) const
void TransportCBM (float dS, const float *dsdr, float P[], float C[], float *dsdr1=0, float *F=0, float *F1=0) const
float GetDistanceFromVertex (const float vtx[]) const
float GetDistanceFromVertex (const KFParticleBase &Vtx) const
float GetDistanceFromParticle (const KFParticleBase &p) const
float GetDeviationFromVertex (const float v[], const float Cv[]=0) const
float GetDeviationFromVertex (const KFParticleBase &Vtx) const
float GetDeviationFromParticle (const KFParticleBase &p) const
void SubtractFromVertex (KFParticleBase &Vtx) const
void SubtractFromParticle (KFParticleBase &Vtx) const
void RotateXY (float angle, float Vtx[3])
int Id () const
Returns Id of the particle.
int NDaughters () const
Returns number of daughter particles.
const std::vector< int > & DaughterIds () const
Returns the vector with the indices of daughter particles.
void CleanDaughtersId ()
Cleans the vector with the indices of daughter particles.
void SetId (int id)
Sets the Id of the particle. After the construction of a particle should be set by user.
void AddDaughterId (int id)
Adds index of the daughter particle.
void SetPDG (int pdg)
Sets the PDG hypothesis.
int GetPDG () const
Returns the PDG hypothesis.
Additional Inherited Members
Static Public Member Functions inherited from KFParticleBase
static void GetArmenterosPodolanski (KFParticleBase &positive, KFParticleBase &negative, float QtAlfa[2])
static void InvertCholetsky3 (float a[6])
static void MultQSQt (const float Q[], const float S[], float SOut[], const int kN)
Protected Member Functions inherited from KFParticleBase
float & Cij (Int_t i, Int_t j)
void TransportLine (float S, const float *dsdr, float P[], float C[], float *dsdr1, float *F, float *F1) const
bool GetMeasurement (const KFParticleBase &daughter, float m[], float V[], float D[3][3])
void SetMassConstraint (float *mP, float *mC, float mJ[7][7], float mass)
Static Protected Member Functions inherited from KFParticleBase
static Int_t IJ (Int_t i, Int_t j)
Protected Attributes inherited from KFParticleBase
float fP [8]
Particle parameters { X, Y, Z, Px, Py, Pz, E, S[=DecayLength/P]}.
float fC [36]
Low-triangle covariance matrix of fP.
float fChi2
Chi^2.
float fSFromDecay
Distance from the decay vertex to the current position.
float SumDaughterMass
Sum of the daughter particles masses. Needed to set the constraint on the minimum mass during particle construction.
float fMassHypo
The mass hypothesis, used for the constraints during particle construction.
Int_t fNDF
Number of degrees of freedom.
int fId
Id of the particle.
Bool_t fAtProductionVertex
Flag shows if particle is at the production point.
char fQ
The charge of the particle in the units of the elementary charge.
char fConstructMethod
Determines the method for the particle construction.
0 - Energy considered as an independent veriable, fitted independently from momentum, without any constraints on mass
2 - Energy considered as an independent variable, fitted independently from momentum, with constraints on mass of daughter particle.
int fPDG
The PDG hypothesis assigned to the particle.
std::vector< int > fDaughtersIds
A vector with ids of the daughter particles:
1) if particle is created from a track - the index of the track, in this case the size of the vector is always equal to one;
2) if particle is constructed from other particles - indices of these particles in the same array.
Detailed Description
The main scalar class of KF Particle package, describes particle objects.
Author
S.Gorbunov, I.Kisel, M.Zyzak
Date
05.02.2019
Version
1.0
The main scalar class of KF Particle pacakge, describes particle objects. The particle is described with the state vector { X, Y, Z, Px, Py, Pz, E } and the corresponding covariance matrix. It contains functionality to create particle-object from track, to construct short-lived particles from other tracks or particles. The mathematics is based on the Kalman filter method. It also allows to subtract particles from the already constructed object, to transport particles, get parameters together with their errors, get distance to other particles and vertices, get deviations from them in terms of errors, etc.
Definition at line 52 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 52 of file KFParticle.h
Constructor & Destructor Documentation
KFParticle::KFParticle () inline
Definition at line 67 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 67 of file KFParticle.h
KFParticle::~KFParticle () inline
Definition at line 71 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 71 of file KFParticle.h
KFParticle::KFParticle (const KFParticle & d1, const KFParticle & d2)
Constructs a particle from two input daughter particles
Parameters
[in] d1 - the first daughter particle
[in] d2 - the second daughter particle
Definition at line 39 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 39 of file KFParticle.cxx
KFParticle::KFParticle (const KFParticle & d1, const KFParticle & d2, const KFParticle & d3) inline
Constructs a particle from three input daughter particles
Parameters
[in] d1 - the first daughter particle
[in] d2 - the second daughter particle
[in] d3 - the third daughter particle
Definition at line 351 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 351 of file KFParticle.h
KFParticle::KFParticle (const KFParticle & d1, const KFParticle & d2, const KFParticle & d3, const KFParticle & d4) inline
Constructs a particle from four input daughter particles
Parameters
[in] d1 - the first daughter particle
[in] d2 - the second daughter particle
[in] d3 - the third daughter particle
[in] d4 - the fourth daughter particle
Definition at line 367 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 367 of file KFParticle.h
KFParticle::KFParticle (const KFPTrack & track, const int PID)
Constructor from a track in the KF Particle format, PID hypothesis should be provided
Parameters
[in] track - KFPTrack containing 6 parameters: { X, Y, Z, Px, Py, Pz } and their errors
[in] PID - PID hypothesis, needed to assign mass to a particle and calculate the energy
Definition at line 97 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 97 of file KFParticle.cxx
References KFPTrack::Charge(), Create(), KFParticleBase::fC, KFParticleBase::fChi2, KFParticleBase::fNDF, KFParticleBase::fP, KFParticleBase::fQ, KFPTrack::GetChi2(), KFPTrack::GetCovarianceXYZPxPyPz(), KFParticleDatabase::GetMass(), KFPTrack::GetNDF(), KFParticleDatabase::Instance(), KFPTrack::PxPyPz(), KFParticleBase::SetPDG(), and KFPTrack::XvYvZv().
KFParticle::KFParticle (const KFPVertex & vertex)
Constructor from a vertex in the KF Particle format
Parameters
[in] vertex - KFPVertex containing 3 parameters: { X, Y, Z } and their errors
Definition at line 121 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 121 of file KFParticle.cxx
References KFParticleBase::fAtProductionVertex, KFParticleBase::fC, KFParticleBase::fChi2, KFParticleBase::fNDF, KFParticleBase::fP, KFParticleBase::fQ, KFParticleBase::fSFromDecay, KFPVertex::GetChi2(), KFPVertex::GetCovarianceMatrix(), KFPVertex::GetNContributors(), and KFPVertex::GetXYZ().
Member Function Documentation
void KFParticle::AddDaughter (const KFParticle & Daughter) inline
Adds daughter to the current particle. Depending on the selected construction method uses:
1) Either simplifyed fast mathematics which consideres momentum and energy as independent variables and thus ignores constraint on the fixed mass (fConstructMethod = 0). In this case the mass of the daughter particle can be corrupted when the constructed vertex is added as the measurement and the mass of the output short-lived particle can become unphysical - smaller then the threshold. Implemented in the AddDaughterWithEnergyFit() function
2) Or slower but correct mathematics which requires that the masses of daughter particles stays fixed in the construction process (fConstructMethod = 2). Implemented in the AddDaughterWithEnergyFitMC() function.
Parameters
[in] Daughter - the daughter particle
Definition at line 834 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 834 of file KFParticle.h
References KFParticleBase::AddDaughter(), and i.
const float& KFParticle::Chi2 () const inline
Returns Chi2 of the fit.
Definition at line 137 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 137 of file KFParticle.h
References KFParticleBase::fChi2.
Referenced by KFParticleSIMD::GetKFParticle(), and KFParticleTopoReconstructor::SelectParticleCandidates().
float & KFParticle::Chi2 () inline
Modifier of Chi2 of the fit.
Definition at line 785 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 785 of file KFParticle.h
References KFParticleBase::Chi2().
void KFParticle::Construct (const KFParticle * vDaughters[], int nDaughters, const KFParticle * ProdVtx = 0, float Mass = -1) inline
Constructs a short-lived particle from a set of daughter particles:
1) all parameters of the "this" objects are initialised;
2) daughters are added one after another;
3) if Parent pointer is not null, the production vertex is set to it;
4) if Mass hypothesis >=0 the mass constraint is set.
Parameters
[in] vDaughters - array of daughter particles
[in] nDaughters - number of daughter particles in the input array
[in] Parent - optional parrent particle
[in] Mass - optional mass hypothesis
Definition at line 855 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 855 of file KFParticle.h
References KFParticleBase::Construct(), and i.
Referenced by KFVertex::ConstructPrimaryVertex(), and KFParticleTest::RunTestSingle().
float & KFParticle::Covariance (int i) inline
Modifier of C[i] element of the covariance matrix in the lower triangular form.
Definition at line 800 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 800 of file KFParticle.h
References KFParticleBase::Covariance().
float & KFParticle::Covariance (int i, int j) inline
Modifier of C[i,j] element of the covariance matrix.
Definition at line 805 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 805 of file KFParticle.h
References KFParticleBase::Covariance().
float * KFParticle::CovarianceMatrix () inline
Returns pointer to the covariance matrix fC.
Definition at line 815 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 815 of file KFParticle.h
References KFParticleBase::fC.
Referenced by KFParticleSIMD::GetKFParticle(), and KFParticleSIMD::KFParticleSIMD().
void KFParticle::Create (const float Param[], const float Cov[], Int_t Charge, float mass)
Constructor from a "cartesian" track, mass hypothesis should be provided
Parameters
[in] Param[6] = { X, Y, Z, Px, Py, Pz } - position and momentum
[in] Cov[21] - lower-triangular part of the covariance matrix:
          (  0  .  .  .  .  . )
          (  1  2  .  .  .  . )
Cov[21] = (3  4  5  .  .  .)
          (  6  7  8  9  .  . )
          ( 10 11 12 13 14  . )
          ( 15 16 17 18 19 20 )
[in] Charge - charge of the particle in elementary charge units
[in] mass - the mass hypothesis
Definition at line 51 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 51 of file KFParticle.cxx
References C, i, and KFParticleBase::Initialize().
Referenced by KFParticle().
void KFParticle::Create (const Double_t Param[], const Double_t Cov[], Int_t Charge, float mass)
Constructor from a "cartesian" track, mass hypothesis should be provided
Parameters
[in] Param[6] = { X, Y, Z, Px, Py, Pz } - position and momentum
[in] Cov[21] - lower-triangular part of the covariance matrix:
          (  0  .  .  .  .  . )
          (  1  2  .  .  .  . )
Cov[21] = (3  4  5  .  .  .)
          (  6  7  8  9  .  . )
          ( 10 11 12 13 14  . )
          ( 15 16 17 18 19 20 )
[in] Charge - charge of the particle in elementary charge units
[in] mass - the mass hypothesis
Definition at line 73 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 73 of file KFParticle.cxx
References C, i, KFParticleBase::Initialize(), and P().
const float& KFParticle::E () const inline
Returns energy of the particle, fP[6].
Definition at line 134 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 134 of file KFParticle.h
References KFParticleBase::fP.
float & KFParticle::E () inline
Modifier of energy of the particle, fP[6].
Definition at line 770 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 770 of file KFParticle.h
References KFParticleBase::E().
float KFParticle::GetAngle (const KFParticle & p) const
Returns the opening angle between the current and the second particle in 3D.
Parameters
[in] p - the second particle
Definition at line 369 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 369 of file KFParticle.cxx
References KFPMath::a, GetDStoParticle(), n, and Transport().
float KFParticle::GetAngleRZ (const KFParticle & p) const
Returns the opening angle between the current and the second particle in the RZ plane, R = sqrt(X*X+Y*Y).
Parameters
[in] p - the second particle
Definition at line 413 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 413 of file KFParticle.cxx
References KFPMath::a, GetDStoParticle(), n, and Transport().
float KFParticle::GetAngleXY (const KFParticle & p) const
Returns the opening angle between the current and the second particle in the XY plane.
Parameters
[in] p - the second particle
Definition at line 391 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 391 of file KFParticle.cxx
References KFPMath::a, GetDStoParticle(), n, and Transport().
Bool_t KFParticle::GetAtProductionVertex () const inline
Returns a flag which shows if the particle is located at the production point.
Definition at line 120 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 120 of file KFParticle.h
References KFParticleBase::fAtProductionVertex.
Referenced by KFParticleSIMD::KFParticleSIMD().
float KFParticle::GetChi2 () const inline
Returns Chi2 of the fit.
Definition at line 438 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 438 of file KFParticle.h
References KFParticleBase::GetChi2().
Referenced by KFVertex::ConstructPrimaryVertex(), KFPHistogramSet::Fill(), and KFParticleSIMD::KFParticleSIMD().
float KFParticle::GetCovariance (int i) const inline
Returns C[i] element of the covariance matrix in the lower triangular form.
Definition at line 453 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 453 of file KFParticle.h
References KFParticleBase::GetCovariance().
Referenced by GetDistanceFromVertexXY(), GetErrE(), GetErrPx(), GetErrPy(), GetErrPz(), GetErrS(), GetErrX(), GetErrY(), GetErrZ(), and GetPseudoProperDecayTime().
float KFParticle::GetCovariance (int i, int j) const inline
Returns C[i,j] element of the covariance matrix.
Definition at line 458 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 458 of file KFParticle.h
References KFParticleBase::GetCovariance().
float KFParticle::GetDecayLength () const inline
Returns decay length.
Definition at line 506 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 506 of file KFParticle.h
References KFParticleBase::GetDecayLength().
int KFParticle::GetDecayLength (float & L, float & SigmaL) const inline
Calculates the decay length of the particle in the laboratory system and its error. If they are well defined returns 0, otherwise 1. The production point should be set before calling this function.
Parameters
[out] L - the decay length
[out] SigmaL - its error
Definition at line 699 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 699 of file KFParticle.h
References KFParticleBase::GetDecayLength().
float KFParticle::GetDecayLengthXY () const inline
Returns decay length in XY.
Definition at line 513 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 513 of file KFParticle.h
References KFParticleBase::GetDecayLengthXY().
int KFParticle::GetDecayLengthXY (float & L, float & SigmaL) const inline
Calculates the projection in the XY plane of the decay length of the particle in the laboratory system and its error. If they are well defined returns 0, otherwise 1. The production point should be set before calling this function.
Parameters
[out] L - the decay length
[out] SigmaL - its error
Definition at line 709 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 709 of file KFParticle.h
References KFParticleBase::GetDecayLengthXY().
float KFParticle::GetDeviationFromParticleXY (const KFParticle & p) const
Returns sqrt(Chi2/ndf) deviation from other particle in the XY plane.
Parameters
[in] p - the second particle
Definition at line 276 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 276 of file KFParticle.cxx
References d, GetDeviationFromVertexXY(), GetDStoParticle(), SVM_v1::h, and Transport().
float KFParticle::GetDeviationFromVertexXY (const float v[], const float Cv[] = 0) const
Returns sqrt(Chi2/ndf) deviation from the vertex in the XY plane.
Parameters
[in] vtx[2] - { X, Y } coordinates of the vertex
[in] Cv[3] - lower-triangular part of the covariance matrix of the vertex
Definition at line 304 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 304 of file KFParticle.cxx
References GetDistanceFromVertexXY().
Referenced by GetDeviationFromParticleXY(), and GetDeviationFromVertexXY().
float KFParticle::GetDeviationFromVertexXY (const KFParticle & Vtx) const
Returns sqrt(Chi2/ndf) deviation from the vertex in the KFParticle format in the XY plane.
Parameters
[in] Vtx - the vertex in the KFParticle format
Definition at line 318 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 318 of file KFParticle.cxx
References KFParticleBase::fC, KFParticleBase::fP, and GetDeviationFromVertexXY().
float KFParticle::GetDistanceFromParticleXY (const KFParticle & p) const
Returns the DCA distance between the current and the second particles in the XY plane.
Parameters
[in] p - the second particle
Definition at line 259 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 259 of file KFParticle.cxx
References dx, dy, GetDStoParticle(), and Transport().
Bool_t KFParticle::GetDistanceFromVertexXY (const float vtx[], float & val, float & err) const
Calculates the DCA distance from a vertex together with the error in the XY plane. Returns "true" if calculation is failed, "false" if both value and the error are well defined.
Parameters
[in] vtx[2] - { X, Y } coordinates of the vertex
[out] val - the distance in the XY plane to the vertex
[out] err - the error of the calculated distance, takes into account errors of the particle only
Definition at line 190 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 190 of file KFParticle.cxx
Referenced by GetDeviationFromVertexXY(), and GetDistanceFromVertexXY().
Bool_t KFParticle::GetDistanceFromVertexXY (const float vtx[], const float Cv[], float & val, float & err) const
Calculates the DCA distance from a vertex together with the error in the XY plane. Returns "true" if calculation is failed, "false" if both value and the error are well defined.
Parameters
[in] vtx[2] - { X, Y } coordinates of the vertex
[in] Cv[3] - lower-triangular part of the covariance matrix of the vertex
[out] val - the distance in the XY plane to the vertex
[out] err - the error of the calculated distance, takes into account errors of the particle and vertex
Definition at line 136 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 136 of file KFParticle.cxx
References dx, dy, GetCovariance(), GetDStoPoint(), h1, and Transport().
Bool_t KFParticle::GetDistanceFromVertexXY (const KFParticle & Vtx, float & val, float & err) const
Calculates the DCA distance from a vertex in the KFParticle format together with the error in the XY plane. Returns "true" if calculation is failed, "false" if both value and the error are well defined.
Parameters
[in] Vtx - the vertex in the KFParticle format
[out] val - the distance in the XY plane to the vertex
[out] err - the error of the calculated distance, takes into account errors of the particle and vertex
Definition at line 202 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 202 of file KFParticle.cxx
References KFParticleBase::fC, KFParticleBase::fP, and GetDistanceFromVertexXY().
float KFParticle::GetDistanceFromVertexXY (const float vtx[]) const
Returns the DCA distance from a vertex in the XY plane.
Parameters
[in] vtx[2] - { X, Y } coordinates of the vertex
Definition at line 228 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 228 of file KFParticle.cxx
References GetDistanceFromVertexXY().
float KFParticle::GetDistanceFromVertexXY (const KFParticle & Vtx) const
Returns the DCA distance from a vertex in the KFParticle format in the XY plane.
Parameters
[in] Vtx - the vertex in the KFParticle format
Definition at line 239 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 239 of file KFParticle.cxx
References KFParticleBase::fP, and GetDistanceFromVertexXY().
void KFParticle::GetDStoParticle (const KFParticleBase & p, float dS[2], float dsdr[4][6]) const inline virtual
Virtual method to get extrapolation parameter dS=l/p to another particle. Is defined in KFParticle.
Calculates dS = l/p parameters for two particles, where
1) l - signed distance to the DCA point with the other particle;
2) p - momentum of the particle
dS[0] is the transport parameter for the current particle, dS[1] - for the particle "p". Also calculates partial derivatives dsdr of the parameters dS[0] and dS[1] over the state vectors of the particles:
1) dsdr[0][6] = d(dS[0])/d(param1);
2) dsdr[1][6] = d(dS[0])/d(param2);
3) dsdr[2][6] = d(dS[1])/d(param1);
4) dsdr[3][6] = d(dS[1])/d(param2);
where param1 are parameters of the current particle fP and param2 are parameters of the second particle p.fP. If "HomogeneousField" is defined KFParticleBase::GetDStoParticleBz() is called, if "NonhomogeneousField" is defined - KFParticleBase::GetDStoParticleCBM()
Parameters
[in] p - second particle
[out] dS[2] - transport parameters dS for the current particle (dS[0]) and the second particle "p" (dS[1])
[out] dsdr[4][6] - partial derivatives of the parameters dS[0] and dS[1] over the state vectors of the both particles
Implements KFParticleBase.
Definition at line 966 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 966 of file KFParticle.h
References KFParticleBase::GetDStoParticleBz(), and KFParticleBase::GetDStoParticleCBM().
Referenced by GetAngle(), GetAngleRZ(), GetAngleXY(), GetDeviationFromParticleXY(), GetDistanceFromParticleXY(), and TransportToParticle().
float KFParticle::GetDStoPoint (const float xyz[3], float dsdr[6]) const inline virtual
Virtual method to get extrapolation parameter dS=l/p to . Is defined in KFParticle.
Returns dS = l/p parameter, where
1) l - signed distance to the DCA point with the input xyz point;
2) p - momentum of the particle;
Also calculates partial derivatives dsdr of the parameter dS over the state vector of the current particle. If "HomogeneousField" is defined KFParticleBase::GetDStoPointBz() is called, if "NonhomogeneousField" is defined - KFParticleBase::GetDStoPointCBM()
Parameters
[in] xyz[3] - point, to which particle should be transported
[out] dsdr[6] = ds/dr partial derivatives of the parameter dS over the state vector of the current particle
[in] param - optional parameter, is used in case if the parameters of the particle are rotated to other coordinate system (see GetDStoPointBy() function), otherwise fP are used
Implements KFParticleBase.
Definition at line 905 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 905 of file KFParticle.h
References KFParticleBase::GetDStoPointBz(), and KFParticleBase::GetDStoPointCBM().
Referenced by GetDistanceFromVertexXY(), GetParametersAtPoint(), and TransportToPoint().
float KFParticle::GetE () const inline
Returns energy of the particle, fP[6].
Definition at line 423 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 423 of file KFParticle.h
References KFParticleBase::GetE().
float KFParticle::GetErrDecayLength () const inline
Returns the error of decay length.
Definition at line 616 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 616 of file KFParticle.h
References KFParticleBase::GetDecayLength().
float KFParticle::GetErrDecayLengthXY () const inline
Returns the error of decay length in XY.
Definition at line 623 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 623 of file KFParticle.h
References KFParticleBase::GetDecayLengthXY().
float KFParticle::GetErrE () const inline
Returns the error of energy.
Definition at line 564 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 564 of file KFParticle.h
References GetCovariance().
float KFParticle::GetErrEta () const inline
Returns the error of pseudorapidity.
Definition at line 588 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 588 of file KFParticle.h
References KFParticleBase::GetEta().
float KFParticle::GetErrLifeTime () const inline
Returns the error of life time.
Definition at line 630 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 630 of file KFParticle.h
References KFParticleBase::GetLifeTime().
float KFParticle::GetErrMass () const inline
Returns the error of mass.
Definition at line 609 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 609 of file KFParticle.h
References KFParticleBase::GetMass().
float KFParticle::GetErrMomentum () const inline
Returns the error of momentum.
Definition at line 602 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 602 of file KFParticle.h
References KFParticleBase::GetMomentum().
float KFParticle::GetErrP () const inline
Returns the error of momentum.
Definition at line 574 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 574 of file KFParticle.h
References KFParticleBase::GetMomentum().
float KFParticle::GetErrPhi () const inline
Returns the error of the azimuthal angle phi.
Definition at line 595 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 595 of file KFParticle.h
References KFParticleBase::GetPhi().
float KFParticle::GetErrPt () const inline
Returns the error of transverse momentum.
Definition at line 581 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 581 of file KFParticle.h
References KFParticleBase::GetPt().
float KFParticle::GetErrPx () const inline
Returns the error of X-compoment of the particle momentum.
Definition at line 549 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 549 of file KFParticle.h
References GetCovariance().
float KFParticle::GetErrPy () const inline
Returns the error of Y-compoment of the particle momentum.
Definition at line 554 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 554 of file KFParticle.h
References GetCovariance().
float KFParticle::GetErrPz () const inline
Returns the error of Z-compoment of the particle momentum.
Definition at line 559 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 559 of file KFParticle.h
References GetCovariance().
float KFParticle::GetErrR () const inline
Returns the error of distance to the origin of the coordinate system {0,0,0}.
Definition at line 637 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 637 of file KFParticle.h
References KFParticleBase::GetR().
float KFParticle::GetErrS () const inline
Returns the error of decay length / momentum.
Definition at line 569 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 569 of file KFParticle.h
References GetCovariance().
float KFParticle::GetErrX () const inline
Returns the error of X of current position.
Definition at line 534 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 534 of file KFParticle.h
References GetCovariance().
float KFParticle::GetErrY () const inline
Returns the error of Y of current position.
Definition at line 539 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 539 of file KFParticle.h
References GetCovariance().
float KFParticle::GetErrZ () const inline
Returns the error of Z of current position.
Definition at line 544 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 544 of file KFParticle.h
References GetCovariance().
float KFParticle::GetEta () const inline
Returns pseudorapidity.
Definition at line 478 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 478 of file KFParticle.h
References KFParticleBase::GetEta().
int KFParticle::GetEta (float & Eta, float & SigmaEta) const inline
Calculates particle pseudorapidity and its error. If they are well defined returns 0, otherwise 1.
Parameters
[out] Eta - pseudorapidity of the particle
[out] SigmaEta - its error
Definition at line 663 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 663 of file KFParticle.h
References KFParticleBase::GetEta().
void KFParticle::GetFieldValue (const float xyz[], float B[]) const virtual
Abstract methods are defined in the KFParticle classVirtual method to access the magnetic field
Implements KFParticleBase.
Referenced by KFParticleTest::RunTestSingle(), and KFParticleTopoReconstructor::SaveInputParticles().
float KFParticle::GetLifeTime () const inline
Returns life time ctau [cm].
Definition at line 520 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 520 of file KFParticle.h
References KFParticleBase::GetLifeTime().
int KFParticle::GetLifeTime (float & T, float & SigmaT) const inline
Calculates the lifetime times speed of life (ctau) [cm] of the particle in the center of mass frame and its error. If they are well defined returns 0, otherwise 1. The production point should be set before calling this function.
Parameters
[out] T - lifetime of the particle [cm]
[out] SigmaT - its error
Definition at line 720 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 720 of file KFParticle.h
References KFParticleBase::GetLifeTime().
float KFParticle::GetMass () const inline
Returns mass.
Definition at line 499 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 499 of file KFParticle.h
References KFParticleBase::GetMass().
Referenced by KFParticleFinder::CombinePartPart(), KFParticleFinder::ConstructTrackV0Cand(), and KFPHistogramSet::Fill().
int KFParticle::GetMass (float & M, float & SigmaM) const inline
Calculates the mass of the particle and its error. If they are well defined returns 0, otherwise 1.
Parameters
[out] M - mass of the particle
[out] SigmaM - its error
Definition at line 690 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 690 of file KFParticle.h
References KFParticleBase::GetMass().
float KFParticle::GetMomentum () const inline
Returns momentum.
Definition at line 492 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 492 of file KFParticle.h
References KFParticleBase::GetMomentum().
Referenced by KFPHistogramSet::Fill().
int KFParticle::GetMomentum (float & P, float & SigmaP) const inline
Calculates particle momentum and its error. If they are well defined returns 0, otherwise 1.
Parameters
[out] P - momentum of the particle
[out] SigmaP - its error
Definition at line 681 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 681 of file KFParticle.h
References KFParticleBase::GetMomentum().
Int_t KFParticle::GetNDF () const inline
Returns number of decrease of freedom.
Definition at line 443 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 443 of file KFParticle.h
References KFParticleBase::GetNDF().
Referenced by KFVertex::ConstructPrimaryVertex(), KFPHistogramSet::Fill(), KFParticlePVReconstructor::FindPrimaryClusters(), and KFParticleSIMD::KFParticleSIMD().
float KFParticle::GetP () const inline
Returns momentum.
Definition at line 464 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 464 of file KFParticle.h
References KFParticleBase::GetMomentum().
int KFParticle::GetP (float & P, float & SigmaP) const inline
Calculates particle momentum and its error. If they are well defined returns 0, otherwise 1.
Parameters
[out] P - momentum of the particle
[out] SigmaP - its error
Definition at line 645 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 645 of file KFParticle.h
References KFParticleBase::GetMomentum().
float KFParticle::GetParameter (int i) const inline
Returns P[i] parameter.
Definition at line 448 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 448 of file KFParticle.h
References KFParticleBase::GetParameter().
void KFParticle::GetParametersAtPoint (const float * point, const float * pointCov, float * m, float * mV)
Transports particle to the DCA of the given point and stores obtained parameters and covariance matrix
Parameters
[in] point[3] - the point to which particle is transported
[in] pointCov[6] - the covariance matrix of the point
[out] m[8] - the parameters of the particle at the DCA point
[out] mV[36] - the covariance matrix of the particle at the DCA point, accounts the covariance matrix of the point as well
Definition at line 339 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 339 of file KFParticle.cxx
References F, F1, GetDStoPoint(), i, KFParticleBase::MultQSQt(), and Transport().
float KFParticle::GetPhi () const inline
Returns the azimuthal angle phi.
Definition at line 485 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 485 of file KFParticle.h
References KFParticleBase::GetPhi().
int KFParticle::GetPhi (float & Phi, float & SigmaPhi) const inline
Calculates particle polar angle at the current point and its error. If they are well defined returns 0, otherwise 1.
Parameters
[out] Phi - polar angle of the particle
[out] SigmaPhi - its error
Definition at line 672 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 672 of file KFParticle.h
References KFParticleBase::GetPhi().
float KFParticle::GetPseudoProperDecayTime (const KFParticle & primVertex, const float & mass, float * timeErr2 = 0) const
Returns the Pseudo Proper Time of the decay = (r*pt) / |pt| * M/|pt|
Parameters
[in] pV - the creation point of the particle
[in] mass - the mass of the particle
[out] timeErr2 - error of the returned value, if null pointer is provided - is not calculated
Definition at line 437 of file KFParticle.cxx.
View newest version in sPHENIX GitHub at line 437 of file KFParticle.cxx
References dx, dy, f2(), GetCovariance(), Px(), Py(), X(), and Y().
float KFParticle::GetPt () const inline
Returns transverse momentum.
Definition at line 471 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 471 of file KFParticle.h
References KFParticleBase::GetPt().
Referenced by KFPHistogramSet::Fill(), and GetTheta().
int KFParticle::GetPt (float & Pt, float & SigmaPt) const inline
Calculates particle transverse momentum and its error. If they are well defined returns 0, otherwise 1.
Parameters
[out] Pt - transverse momentum of the particle
[out] SigmaPt - its error
Definition at line 654 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 654 of file KFParticle.h
References KFParticleBase::GetPt().
float KFParticle::GetPx () const inline
Retruns X component of the momentum, fP[3].
Definition at line 408 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 408 of file KFParticle.h
References KFParticleBase::GetPx().
float KFParticle::GetPy () const inline
Retruns Y component of the momentum, fP[4].
Definition at line 413 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 413 of file KFParticle.h
References KFParticleBase::GetPy().
float KFParticle::GetPz () const inline
Retruns Z component of the momentum, fP[5].
Definition at line 418 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 418 of file KFParticle.h
References KFParticleBase::GetPz().
char KFParticle::GetQ () const inline
Returns charge of the particle.
Definition at line 433 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 433 of file KFParticle.h
References KFParticleBase::GetQ().
Referenced by KFParticleSIMD::KFParticleSIMD().
float KFParticle::GetR () const inline
Returns distance to the origin of the coordinate system {0,0,0}.
Definition at line 527 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 527 of file KFParticle.h
References KFParticleBase::GetR().
int KFParticle::GetR (float & R, float & SigmaR) const inline
Calculates the distance to the point {0,0,0} and its error. If they are well defined returns 0, otherwise 1.
Parameters
[out] R - polar angle of the particle
[out] SigmaR - its error
Definition at line 731 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 731 of file KFParticle.h
References KFParticleBase::GetR().
float KFParticle::GetRapidity () const inline
Returns rapidity of the particle.
Definition at line 191 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 191 of file KFParticle.h
References KFParticleBase::fP.
Referenced by KFPHistogramSet::Fill().
float KFParticle::GetS () const inline
Returns dS=l/p, l - decay length, fP[7], defined if production vertex is set.
Definition at line 428 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 428 of file KFParticle.h
References KFParticleBase::GetS().
float KFParticle::GetTheta () const inline
Returns the polar angle in RZ.
Definition at line 192 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 192 of file KFParticle.h
References KFParticleBase::fP, and GetPt().
float KFParticle::GetX () const inline
Retruns X coordinate of the particle, fP[0].
Definition at line 393 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 393 of file KFParticle.h
References KFParticleBase::GetX().
float KFParticle::GetY () const inline
Retruns Y coordinate of the particle, fP[1].
Definition at line 398 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 398 of file KFParticle.h
References KFParticleBase::GetY().
float KFParticle::GetZ () const inline
Retruns Z coordinate of the particle, fP[2].
Definition at line 403 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 403 of file KFParticle.h
References KFParticleBase::GetZ().
void KFParticle::Initialize () inline
Calls KFParticleBase::Initialize()
Definition at line 387 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 387 of file KFParticle.h
References KFParticleBase::Initialize().
const Int_t& KFParticle::NDF () const inline
Returns number of decrease of freedom.
Definition at line 138 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 138 of file KFParticle.h
References KFParticleBase::fNDF.
Referenced by KFParticleFinder::AddCandidate(), KFParticleSIMD::GetKFParticle(), and KFParticleTopoReconstructor::SelectParticleCandidates().
Int_t & KFParticle::NDF () inline
Modifier of number of decrease of freedom.
Definition at line 790 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 790 of file KFParticle.h
References KFParticleBase::NDF().
void KFParticle::operator+= (const KFParticle & Daughter) inline
Operator to add daughter to the current particle. Calls AddDaughter() function.
Parameters
[in] Daughter - the daughter particle
Definition at line 821 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 821 of file KFParticle.h
References i, and KFParticleBase::operator+=().
Referenced by KFVertex::operator+=().
float & KFParticle::Parameter (int i) inline
Modifier of P[i] parameter.
Definition at line 795 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 795 of file KFParticle.h
References KFParticleBase::Parameter().
float * KFParticle::Parameters () inline
Returns pointer to the parameters fP.
Definition at line 810 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 810 of file KFParticle.h
References KFParticleBase::fP.
Referenced by KFParticleSIMD::GetKFParticle(), and KFParticleSIMD::KFParticleSIMD().
const float& KFParticle::Px () const inline
Retruns X component of the momentum, fP[3].
Definition at line 131 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 131 of file KFParticle.h
References KFParticleBase::fP.
Referenced by GetPseudoProperDecayTime().
float & KFParticle::Px () inline
Modifier of X component of the momentum, fP[3].
Definition at line 755 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 755 of file KFParticle.h
References KFParticleBase::Px().
const float& KFParticle::Py () const inline
Retruns Y component of the momentum, fP[4].
Definition at line 132 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 132 of file KFParticle.h
References KFParticleBase::fP.
Referenced by GetPseudoProperDecayTime().
float & KFParticle::Py () inline
Modifier of Y component of the momentum, fP[4].
Definition at line 760 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 760 of file KFParticle.h
References KFParticleBase::Py().
const float& KFParticle::Pz () const inline
Retruns Z component of the momentum, fP[5].
Definition at line 133 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 133 of file KFParticle.h
References KFParticleBase::fP.
float & KFParticle::Pz () inline
Modifier of Z component of the momentum, fP[5].
Definition at line 765 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 765 of file KFParticle.h
References KFParticleBase::Pz().
const char& KFParticle::Q () const inline
Returns charge of the particle.
Definition at line 136 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 136 of file KFParticle.h
References KFParticleBase::fQ.
Referenced by KFParticleSIMD::GetKFParticle().
char & KFParticle::Q () inline
Modifier of charge of the particle.
Definition at line 780 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 780 of file KFParticle.h
References KFParticleBase::Q().
const float& KFParticle::S () const inline
Returns dS=l/p, l - decay length, fP[7], defined if production vertex is set.
Definition at line 135 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 135 of file KFParticle.h
References KFParticleBase::fP.
float & KFParticle::S () inline
Modifier of dS=l/p, l - decay length, fP[7], defined if production vertex is set.
Definition at line 775 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 775 of file KFParticle.h
References KFParticleBase::S().
void KFParticle::SetAtProductionVertex (Bool_t b) inline
Set a flag that particle is at the production point.
Definition at line 121 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 121 of file KFParticle.h
References KFPMath::b, and KFParticleBase::fAtProductionVertex.
Referenced by KFParticleSIMD::GetKFParticle().
void KFParticle::Transport (float dS, const float * dsdr, float P[], float C[], float * dsdr1 = 0, float * F = 0, float * F1 = 0) const inline
Transports the parameters and their covariance matrix of the current particle on a length defined by the transport parameter dS = l/p, where l is the signed distance and p is the momentum of the current particle. If "HomogeneousField" is defined KFParticleBase::TransportBz() is called, if "NonhomogeneousField" - KFParticleBase::TransportCBM(). The obtained parameters and covariance matrix are stored to the arrays P and C respectively. P and C can be set to the parameters fP and covariance matrix fC of the current particle. In this case the particle parameters will be modified. Dependence of the transport parameter dS on the state vector of the current particle is taken into account in the covariance matrix using partial derivatives dsdr = d(dS)/d(fP). If a pointer to F is initialised the transport jacobian F = d(fP new)/d(fP old) is stored. Since dS can depend on the state vector r1 of other particle or vertex, the corelation matrix F1 = d(fP new)/d(r1) can be optionally calculated if a pointer F1 is provided. Parameters F and F1 should be either both initialised or both set to null pointer.
Parameters
[in] dS - transport parameter which defines the distance to which particle should be transported
[in] dsdr[6] = ds/dr - partial derivatives of the parameter dS over the state vector of the current particle
[out] P[8] - array, where transported parameters should be stored
[out] C[36] - array, where transported covariance matrix (8x8) should be stored in the lower triangular form
[in] dsdr1[6] = ds/dr - partial derivatives of the parameter dS over the state vector of another particle or vertex
[out] F[36] - optional parameter, transport jacobian, 6x6 matrix F = d(fP new)/d(fP old)
[out] F1[36] - optional parameter, corelation 6x6 matrix betweeen the current particle and particle or vertex with the state vector r1, to which the current particle is being transported, F1 = d(fP new)/d(r1)
Definition at line 992 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 992 of file KFParticle.h
References KFParticleBase::TransportBz(), and KFParticleBase::TransportCBM().
Referenced by GetAngle(), GetAngleRZ(), GetAngleXY(), GetDeviationFromParticleXY(), GetDistanceFromParticleXY(), GetDistanceFromVertexXY(), and GetParametersAtPoint().
void KFParticle::TransportToParticle (const KFParticle & p) inline
Transports particle to the distance of closest approach to the particle p.
Parameters
[in] p - particle, to which the current particle should be transported.
Definition at line 894 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 894 of file KFParticle.h
References GetDStoParticle(), and KFParticleBase::TransportToDS().
void KFParticle::TransportToPoint (const float xyz[]) inline
Transports particle to the distance of closest approach to the point xyz.
Parameters
[in] xyz[3] - point, where particle should be transported
Definition at line 876 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 876 of file KFParticle.h
References GetDStoPoint(), and KFParticleBase::TransportToDS().
const float& KFParticle::X () const inline
Retruns X coordinate of the particle, fP[0].
Definition at line 128 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 128 of file KFParticle.h
References KFParticleBase::fP.
Referenced by KFPHistogramSet::Fill(), and GetPseudoProperDecayTime().
float & KFParticle::X () inline
Modifier of X coordinate of the particle, fP[0].
Definition at line 740 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 740 of file KFParticle.h
References KFParticleBase::X().
const float& KFParticle::Y () const inline
Retruns Y coordinate of the particle, fP[1].
Definition at line 129 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 129 of file KFParticle.h
References KFParticleBase::fP.
Referenced by KFPHistogramSet::Fill(), and GetPseudoProperDecayTime().
float & KFParticle::Y () inline
Modifier of Y coordinate of the particle, fP[1].
Definition at line 745 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 745 of file KFParticle.h
References KFParticleBase::Y().
const float& KFParticle::Z () const inline
Retruns Z coordinate of the particle, fP[2].
Definition at line 130 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 130 of file KFParticle.h
References KFParticleBase::fP.
Referenced by KFPHistogramSet::Fill().
float & KFParticle::Z () inline
Modifier of Z coordinate of the particle, fP[2].
Definition at line 750 of file KFParticle.h.
View newest version in sPHENIX GitHub at line 750 of file KFParticle.h
References KFParticleBase::Z().
The documentation for this class was generated from the following files:
KFParticle/blob/master/KFParticle/KFParticle.h
KFParticle/blob/master/KFParticle/KFParticle.cxx