Analysis Software: genfit::ProlateSpacepointMeasurement Class Reference
genfit::ProlateSpacepointMeasurement Class Reference
Class for measurements implementing a space point hit geometry with a very prolate form of the covariance matrix.
#include <GenFit/blob/master/measurements/include/ProlateSpacepointMeasurement.h>
Public Member Functions
ProlateSpacepointMeasurement (int nDim=3)
ProlateSpacepointMeasurement (const TVectorD &rawHitCoords, const TMatrixDSym &rawHitCov, int detId, int hitId, TrackPoint *trackPoint)
virtual ~ProlateSpacepointMeasurement ()
virtual AbsMeasurement * clone () const
Deep copy ctor for polymorphic class.
virtual SharedPlanePtr constructPlane (const StateOnPlane &state) const
Contruct the virtual detector plane.
const TVector3 & getLargestErrorDirection ()
void setLargestErrorDirection (const TVector3 &dir)
Public Member Functions inherited from genfit::SpacepointMeasurement
SpacepointMeasurement (int nDim=3)
SpacepointMeasurement (const TVectorD &rawHitCoords, const TMatrixDSym &rawHitCov, int detId, int hitId, TrackPoint *trackPoint, bool weightedPlaneContruction=true, bool cutCov=true)
virtual ~SpacepointMeasurement ()
virtual std::vector
< MeasurementOnPlane * > constructMeasurementsOnPlane (const StateOnPlane &state) const override
virtual const AbsHMatrix * constructHMatrix (const AbsTrackRep *) const override
bool getWeightedPlaneConstruction () const
false: project 3D cov onto DetPlane. true: cut 3D cov with DetPlane
void setWeightedPlaneConstruction (bool value)
bool getCutCov () const
false: use POCA to construct DetPlane. true: Use metric G to construct POCA
void setCutCov (bool value)
Public Member Functions inherited from genfit::AbsMeasurement
AbsMeasurement ()
AbsMeasurement (int nDims)
AbsMeasurement (const TVectorD &rawHitCoords, const TMatrixDSym &rawHitCov, int detId, int hitId, TrackPoint *trackPoint)
virtual ~AbsMeasurement ()
TrackPoint * getTrackPoint () const
void setTrackPoint (TrackPoint *tp)
const TVectorD & getRawHitCoords () const
const TMatrixDSym & getRawHitCov () const
TVectorD & getRawHitCoords ()
TMatrixDSym & getRawHitCov ()
int getDetId () const
int getHitId () const
virtual bool isLeftRightMeasurement () const
If the AbsMeasurement is a wire hit, the left/right resolution will be used.
virtual int getLeftRightResolution () const
unsigned int getDim () const
void setRawHitCoords (const TVectorD &coords)
void setRawHitCov (const TMatrixDSym &cov)
void setDetId (int detId)
void setHitId (int hitId)
virtual void Print (const Option_t *="") const
Protected Attributes
TVector3 largestErrorDirection_
Additional Inherited Members
Protected Member Functions inherited from genfit::SpacepointMeasurement
void initG ()
Detailed Description
Class for measurements implementing a space point hit geometry with a very prolate form of the covariance matrix.
Author
Johannes Rauch (Technische Universität München, original author)
Measurements from detectors measuring 3D space points with errors in one direction much larger than the errors perpendicular should use this class.
For these hits, a virtual detector plane lying in the POCA and perpendicular to the track yields wrong results. Instead, the plane should contain the direction of the largest error.
The largest error direction can be set. Standard is in z.
Definition at line 46 of file ProlateSpacepointMeasurement.h.
View newest version in sPHENIX GitHub at line 46 of file ProlateSpacepointMeasurement.h
Constructor & Destructor Documentation
genfit::ProlateSpacepointMeasurement::ProlateSpacepointMeasurement (int nDim = 3)
Definition at line 30 of file ProlateSpacepointMeasurement.cc.
View newest version in sPHENIX GitHub at line 30 of file ProlateSpacepointMeasurement.cc
Referenced by clone().
genfit::ProlateSpacepointMeasurement::ProlateSpacepointMeasurement (const TVectorD & rawHitCoords, const TMatrixDSym & rawHitCov, int detId, int hitId, TrackPoint * trackPoint)
Definition at line 36 of file ProlateSpacepointMeasurement.cc.
View newest version in sPHENIX GitHub at line 36 of file ProlateSpacepointMeasurement.cc
virtual genfit::ProlateSpacepointMeasurement::~ProlateSpacepointMeasurement () inline virtual
Definition at line 52 of file ProlateSpacepointMeasurement.h.
View newest version in sPHENIX GitHub at line 52 of file ProlateSpacepointMeasurement.h
Member Function Documentation
virtual AbsMeasurement* genfit::ProlateSpacepointMeasurement::clone () const inline virtual
Deep copy ctor for polymorphic class.
Reimplemented from genfit::SpacepointMeasurement.
Definition at line 54 of file ProlateSpacepointMeasurement.h.
View newest version in sPHENIX GitHub at line 54 of file ProlateSpacepointMeasurement.h
References ProlateSpacepointMeasurement().
SharedPlanePtr genfit::ProlateSpacepointMeasurement::constructPlane (const StateOnPlane & state) const virtual
Contruct the virtual detector plane.
Per default, the plane will be constructed such that it contains the measurement and POCA to the measurement in cartesian space. The plane is perpendicular to the track (at the POCA).
If weightedPlaneContruction_ is set, the POCA will be calculated in a space weighted with the inverse of the 3D covariance. E.g. if the covariance is very oblate, the plane will be almost defined by the covariance shape. If the covariance is very prolate, the behaviour will be very similar to the ProlateSpacepointHit.
Reimplemented from genfit::SpacepointMeasurement.
Definition at line 43 of file ProlateSpacepointMeasurement.cc.
View newest version in sPHENIX GitHub at line 43 of file ProlateSpacepointMeasurement.cc
References genfit::AbsTrackRep::extrapolateToLine(), genfit::AbsTrackRep::getMom(), genfit::StateOnPlane::getRep(), largestErrorDirection_, and genfit::AbsMeasurement::rawHitCoords_.
const TVector3& genfit::ProlateSpacepointMeasurement::getLargestErrorDirection () inline
Definition at line 59 of file ProlateSpacepointMeasurement.h.
View newest version in sPHENIX GitHub at line 59 of file ProlateSpacepointMeasurement.h
References largestErrorDirection_.
void genfit::ProlateSpacepointMeasurement::setLargestErrorDirection (const TVector3 & dir) inline
Definition at line 60 of file ProlateSpacepointMeasurement.h.
View newest version in sPHENIX GitHub at line 60 of file ProlateSpacepointMeasurement.h
References largestErrorDirection_.
Member Data Documentation
TVector3 genfit::ProlateSpacepointMeasurement::largestErrorDirection_ protected
Definition at line 63 of file ProlateSpacepointMeasurement.h.
View newest version in sPHENIX GitHub at line 63 of file ProlateSpacepointMeasurement.h
Referenced by constructPlane(), getLargestErrorDirection(), and setLargestErrorDirection().
The documentation for this class was generated from the following files:
GenFit/blob/master/measurements/include/ProlateSpacepointMeasurement.h
GenFit/blob/master/measurements/src/ProlateSpacepointMeasurement.cc