Analysis Software: KFParticleTest Class Reference
KFParticleTest Class Reference
#include <KFParticle/blob/master/KFParticleTest/KFParticleTest.h>
Public Member Functions
KFParticleTest ()
~KFParticleTest ()
void PrintTutorial ()
void RunTest ()
Private Member Functions
void RunTestSingle ()
void RunTestSIMD ()
void CompareSingleAndSIMDResults ()
Private Attributes
KFParticle * fMotherSingle
KFParticleSIMD * fMotherSIMD
Detailed Description
Definition at line 28 of file KFParticleTest.h.
View newest version in sPHENIX GitHub at line 28 of file KFParticleTest.h
Constructor & Destructor Documentation
KFParticleTest::KFParticleTest ()
Definition at line 61 of file KFParticleTest.cxx.
View newest version in sPHENIX GitHub at line 61 of file KFParticleTest.cxx
References fMotherSIMD, and fMotherSingle.
KFParticleTest::~KFParticleTest ()
Definition at line 67 of file KFParticleTest.cxx.
View newest version in sPHENIX GitHub at line 67 of file KFParticleTest.cxx
References fMotherSIMD, and fMotherSingle.
Member Function Documentation
void KFParticleTest::CompareSingleAndSIMDResults () private
Definition at line 217 of file KFParticleTest.cxx.
View newest version in sPHENIX GitHub at line 217 of file KFParticleTest.cxx
void KFParticleTest::PrintTutorial ()
Definition at line 221 of file KFParticleTest.cxx.
View newest version in sPHENIX GitHub at line 221 of file KFParticleTest.cxx
void KFParticleTest::RunTest ()
Definition at line 73 of file KFParticleTest.cxx.
View newest version in sPHENIX GitHub at line 73 of file KFParticleTest.cxx
References RunTestSIMD(), and RunTestSingle().
Referenced by KFParticleTest().
void KFParticleTest::RunTestSIMD () private
Definition at line 213 of file KFParticleTest.cxx.
View newest version in sPHENIX GitHub at line 213 of file KFParticleTest.cxx
Referenced by RunTest().
void KFParticleTest::RunTestSingle () private
This is the example of the KFParticleBase::Construct function usage. parameter 1 - array of the daughter particles parameter 2 - number of the daughter particles parameter 3 - vertex (it should be the object of the KFParticle class) parameter 4 - the value we force the particle mass to be equial to.
we assume Mass to be the mass of the constructed particle
we assume p1 to be the vertex of the constructed particle
we assume p1 to be the vertex of the constructed particle, Mass to be the mass of the constructed particle
we assume p1 to be the vertex of the constructed particle, Mass to be the mass of the constructed particle
Definition at line 79 of file KFParticleTest.cxx.
View newest version in sPHENIX GitHub at line 79 of file KFParticleTest.cxx
References KFPMath::b, C, KFParticle::Construct(), KFParticle::GetFieldValue(), NDaughters(), KFPTrack::SetCharge(), KFPVertex::SetChi2(), KFPTrack::SetChi2(), KFPVertex::SetCovarianceMatrix(), KFPTrack::SetCovarianceMatrix(), KFPVertex::SetNContributors(), KFPTrack::SetNDF(), KFPTrack::SetParameters(), KFParticleBase::SetProductionVertex(), and KFPVertex::SetXYZ().
Referenced by RunTest().
Member Data Documentation
KFParticleSIMD* KFParticleTest::fMotherSIMD private
Definition at line 45 of file KFParticleTest.h.
View newest version in sPHENIX GitHub at line 45 of file KFParticleTest.h
Referenced by KFParticleTest(), and ~KFParticleTest().
KFParticle* KFParticleTest::fMotherSingle private
Definition at line 44 of file KFParticleTest.h.
View newest version in sPHENIX GitHub at line 44 of file KFParticleTest.h
Referenced by KFParticleTest(), and ~KFParticleTest().
The documentation for this class was generated from the following files:
KFParticle/blob/master/KFParticleTest/KFParticleTest.h
KFParticle/blob/master/KFParticleTest/KFParticleTest.cxx