Analysis Software: genfit::GblFitterInfo Class Reference
genfit::GblFitterInfo Class Reference
Collects information needed and produced by a GblFitter/GBL and is specific to one AbsTrackRep of the Track.
#include <GenFit/blob/master/GBL/include/GblFitterInfo.h>
Public Member Functions
GblFitterInfo ()
Constructor for ROOT I/O.
GblFitterInfo (const TrackPoint *trackPoint, const AbsTrackRep *rep)
Default (inherited) constructor Should not be used or the reference should set immediately upon construction (to set the plane).
GblFitterInfo (const TrackPoint *trackPoint, const AbsTrackRep *rep, StateOnPlane &referenceState)
Default user constructor.
void reset (unsigned int measurementDim=2, unsigned int repDim=5)
(Initial) reset of fitter info
void setReferenceState (StateOnPlane &referenceState)
Set the prediction and plane (from measurement if any) You should use the user constructor instead.
void setJacobian (TMatrixD jacobian)
Set the Jacobian for further GblPoint construction.
TMatrixDSym getCovariance (double variance, TVector3 trackDirection, SharedPlanePtr measurementPlane) const
Get scattering covariance projected into (measurement) plane.
gbl::GblPoint constructGblPoint ()
Collect all data and create a GblPoint.
void updateFitResults (gbl::GblTrajectory &traj)
Update fitter info from GBL fit results.
const MeasuredStateOnPlane & getFittedState (bool afterKink=true) const override
Get the prediction at this point Always biased in GBL (global fit) There are 2 states, before and after kink (if there is a scatterer at this point). Per default the state after kink for forward propagation is returned.
MeasurementOnPlane getResidual (unsigned int=0, bool=false, bool onlyMeasurementErrors=true) const override
Get the residual.
MeasurementOnPlane getKink () const
Get kink (residual) with diagonalized covariance (2D) Covariance may be zero if not yet fitted or no scatterer!
TVectorD getKinks () const
Get kink (residual) (2D) = 0 - ((+)pred - (-)pred)
MeasurementOnPlane getMeasurement () const
Get the measurement on plane from stored measurement data (from last construction/update)
void updateMeasurementAndPlane (const StateOnPlane &sop)
SHOULD BE USED ONLY INTERNALY! Update the plane from measurement constructed with state or take plane from state if there is no measurement. 1st raw Measurement with highest weight is constructed and stored as matrices.
StateOnPlane getReferenceState () const
Returns (copy of) the stored reference 5D state at current plane with internal rep.
void recalculateJacobian (GblFitterInfo *prevFitterInfo)
Re-extrapolates between prevFitterInfo and this point using forward state to update the Jacobian (if planes and/or states changed, internal predictions are extrapolated to new planes)
virtual ~GblFitterInfo ()
virtual GblFitterInfo * clone () const override
Deep copy ctor for polymorphic class.
bool hasMeasurements () const override
bool hasReferenceState () const override
bool hasForwardPrediction () const override
bool hasBackwardPrediction () const override
bool hasForwardUpdate () const override
bool hasBackwardUpdate () const override
bool hasUpdate (int direction) const override
bool hasPredictionsAndUpdates () const
void deleteForwardInfo () override
void deleteBackwardInfo () override
void deletePredictions ()
void deleteReferenceInfo () override
void deleteMeasurementInfo () override
virtual void Print (const Option_t *="") const override
virtual bool checkConsistency (const genfit::PruneFlags *=nullptr) const override
Public Member Functions inherited from genfit::AbsFitterInfo
AbsFitterInfo ()
AbsFitterInfo (const TrackPoint *trackPoint, const AbsTrackRep *rep)
virtual ~AbsFitterInfo ()
const TrackPoint * getTrackPoint () const
const AbsTrackRep * getRep () const
void setTrackPoint (const TrackPoint *tp)
virtual void setRep (const AbsTrackRep *rep)
virtual bool hasPrediction (int direction) const
const SharedPlanePtr & getPlane () const
void setPlane (const SharedPlanePtr &plane)
Private Attributes
TMatrixD jacobian_
TVectorD measResiduals_
TVectorD measResidualErrors_
TVectorD kinkResiduals_
TVectorD kinkResidualErrors_
TVectorD measDownWeights_
TVectorD kinkDownWeights_
TVectorD bwdStateCorrection_
TVectorD fwdStateCorrection_
TMatrixDSym bwdCov_
TMatrixDSym fwdCov_
TVectorD fwdPrediction_
TVectorD bwdPrediction_
TVectorD refPrediction_
TVectorD measurement_
TMatrixDSym measCov_
TMatrixD hMatrix_
std::unique_ptr
< MeasuredStateOnPlane > fittedStateBwd_
std::unique_ptr
< MeasuredStateOnPlane > fittedStateFwd_
cache
Additional Inherited Members
Protected Attributes inherited from genfit::AbsFitterInfo
const TrackPoint * trackPoint_
const AbsTrackRep * rep_
No ownership.
SharedPlanePtr sharedPlane_
No ownership.
Detailed Description
Collects information needed and produced by a GblFitter/GBL and is specific to one AbsTrackRep of the Track.
Definition at line 52 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 52 of file GblFitterInfo.h
Constructor & Destructor Documentation
genfit::GblFitterInfo::GblFitterInfo ()
Constructor for ROOT I/O.
Definition at line 10 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 10 of file GblFitterInfo.cc
References reset().
Referenced by clone().
genfit::GblFitterInfo::GblFitterInfo (const TrackPoint * trackPoint, const AbsTrackRep * rep)
Default (inherited) constructor Should not be used or the reference should set immediately upon construction (to set the plane).
Definition at line 14 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 14 of file GblFitterInfo.cc
References genfit::AbsTrackRep::getDim(), genfit::AbsTrackRep::getForwardJacobianAndNoise(), jacobian_, and reset().
genfit::GblFitterInfo::GblFitterInfo (const TrackPoint * trackPoint, const AbsTrackRep * rep, StateOnPlane & referenceState)
Default user constructor.
Parameters
trackPoint The point at track to attach fitter info.
rep The representation this fitter info belongs to
referenceState State from extrapolation to init predictions and plane
Definition at line 27 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 27 of file GblFitterInfo.cc
References genfit::AbsTrackRep::getDim(), genfit::AbsTrackRep::getForwardJacobianAndNoise(), jacobian_, reset(), and setReferenceState().
virtual genfit::GblFitterInfo::~GblFitterInfo () inline virtual
Definition at line 225 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 225 of file GblFitterInfo.h
Member Function Documentation
bool genfit::GblFitterInfo::checkConsistency (const genfit::PruneFlags * = nullptr) const override virtual
Implements genfit::AbsFitterInfo.
Definition at line 477 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 477 of file GblFitterInfo.cc
GblFitterInfo * genfit::GblFitterInfo::clone () const override virtual
Deep copy ctor for polymorphic class.
Implements genfit::AbsFitterInfo.
Definition at line 482 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 482 of file GblFitterInfo.cc
References bwdCov_, bwdPrediction_, bwdStateCorrection_, fwdCov_, fwdPrediction_, fwdStateCorrection_, GblFitterInfo(), genfit::AbsFitterInfo::getRep(), genfit::AbsFitterInfo::getTrackPoint(), hMatrix_, jacobian_, kinkDownWeights_, kinkResidualErrors_, kinkResiduals_, measCov_, measDownWeights_, measResidualErrors_, measResiduals_, measurement_, refPrediction_, genfit::AbsFitterInfo::setPlane(), and genfit::AbsFitterInfo::sharedPlane_.
gbl::GblPoint genfit::GblFitterInfo::constructGblPoint ()
Collect all data and create a GblPoint.
Jacobian is taken from fitter info ... use setJaobian() to change it
A scatterer is added if ThinScatterer at point
A measurement (first MeasurementOnPlane in 1st RawMeasurement) is added.
Global and local derivatives are added for RawMesurement implementing ICalibrationParametersDerivatives interface. Using most up to date prediction.
Returns
gbl::GblPoint
Definition at line 111 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 111 of file GblFitterInfo.cc
References gbl::GblPoint::addGlobals(), gbl::GblPoint::addLocals(), gbl::GblPoint::addMeasurement(), gbl::GblPoint::addScatterer(), genfit::Material::density, genfit::MeasuredStateOnPlane::getCov(), getCovariance(), genfit::StateOnPlane::getDir(), genfit::Track::getFitStatus(), getFittedState(), getKinks(), genfit::ThinScatterer::getMaterial(), genfit::TrackPoint::getMaterialInfo(), genfit::HMatrixU::getMatrix(), genfit::GblFitStatus::getMaxLocalFitParams(), genfit::StateOnPlane::getPlane(), genfit::TrackPoint::getRawMeasurement(), getResidual(), genfit::StateOnPlane::getState(), genfit::TrackPoint::getTrack(), genfit::ICalibrationParametersDerivatives::globalDerivatives(), hasMeasurements(), genfit::TrackPoint::hasThinScatterer(), hMatrix_, jacobian_, genfit::ICalibrationParametersDerivatives::localDerivatives(), genfit::AbsFitterInfo::rep_, genfit::GblFitStatus::setMaxLocalFitParams(), genfit::AbsFitterInfo::sharedPlane_, and genfit::AbsFitterInfo::trackPoint_.
Referenced by genfit::GblFitter::collectGblPoints().
void genfit::GblFitterInfo::deleteBackwardInfo () inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 237 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 237 of file GblFitterInfo.h
Referenced by deletePredictions().
void genfit::GblFitterInfo::deleteForwardInfo () inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 236 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 236 of file GblFitterInfo.h
Referenced by deletePredictions().
void genfit::GblFitterInfo::deleteMeasurementInfo () inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 243 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 243 of file GblFitterInfo.h
void genfit::GblFitterInfo::deletePredictions () inline
Definition at line 238 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 238 of file GblFitterInfo.h
References deleteBackwardInfo(), and deleteForwardInfo().
void genfit::GblFitterInfo::deleteReferenceInfo () inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 242 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 242 of file GblFitterInfo.h
TMatrixDSym genfit::GblFitterInfo::getCovariance (double variance, TVector3 trackDirection, SharedPlanePtr measurementPlane) const
Get scattering covariance projected into (measurement) plane.
Parameters
variance Variance of slopes in track frame
trackDirection Direction of the track at the plane
measurementPlane The plane with measurement to which MS shall be projected
Returns
TMatrixDSym
Definition at line 96 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 96 of file GblFitterInfo.cc
References c2.
Referenced by constructGblPoint().
const MeasuredStateOnPlane & genfit::GblFitterInfo::getFittedState (bool afterKink = true) const override virtual
Get the prediction at this point Always biased in GBL (global fit) There are 2 states, before and after kink (if there is a scatterer at this point). Per default the state after kink for forward propagation is returned.
If not yet fitted, returns the reference state
Parameters
afterKink If true, returns prediction for forward propagation. If false, for backward
Returns
const genfit::MeasuredStateOnPlane&
Implements genfit::AbsFitterInfo.
Definition at line 398 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 398 of file GblFitterInfo.cc
References bwdCov_, bwdPrediction_, fittedStateBwd_, fittedStateFwd_, fwdCov_, fwdPrediction_, genfit::AbsFitterInfo::rep_, and genfit::AbsFitterInfo::sharedPlane_.
Referenced by constructGblPoint(), getKinks(), getResidual(), recalculateJacobian(), and updateFitResults().
MeasurementOnPlane genfit::GblFitterInfo::getKink () const
Get kink (residual) with diagonalized covariance (2D) Covariance may be zero if not yet fitted or no scatterer!
Returns
genfit::MeasurementOnPlane
Definition at line 453 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 453 of file GblFitterInfo.cc
References getKinks(), kinkResidualErrors_, genfit::AbsFitterInfo::rep_, and genfit::AbsFitterInfo::sharedPlane_.
TVectorD genfit::GblFitterInfo::getKinks () const
Get kink (residual) (2D) = 0 - ((+)pred - (-)pred)
Returns
TVectorD
Definition at line 462 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 462 of file GblFitterInfo.cc
References getFittedState().
Referenced by constructGblPoint(), getKink(), and Print().
MeasurementOnPlane genfit::GblFitterInfo::getMeasurement () const
Get the measurement on plane from stored measurement data (from last construction/update)
Returns
genfit::MeasuredStateOnPlane
Definition at line 473 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 473 of file GblFitterInfo.cc
References genfit::AbsMeasurement::constructHMatrix(), genfit::TrackPoint::getRawMeasurement(), hasMeasurements(), measCov_, measurement_, genfit::AbsFitterInfo::rep_, genfit::AbsFitterInfo::sharedPlane_, and genfit::AbsFitterInfo::trackPoint_.
StateOnPlane genfit::GblFitterInfo::getReferenceState () const inline
Returns (copy of) the stored reference 5D state at current plane with internal rep.
Returns
genfit::StateOnPlane
Definition at line 213 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 213 of file GblFitterInfo.h
References refPrediction_, genfit::AbsFitterInfo::rep_, and genfit::AbsFitterInfo::sharedPlane_.
MeasurementOnPlane genfit::GblFitterInfo::getResidual (unsigned int = 0, bool = false, bool onlyMeasurementErrors = true) const override virtual
Get the residual.
Temporarily constructs measurements and calculates residual as meas - prediction.
Always biased. Always only one (1st) measurement!
Parameters
...
...
onlyMeasurementErrors If true, covariance of measurement returned. If false, diagonalized residual error incl. correlation from track fit is returned.
Returns
genfit::MeasurementOnPlane
Implements genfit::AbsFitterInfo.
Definition at line 416 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 416 of file GblFitterInfo.cc
References genfit::AbsMeasurement::constructHMatrix(), getFittedState(), genfit::TrackPoint::getRawMeasurement(), genfit::AbsFitterInfo::getRep(), hasMeasurements(), hMatrix_, measCov_, measResidualErrors_, measurement_, genfit::AbsFitterInfo::rep_, genfit::AbsFitterInfo::sharedPlane_, and genfit::AbsFitterInfo::trackPoint_.
Referenced by constructGblPoint(), and Print().
bool genfit::GblFitterInfo::hasBackwardPrediction () const inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 230 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 230 of file GblFitterInfo.h
References hasReferenceState().
Referenced by hasBackwardUpdate(), hasPredictionsAndUpdates(), and hasUpdate().
bool genfit::GblFitterInfo::hasBackwardUpdate () const inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 232 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 232 of file GblFitterInfo.h
References hasBackwardPrediction().
Referenced by hasPredictionsAndUpdates().
bool genfit::GblFitterInfo::hasForwardPrediction () const inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 229 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 229 of file GblFitterInfo.h
References hasReferenceState().
Referenced by hasForwardUpdate(), hasPredictionsAndUpdates(), and hasUpdate().
bool genfit::GblFitterInfo::hasForwardUpdate () const inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 231 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 231 of file GblFitterInfo.h
References hasForwardPrediction().
Referenced by hasPredictionsAndUpdates().
bool genfit::GblFitterInfo::hasMeasurements () const inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 227 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 227 of file GblFitterInfo.h
References genfit::TrackPoint::hasRawMeasurements(), and genfit::AbsFitterInfo::trackPoint_.
Referenced by constructGblPoint(), getMeasurement(), getResidual(), Print(), and recalculateJacobian().
bool genfit::GblFitterInfo::hasPredictionsAndUpdates () const inline
Definition at line 234 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 234 of file GblFitterInfo.h
References hasBackwardPrediction(), hasBackwardUpdate(), hasForwardPrediction(), and hasForwardUpdate().
bool genfit::GblFitterInfo::hasReferenceState () const inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 228 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 228 of file GblFitterInfo.h
References refPrediction_.
Referenced by hasBackwardPrediction(), and hasForwardPrediction().
bool genfit::GblFitterInfo::hasUpdate (int direction) const inline override virtual
Reimplemented from genfit::AbsFitterInfo.
Definition at line 233 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 233 of file GblFitterInfo.h
References hasBackwardPrediction(), and hasForwardPrediction().
void genfit::GblFitterInfo::Print (const Option_t * = "") const override virtual
Reimplemented from genfit::AbsFitterInfo.
Definition at line 512 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 512 of file GblFitterInfo.cc
References bwdCov_, bwdPrediction_, bwdStateCorrection_, genfit::AbsMeasurement::constructHMatrix(), fwdCov_, fwdPrediction_, fwdStateCorrection_, getKinks(), genfit::TrackPoint::getRawMeasurement(), genfit::AbsFitterInfo::getRep(), getResidual(), genfit::StateOnPlane::getState(), hasMeasurements(), hMatrix_, i, genfit::AbsHMatrix::isEqual(), jacobian_, kinkDownWeights_, kinkResidualErrors_, kinkResiduals_, measCov_, measDownWeights_, measResidualErrors_, measResiduals_, measurement_, refPrediction_, genfit::AbsFitterInfo::rep_, genfit::AbsFitterInfo::sharedPlane_, and genfit::AbsFitterInfo::trackPoint_.
void genfit::GblFitterInfo::recalculateJacobian (GblFitterInfo * prevFitterInfo)
Re-extrapolates between prevFitterInfo and this point using forward state to update the Jacobian (if planes and/or states changed, internal predictions are extrapolated to new planes)
Parameters
prevFitterInfo Pointer to GblFitterInfo of previous point
Returns
void
Definition at line 346 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 346 of file GblFitterInfo.cc
References bwdCov_, bwdPrediction_, genfit::AbsMeasurement::constructPlane(), genfit::AbsTrackRep::extrapolateToPlane(), fittedStateBwd_, fittedStateFwd_, fwdCov_, fwdPrediction_, genfit::StateOnPlane::getAuxInfo(), getFittedState(), genfit::AbsTrackRep::getForwardJacobianAndNoise(), genfit::AbsFitterInfo::getPlane(), genfit::TrackPoint::getRawMeasurement(), genfit::StateOnPlane::getState(), hasMeasurements(), jacobian_, genfit::AbsFitterInfo::rep_, genfit::AbsFitterInfo::sharedPlane_, genfit::AbsFitterInfo::trackPoint_, and updateMeasurementAndPlane().
Referenced by genfit::GblFitter::processTrackWithRep().
void genfit::GblFitterInfo::reset (unsigned int measurementDim = 2, unsigned int repDim = 5)
(Initial) reset of fitter info
Parameters
measurementDim Measurement dimesion (2)
repDim Representation dimesion (5)
Returns
void
Definition at line 41 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 41 of file GblFitterInfo.cc
References bwdCov_, bwdPrediction_, bwdStateCorrection_, fwdCov_, fwdPrediction_, fwdStateCorrection_, genfit::HMatrixUV::getMatrix(), hMatrix_, kinkDownWeights_, kinkResidualErrors_, kinkResiduals_, measCov_, measDownWeights_, measResidualErrors_, measResiduals_, measurement_, refPrediction_, and zero.
Referenced by GblFitterInfo().
void genfit::GblFitterInfo::setJacobian (TMatrixD jacobian)
Set the Jacobian for further GblPoint construction.
Parameters
jacobian 5x5 TMatrixD with Jacobian for propagation of the state from previous point to this point.
Returns
void
Definition at line 91 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 91 of file GblFitterInfo.cc
References jacobian_.
Referenced by genfit::GblFitter::constructGblInfo().
void genfit::GblFitterInfo::setReferenceState (StateOnPlane & referenceState)
Set the prediction and plane (from measurement if any) You should use the user constructor instead.
Reference gets not updated internally in fitter info. After updateFitResults(...), updates affect the +/- predictions directly.
Should be called only once (so rather use constructor). Otherwise will rewrite fitted state by reference (and you have to update from fit again)
Parameters
referenceState StateOnPlane from extrapolation to this point
Returns
void
Definition at line 78 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 78 of file GblFitterInfo.cc
References bwdPrediction_, fittedStateBwd_, fittedStateFwd_, fwdPrediction_, genfit::StateOnPlane::getAuxInfo(), genfit::Track::getCovSeed(), genfit::StateOnPlane::getState(), genfit::TrackPoint::getTrack(), refPrediction_, genfit::AbsFitterInfo::rep_, genfit::AbsFitterInfo::sharedPlane_, genfit::AbsFitterInfo::trackPoint_, and updateMeasurementAndPlane().
Referenced by GblFitterInfo().
void genfit::GblFitterInfo::updateFitResults (gbl::GblTrajectory & traj)
Update fitter info from GBL fit results.
Locates itself in track/trajectory and updates predictions, errors, etc.
Parameters
traj Fitted GblTrajectory constructed with this point
Returns
void
Definition at line 246 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 246 of file GblFitterInfo.cc
References bwdCov_, bwdPrediction_, bwdStateCorrection_, fittedStateBwd_, fittedStateFwd_, fwdCov_, fwdPrediction_, fwdStateCorrection_, genfit::Track::getFitStatus(), getFittedState(), genfit::TrackPoint::getFitterInfo(), genfit::GblFitStatus::getMaxLocalFitParams(), gbl::GblTrajectory::getMeasResults(), gbl::GblTrajectory::getNumPoints(), genfit::Track::getNumPoints(), genfit::Track::getPoint(), gbl::GblTrajectory::getResults(), gbl::GblTrajectory::getScatResults(), genfit::TrackPoint::getTrack(), i, gbl::GblTrajectory::isValid(), j, kinkDownWeights_, kinkResidualErrors_, kinkResiduals_, measDownWeights_, measResidualErrors_, measResiduals_, genfit::AbsFitterInfo::rep_, genfit::AbsFitterInfo::sharedPlane_, and genfit::AbsFitterInfo::trackPoint_.
Referenced by genfit::GblFitter::updateGblInfo().
void genfit::GblFitterInfo::updateMeasurementAndPlane (const StateOnPlane & sop)
SHOULD BE USED ONLY INTERNALY! Update the plane from measurement constructed with state or take plane from state if there is no measurement. 1st raw Measurement with highest weight is constructed and stored as matrices.
Returns
void
Definition at line 195 of file GblFitterInfo.cc.
View newest version in sPHENIX GitHub at line 195 of file GblFitterInfo.cc
References genfit::AbsMeasurement::constructMeasurementsOnPlane(), genfit::StateOnPlane::getPlane(), genfit::TrackPoint::getRawMeasurement(), genfit::TrackPoint::hasRawMeasurements(), hMatrix_, i, measCov_, measurement_, genfit::AbsFitterInfo::setPlane(), and genfit::AbsFitterInfo::trackPoint_.
Referenced by recalculateJacobian(), and setReferenceState().
Member Data Documentation
TMatrixDSym genfit::GblFitterInfo::bwdCov_ private
Definition at line 257 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 257 of file GblFitterInfo.h
Referenced by clone(), getFittedState(), Print(), recalculateJacobian(), reset(), and updateFitResults().
TVectorD genfit::GblFitterInfo::bwdPrediction_ private
Definition at line 260 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 260 of file GblFitterInfo.h
Referenced by clone(), getFittedState(), Print(), recalculateJacobian(), reset(), setReferenceState(), and updateFitResults().
TVectorD genfit::GblFitterInfo::bwdStateCorrection_ private
Definition at line 255 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 255 of file GblFitterInfo.h
Referenced by clone(), Print(), reset(), and updateFitResults().
std::unique_ptr<MeasuredStateOnPlane> genfit::GblFitterInfo::fittedStateBwd_ mutable private
Definition at line 267 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 267 of file GblFitterInfo.h
Referenced by getFittedState(), recalculateJacobian(), setReferenceState(), and updateFitResults().
std::unique_ptr<MeasuredStateOnPlane> genfit::GblFitterInfo::fittedStateFwd_ mutable private
cache
Definition at line 268 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 268 of file GblFitterInfo.h
Referenced by getFittedState(), recalculateJacobian(), setReferenceState(), and updateFitResults().
TMatrixDSym genfit::GblFitterInfo::fwdCov_ private
Definition at line 258 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 258 of file GblFitterInfo.h
Referenced by clone(), getFittedState(), Print(), recalculateJacobian(), reset(), and updateFitResults().
TVectorD genfit::GblFitterInfo::fwdPrediction_ private
Definition at line 259 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 259 of file GblFitterInfo.h
Referenced by clone(), getFittedState(), Print(), recalculateJacobian(), reset(), setReferenceState(), and updateFitResults().
TVectorD genfit::GblFitterInfo::fwdStateCorrection_ private
Definition at line 256 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 256 of file GblFitterInfo.h
Referenced by clone(), Print(), reset(), and updateFitResults().
TMatrixD genfit::GblFitterInfo::hMatrix_ private
Definition at line 265 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 265 of file GblFitterInfo.h
Referenced by clone(), constructGblPoint(), getResidual(), Print(), reset(), and updateMeasurementAndPlane().
TMatrixD genfit::GblFitterInfo::jacobian_ private
Definition at line 248 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 248 of file GblFitterInfo.h
Referenced by clone(), constructGblPoint(), GblFitterInfo(), Print(), recalculateJacobian(), and setJacobian().
TVectorD genfit::GblFitterInfo::kinkDownWeights_ private
Definition at line 254 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 254 of file GblFitterInfo.h
Referenced by clone(), Print(), reset(), and updateFitResults().
TVectorD genfit::GblFitterInfo::kinkResidualErrors_ private
Definition at line 252 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 252 of file GblFitterInfo.h
Referenced by clone(), getKink(), Print(), reset(), and updateFitResults().
TVectorD genfit::GblFitterInfo::kinkResiduals_ private
Definition at line 251 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 251 of file GblFitterInfo.h
Referenced by clone(), Print(), reset(), and updateFitResults().
TMatrixDSym genfit::GblFitterInfo::measCov_ private
Definition at line 264 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 264 of file GblFitterInfo.h
Referenced by clone(), getMeasurement(), getResidual(), Print(), reset(), and updateMeasurementAndPlane().
TVectorD genfit::GblFitterInfo::measDownWeights_ private
Definition at line 253 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 253 of file GblFitterInfo.h
Referenced by clone(), Print(), reset(), and updateFitResults().
TVectorD genfit::GblFitterInfo::measResidualErrors_ private
Definition at line 250 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 250 of file GblFitterInfo.h
Referenced by clone(), getResidual(), Print(), reset(), and updateFitResults().
TVectorD genfit::GblFitterInfo::measResiduals_ private
Definition at line 249 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 249 of file GblFitterInfo.h
Referenced by clone(), Print(), reset(), and updateFitResults().
TVectorD genfit::GblFitterInfo::measurement_ private
Definition at line 263 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 263 of file GblFitterInfo.h
Referenced by clone(), getMeasurement(), getResidual(), Print(), reset(), and updateMeasurementAndPlane().
TVectorD genfit::GblFitterInfo::refPrediction_ private
Definition at line 261 of file GblFitterInfo.h.
View newest version in sPHENIX GitHub at line 261 of file GblFitterInfo.h
Referenced by clone(), getReferenceState(), hasReferenceState(), Print(), reset(), and setReferenceState().
The documentation for this class was generated from the following files:
GenFit/blob/master/GBL/include/GblFitterInfo.h
GenFit/blob/master/GBL/src/GblFitterInfo.cc