Analysis Software: genfit::GFGbl Class Reference
genfit::GFGbl Class Reference
Generic GBL implementation.
#include <GenFit/blob/master/GBL/include/GFGbl.h>
Public Member Functions
GFGbl ()
virtual ~GFGbl ()
void beginRun ()
void endRun ()
void setGBLOptions (std::string internalIterations="THC", bool enableScatterers=true, bool enableIntermediateScatterer=true)
Sets internal GBL down-weighting.
void setMP2Options (double pValueCut=0., unsigned int minNdf=1, std::string mille_file_name="millefile.dat", double chi2Cut=0.)
Sets GBL & Millepede settings.
void processTrackWithRep (Track *trk, const AbsTrackRep *rep, bool resortHits=false) override
Public Member Functions inherited from genfit::AbsFitter
AbsFitter ()
virtual ~AbsFitter ()
void processTrack (Track *, bool resortHits=false)
virtual void setDebugLvl (unsigned int lvl=1)
Private Member Functions
GFGbl (const GFGbl &)
GFGbl & operator= (GFGbl const &)
Private Attributes
std::string m_milleFileName
std::string m_gblInternalIterations
double m_pValueCut
int m_minNdf
double m_chi2Cut
bool m_enableScatterers
bool m_enableIntermediateScatterer
Additional Inherited Members
Protected Attributes inherited from genfit::AbsFitter
unsigned int debugLvl_
Detailed Description
Generic GBL implementation.
The interface class to GBL track fit
Definition at line 48 of file GFGbl.h.
View newest version in sPHENIX GitHub at line 48 of file GFGbl.h
Constructor & Destructor Documentation
genfit::GFGbl::GFGbl (const GFGbl &) private
GFGbl::GFGbl ()
Constructor
Definition at line 175 of file GFGbl.cc.
View newest version in sPHENIX GitHub at line 175 of file GFGbl.cc
virtual genfit::GFGbl::~GFGbl () inline virtual
Destructor
Definition at line 73 of file GFGbl.h.
View newest version in sPHENIX GitHub at line 73 of file GFGbl.h
Member Function Documentation
void GFGbl::beginRun ()
Creates the mille binary file for output of data for Millepede II alignment, can be set by setMP2Options
Definition at line 184 of file GFGbl.cc.
View newest version in sPHENIX GitHub at line 184 of file GFGbl.cc
References i, m_milleFileName, and name.
void GFGbl::endRun ()
Required to write and close ROOT file with debug output. Destructor cannot be used. To be called from endRun function of a module
Definition at line 231 of file GFGbl.cc.
View newest version in sPHENIX GitHub at line 231 of file GFGbl.cc
References milleFile.
GFGbl& genfit::GFGbl::operator= (GFGbl const &) private
void GFGbl::processTrackWithRep (Track * trk, const AbsTrackRep * rep, bool resortHits = false) override virtual
Performs fit on a Track. Hit resorting currently NOT supported.
Implements genfit::AbsFitter.
Definition at line 326 of file GFGbl.cc.
View newest version in sPHENIX GitHub at line 326 of file GFGbl.cc
References gbl::GblPoint::addGlobals(), gbl::GblPoint::addMeasurement(), gbl::GblPoint::addScatterer(), c2, Chi2, col, genfit::AbsMeasurement::constructHMatrix(), genfit::AbsTrackRep::extrapolateBy(), genfit::AbsTrackRep::extrapolateToPlane(), gbl::GblTrajectory::fit(), genfit::Track::getCardinalRep(), genfit::AbsTrackRep::getCharge(), genfit::AbsMeasurement::getDetId(), genfit::AbsMeasurement::getDim(), genfit::AbsTrackRep::getDim(), genfit::AbsTrackRep::getDir(), genfit::FieldManager::getFieldVal(), genfit::TrackPoint::getFitterInfo(), genfit::AbsTrackRep::getForwardJacobianAndNoise(), genfit::AbsMeasurement::getHitId(), genfit::FieldManager::getInstance(), genfit::AbsTrackRep::getMass(), gbl::GblTrajectory::getMeasResults(), genfit::AbsTrackRep::getMomMag(), genfit::Track::getNumPoints(), genfit::Track::getNumPointsWithMeasurement(), genfit::TrackPoint::getNumRawMeasurements(), genfit::AbsTrackRep::getPDG(), genfit::AbsFitterInfo::getPlane(), genfit::PlanarMeasurement::getPlaneId(), genfit::Track::getPoint(), genfit::Track::getPointWithMeasurement(), genfit::AbsMeasurement::getRawHitCoords(), genfit::AbsMeasurement::getRawHitCov(), genfit::TrackPoint::getRawMeasurement(), genfit::KalmanFitterInfo::getReferenceState(), gbl::GblTrajectory::getResults(), getScattererFromMatList(), genfit::StateOnPlane::getState(), genfit::AbsTrackRep::getSteps(), genfit::TrackPoint::hasFitterInfo(), genfit::KalmanFitterInfo::hasReferenceState(), genfit::AbsHMatrix::isEqual(), gbl::GblTrajectory::isValid(), m_chi2Cut, m_enableIntermediateScatterer, m_enableScatterers, m_gblInternalIterations, m_milleFileName, m_minNdf, m_pValueCut, gbl::GblTrajectory::milleOut(), offset, and s1.
void genfit::GFGbl::setGBLOptions (std::string internalIterations = "THC", bool enableScatterers = true, bool enableIntermediateScatterer = true) inline
Sets internal GBL down-weighting.
Parameters
internalIterations GBL internal down-weighting settings, see GBL doc
Returns
void
Definition at line 94 of file GFGbl.h.
View newest version in sPHENIX GitHub at line 94 of file GFGbl.h
References m_enableIntermediateScatterer, m_enableScatterers, and m_gblInternalIterations.
void genfit::GFGbl::setMP2Options (double pValueCut = 0., unsigned int minNdf = 1, std::string mille_file_name = "millefile.dat", double chi2Cut = 0.) inline
Sets GBL & Millepede settings.
Parameters
pValueCut minimum track p-value for MP2 output
minNdf minimum track NDF for MP2 output
mille_file_name name of MP2 binary file for output
Returns
void
Definition at line 109 of file GFGbl.h.
View newest version in sPHENIX GitHub at line 109 of file GFGbl.h
References m_chi2Cut, m_milleFileName, m_minNdf, and m_pValueCut.
Member Data Documentation
double genfit::GFGbl::m_chi2Cut private
Definition at line 58 of file GFGbl.h.
View newest version in sPHENIX GitHub at line 58 of file GFGbl.h
Referenced by processTrackWithRep(), and setMP2Options().
bool genfit::GFGbl::m_enableIntermediateScatterer private
Definition at line 60 of file GFGbl.h.
View newest version in sPHENIX GitHub at line 60 of file GFGbl.h
Referenced by processTrackWithRep(), and setGBLOptions().
bool genfit::GFGbl::m_enableScatterers private
Definition at line 59 of file GFGbl.h.
View newest version in sPHENIX GitHub at line 59 of file GFGbl.h
Referenced by processTrackWithRep(), and setGBLOptions().
std::string genfit::GFGbl::m_gblInternalIterations private
Definition at line 55 of file GFGbl.h.
View newest version in sPHENIX GitHub at line 55 of file GFGbl.h
Referenced by processTrackWithRep(), and setGBLOptions().
std::string genfit::GFGbl::m_milleFileName private
Definition at line 54 of file GFGbl.h.
View newest version in sPHENIX GitHub at line 54 of file GFGbl.h
Referenced by beginRun(), processTrackWithRep(), and setMP2Options().
int genfit::GFGbl::m_minNdf private
Definition at line 57 of file GFGbl.h.
View newest version in sPHENIX GitHub at line 57 of file GFGbl.h
Referenced by processTrackWithRep(), and setMP2Options().
double genfit::GFGbl::m_pValueCut private
Definition at line 56 of file GFGbl.h.
View newest version in sPHENIX GitHub at line 56 of file GFGbl.h
Referenced by processTrackWithRep(), and setMP2Options().
The documentation for this class was generated from the following files:
GenFit/blob/master/GBL/include/GFGbl.h
GenFit/blob/master/GBL/src/GFGbl.cc