Analysis Software: genfit::PruneFlags Struct Reference
genfit::PruneFlags Struct Reference
Info which information has been pruned from the Track.
#include <GenFit/blob/master/core/include/FitStatus.h>
Public Member Functions
PruneFlags ()
void reset ()
void setFlags (Option_t *option="")
does not reset! If a flag is already true and is not in opt, it will stay true.
bool hasFlags (Option_t *option="CFLWRMIU") const
check if all the given flags are set
bool isPruned () const
check if any of the flags is set
void Print (const Option_t *="") const
Private Types
enum fields {
C = 1 << 0, F = 1 << 1, L = 1 << 2, W = 1 << 3,
R = 1 << 4, M = 1 << 5, I = 1 << 6, U = 1 << 7
}
Private Attributes
int value
Detailed Description
Info which information has been pruned from the Track.
Possible options: C: prune all reps except cardinalRep F: prune all points except first point (also prune referenceInfo from fitterInfos) L: prune all points except last point (also prune referenceInfo from fitterInfos) FL: prune all points except first and last point (also prune referenceInfo from fitterInfos) W: prune rawMeasurements from TrackPoints R: prune referenceInfo from fitterInfos M: prune measurementInfo from fitterInfos I: if F, L, or FL is set, prune forward (backward) info of first (last) point U: if fitterInfo is a KalmanFitterInfo, prune predictions and keep updates
Definition at line 47 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 47 of file FitStatus.h
Member Enumeration Documentation
enum genfit::PruneFlags::fields private
Enumerator:
C
F
L
W
R
M
I
U
Definition at line 60 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 60 of file FitStatus.h
Constructor & Destructor Documentation
genfit::PruneFlags::PruneFlags ()
Definition at line 28 of file FitStatus.cc.
View newest version in sPHENIX GitHub at line 28 of file FitStatus.cc
References reset().
Member Function Documentation
bool genfit::PruneFlags::hasFlags (Option_t * option = "CFLWRMIU") const
check if all the given flags are set
Definition at line 53 of file FitStatus.cc.
View newest version in sPHENIX GitHub at line 53 of file FitStatus.cc
References C, F, I, L, M, R, U, value, and W.
Referenced by genfit::KalmanFitterInfo::checkConsistency(), genfit::KalmanFitterInfo::getFittedState(), and genfit::Track::prune().
bool genfit::PruneFlags::isPruned () const
check if any of the flags is set
Definition at line 68 of file FitStatus.cc.
View newest version in sPHENIX GitHub at line 68 of file FitStatus.cc
References value.
Referenced by genfit::KalmanFitterInfo::getFittedState(), and genfit::FitStatus::isTrackPruned().
void genfit::PruneFlags::Print (const Option_t * = "") const
Definition at line 73 of file FitStatus.cc.
View newest version in sPHENIX GitHub at line 73 of file FitStatus.cc
References C, F, I, L, M, genfit::printOut, R, U, value, and W.
Referenced by genfit::KalmanFitterInfo::getFittedState(), main(), and genfit::FitStatus::Print().
void genfit::PruneFlags::reset ()
Definition at line 33 of file FitStatus.cc.
View newest version in sPHENIX GitHub at line 33 of file FitStatus.cc
Referenced by PruneFlags().
void genfit::PruneFlags::setFlags (Option_t * option = "")
does not reset! If a flag is already true and is not in opt, it will stay true.
Definition at line 38 of file FitStatus.cc.
View newest version in sPHENIX GitHub at line 38 of file FitStatus.cc
References C, F, I, L, M, R, U, value, and W.
Referenced by genfit::Track::prune().
Member Data Documentation
int genfit::PruneFlags::value private
Definition at line 69 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 69 of file FitStatus.h
Referenced by hasFlags(), isPruned(), Print(), and setFlags().
The documentation for this struct was generated from the following files:
GenFit/blob/master/core/include/FitStatus.h
GenFit/blob/master/core/src/FitStatus.cc