Analysis Software: gbl::GblTrajectory Class Reference
gbl::GblTrajectory Class Reference
GBL trajectory.
#include <GenFit/blob/master/GBL/include/GblTrajectory.h>
Public Member Functions
GblTrajectory (const std::vector< GblPoint > &aPointList, bool flagCurv=true, bool flagU1dir=true, bool flagU2dir=true)
Create new (simple) trajectory from list of points.
GblTrajectory (const std::vector< GblPoint > &aPointList, unsigned int aLabel, const TMatrixDSym &aSeed, bool flagCurv=true, bool flagU1dir=true, bool flagU2dir=true)
Create new (simple) trajectory from list of points with external seed.
GblTrajectory (const std::vector< std::pair< std::vector< GblPoint >, TMatrixD > > &aPointaAndTransList)
Create new composed trajectory from list of points and transformations.
GblTrajectory (const std::vector< std::pair< std::vector< GblPoint >, TMatrixD > > &aPointaAndTransList, const TMatrixD &extDerivatives, const TVectorD &extMeasurements, const TVectorD &extPrecisions)
Create new composed trajectory from list of points and transformations with (independent) external measurements.
GblTrajectory (const std::vector< std::pair< std::vector< GblPoint >, TMatrixD > > &aPointaAndTransList, const TMatrixD &extDerivatives, const TVectorD &extMeasurements, const TMatrixDSym &extPrecisions)
Create new composed trajectory from list of points and transformations with (correlated) external measurements.
virtual ~GblTrajectory ()
bool isValid () const
Retrieve validity of trajectory.
unsigned int getNumPoints () const
Retrieve number of point from trajectory.
unsigned int getResults (int aSignedLabel, TVectorD &localPar, TMatrixDSym &localCov) const
Get fit results at point.
unsigned int getMeasResults (unsigned int aLabel, unsigned int &numRes, TVectorD &aResiduals, TVectorD &aMeasErrors, TVectorD &aResErrors, TVectorD &aDownWeights)
Get residuals from fit at point for measurement.
unsigned int getScatResults (unsigned int aLabel, unsigned int &numRes, TVectorD &aResiduals, TVectorD &aMeasErrors, TVectorD &aResErrors, TVectorD &aDownWeights)
Get (kink) residuals from fit at point for scatterer.
unsigned int getLabels (std::vector< unsigned int > &aLabelList)
Get (list of) labels of points on (simple) valid trajectory.
unsigned int getLabels (std::vector< std::vector< unsigned int > > &aLabelList)
Get (list of lists of) labels of points on (composed) valid trajectory.
unsigned int fit (double &Chi2, int &Ndf, double &lostWeight, std::string optionList="")
Perform fit of (valid) trajectory.
void milleOut (MilleBinary &aMille)
Write valid trajectory to Millepede-II binary file.
void printTrajectory (unsigned int level=0)
Print GblTrajectory.
void printPoints (unsigned int level=0)
Print GblPoints on trajectory.
void printData ()
Print GblData blocks for trajectory.
std::vector< GblData > getData ()
Private Member Functions
std::pair< std::vector
< unsigned int >, TMatrixD > getJacobian (int aSignedLabel) const
Get jacobian for transformation from fit to track parameters at point.
void getFitToLocalJacobian (std::vector< unsigned int > &anIndex, SMatrix55 &aJacobian, const GblPoint &aPoint, unsigned int measDim, unsigned int nJacobian=1) const
Get (part of) jacobian for transformation from (trajectory) fit to track parameters at point.
void getFitToKinkJacobian (std::vector< unsigned int > &anIndex, SMatrix27 &aJacobian, const GblPoint &aPoint) const
Get jacobian for transformation from (trajectory) fit to kink parameters at point.
void construct ()
Construct trajectory from list of points.
void defineOffsets ()
Define offsets from list of points.
void calcJacobians ()
Calculate Jacobians to previous/next scatterer from point to point ones.
void prepare ()
Prepare fit for simple or composed trajectory.
void buildLinearEquationSystem ()
Build linear equation system from data (blocks).
void predict ()
Calculate predictions for all points.
double downWeight (unsigned int aMethod)
Down-weight all points.
void getResAndErr (unsigned int aData, double &aResidual, double &aMeadsError, double &aResError, double &aDownWeight)
Get residual and errors from data block.
Private Attributes
unsigned int numAllPoints
Number of all points on trajectory.
std::vector< unsigned int > numPoints
Number of points on (sub)trajectory.
unsigned int numTrajectories
Number of trajectories (in composed trajectory)
unsigned int numOffsets
Number of (points with) offsets on trajectory.
unsigned int numInnerTrans
Number of inner transformations to external parameters.
unsigned int numCurvature
Number of curvature parameters (0 or 1) or external parameters.
unsigned int numParameters
Number of fit parameters.
unsigned int numLocals
Total number of (additional) local parameters.
unsigned int numMeasurements
Total number of measurements.
unsigned int externalPoint
Label of external point (or 0)
bool constructOK
Trajectory has been successfully constructed (ready for fit/output)
bool fitOK
Trajectory has been successfully fitted (results are valid)
std::vector< unsigned int > theDimension
List of active dimensions (0=u1, 1=u2) in fit.
std::vector< std::vector
< GblPoint > > thePoints
(list of) List of points on trajectory
std::vector< GblData > theData
List of data blocks.
std::vector< unsigned int > measDataIndex
mapping points to data blocks from measurements
std::vector< unsigned int > scatDataIndex
mapping points to data blocks from scatterers
TMatrixDSym externalSeed
Precision (inverse covariance matrix) of external seed.
std::vector< TMatrixD > innerTransformations
Transformations at innermost points of.
TMatrixD externalDerivatives
TVectorD externalMeasurements
TVectorD externalPrecisions
VVector theVector
Vector of linear equation system.
BorderedBandMatrix theMatrix
(Bordered band) matrix of linear equation system
Detailed Description
GBL trajectory.
List of GblPoints ordered by arc length. Can be fitted and optionally written to MP-II binary file.
Definition at line 48 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 48 of file GblTrajectory.h
Constructor & Destructor Documentation
gbl::GblTrajectory::GblTrajectory (const std::vector< GblPoint > & aPointList, bool flagCurv = true, bool flagU1dir = true, bool flagU2dir = true)
Create new (simple) trajectory from list of points.
Curved trajectory in space (default) or without curvature (q/p) or in one plane (u-direction) only.
Parameters
[in] aPointList List of points
[in] flagCurv Use q/p
[in] flagU1dir Use in u1 direction
[in] flagU2dir Use in u2 direction
Definition at line 147 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 147 of file GblTrajectory.cc
References construct(), numAllPoints, numPoints, theDimension, and thePoints.
gbl::GblTrajectory::GblTrajectory (const std::vector< GblPoint > & aPointList, unsigned int aLabel, const TMatrixDSym & aSeed, bool flagCurv = true, bool flagU1dir = true, bool flagU2dir = true)
Create new (simple) trajectory from list of points with external seed.
Curved trajectory in space (default) or without curvature (q/p) or in one plane (u-direction) only.
Parameters
[in] aPointList List of points
[in] aLabel (Signed) label of point for external seed (<0: in front, >0: after point, slope changes at scatterer!)
[in] aSeed Precision matrix of external seed
[in] flagCurv Use q/p
[in] flagU1dir Use in u1 direction
[in] flagU2dir Use in u2 direction
Definition at line 175 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 175 of file GblTrajectory.cc
References construct(), numAllPoints, numPoints, theDimension, and thePoints.
gbl::GblTrajectory::GblTrajectory (const std::vector< std::pair< std::vector< GblPoint >, TMatrixD > > & aPointsAndTransList)
Create new composed trajectory from list of points and transformations.
Composed of curved trajectory in space.
Parameters
[in] aPointsAndTransList List containing pairs with list of points and transformation (at inner (first) point)
Definition at line 198 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 198 of file GblTrajectory.cc
References construct(), innerTransformations, numAllPoints, numCurvature, numPoints, theDimension, and thePoints.
gbl::GblTrajectory::GblTrajectory (const std::vector< std::pair< std::vector< GblPoint >, TMatrixD > > & aPointsAndTransList, const TMatrixD & extDerivatives, const TVectorD & extMeasurements, const TVectorD & extPrecisions)
Create new composed trajectory from list of points and transformations with (independent) external measurements.
Composed of curved trajectory in space.
Parameters
[in] aPointsAndTransList List containing pairs with list of points and transformation (at inner (first) point)
[in] extDerivatives Derivatives of external measurements vs external parameters
[in] extMeasurements External measurements (residuals)
[in] extPrecisions Precision of external measurements
Definition at line 224 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 224 of file GblTrajectory.cc
References construct(), innerTransformations, numAllPoints, numCurvature, numPoints, theDimension, and thePoints.
gbl::GblTrajectory::GblTrajectory (const std::vector< std::pair< std::vector< GblPoint >, TMatrixD > > & aPointsAndTransList, const TMatrixD & extDerivatives, const TVectorD & extMeasurements, const TMatrixDSym & extPrecisions)
Create new composed trajectory from list of points and transformations with (correlated) external measurements.
Composed of curved trajectory in space.
Parameters
[in] aPointsAndTransList List containing pairs with list of points and transformation (at inner (first) point)
[in] extDerivatives Derivatives of external measurements vs external parameters
[in] extMeasurements External measurements (residuals)
[in] extPrecisions Precision of external measurements
Definition at line 254 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 254 of file GblTrajectory.cc
References construct(), externalDerivatives, externalMeasurements, externalPrecisions, innerTransformations, numAllPoints, numCurvature, numPoints, theDimension, and thePoints.
gbl::GblTrajectory::~GblTrajectory () virtual
Definition at line 285 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 285 of file GblTrajectory.cc
Member Function Documentation
void gbl::GblTrajectory::buildLinearEquationSystem () private
Build linear equation system from data (blocks).
Definition at line 776 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 776 of file GblTrajectory.cc
References gbl::BorderedBandMatrix::addBlockMatrix(), j, numCurvature, numLocals, numParameters, gbl::VVector::resize(), gbl::BorderedBandMatrix::resize(), theData, theMatrix, and theVector.
Referenced by fit().
void gbl::GblTrajectory::calcJacobians () private
Calculate Jacobians to previous/next scatterer from point to point ones.
Definition at line 366 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 366 of file GblTrajectory.cc
References gbl::GblPoint::addNextJacobian(), numTrajectories, and thePoints.
Referenced by construct().
void gbl::GblTrajectory::construct () private
Construct trajectory from list of points.
Trajectory is prepared for fit or output to binary file, may consists of sub-trajectories.
Definition at line 302 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 302 of file GblTrajectory.cc
References calcJacobians(), constructOK, defineOffsets(), fitOK, max, numAllPoints, numCurvature, numInnerTrans, numLocals, numMeasurements, numOffsets, numParameters, numTrajectories, prepare(), theDimension, and thePoints.
Referenced by GblTrajectory().
void gbl::GblTrajectory::defineOffsets () private
Define offsets from list of points.
Define offsets at points with scatterers and first and last point. All other points need interpolation from adjacent points with offsets.
Definition at line 344 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 344 of file GblTrajectory.cc
References numOffsets, numTrajectories, and thePoints.
Referenced by construct().
double gbl::GblTrajectory::downWeight (unsigned int aMethod) private
Down-weight all points.
Parameters
[in] aMethod M-estimator (1: Tukey, 2:Huber, 3:Cauchy)
Definition at line 1022 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 1022 of file GblTrajectory.cc
References theData.
Referenced by fit().
unsigned int gbl::GblTrajectory::fit (double & Chi2, int & Ndf, double & lostWeight, std::string optionList = "")
Perform fit of (valid) trajectory.
Optionally iterate for outlier down-weighting. Fit may fail due to singular or not positive definite matrices (internal exceptions 1-3).
Parameters
[out] Chi2 Chi2 sum (corrected for down-weighting)
[out] Ndf Number of degrees of freedom
[out] lostWeight Sum of weights lost due to down-weighting
[in] optionList Iterations for down-weighting (One character per iteration: t,h,c (or T,H,C) for Tukey, Huber or Cauchy function)
Returns
Error code (non zero value indicates failure of fit)
Definition at line 1043 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 1043 of file GblTrajectory.cc
References buildLinearEquationSystem(), constructOK, downWeight(), fitOK, i, numParameters, predict(), gbl::BorderedBandMatrix::solveAndInvertBorderedBand(), theData, theMatrix, and theVector.
Referenced by genfit::GFGbl::processTrackWithRep(), and genfit::GblFitter::processTrackWithRep().
std::vector<GblData> gbl::GblTrajectory::getData () inline
Definition at line 84 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 84 of file GblTrajectory.h
References theData.
void gbl::GblTrajectory::getFitToKinkJacobian (std::vector< unsigned int > & anIndex, SMatrix27 & aJacobian, const GblPoint & aPoint) const private
Get jacobian for transformation from (trajectory) fit to kink parameters at point.
Jacobian broken lines (q/p,..,u_i-1,u_i,u_i+1..) to kink (du') parameters.
Parameters
[out] anIndex List of fit parameters with non zero derivatives
[out] aJacobian Corresponding transformation matrix
[in] aPoint Point to use
Definition at line 583 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 583 of file GblTrajectory.cc
References gbl::GblPoint::getDerivatives(), gbl::GblPoint::getOffset(), i, numCurvature, numLocals, and theDimension.
Referenced by prepare().
void gbl::GblTrajectory::getFitToLocalJacobian (std::vector< unsigned int > & anIndex, SMatrix55 & aJacobian, const GblPoint & aPoint, unsigned int measDim, unsigned int nJacobian = 1) const private
Get (part of) jacobian for transformation from (trajectory) fit to track parameters at point.
Jacobian broken lines (q/p,..,u_i,u_i+1..) to local (q/p,u',u) parameters.
Parameters
[out] anIndex List of fit parameters with non zero derivatives
[out] aJacobian Corresponding transformation matrix
[in] aPoint Point to use
[in] measDim Dimension of 'measurement' (<=2: calculate only offset part, >2: complete matrix)
[in] nJacobian Direction (0: to previous offset, 1: to next offset)
Definition at line 488 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 488 of file GblTrajectory.cc
References gbl::GblPoint::getDerivatives(), gbl::GblPoint::getOffset(), i, numCurvature, numLocals, sign(), and theDimension.
Referenced by getJacobian(), and prepare().
std::pair< std::vector< unsigned int >, TMatrixD > gbl::GblTrajectory::getJacobian (int aSignedLabel) const private
Get jacobian for transformation from fit to track parameters at point.
Jacobian broken lines (q/p,..,u_i,u_i+1..) to track (q/p,u',u) parameters including additional local parameters.
Parameters
[in] aSignedLabel (Signed) label of point for external seed (<0: in front, >0: after point, slope changes at scatterer!)
Returns
List of fit parameters with non zero derivatives and corresponding transformation matrix
Definition at line 412 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 412 of file GblTrajectory.cc
References getFitToLocalJacobian(), i, j, numCurvature, numLocals, numPoints, numTrajectories, theDimension, and thePoints.
Referenced by getResults(), and prepare().
unsigned int gbl::GblTrajectory::getLabels (std::vector< unsigned int > & aLabelList)
Get (list of) labels of points on (simple) valid trajectory.
Parameters
[out] aLabelList List of labels (aLabelList[i] = i+1)
Returns
error code (non-zero if trajectory not valid (constructed successfully))
Definition at line 711 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 711 of file GblTrajectory.cc
References constructOK, i, and thePoints.
unsigned int gbl::GblTrajectory::getLabels (std::vector< std::vector< unsigned int > > & aLabelList)
Get (list of lists of) labels of points on (composed) valid trajectory.
Parameters
[out] aLabelList List of of lists of labels
Returns
error code (non-zero if trajectory not valid (constructed successfully))
Definition at line 729 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 729 of file GblTrajectory.cc
References constructOK, i, numTrajectories, and thePoints.
unsigned int gbl::GblTrajectory::getMeasResults (unsigned int aLabel, unsigned int & numData, TVectorD & aResiduals, TVectorD & aMeasErrors, TVectorD & aResErrors, TVectorD & aDownWeights)
Get residuals from fit at point for measurement.
Get (diagonalized) residual, error of measurement and residual and down-weighting factor for measurement at point
Parameters
[in] aLabel Label of point on trajectory
[out] numData Number of data blocks from measurement at point
[out] aResiduals Measurements-Predictions
[out] aMeasErrors Errors of Measurements
[out] aResErrors Errors of Residuals (including correlations from track fit)
[out] aDownWeights Down-Weighting factors
Returns
error code (non-zero if trajectory not fitted successfully)
Definition at line 661 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 661 of file GblTrajectory.cc
References fitOK, getResAndErr(), i, and measDataIndex.
Referenced by genfit::GFGbl::processTrackWithRep(), and genfit::GblFitterInfo::updateFitResults().
unsigned int gbl::GblTrajectory::getNumPoints () const
Retrieve number of point from trajectory.
Definition at line 294 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 294 of file GblTrajectory.cc
References numAllPoints.
Referenced by genfit::GblFitterInfo::updateFitResults().
void gbl::GblTrajectory::getResAndErr (unsigned int aData, double & aResidual, double & aMeasError, double & aResError, double & aDownWeight) private
Get residual and errors from data block.
Get residual, error of measurement and residual and down-weighting factor for (single) data block
Parameters
[in] aData Label of data block
[out] aResidual Measurement-Prediction
[out] aMeasError Error of Measurement
[out] aResError Error of Residual (including correlations from track fit)
[out] aDownWeight Down-Weighting factor
Definition at line 756 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 756 of file GblTrajectory.cc
References gbl::BorderedBandMatrix::getBlockMatrix(), j, theData, and theMatrix.
Referenced by getMeasResults(), and getScatResults().
unsigned int gbl::GblTrajectory::getResults (int aSignedLabel, TVectorD & localPar, TMatrixDSym & localCov) const
Get fit results at point.
Get corrections and covariance matrix for local track and additional parameters in forward or backward direction.
The point is identified by its label (1..number(points)), the sign distinguishes the backward (facing previous point) and forward 'side' (facing next point). For scatterers the track direction may change in between.
Parameters
[in] aSignedLabel (Signed) label of point on trajectory (<0: in front, >0: after point, slope changes at scatterer!)
[out] localPar Corrections for local parameters
[out] localCov Covariance for local parameters
Returns
error code (non-zero if trajectory not fitted successfully)
Definition at line 631 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 631 of file GblTrajectory.cc
References fitOK, gbl::BorderedBandMatrix::getBlockMatrix(), getJacobian(), i, theMatrix, and theVector.
Referenced by genfit::GFGbl::processTrackWithRep(), and genfit::GblFitterInfo::updateFitResults().
unsigned int gbl::GblTrajectory::getScatResults (unsigned int aLabel, unsigned int & numData, TVectorD & aResiduals, TVectorD & aMeasErrors, TVectorD & aResErrors, TVectorD & aDownWeights)
Get (kink) residuals from fit at point for scatterer.
Get (diagonalized) residual, error of measurement and residual and down-weighting factor for scatterering kinks at point
Parameters
[in] aLabel Label of point on trajectory
[out] numData Number of data blocks from scatterer at point
[out] aResiduals (kink)Measurements-(kink)Predictions
[out] aMeasErrors Errors of (kink)Measurements
[out] aResErrors Errors of Residuals (including correlations from track fit)
[out] aDownWeights Down-Weighting factors
Returns
error code (non-zero if trajectory not fitted successfully)
Definition at line 690 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 690 of file GblTrajectory.cc
References fitOK, getResAndErr(), i, and scatDataIndex.
Referenced by genfit::GblFitterInfo::updateFitResults().
bool gbl::GblTrajectory::isValid () const
Retrieve validity of trajectory.
Definition at line 289 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 289 of file GblTrajectory.cc
References constructOK.
Referenced by genfit::GFGbl::processTrackWithRep(), genfit::GblFitterInfo::updateFitResults(), and genfit::GblFitter::updateGblInfo().
void gbl::GblTrajectory::milleOut (MilleBinary & aMille)
Write valid trajectory to Millepede-II binary file.
Definition at line 1091 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 1091 of file GblTrajectory.cc
References gbl::MilleBinary::addData(), constructOK, theData, and gbl::MilleBinary::writeRecord().
Referenced by genfit::GFGbl::processTrackWithRep().
void gbl::GblTrajectory::predict () private
Calculate predictions for all points.
Definition at line 1011 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 1011 of file GblTrajectory.cc
References theData, and theVector.
Referenced by fit().
void gbl::GblTrajectory::prepare () private
Prepare fit for simple or composed trajectory.
Generate data (blocks) from measurements, kinks, external seed and measurements.
Definition at line 797 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 797 of file GblTrajectory.cc
References gbl::GblData::addDerivatives(), externalDerivatives, externalMeasurements, externalPoint, externalPrecisions, externalSeed, getFitToKinkJacobian(), getFitToLocalJacobian(), getJacobian(), i, index, innerTransformations, j, k, measDataIndex, numAllPoints, numCurvature, numInnerTrans, numLocals, numMeasurements, numOffsets, numTrajectories, scatDataIndex, theData, theDimension, and thePoints.
Referenced by construct().
void gbl::GblTrajectory::printData ()
Print GblData blocks for trajectory.
Definition at line 1195 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 1195 of file GblTrajectory.cc
References theData.
void gbl::GblTrajectory::printPoints (unsigned int level = 0)
Print GblPoints on trajectory.
Parameters
[in] level print level (0: minimum, >0: more)
Definition at line 1183 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 1183 of file GblTrajectory.cc
References numTrajectories, and thePoints.
void gbl::GblTrajectory::printTrajectory (unsigned int level = 0)
Print GblTrajectory.
Parameters
[in] level print level (0: minimum, >0: more)
Definition at line 1117 of file GblTrajectory.cc.
View newest version in sPHENIX GitHub at line 1117 of file GblTrajectory.cc
References constructOK, externalDerivatives, externalMeasurements, externalPoint, externalPrecisions, externalSeed, fitOK, i, innerTransformations, numAllPoints, numInnerTrans, numMeasurements, numOffsets, numParameters, gbl::VVector::print(), gbl::BorderedBandMatrix::printMatrix(), theDimension, theMatrix, and theVector.
Member Data Documentation
bool gbl::GblTrajectory::constructOK private
Trajectory has been successfully constructed (ready for fit/output)
Definition at line 97 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 97 of file GblTrajectory.h
Referenced by construct(), fit(), getLabels(), isValid(), milleOut(), and printTrajectory().
TMatrixD gbl::GblTrajectory::externalDerivatives private
Definition at line 107 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 107 of file GblTrajectory.h
Referenced by GblTrajectory(), prepare(), and printTrajectory().
TVectorD gbl::GblTrajectory::externalMeasurements private
Definition at line 108 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 108 of file GblTrajectory.h
Referenced by GblTrajectory(), prepare(), and printTrajectory().
unsigned int gbl::GblTrajectory::externalPoint private
Label of external point (or 0)
Definition at line 96 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 96 of file GblTrajectory.h
Referenced by prepare(), and printTrajectory().
TVectorD gbl::GblTrajectory::externalPrecisions private
Definition at line 109 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 109 of file GblTrajectory.h
Referenced by GblTrajectory(), prepare(), and printTrajectory().
TMatrixDSym gbl::GblTrajectory::externalSeed private
Precision (inverse covariance matrix) of external seed.
Definition at line 104 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 104 of file GblTrajectory.h
Referenced by prepare(), and printTrajectory().
bool gbl::GblTrajectory::fitOK private
Trajectory has been successfully fitted (results are valid)
Definition at line 98 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 98 of file GblTrajectory.h
Referenced by construct(), fit(), getMeasResults(), getResults(), getScatResults(), and printTrajectory().
std::vector<TMatrixD> gbl::GblTrajectory::innerTransformations private
Transformations at innermost points of.
Definition at line 105 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 105 of file GblTrajectory.h
Referenced by GblTrajectory(), prepare(), and printTrajectory().
std::vector<unsigned int> gbl::GblTrajectory::measDataIndex private
mapping points to data blocks from measurements
Definition at line 102 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 102 of file GblTrajectory.h
Referenced by getMeasResults(), and prepare().
unsigned int gbl::GblTrajectory::numAllPoints private
Number of all points on trajectory.
Definition at line 87 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 87 of file GblTrajectory.h
Referenced by construct(), GblTrajectory(), getNumPoints(), prepare(), and printTrajectory().
unsigned int gbl::GblTrajectory::numCurvature private
Number of curvature parameters (0 or 1) or external parameters.
Definition at line 92 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 92 of file GblTrajectory.h
Referenced by buildLinearEquationSystem(), construct(), GblTrajectory(), getFitToKinkJacobian(), getFitToLocalJacobian(), getJacobian(), and prepare().
unsigned int gbl::GblTrajectory::numInnerTrans private
Number of inner transformations to external parameters.
Definition at line 91 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 91 of file GblTrajectory.h
Referenced by construct(), prepare(), and printTrajectory().
unsigned int gbl::GblTrajectory::numLocals private
Total number of (additional) local parameters.
Definition at line 94 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 94 of file GblTrajectory.h
Referenced by buildLinearEquationSystem(), construct(), getFitToKinkJacobian(), getFitToLocalJacobian(), getJacobian(), and prepare().
unsigned int gbl::GblTrajectory::numMeasurements private
Total number of measurements.
Definition at line 95 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 95 of file GblTrajectory.h
Referenced by construct(), prepare(), and printTrajectory().
unsigned int gbl::GblTrajectory::numOffsets private
Number of (points with) offsets on trajectory.
Definition at line 90 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 90 of file GblTrajectory.h
Referenced by construct(), defineOffsets(), prepare(), and printTrajectory().
unsigned int gbl::GblTrajectory::numParameters private
Number of fit parameters.
Definition at line 93 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 93 of file GblTrajectory.h
Referenced by buildLinearEquationSystem(), construct(), fit(), and printTrajectory().
std::vector<unsigned int> gbl::GblTrajectory::numPoints private
Number of points on (sub)trajectory.
Definition at line 88 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 88 of file GblTrajectory.h
Referenced by GblTrajectory(), and getJacobian().
unsigned int gbl::GblTrajectory::numTrajectories private
Number of trajectories (in composed trajectory)
Definition at line 89 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 89 of file GblTrajectory.h
Referenced by calcJacobians(), construct(), defineOffsets(), getJacobian(), getLabels(), prepare(), and printPoints().
std::vector<unsigned int> gbl::GblTrajectory::scatDataIndex private
mapping points to data blocks from scatterers
Definition at line 103 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 103 of file GblTrajectory.h
Referenced by getScatResults(), and prepare().
std::vector<GblData> gbl::GblTrajectory::theData private
List of data blocks.
Definition at line 101 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 101 of file GblTrajectory.h
Referenced by buildLinearEquationSystem(), downWeight(), fit(), getData(), getResAndErr(), milleOut(), predict(), prepare(), and printData().
std::vector<unsigned int> gbl::GblTrajectory::theDimension private
List of active dimensions (0=u1, 1=u2) in fit.
Definition at line 99 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 99 of file GblTrajectory.h
Referenced by construct(), GblTrajectory(), getFitToKinkJacobian(), getFitToLocalJacobian(), getJacobian(), prepare(), and printTrajectory().
BorderedBandMatrix gbl::GblTrajectory::theMatrix private
(Bordered band) matrix of linear equation system
Definition at line 111 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 111 of file GblTrajectory.h
Referenced by buildLinearEquationSystem(), fit(), getResAndErr(), getResults(), and printTrajectory().
std::vector<std::vector<GblPoint> > gbl::GblTrajectory::thePoints private
(list of) List of points on trajectory
Definition at line 100 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 100 of file GblTrajectory.h
Referenced by calcJacobians(), construct(), defineOffsets(), GblTrajectory(), getJacobian(), getLabels(), prepare(), and printPoints().
VVector gbl::GblTrajectory::theVector private
Vector of linear equation system.
Definition at line 110 of file GblTrajectory.h.
View newest version in sPHENIX GitHub at line 110 of file GblTrajectory.h
Referenced by buildLinearEquationSystem(), fit(), getResults(), predict(), and printTrajectory().
The documentation for this class was generated from the following files:
GenFit/blob/master/GBL/include/GblTrajectory.h
GenFit/blob/master/GBL/src/GblTrajectory.cc