Analysis Software: KFEfficiencyParticleInfo Class Reference
KFEfficiencyParticleInfo Class Reference
A helper class to define parameters of the decay list in KFPartEfficiencies.
#include <KFParticle/blob/master/KFParticlePerformance/KFPartEfficiencies.h>
Public Member Functions
KFEfficiencyParticleInfo ()
KFEfficiencyParticleInfo (std::string name, std::string title, int pdg, float histoMin, float histoMax, float mass, float lifeTime, int charge, float massSigma)
Constructor with all parameters set in. There is no other way to define the parameters other then use this constructor.
~KFEfficiencyParticleInfo ()
std::string Name () const
Returns name of the decay in the file with histograms.
std::string Title () const
Returns name of the decay in the output table with efficiency.
int PDG () const
Returns the assigned PDG code.
float HistoMin () const
Returns lower boundary in the mass histogram for the current decay.
float HistoMax () const
Returns upper boundary in the mass histogram for the current decay.
float Mass () const
Returns table mass of the particle.
float LifeTime () const
Returns lifetime of the particle.
int Charge () const
Returns charge of the particle in units of the elementary charge.
float MassSigma () const
Returns expected width of the mass peak, used in the side bands method.
Private Attributes
std::string fName
Name of the decay in the file with histograms.
std::string fTitle
Name of the decay in the output table with efficiency.
int fPDG
PDG code assigned to the current decay in the scheme of KF Particle Finder.
float fHistoMin
Lower boundary in the mass histogram for the current decay.
float fHistoMax
Upper boundary in the mass histogram for the current decay.
float fMass
Table mass of the particle.
float fLifeTime
Lifetime of the particle in seconds.
int fCharge
Charge in units of the elementary charge.
float fMassSigma
Expected width of the decay, determines peak sigma for the side bands method.
Detailed Description
A helper class to define parameters of the decay list in KFPartEfficiencies.
Author
M.Zyzak, I.Kisel
Date
05.02.2019
Version
1.0
Definition at line 42 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 42 of file KFPartEfficiencies.h
Constructor & Destructor Documentation
KFEfficiencyParticleInfo::KFEfficiencyParticleInfo () inline
Definition at line 45 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 45 of file KFPartEfficiencies.h
KFEfficiencyParticleInfo::KFEfficiencyParticleInfo (std::string name, std::string title, int pdg, float histoMin, float histoMax, float mass, float lifeTime, int charge, float massSigma) inline
Constructor with all parameters set in. There is no other way to define the parameters other then use this constructor.
Definition at line 47 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 47 of file KFPartEfficiencies.h
KFEfficiencyParticleInfo::~KFEfficiencyParticleInfo () inline
Definition at line 49 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 49 of file KFPartEfficiencies.h
Member Function Documentation
int KFEfficiencyParticleInfo::Charge () const inline
Returns charge of the particle in units of the elementary charge.
Definition at line 59 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 59 of file KFPartEfficiencies.h
References fCharge.
Referenced by KFPartEfficiencies::KFPartEfficiencies().
float KFEfficiencyParticleInfo::HistoMax () const inline
Returns upper boundary in the mass histogram for the current decay.
Definition at line 56 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 56 of file KFPartEfficiencies.h
References fHistoMax.
Referenced by KFPartEfficiencies::KFPartEfficiencies().
float KFEfficiencyParticleInfo::HistoMin () const inline
Returns lower boundary in the mass histogram for the current decay.
Definition at line 55 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 55 of file KFPartEfficiencies.h
References fHistoMin.
Referenced by KFPartEfficiencies::KFPartEfficiencies().
float KFEfficiencyParticleInfo::LifeTime () const inline
Returns lifetime of the particle.
Definition at line 58 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 58 of file KFPartEfficiencies.h
References fLifeTime.
Referenced by KFPartEfficiencies::KFPartEfficiencies().
float KFEfficiencyParticleInfo::Mass () const inline
Returns table mass of the particle.
Definition at line 57 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 57 of file KFPartEfficiencies.h
References fMass.
Referenced by KFPartEfficiencies::KFPartEfficiencies().
float KFEfficiencyParticleInfo::MassSigma () const inline
Returns expected width of the mass peak, used in the side bands method.
Definition at line 60 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 60 of file KFPartEfficiencies.h
References fMassSigma.
Referenced by KFPartEfficiencies::KFPartEfficiencies().
std::string KFEfficiencyParticleInfo::Name () const inline
Returns name of the decay in the file with histograms.
Definition at line 52 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 52 of file KFPartEfficiencies.h
References fName.
Referenced by KFPartEfficiencies::KFPartEfficiencies().
int KFEfficiencyParticleInfo::PDG () const inline
Returns the assigned PDG code.
Definition at line 54 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 54 of file KFPartEfficiencies.h
References fPDG.
Referenced by KFPartEfficiencies::KFPartEfficiencies().
std::string KFEfficiencyParticleInfo::Title () const inline
Returns name of the decay in the output table with efficiency.
Definition at line 53 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 53 of file KFPartEfficiencies.h
References fTitle.
Referenced by KFPartEfficiencies::KFPartEfficiencies().
Member Data Documentation
int KFEfficiencyParticleInfo::fCharge private
Charge in units of the elementary charge.
Definition at line 70 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 70 of file KFPartEfficiencies.h
Referenced by Charge().
float KFEfficiencyParticleInfo::fHistoMax private
Upper boundary in the mass histogram for the current decay.
Definition at line 67 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 67 of file KFPartEfficiencies.h
Referenced by HistoMax().
float KFEfficiencyParticleInfo::fHistoMin private
Lower boundary in the mass histogram for the current decay.
Definition at line 66 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 66 of file KFPartEfficiencies.h
Referenced by HistoMin().
float KFEfficiencyParticleInfo::fLifeTime private
Lifetime of the particle in seconds.
Definition at line 69 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 69 of file KFPartEfficiencies.h
Referenced by LifeTime().
float KFEfficiencyParticleInfo::fMass private
Table mass of the particle.
Definition at line 68 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 68 of file KFPartEfficiencies.h
Referenced by Mass().
float KFEfficiencyParticleInfo::fMassSigma private
Expected width of the decay, determines peak sigma for the side bands method.
Definition at line 71 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 71 of file KFPartEfficiencies.h
Referenced by MassSigma().
std::string KFEfficiencyParticleInfo::fName private
Name of the decay in the file with histograms.
Definition at line 63 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 63 of file KFPartEfficiencies.h
Referenced by Name().
int KFEfficiencyParticleInfo::fPDG private
PDG code assigned to the current decay in the scheme of KF Particle Finder.
Definition at line 65 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 65 of file KFPartEfficiencies.h
Referenced by PDG().
std::string KFEfficiencyParticleInfo::fTitle private
Name of the decay in the output table with efficiency.
Definition at line 64 of file KFPartEfficiencies.h.
View newest version in sPHENIX GitHub at line 64 of file KFPartEfficiencies.h
Referenced by Title().
The documentation for this class was generated from the following file:
KFParticle/blob/master/KFParticlePerformance/KFPartEfficiencies.h