Analysis Software: KFPInputData Class Reference
KFPInputData Class Reference
Class with the input data for KF Particle Finder: tracks, primary vertex and magnetic field.
#include <KFParticle/blob/master/KFParticle/KFPInputData.h>
Public Member Functions
void * operator new (size_t size)
new operator for allocation of the SIMD-alligned dynamic memory allocation
void * operator new[] (size_t size)
new operator for allocation of the SIMD-alligned dynamic memory allocation
void * operator new (size_t size, void *ptr)
new operator for allocation of the SIMD-alligned dynamic memory allocation
void * operator new[] (size_t size, void *ptr)
new operator for allocation of the SIMD-alligned dynamic memory allocation
void operator delete (void *ptr, size_t)
delete operator for the SIMD-alligned dynamic memory release
void operator delete[] (void *ptr, size_t)
delete operator for the SIMD-alligned dynamic memory release
KFPInputData ()
~KFPInputData ()
bool ReadDataFromFile (std::string prefix)
void SetDataToVector (int *data, int &dataSize)
void ReadDataFromVector (int *data)
void Print ()
KFPTrackVector * GetTracks ()
Returns pointer to the array with track vectors.
float GetBz () const
Returns value of the constant field Bz.
const std::vector< KFParticle > & GetPV () const
Returns vector with primary vertices.
const KFPInputData & operator= (const KFPInputData &data)
KFPInputData (const KFPInputData &data)
Protected Member Functions
KFPTrackVector fTracks[NInputSets] __attribute__ ((aligned(sizeof(float_v))))
Protected Attributes
std::vector< KFParticle > fPV
Vector with primary vertices.
float fBz
Constant homogenious one-component magnetic field Bz.
Detailed Description
Class with the input data for KF Particle Finder: tracks, primary vertex and magnetic field.
Author
M.Zyzak, I.Kisel
Date
05.02.2019
Version
1.0
The class is used to transfer the data between devices: CPU and Intel Xeon Phi. The memory is aligned with the size of the SIMD vectors.
Definition at line 77 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 77 of file KFPInputData.h
Constructor & Destructor Documentation
KFPInputData::KFPInputData () inline
Definition at line 88 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 88 of file KFPInputData.h
KFPInputData::~KFPInputData () inline
Definition at line 89 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 89 of file KFPInputData.h
KFPInputData::KFPInputData (const KFPInputData & data) inline
Copies input data from object "data" to the current object.
Parameters
[in] data - input data
Definition at line 308 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 308 of file KFPInputData.h
References fBz, fPV, fTracks, i, and NInputSets.
Member Function Documentation
KFPTrackVector fTracks [NInputSets] KFPInputData::__attribute__ ((aligned(sizeof(float_v)))) protected
Array of track vectors:
0 - positive secondary tracks stored at the first point;
1 - negative secondary tracks stored at the first point;
2 - positive primary tracks stored at the first point;
3 - positive primary tracks stored at the first point;
4 - positive secondary tracks stored at the last point;
5 - negative secondary tracks stored at the last point;
6 - positive primary tracks stored at the last point;
7 - positive primary tracks stored at the last point.
See Also
KFPTrackVector for documentation.
float KFPInputData::GetBz () const inline
Returns value of the constant field Bz.
Definition at line 295 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 295 of file KFPInputData.h
References fBz.
const std::vector<KFParticle>& KFPInputData::GetPV () const inline
Returns vector with primary vertices.
Definition at line 296 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 296 of file KFPInputData.h
References fPV.
KFPTrackVector* KFPInputData::GetTracks () inline
Returns pointer to the array with track vectors.
Definition at line 294 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 294 of file KFPInputData.h
References fTracks.
void KFPInputData::operator delete (void * ptr, size_t) inline
delete operator for the SIMD-alligned dynamic memory release
Definition at line 85 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 85 of file KFPInputData.h
void KFPInputData::operator delete[] (void * ptr, size_t) inline
delete operator for the SIMD-alligned dynamic memory release
Definition at line 86 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 86 of file KFPInputData.h
void* KFPInputData::operator new (size_t size) inline
new operator for allocation of the SIMD-alligned dynamic memory allocation
Definition at line 81 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 81 of file KFPInputData.h
void* KFPInputData::operator new (size_t size, void * ptr) inline
new operator for allocation of the SIMD-alligned dynamic memory allocation
Definition at line 83 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 83 of file KFPInputData.h
void* KFPInputData::operator new[] (size_t size) inline
new operator for allocation of the SIMD-alligned dynamic memory allocation
Definition at line 82 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 82 of file KFPInputData.h
void* KFPInputData::operator new[] (size_t size, void * ptr) inline
new operator for allocation of the SIMD-alligned dynamic memory allocation
Definition at line 84 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 84 of file KFPInputData.h
const KFPInputData& KFPInputData::operator= (const KFPInputData & data) inline
Copies input data from object "data" to the current object. Returns the current object.
Parameters
[in] data - input data
Definition at line 298 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 298 of file KFPInputData.h
References fBz, fPV, fTracks, i, and NInputSets.
void KFPInputData::Print () inline
Prints all fields of the current object.
Definition at line 262 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 262 of file KFPInputData.h
References Covariance(), fBz, fPV, fTracks, NInputSets, TauVsDIS_MachineLearning_Differentiation::X, TauVsDIS_MachineLearning_Differentiation::Y, and SVM_v1::Z.
bool KFPInputData::ReadDataFromFile (std::string prefix) inline
Reads the input data from the input file with the name defined by "prefix".
Parameters
[in] prefix - string with the name of the input file
Definition at line 91 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 91 of file KFPInputData.h
References Covariance(), fBz, fPV, fTracks, Parameter(), KFPTrackVector::Resize(), KFPTrackVector::SetCovariance(), KFPTrackVector::SetId(), KFPTrackVector::SetLastElectron(), KFPTrackVector::SetLastKaon(), KFPTrackVector::SetLastMuon(), KFPTrackVector::SetLastPion(), KFPTrackVector::SetLastProton(), KFPTrackVector::SetParameter(), KFPTrackVector::SetPDG(), KFPTrackVector::SetPVIndex(), KFPTrackVector::SetQ(), KFPTrackVector::Size(), and value.
void KFPInputData::ReadDataFromVector (int * data) inline
Reads input data from the given memory.
Parameters
[in] data - pointer to the memory with the input data
Definition at line 224 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 224 of file KFPInputData.h
References fBz, fPV, fTracks, NInputSets, offset, KFPTrackVector::ReadDataFromVector(), and KFPTrackVector::Resize().
void KFPInputData::SetDataToVector (int * data, int & dataSize) inline
Stores information to the memory under pointer "data".
Parameters
[out] data - memory, where input information will be stored
[out] dataSize - size of the stored memory in "int" (or bloks of 4 bytes, or 32 bits)
Definition at line 180 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 180 of file KFPInputData.h
References DataSize(), fBz, fPV, fTracks, NInputSets, offset, and Size().
Member Data Documentation
float KFPInputData::fBz protected
Constant homogenious one-component magnetic field Bz.
Definition at line 331 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 331 of file KFPInputData.h
Referenced by GetBz(), KFPInputData(), operator=(), Print(), ReadDataFromFile(), ReadDataFromVector(), and SetDataToVector().
std::vector<KFParticle> KFPInputData::fPV protected
Vector with primary vertices.
Definition at line 330 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 330 of file KFPInputData.h
Referenced by GetPV(), KFPInputData(), operator=(), Print(), ReadDataFromFile(), ReadDataFromVector(), and SetDataToVector().
The documentation for this class was generated from the following file:
KFParticle/blob/master/KFParticle/KFPInputData.h