Analysis Software: genfit::GFRavePropagator Class Reference
genfit::GFRavePropagator Class Reference
GFRavePropagator class.
#include <GenFit/blob/master/GFRave/include/GFRavePropagator.h>
Public Member Functions
GFRavePropagator ()
virtual GFRavePropagator * copy () const
virtual rave::Track closestTo (const rave::Track &, const rave::Point3D &, bool transverse) const
virtual std::pair< rave::Track,
double > to (const rave::Track &orig, const ravesurf::Plane &) const
virtual std::pair< rave::Track,
double > to (const rave::Track &orig, const ravesurf::Cylinder &) const
virtual ~GFRavePropagator ()
void setIdGFTrackStateMap (std::map< int, genfit::trackAndState > *map)
Private Attributes
std::map< int,
genfit::trackAndState > * IdGFTrackStateMap_
Detailed Description
GFRavePropagator class.
Inherits from rave::Propagator. A map has to be provided, containing pointers the genfit::Tracks, as well as pointers to clones of fitted states. The GFRavePropagator uses the information of the rave::track to set the state and covariance of the corresponding MeasuredStateOnPlane, extrapolates and then returns a new rave::track with the extrapolated state and covariance.
Definition at line 55 of file GFRavePropagator.h.
View newest version in sPHENIX GitHub at line 55 of file GFRavePropagator.h
Constructor & Destructor Documentation
genfit::GFRavePropagator::GFRavePropagator ()
Definition at line 30 of file GFRavePropagator.cc.
View newest version in sPHENIX GitHub at line 30 of file GFRavePropagator.cc
Referenced by copy().
genfit::GFRavePropagator::~GFRavePropagator () virtual
Definition at line 44 of file GFRavePropagator.cc.
View newest version in sPHENIX GitHub at line 44 of file GFRavePropagator.cc
Member Function Documentation
rave::Track genfit::GFRavePropagator::closestTo (const rave::Track & orig, const rave::Point3D & pt, bool transverse) const virtual
Definition at line 73 of file GFRavePropagator.cc.
View newest version in sPHENIX GitHub at line 73 of file GFRavePropagator.cc
References genfit::GFTrackToTrack(), IdGFTrackStateMap_, and genfit::Point3DToTVector3().
GFRavePropagator * genfit::GFRavePropagator::copy () const virtual
Definition at line 37 of file GFRavePropagator.cc.
View newest version in sPHENIX GitHub at line 37 of file GFRavePropagator.cc
References GFRavePropagator().
void genfit::GFRavePropagator::setIdGFTrackStateMap (std::map< int, genfit::trackAndState > * map)
Definition at line 90 of file GFRavePropagator.cc.
View newest version in sPHENIX GitHub at line 90 of file GFRavePropagator.cc
References IdGFTrackStateMap_.
std::pair< rave::Track, double > genfit::GFRavePropagator::to (const rave::Track & orig, const ravesurf::Plane & rplane) const virtual
Definition at line 61 of file GFRavePropagator.cc.
View newest version in sPHENIX GitHub at line 61 of file GFRavePropagator.cc
References genfit::GFTrackToTrack(), IdGFTrackStateMap_, path, and genfit::PlaneToGFDetPlane().
Referenced by __example_2.f__(), __example_3.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), attflv(), attrad(), eix(), eixint(), gmin(), gmre(), hiboost(), hijcsc(), hijels(), hijfrg(), hijhrd(), hijing(), hijset(), hijsft(), hijsrt(), hirnd(), hirnd2(), jetini(), luprep(), parton(), pyhiremn(), pyhistfu(), quench(), romg(), sgmin(), and vegas().
std::pair< rave::Track, double > genfit::GFRavePropagator::to (const rave::Track & orig, const ravesurf::Cylinder & rcyl) const virtual
Definition at line 51 of file GFRavePropagator.cc.
View newest version in sPHENIX GitHub at line 51 of file GFRavePropagator.cc
Member Data Documentation
std::map< int, genfit::trackAndState >* genfit::GFRavePropagator::IdGFTrackStateMap_ private
Definition at line 74 of file GFRavePropagator.h.
View newest version in sPHENIX GitHub at line 74 of file GFRavePropagator.h
Referenced by closestTo(), setIdGFTrackStateMap(), and to().
The documentation for this class was generated from the following files:
GenFit/blob/master/GFRave/include/GFRavePropagator.h
GenFit/blob/master/GFRave/src/GFRavePropagator.cc