Analysis Software: genfit::AbsTrackRep Class Reference
genfit::AbsTrackRep Class Reference abstract
Abstract base class for a track representation.
#include <GenFit/blob/master/core/include/AbsTrackRep.h>
Public Member Functions
AbsTrackRep ()
AbsTrackRep (int pdgCode, char propDir=0)
virtual ~AbsTrackRep ()
virtual AbsTrackRep * clone () const =0
Clone the trackRep.
virtual double extrapolateToPlane (StateOnPlane &state, const genfit::SharedPlanePtr &plane, bool stopAtBoundary=false, bool calcJacobianNoise=false) const =0
Extrapolates the state to plane, and returns the extrapolation length and, via reference, the extrapolated state.
virtual double extrapolateToLine (StateOnPlane &state, const TVector3 &linePoint, const TVector3 &lineDirection, bool stopAtBoundary=false, bool calcJacobianNoise=false) const =0
Extrapolates the state to the POCA to a line, and returns the extrapolation length and, via reference, the extrapolated state.
virtual double extrapolateToLine (StateOnPlane &state, const TVector3 &point1, const TVector3 &point2, TVector3 &poca, TVector3 &dirInPoca, TVector3 &poca_onwire, bool stopAtBoundary=false, bool calcJacobianNoise=false) const
Resembles the interface of GFAbsTrackRep in old versions of genfit.
virtual double extrapolateToPoint (StateOnPlane &state, const TVector3 &point, bool stopAtBoundary=false, bool calcJacobianNoise=false) const =0
Extrapolates the state to the POCA to a point, and returns the extrapolation length and, via reference, the extrapolated state.
virtual double extrapolateToPoint (StateOnPlane &state, const TVector3 &point, const TMatrixDSym &G, bool stopAtBoundary=false, bool calcJacobianNoise=false) const =0
Extrapolates the state to the POCA to a point in the metric of G, and returns the extrapolation length and, via reference, the extrapolated state.
virtual double extrapolateToCylinder (StateOnPlane &state, double radius, const TVector3 &linePoint=TVector3(0., 0., 0.), const TVector3 &lineDirection=TVector3(0., 0., 1.), bool stopAtBoundary=false, bool calcJacobianNoise=false) const =0
Extrapolates the state to the cylinder surface, and returns the extrapolation length and, via reference, the extrapolated state.
virtual double extrapolateToCone (StateOnPlane &state, double radius, const TVector3 &linePoint=TVector3(0., 0., 0.), const TVector3 &lineDirection=TVector3(0., 0., 1.), bool stopAtBoundary=false, bool calcJacobianNoise=false) const =0
Extrapolates the state to the cone surface, and returns the extrapolation length and, via reference, the extrapolated state.
virtual double extrapolateToSphere (StateOnPlane &state, double radius, const TVector3 &point=TVector3(0., 0., 0.), bool stopAtBoundary=false, bool calcJacobianNoise=false) const =0
Extrapolates the state to the sphere surface, and returns the extrapolation length and, via reference, the extrapolated state.
virtual double extrapolateBy (StateOnPlane &state, double step, bool stopAtBoundary=false, bool calcJacobianNoise=false) const =0
Extrapolates the state by step (cm) and returns the extrapolation length and, via reference, the extrapolated state.
double extrapolateToMeasurement (StateOnPlane &state, const AbsMeasurement *measurement, bool stopAtBoundary=false, bool calcJacobianNoise=false) const
extrapolate to an AbsMeasurement
virtual unsigned int getDim () const =0
Get the dimension of the state vector used by the track representation.
virtual TVector3 getPos (const StateOnPlane &state) const =0
Get the cartesian position of a state.
virtual TVector3 getMom (const StateOnPlane &state) const =0
Get the cartesian momentum vector of a state.
TVector3 getDir (const StateOnPlane &state) const
Get the direction vector of a state.
virtual void getPosMom (const StateOnPlane &state, TVector3 &pos, TVector3 &mom) const =0
Get cartesian position and momentum vector of a state.
void getPosDir (const StateOnPlane &state, TVector3 &pos, TVector3 &dir) const
Get cartesian position and direction vector of a state.
virtual TVectorD get6DState (const StateOnPlane &state) const
Get the 6D state vector (x, y, z, p_x, p_y, p_z).
virtual TMatrixDSym get6DCov (const MeasuredStateOnPlane &state) const =0
Get the 6D covariance.
virtual void getPosMomCov (const MeasuredStateOnPlane &state, TVector3 &pos, TVector3 &mom, TMatrixDSym &cov) const =0
Translates MeasuredStateOnPlane into 3D position, momentum and 6x6 covariance.
virtual void get6DStateCov (const MeasuredStateOnPlane &state, TVectorD &stateVec, TMatrixDSym &cov) const
Translates MeasuredStateOnPlane into 6D state vector (x, y, z, p_x, p_y, p_z) and 6x6 covariance.
virtual double getMomMag (const StateOnPlane &state) const =0
get the magnitude of the momentum in GeV.
virtual double getMomVar (const MeasuredStateOnPlane &state) const =0
get the variance of the absolute value of the momentum .
int getPDG () const
Get the pdg code.
double getPDGCharge () const
Get the charge of the particle of the pdg code.
virtual double getCharge (const StateOnPlane &state) const =0
Get the (fitted) charge of a state. This is not always equal the pdg charge (e.g. if the charge sign was flipped during the fit).
virtual double getQop (const StateOnPlane &state) const =0
Get charge over momentum.
double getMass (const StateOnPlane &state) const
Get tha particle mass in GeV/c^2.
char getPropDir () const
Get propagation direction. (-1, 0, 1) -> (backward, auto, forward).
virtual void getForwardJacobianAndNoise (TMatrixD &jacobian, TMatrixDSym &noise, TVectorD &deltaState) const =0
Get the jacobian and noise matrix of the last extrapolation.
virtual void getBackwardJacobianAndNoise (TMatrixD &jacobian, TMatrixDSym &noise, TVectorD &deltaState) const =0
Get the jacobian and noise matrix of the last extrapolation if it would have been done in opposite direction.
virtual std::vector
< genfit::MatStep > getSteps () const =0
Get stepsizes and material properties of crossed materials of the last extrapolation.
virtual double getRadiationLenght () const =0
Get the accumulated X/X0 (path / radiation length) of the material crossed in the last extrapolation.
virtual double getTime (const StateOnPlane &) const =0
Get the time corresponding to the StateOnPlane. Extrapolation.
void calcJacobianNumerically (const genfit::StateOnPlane &origState, const genfit::SharedPlanePtr destPlane, TMatrixD &jacobian) const
Calculate Jacobian of transportation numerically. Slow but accurate. Can be used to validate (semi)analytic calculations.
bool switchPDGSign ()
try to multiply pdg code with -1. (Switch from particle to anti-particle and vice versa).
virtual void setPosMom (StateOnPlane &state, const TVector3 &pos, const TVector3 &mom) const =0
Set position and momentum of state.
virtual void setPosMom (StateOnPlane &state, const TVectorD &state6) const =0
Set position and momentum of state.
virtual void setPosMomErr (MeasuredStateOnPlane &state, const TVector3 &pos, const TVector3 &mom, const TVector3 &posErr, const TVector3 &momErr) const =0
Set position and momentum and error of state.
virtual void setPosMomCov (MeasuredStateOnPlane &state, const TVector3 &pos, const TVector3 &mom, const TMatrixDSym &cov6x6) const =0
Set position, momentum and covariance of state.
virtual void setPosMomCov (MeasuredStateOnPlane &state, const TVectorD &state6, const TMatrixDSym &cov6x6) const =0
Set position, momentum and covariance of state.
virtual void setChargeSign (StateOnPlane &state, double charge) const =0
Set the sign of the charge according to charge.
virtual void setQop (StateOnPlane &state, double qop) const =0
Set charge/momentum.
virtual void setTime (StateOnPlane &state, double time) const =0
Set time at which the state was defined.
void setPropDir (int dir)
Set propagation direction. (-1, 0, 1) -> (backward, auto, forward).
void switchPropDir ()
Switch propagation direction. Has no effect if propDir_ is set to 0.
virtual bool isSameType (const AbsTrackRep *other)=0
check if other is of same type (e.g. RKTrackRep).
virtual bool isSame (const AbsTrackRep *other)=0
check if other is of same type (e.g. RKTrackRep) and has same pdg code.
virtual void setDebugLvl (unsigned int lvl=1)
virtual void Print (const Option_t *="") const
Protected Member Functions
AbsTrackRep (const AbsTrackRep &)
protect from calling copy c'tor from outside the class. Use clone() if you want a copy!
AbsTrackRep & operator= (const AbsTrackRep &)
protect from calling assignment operator from outside the class. Use clone() instead!
Protected Attributes
int pdgCode_
Particle code.
char propDir_
propagation direction (-1, 0, 1) -> (backward, auto, forward)
unsigned int debugLvl_
Detailed Description
Abstract base class for a track representation.
Provides functionality to extrapolate a StateOnPlane to another DetPlane, to the POCA to a line or a point, or a cylinder or sphere. Defines a set of parameters describing the track. StateOnPlane objects are always defined with a track parameterization of a specific AbsTrackRep. The AbsTrackRep provides functionality to translate from the internal representation of a state into cartesian position and momentum (and covariance) and vice versa.
Definition at line 66 of file AbsTrackRep.h.
View newest version in sPHENIX GitHub at line 66 of file AbsTrackRep.h
Constructor & Destructor Documentation
genfit::AbsTrackRep::AbsTrackRep ()
Definition at line 31 of file AbsTrackRep.cc.
View newest version in sPHENIX GitHub at line 31 of file AbsTrackRep.cc
genfit::AbsTrackRep::AbsTrackRep (int pdgCode, char propDir = 0)
Definition at line 37 of file AbsTrackRep.cc.
View newest version in sPHENIX GitHub at line 37 of file AbsTrackRep.cc
virtual genfit::AbsTrackRep::~AbsTrackRep () inline virtual
Definition at line 73 of file AbsTrackRep.h.
View newest version in sPHENIX GitHub at line 73 of file AbsTrackRep.h
genfit::AbsTrackRep::AbsTrackRep (const AbsTrackRep & rep) protected
protect from calling copy c'tor from outside the class. Use clone() if you want a copy!
Definition at line 43 of file AbsTrackRep.cc.
View newest version in sPHENIX GitHub at line 43 of file AbsTrackRep.cc
Member Function Documentation
void genfit::AbsTrackRep::calcJacobianNumerically (const genfit::StateOnPlane & origState, const genfit::SharedPlanePtr destPlane, TMatrixD & jacobian) const
Calculate Jacobian of transportation numerically. Slow but accurate. Can be used to validate (semi)analytic calculations.
Definition at line 105 of file AbsTrackRep.cc.
View newest version in sPHENIX GitHub at line 105 of file AbsTrackRep.cc
References extrapolateToPlane(), getDim(), genfit::StateOnPlane::getState(), i, and j.
Referenced by compareForthBackJacNoise().
virtual AbsTrackRep* genfit::AbsTrackRep::clone () const pure virtual
Clone the trackRep.
Implemented in genfit::RKTrackRep.
Referenced by main(), and genfit::Track::Track().
virtual double genfit::AbsTrackRep::extrapolateBy (StateOnPlane & state, double step, bool stopAtBoundary = false, bool calcJacobianNoise = false) const pure virtual
Extrapolates the state by step (cm) and returns the extrapolation length and, via reference, the extrapolated state.
If stopAtBoundary is true, the extrapolation stops as soon as a material boundary is encountered.
If state has a covariance, jacobian and noise matrices will be calculated and the covariance will be propagated. If state has no covariance, jacobian and noise will only be calculated if calcJacobianNoise == true.
Implemented in genfit::RKTrackRep.
Referenced by checkExtrapolateBy(), genfit::GblFitter::constructGblInfo(), genfit::StateOnPlane::extrapolateBy(), and genfit::GFGbl::processTrackWithRep().
virtual double genfit::AbsTrackRep::extrapolateToCone (StateOnPlane & state, double radius, const TVector3 & linePoint = TVector3(0., 0., 0.), const TVector3 & lineDirection = TVector3(0., 0., 1.), bool stopAtBoundary = false, bool calcJacobianNoise = false) const pure virtual
Extrapolates the state to the cone surface, and returns the extrapolation length and, via reference, the extrapolated state.
If stopAtBoundary is true, the extrapolation stops as soon as a material boundary is encountered.
If state has a covariance, jacobian and noise matrices will be calculated and the covariance will be propagated. If state has no covariance, jacobian and noise will only be calculated if calcJacobianNoise == true.
Implemented in genfit::RKTrackRep.
Referenced by genfit::StateOnPlane::extrapolateToCone().
virtual double genfit::AbsTrackRep::extrapolateToCylinder (StateOnPlane & state, double radius, const TVector3 & linePoint = TVector3(0., 0., 0.), const TVector3 & lineDirection = TVector3(0., 0., 1.), bool stopAtBoundary = false, bool calcJacobianNoise = false) const pure virtual
Extrapolates the state to the cylinder surface, and returns the extrapolation length and, via reference, the extrapolated state.
If stopAtBoundary is true, the extrapolation stops as soon as a material boundary is encountered.
If state has a covariance, jacobian and noise matrices will be calculated and the covariance will be propagated. If state has no covariance, jacobian and noise will only be calculated if calcJacobianNoise == true.
Implemented in genfit::RKTrackRep.
Referenced by checkExtrapolateToCylinder(), PHGenFit::extrapolateToCylinder(), PHGenFit::Track::extrapolateToCylinder(), genfit::StateOnPlane::extrapolateToCylinder(), and GenFitTrackProp::fill_tree().
virtual double genfit::AbsTrackRep::extrapolateToLine (StateOnPlane & state, const TVector3 & linePoint, const TVector3 & lineDirection, bool stopAtBoundary = false, bool calcJacobianNoise = false) const pure virtual
Extrapolates the state to the POCA to a line, and returns the extrapolation length and, via reference, the extrapolated state.
If stopAtBoundary is true, the extrapolation stops as soon as a material boundary is encountered.
If state has a covariance, jacobian and noise matrices will be calculated and the covariance will be propagated. If state has no covariance, jacobian and noise will only be calculated if calcJacobianNoise == true.
Implemented in genfit::RKTrackRep.
Referenced by checkExtrapolateToLine(), genfit::ProlateSpacepointMeasurement::constructPlane(), genfit::WirePointMeasurement::constructPlane(), genfit::WireMeasurement::constructPlane(), genfit::WireMeasurementNew::constructPlane(), PHGenFit::Track::extrapolateToLine(), genfit::StateOnPlane::extrapolateToLine(), and extrapolateToLine().
virtual double genfit::AbsTrackRep::extrapolateToLine (StateOnPlane & state, const TVector3 & point1, const TVector3 & point2, TVector3 & poca, TVector3 & dirInPoca, TVector3 & poca_onwire, bool stopAtBoundary = false, bool calcJacobianNoise = false) const inline virtual
Resembles the interface of GFAbsTrackRep in old versions of genfit.
This interface to extrapolateToLine is intended to resemble the interface of GFAbsTrackRep in old versions of genfit and is implemented by default via the preceding function.
If stopAtBoundary is true, the extrapolation stops as soon as a material boundary is encountered.
If state has a covariance, jacobian and noise matrices will be calculated and the covariance will be propagated. If state has no covariance, jacobian and noise will only be calculated if calcJacobianNoise == true.
Definition at line 120 of file AbsTrackRep.h.
View newest version in sPHENIX GitHub at line 120 of file AbsTrackRep.h
References extrapolateToLine(), getMom(), and getPos().
double genfit::AbsTrackRep::extrapolateToMeasurement (StateOnPlane & state, const AbsMeasurement * measurement, bool stopAtBoundary = false, bool calcJacobianNoise = false) const
extrapolate to an AbsMeasurement
Definition at line 50 of file AbsTrackRep.cc.
View newest version in sPHENIX GitHub at line 50 of file AbsTrackRep.cc
References genfit::AbsMeasurement::constructPlane(), and extrapolateToPlane().
Referenced by genfit::StateOnPlane::extrapolateToMeasurement().
virtual double genfit::AbsTrackRep::extrapolateToPlane (StateOnPlane & state, const genfit::SharedPlanePtr & plane, bool stopAtBoundary = false, bool calcJacobianNoise = false) const pure virtual
Extrapolates the state to plane, and returns the extrapolation length and, via reference, the extrapolated state.
If stopAtBoundary is true, the extrapolation stops as soon as a material boundary is encountered.
If state has a covariance, jacobian and noise matrices will be calculated and the covariance will be propagated. If state has no covariance, jacobian and noise will only be calculated if calcJacobianNoise == true.
Implemented in genfit::RKTrackRep.
Referenced by calcJacobianNumerically(), checkErrorPropagation(), checkStopAtBoundary(), compareForthBackExtrapolation(), compareForthBackJacNoise(), genfit::GblFitter::constructGblInfo(), extrapolateToMeasurement(), PHGenFit::Track::extrapolateToPlane(), genfit::StateOnPlane::extrapolateToPlane(), GenFitTrackProp::fill_tree(), genfit::Track::getTrackLen(), main(), genfit::EventDisplay::makeLines(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitter::processTrackPoint(), genfit::GFGbl::processTrackWithRep(), genfit::GblFitterInfo::recalculateJacobian(), and PHGenFit::Track::updateOneMeasurementKalman().
virtual double genfit::AbsTrackRep::extrapolateToPoint (StateOnPlane & state, const TVector3 & point, bool stopAtBoundary = false, bool calcJacobianNoise = false) const pure virtual
Extrapolates the state to the POCA to a point, and returns the extrapolation length and, via reference, the extrapolated state.
If stopAtBoundary is true, the extrapolation stops as soon as a material boundary is encountered.
If state has a covariance, jacobian and noise matrices will be calculated and the covariance will be propagated. If state has no covariance, jacobian and noise will only be calculated if calcJacobianNoise == true.
Implemented in genfit::RKTrackRep.
Referenced by checkExtrapolateToPoint(), PHGenFit::Track::extrapolateToPoint(), and genfit::StateOnPlane::extrapolateToPoint().
virtual double genfit::AbsTrackRep::extrapolateToPoint (StateOnPlane & state, const TVector3 & point, const TMatrixDSym & G, bool stopAtBoundary = false, bool calcJacobianNoise = false) const pure virtual
Extrapolates the state to the POCA to a point in the metric of G, and returns the extrapolation length and, via reference, the extrapolated state.
If stopAtBoundary is true, the extrapolation stops as soon as a material boundary is encountered.
If state has a covariance, jacobian and noise matrices will be calculated and the covariance will be propagated. If state has no covariance, jacobian and noise will only be calculated if calcJacobianNoise == true.
Implemented in genfit::RKTrackRep.
virtual double genfit::AbsTrackRep::extrapolateToSphere (StateOnPlane & state, double radius, const TVector3 & point = TVector3(0., 0., 0.), bool stopAtBoundary = false, bool calcJacobianNoise = false) const pure virtual
Extrapolates the state to the sphere surface, and returns the extrapolation length and, via reference, the extrapolated state.
If stopAtBoundary is true, the extrapolation stops as soon as a material boundary is encountered.
If state has a covariance, jacobian and noise matrices will be calculated and the covariance will be propagated. If state has no covariance, jacobian and noise will only be calculated if calcJacobianNoise == true.
Implemented in genfit::RKTrackRep.
Referenced by checkExtrapolateToSphere(), and genfit::StateOnPlane::extrapolateToSphere().
virtual TMatrixDSym genfit::AbsTrackRep::get6DCov (const MeasuredStateOnPlane & state) const pure virtual
Get the 6D covariance.
Implemented in genfit::RKTrackRep.
Referenced by genfit::MeasuredStateOnPlane::get6DCov(), TrackProjectorPid::project_track(), and TrackProjectorPlaneECAL::project_track().
TVectorD genfit::AbsTrackRep::get6DState (const StateOnPlane & state) const virtual
Get the 6D state vector (x, y, z, p_x, p_y, p_z).
Definition at line 59 of file AbsTrackRep.cc.
View newest version in sPHENIX GitHub at line 59 of file AbsTrackRep.cc
References getPosMom(), and pos.
Referenced by genfit::StateOnPlane::get6DState().
void genfit::AbsTrackRep::get6DStateCov (const MeasuredStateOnPlane & state, TVectorD & stateVec, TMatrixDSym & cov) const virtual
Translates MeasuredStateOnPlane into 6D state vector (x, y, z, p_x, p_y, p_z) and 6x6 covariance.
Definition at line 77 of file AbsTrackRep.cc.
View newest version in sPHENIX GitHub at line 77 of file AbsTrackRep.cc
References getPosMomCov(), and pos.
Referenced by genfit::MeasuredStateOnPlane::get6DStateCov(), and main().
virtual void genfit::AbsTrackRep::getBackwardJacobianAndNoise (TMatrixD & jacobian, TMatrixDSym & noise, TVectorD & deltaState) const pure virtual
Get the jacobian and noise matrix of the last extrapolation if it would have been done in opposite direction.
Implemented in genfit::RKTrackRep.
Referenced by compareForthBackJacNoise(), and genfit::KalmanFitterRefTrack::prepareTrack().
virtual double genfit::AbsTrackRep::getCharge (const StateOnPlane & state) const pure virtual
Get the (fitted) charge of a state. This is not always equal the pdg charge (e.g. if the charge sign was flipped during the fit).
Implemented in genfit::RKTrackRep.
Referenced by genfit::GblFitter::constructGblInfo(), PHGenFit::Track::get_charge(), genfit::StateOnPlane::getCharge(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::KalmanFitterRefTrack::processTrackWithRep(), and genfit::GFGbl::processTrackWithRep().
virtual unsigned int genfit::AbsTrackRep::getDim () const pure virtual
Get the dimension of the state vector used by the track representation.
Implemented in genfit::RKTrackRep.
Referenced by calcJacobianNumerically(), genfit::KalmanFitterInfo::checkConsistency(), genfit::GblFitter::constructGblInfo(), genfit::EventDisplay::drawEvent(), genfit::KalmanFitterRefTrack::fitTrack(), genfit::KalmanFitter::fitTrack(), genfit::FullMeasurement::FullMeasurement(), genfit::GblFitterInfo::GblFitterInfo(), genfit::AbsKalmanFitter::getChiSquNdf(), genfit::MeasuredStateOnPlane::MeasuredStateOnPlane(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::GFGbl::processTrackWithRep(), and genfit::StateOnPlane::StateOnPlane().
TVector3 genfit::AbsTrackRep::getDir (const StateOnPlane & state) const inline
Get the direction vector of a state.
Definition at line 246 of file AbsTrackRep.h.
View newest version in sPHENIX GitHub at line 246 of file AbsTrackRep.h
References getMom().
Referenced by genfit::GblFitter::constructGblInfo(), genfit::StateOnPlane::getDir(), and genfit::GFGbl::processTrackWithRep().
virtual void genfit::AbsTrackRep::getForwardJacobianAndNoise (TMatrixD & jacobian, TMatrixDSym & noise, TVectorD & deltaState) const pure virtual
Get the jacobian and noise matrix of the last extrapolation.
Implemented in genfit::RKTrackRep.
Referenced by compareForthBackJacNoise(), genfit::GblFitter::constructGblInfo(), genfit::GblFitterInfo::GblFitterInfo(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::GFGbl::processTrackWithRep(), and genfit::GblFitterInfo::recalculateJacobian().
double genfit::AbsTrackRep::getMass (const StateOnPlane & state) const
Get tha particle mass in GeV/c^2.
Definition at line 100 of file AbsTrackRep.cc.
View newest version in sPHENIX GitHub at line 100 of file AbsTrackRep.cc
References pdgCode_.
Referenced by genfit::GblFitter::constructGblInfo(), genfit::RKTrackRep::extrapolateBy(), genfit::RKTrackRep::extrapolateToCone(), genfit::RKTrackRep::extrapolateToCylinder(), genfit::RKTrackRep::extrapolateToLine(), genfit::RKTrackRep::extrapolateToPlane(), genfit::RKTrackRep::extrapolateToSphere(), genfit::RKTrackRep::extrapToPoint(), genfit::StateOnPlane::getMass(), and genfit::GFGbl::processTrackWithRep().
virtual TVector3 genfit::AbsTrackRep::getMom (const StateOnPlane & state) const pure virtual
Get the cartesian momentum vector of a state.
Implemented in genfit::RKTrackRep.
Referenced by checkExtrapolateToLine(), checkExtrapolateToPoint(), checkSetGetPosMom(), compareForthBackExtrapolation(), genfit::ProlateSpacepointMeasurement::constructPlane(), genfit::WirePointMeasurement::constructPlane(), genfit::WireMeasurement::constructPlane(), genfit::WireMeasurementNew::constructPlane(), extrapolateToLine(), getDir(), genfit::StateOnPlane::getMom(), PHGenFitTrackProjection::process_event(), TrackProjectorPid::project_track(), and TrackProjectorPlaneECAL::project_track().
virtual double genfit::AbsTrackRep::getMomMag (const StateOnPlane & state) const pure virtual
get the magnitude of the momentum in GeV.
Implemented in genfit::RKTrackRep.
Referenced by genfit::GblFitter::constructGblInfo(), genfit::StateOnPlane::getMomMag(), and genfit::GFGbl::processTrackWithRep().
virtual double genfit::AbsTrackRep::getMomVar (const MeasuredStateOnPlane & state) const pure virtual
get the variance of the absolute value of the momentum .
Implemented in genfit::RKTrackRep.
Referenced by genfit::MeasuredStateOnPlane::getMomVar().
int genfit::AbsTrackRep::getPDG () const inline
Get the pdg code.
Definition at line 272 of file AbsTrackRep.h.
View newest version in sPHENIX GitHub at line 272 of file AbsTrackRep.h
References pdgCode_.
Referenced by genfit::GFRaveTrackParameters::getPdg(), genfit::StateOnPlane::getPDG(), genfit::RKTrackRep::isSame(), and genfit::GFGbl::processTrackWithRep().
double genfit::AbsTrackRep::getPDGCharge () const
Get the charge of the particle of the pdg code.
Definition at line 93 of file AbsTrackRep.cc.
View newest version in sPHENIX GitHub at line 93 of file AbsTrackRep.cc
References assert, and pdgCode_.
Referenced by genfit::RKTrackRep::getCharge().
virtual TVector3 genfit::AbsTrackRep::getPos (const StateOnPlane & state) const pure virtual
Get the cartesian position of a state.
Implemented in genfit::RKTrackRep.
Referenced by checkExtrapolateToCylinder(), checkExtrapolateToSphere(), checkSetGetPosMom(), checkStopAtBoundary(), compareForthBackExtrapolation(), genfit::WireMeasurement::constructPlane(), genfit::WireMeasurementNew::constructPlane(), extrapolateToLine(), genfit::StateOnPlane::getPos(), PHGenFitTrackProjection::process_event(), TrackProjectorPid::project_track(), and TrackProjectorPlaneECAL::project_track().
void genfit::AbsTrackRep::getPosDir (const StateOnPlane & state, TVector3 & pos, TVector3 & dir) const inline
Get cartesian position and direction vector of a state.
Definition at line 252 of file AbsTrackRep.h.
View newest version in sPHENIX GitHub at line 252 of file AbsTrackRep.h
References getPosMom().
Referenced by genfit::StateOnPlane::getPosDir(), and genfit::EventDisplay::makeLines().
virtual void genfit::AbsTrackRep::getPosMom (const StateOnPlane & state, TVector3 & pos, TVector3 & mom) const pure virtual
Get cartesian position and momentum vector of a state.
Implemented in genfit::RKTrackRep.
Referenced by get6DState(), getPosDir(), genfit::StateOnPlane::getPosMom(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::StateOnPlane::Print(), genfit::KalmanFitterRefTrack::processTrackPoint(), and genfit::KalmanFitterRefTrack::processTrackPointSqrt().
virtual void genfit::AbsTrackRep::getPosMomCov (const MeasuredStateOnPlane & state, TVector3 & pos, TVector3 & mom, TMatrixDSym & cov) const pure virtual
Translates MeasuredStateOnPlane into 3D position, momentum and 6x6 covariance.
Implemented in genfit::RKTrackRep.
Referenced by get6DStateCov(), genfit::MeasuredStateOnPlane::getPosMomCov(), genfit::EventDisplay::makeLines(), genfit::MeasuredStateOnPlane::Print(), genfit::KalmanFitter::processTrackPartially(), and genfit::KalmanFitter::processTrackWithRep().
char genfit::AbsTrackRep::getPropDir () const inline
Get propagation direction. (-1, 0, 1) -> (backward, auto, forward).
Definition at line 288 of file AbsTrackRep.h.
View newest version in sPHENIX GitHub at line 288 of file AbsTrackRep.h
References propDir_.
virtual double genfit::AbsTrackRep::getQop (const StateOnPlane & state) const pure virtual
Get charge over momentum.
Implemented in genfit::RKTrackRep.
Referenced by genfit::StateOnPlane::getQop(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitter::processTrackPartially(), and genfit::KalmanFitter::processTrackWithRep().
virtual double genfit::AbsTrackRep::getRadiationLenght () const pure virtual
Get the accumulated X/X0 (path / radiation length) of the material crossed in the last extrapolation.
Implemented in genfit::RKTrackRep.
virtual std::vector<genfit::MatStep> genfit::AbsTrackRep::getSteps () const pure virtual
Get stepsizes and material properties of crossed materials of the last extrapolation.
Implemented in genfit::RKTrackRep.
Referenced by genfit::GblFitter::constructGblInfo(), and genfit::GFGbl::processTrackWithRep().
virtual double genfit::AbsTrackRep::getTime (const StateOnPlane &) const pure virtual
Get the time corresponding to the StateOnPlane. Extrapolation.
Implemented in genfit::RKTrackRep.
Referenced by genfit::StateOnPlane::getTime(), and genfit::Track::getTOF().
virtual bool genfit::AbsTrackRep::isSame (const AbsTrackRep * other) pure virtual
check if other is of same type (e.g. RKTrackRep) and has same pdg code.
Implemented in genfit::RKTrackRep.
virtual bool genfit::AbsTrackRep::isSameType (const AbsTrackRep * other) pure virtual
check if other is of same type (e.g. RKTrackRep).
Implemented in genfit::RKTrackRep.
AbsTrackRep& genfit::AbsTrackRep::operator= (const AbsTrackRep &) protected
protect from calling assignment operator from outside the class. Use clone() instead!
void genfit::AbsTrackRep::Print (const Option_t * = "") const virtual
Definition at line 194 of file AbsTrackRep.cc.
View newest version in sPHENIX GitHub at line 194 of file AbsTrackRep.cc
References pdgCode_, genfit::printOut, and propDir_.
virtual void genfit::AbsTrackRep::setChargeSign (StateOnPlane & state, double charge) const pure virtual
Set the sign of the charge according to charge.
Implemented in genfit::RKTrackRep.
Referenced by genfit::StateOnPlane::setChargeSign().
virtual void genfit::AbsTrackRep::setDebugLvl (unsigned int lvl = 1) inline virtual
Definition at line 351 of file AbsTrackRep.h.
View newest version in sPHENIX GitHub at line 351 of file AbsTrackRep.h
References debugLvl_.
virtual void genfit::AbsTrackRep::setPosMom (StateOnPlane & state, const TVector3 & pos, const TVector3 & mom) const pure virtual
Set position and momentum of state.
Implemented in genfit::RKTrackRep.
Referenced by checkErrorPropagation(), checkExtrapolateBy(), checkExtrapolateToCylinder(), checkExtrapolateToLine(), checkExtrapolateToPoint(), checkExtrapolateToSphere(), checkSetGetPosMom(), checkStopAtBoundary(), compareForthBackExtrapolation(), compareForthBackJacNoise(), genfit::GblFitter::constructGblInfo(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::StateOnPlane::setPosMom(), and genfit::GblFitter::sortHits().
virtual void genfit::AbsTrackRep::setPosMom (StateOnPlane & state, const TVectorD & state6) const pure virtual
Set position and momentum of state.
Implemented in genfit::RKTrackRep.
virtual void genfit::AbsTrackRep::setPosMomCov (MeasuredStateOnPlane & state, const TVector3 & pos, const TVector3 & mom, const TMatrixDSym & cov6x6) const pure virtual
Set position, momentum and covariance of state.
Implemented in genfit::RKTrackRep.
Referenced by PHGenFit::Track::extrapolateToCylinder(), main(), PHGenFitTrackProjection::process_event(), genfit::KalmanFitter::processTrackPartially(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::KalmanFitter::processTrackWithRep(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), genfit::MeasuredStateOnPlane::setPosMomCov(), and PHGenFit::Track::updateOneMeasurementKalman().
virtual void genfit::AbsTrackRep::setPosMomCov (MeasuredStateOnPlane & state, const TVectorD & state6, const TMatrixDSym & cov6x6) const pure virtual
Set position, momentum and covariance of state.
Implemented in genfit::RKTrackRep.
virtual void genfit::AbsTrackRep::setPosMomErr (MeasuredStateOnPlane & state, const TVector3 & pos, const TVector3 & mom, const TVector3 & posErr, const TVector3 & momErr) const pure virtual
Set position and momentum and error of state.
Implemented in genfit::RKTrackRep.
Referenced by genfit::MeasuredStateOnPlane::setPosMomErr().
void genfit::AbsTrackRep::setPropDir (int dir) inline
Set propagation direction. (-1, 0, 1) -> (backward, auto, forward).
Definition at line 336 of file AbsTrackRep.h.
View newest version in sPHENIX GitHub at line 336 of file AbsTrackRep.h
References propDir_.
Referenced by genfit::EventDisplay::drawEvent().
virtual void genfit::AbsTrackRep::setQop (StateOnPlane & state, double qop) const pure virtual
Set charge/momentum.
Implemented in genfit::RKTrackRep.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitter::processTrackPartially(), genfit::KalmanFitter::processTrackWithRep(), and genfit::StateOnPlane::setQop().
virtual void genfit::AbsTrackRep::setTime (StateOnPlane & state, double time) const pure virtual
Set time at which the state was defined.
Implemented in genfit::RKTrackRep.
Referenced by genfit::GblFitter::constructGblInfo(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitter::processTrackPartially(), genfit::KalmanFitter::processTrackWithRep(), genfit::StateOnPlane::setTime(), and genfit::GblFitter::sortHits().
bool genfit::AbsTrackRep::switchPDGSign ()
try to multiply pdg code with -1. (Switch from particle to anti-particle and vice versa).
Definition at line 183 of file AbsTrackRep.cc.
View newest version in sPHENIX GitHub at line 183 of file AbsTrackRep.cc
References pdgCode_.
Referenced by genfit::Track::switchPDGSigns().
void genfit::AbsTrackRep::switchPropDir () inline
Switch propagation direction. Has no effect if propDir_ is set to 0.
Definition at line 343 of file AbsTrackRep.h.
View newest version in sPHENIX GitHub at line 343 of file AbsTrackRep.h
References propDir_.
Member Data Documentation
unsigned int genfit::AbsTrackRep::debugLvl_ protected
Definition at line 368 of file AbsTrackRep.h.
View newest version in sPHENIX GitHub at line 368 of file AbsTrackRep.h
Referenced by genfit::RKTrackRep::calcForwardJacobianAndNoise(), genfit::RKTrackRep::checkCache(), genfit::RKTrackRep::estimateStep(), genfit::RKTrackRep::Extrap(), genfit::RKTrackRep::extrapolateBy(), genfit::RKTrackRep::extrapolateToCone(), genfit::RKTrackRep::extrapolateToCylinder(), genfit::RKTrackRep::extrapolateToLine(), genfit::RKTrackRep::extrapolateToPlane(), genfit::RKTrackRep::extrapolateToSphere(), genfit::RKTrackRep::extrapToPoint(), genfit::RKTrackRep::getBackwardJacobianAndNoise(), genfit::RKTrackRep::getForwardJacobianAndNoise(), genfit::RKTrackRep::RKPropagate(), genfit::RKTrackRep::RKutta(), and setDebugLvl().
int genfit::AbsTrackRep::pdgCode_ protected
Particle code.
Definition at line 364 of file AbsTrackRep.h.
View newest version in sPHENIX GitHub at line 364 of file AbsTrackRep.h
Referenced by genfit::RKTrackRep::estimateStep(), genfit::RKTrackRep::Extrap(), getMass(), getPDG(), getPDGCharge(), Print(), and switchPDGSign().
char genfit::AbsTrackRep::propDir_ protected
propagation direction (-1, 0, 1) -> (backward, auto, forward)
Definition at line 366 of file AbsTrackRep.h.
View newest version in sPHENIX GitHub at line 366 of file AbsTrackRep.h
Referenced by genfit::RKTrackRep::estimateStep(), getPropDir(), Print(), setPropDir(), and switchPropDir().
The documentation for this class was generated from the following files:
GenFit/blob/master/core/include/AbsTrackRep.h
GenFit/blob/master/core/src/AbsTrackRep.cc