Analysis Software: genfit Namespace Reference
genfit Namespace Reference
Genfit | EventDisplay | GFRave | RKTrackRep | Utilities
Defines for I/O streams used for error and debug printing.
Namespaces
namespace Constants
namespace RKTools
Array matrix multiplications used in RKTrackRep.
namespace tools
namespace Unit
Classes
class Field
Field Wrapper.
class AbsBField
Abstract Interface to magnetic fields in GENFIT.
class AbsFinitePlane
Abstract base class for finite detector planes.
class AbsFitter
Abstract base class for fitters.
class AbsFitterInfo
This class collects all information needed and produced by a specific AbsFitter and is specific to one AbsTrackRep of the Track.
class AbsHMatrix
HMatrix for projecting from AbsTrackRep parameters to measured parameters in a DetPlane.
class AbsMeasurement
Contains the measurement and covariance in raw detector coordinates.
struct MatStep
Simple struct containing MaterialProperties and stepsize in the material.
class AbsTrackRep
Abstract base class for a track representation.
class DetPlane
Detector plane.
class Exception
Exception class for error handling in GENFIT (provides storage for diagnostic information)
struct fieldCache
Cache B field at a position. Used by FieldManager.
class FieldManager
Singleton which provides access to magnetic field maps.
struct PruneFlags
Info which information has been pruned from the Track.
class FitStatus
Class where important numbers and properties of a fit can be stored.
struct Material
class MeasuredStateOnPlane
StateOnPlane with additional covariance matrix.
class MeasurementFactory
Factory object to create AbsMeasurement objects from digitized and clustered data.
class MeasurementOnPlane
Measured coordinates on a plane.
class AbsMeasurementProducer
Abstract interface class for MeasurementProducer.
class MeasurementProducer
Template class for a measurement producer module.
class SharedPlanePtrCreator
class StateOnPlane
A state with arbitrary dimension defined in a DetPlane.
class ThinScatterer
Thin or thick scatterer.
class TrackPointComparator
Helper class for TrackPoint sorting, used in Track::sort().
class Track
Collection of TrackPoint objects, AbsTrackRep objects and FitStatus objects.
class TrackCand
Track candidate – seed values and indices.
class TrackCandHit
Hit object for use in TrackCand. Provides IDs and sorting parameters.
class TrackPoint
Object containing AbsMeasurement and AbsFitterInfo objects.
class EventDisplay
Event display designed to run with Genfit.
class ConstField
Constant Magnetic field.
class RectangularFinitePlane
Rectangular finite plane.
class AbsKalmanFitter
Abstract base class for Kalman fitter and derived fitting algorithms.
class DAF
Determinstic Annealing Filter (DAF) implementation.
class KalmanFitStatus
FitStatus for use with AbsKalmanFitter implementations.
class KalmanFittedStateOnPlane
MeasuredStateOnPlane with additional info produced by a Kalman filter or DAF.
class KalmanFitter
Simple Kalman filter implementation.
class KalmanFitterInfo
Collects information needed and produced by a AbsKalmanFitter implementations and is specific to one AbsTrackRep of the Track.
class KalmanFitterRefTrack
Kalman filter implementation with linearization around a reference track.
class ReferenceStateOnPlane
StateOnPlane with linearized transport to that ReferenceStateOnPlane from previous and next ReferenceStateOnPlane
class GblFitStatus
FitStatus for use with GblFitter.
class GblFitter
Generic GBL implementation.
class GblFitterInfo
Collects information needed and produced by a GblFitter/GBL and is specific to one AbsTrackRep of the Track.
class GblTrackSegmentController
TrackSegmentController for use with GblFitter.
class GFGbl
Generic GBL implementation.
class ICalibrationParametersDerivatives
Abstract base class to establish an interface between physical representation of the detector for alignment/calibration and (fitted) state on genfit::Track.
class GFRaveMagneticField
GFRaveMagneticField class Uses the FieldManager to provide a magnetic field to rave.
class GFRavePropagator
GFRavePropagator class.
class GFRaveTrackParameters
GFRaveTrackParameters class Contains a pointer to the original genfit::Track, the weight of the track in the vertex, and smoothed (with the vertex information) state and covariance of the track.
class GFRaveVertex
GFRaveVertex class.
struct trackAndState
Simple struct containing a Track pointer and a MeasuredStateOnPlane. Used in GFRave.
class GFRaveVertexFactory
Vertex factory for producing GFRaveVertex objects from Track objects.
class ConstFieldUninitializedTests
class ConstFieldInitializedTests
class MaterialTests
class MaterialEffectsTests
class RKMatrixEigenTransformations
class RKTrackRepTests
class RootEigenTransformations
class UnitTests
class FullMeasurement
Measurement class implementing a measurement of all track parameters.
class HMatrixPhi
AbsHMatrix implementation for one-dimensional MeasurementOnPlane and RKTrackRep parameterization.
class HMatrixU
AbsHMatrix implementation for one-dimensional MeasurementOnPlane and RKTrackRep parameterization.
class HMatrixUnit
AbsHMatrix implementation for 5-dimensional MeasurementOnPlane and RKTrackRep parameterization.
class HMatrixUV
AbsHMatrix implementation for two-dimensional MeasurementOnPlane and RKTrackRep parameterization.
class HMatrixV
AbsHMatrix implementation for one-dimensional MeasurementOnPlane and RKTrackRep parameterization.
class PlanarMeasurement
Measurement class implementing a planar hit geometry (1 or 2D).
class ProlateSpacepointMeasurement
Class for measurements implementing a space point hit geometry with a very prolate form of the covariance matrix.
class SpacepointMeasurement
Class for measurements implementing a space point hit geometry.
class WireMeasurement
Class for measurements in wire detectors (Straw tubes and drift chambers) which do not measure the coordinate along the wire.
class WireMeasurementNew
Class for measurements in wire detectors (Straw tubes and drift chambers) which do not measure the coordinate along the wire.
class WirePointMeasurement
Class for measurements in wire detectors (Straw tubes and drift chambers) which can measure the coordinate along the wire.
class WireTrackCandHit
Hit object for use in TrackCand. Provides additional left/right parameter.
class AbsMaterialInterface
Abstract base class for geometry interfacing.
class MaterialEffects
Stepper and energy loss/noise matrix calculation.
struct RKMatrix
struct RKStep
Helper for RKTrackRep.
struct ExtrapStep
Helper for RKTrackRep.
class RKTrackRep
AbsTrackRep with 5D track parameterization in plane coordinates: (q/p, u', v', u, v)
class StepLimits
Helper to store different limits on the stepsize for the RKTRackRep.
class TGeoMaterialInterface
AbsMaterialInterface implementation for use with ROOT's TGeoManager.
class HelixTrackModel
Helix track model for testing purposes.
class MeasurementCreator
Create different measurement types along a HelixTrackModel for testing purposes.
class mySpacepointDetectorHit
Example class for a spacepoint detector hit.
class mySpacepointMeasurement
Example class for a spacepoint measurement which can be created from mySpacepointDetectorHit via the MeasurementFactory.
Typedefs
typedef double Precision
typedef Precision Scalar
typedef Eigen::Matrix
< Precision, 3, 1 > Vector3
typedef Eigen::Matrix
< Precision, 5, 1 > Vector5
typedef Eigen::Matrix
< Precision, 6, 1 > Vector6
typedef Eigen::Matrix
< Precision, 7, 1 > Vector7
typedef Eigen::Matrix
< Precision, 3, 3 > Matrix3x3
typedef Eigen::Matrix
< Precision, 4, 4 > Matrix4x4
typedef Eigen::Matrix
< Precision, 5, 5 > Matrix5x5
typedef Eigen::Matrix
< Precision, 6, 6 > Matrix6x6
typedef Eigen::Matrix
< Precision, 7, 7 > Matrix7x7
typedef Eigen::Matrix
< Precision, Eigen::Dynamic, 1 > VectorDynamic
typedef Eigen::Matrix
< Precision, Eigen::Dynamic,
Eigen::Dynamic > MatrixDynamic
typedef Matrix3x3 Matrix3x3Sym
typedef Matrix4x4 Matrix4x4Sym
typedef Matrix5x5 Matrix5x5Sym
typedef Matrix6x6 Matrix6x6Sym
typedef Matrix7x7 Matrix7x7Sym
typedef std::shared_ptr
< genfit::DetPlane > SharedPlanePtr
Shared Pointer to a DetPlane.
typedef RKMatrix< 1, 3 > M1x3
typedef RKMatrix< 1, 4 > M1x4
typedef RKMatrix< 1, 7 > M1x7
typedef RKMatrix< 5, 5 > M5x5
typedef RKMatrix< 6, 6 > M6x6
typedef RKMatrix< 7, 7 > M7x7
typedef RKMatrix< 6, 5 > M6x5
typedef RKMatrix< 7, 5 > M7x5
typedef RKMatrix< 5, 6 > M5x6
typedef RKMatrix< 5, 7 > M5x7
Enumerations
enum eFitterType { SimpleKalman, RefKalman, DafSimple, DafRef }
enum eMultipleMeasurementHandling {
weightedAverage, unweightedAverage, weightedClosestToReference, unweightedClosestToReference,
weightedClosestToPrediction, unweightedClosestToPrediction, weightedClosestToReferenceWire, unweightedClosestToReferenceWire,
weightedClosestToPredictionWire, unweightedClosestToPredictionWire
}
enum StepLimitType {
stp_noLimit = 0, stp_fieldCurv, stp_momLoss, stp_sMax,
stp_sMaxArg, stp_boundary, stp_plane, ENUM_NR_ITEMS
}
enum eMeasurementType {
Pixel = 0, Spacepoint, ProlateSpacepoint, StripU,
StripV, StripUV, Wire, WirePoint,
nMeasurementTypes
}
Functions
AbsFitterInfo * new_clone (const AbsFitterInfo &a)
Needed for boost cloneability:
bool operator== (const Material &lhs, const Material &rhs)
bool operator!= (const Material &lhs, const Material &rhs)
MeasuredStateOnPlane calcAverageState (const MeasuredStateOnPlane &forwardState, const MeasuredStateOnPlane &backwardState)
Calculate weighted average between two MeasuredStateOnPlanes.
bool operator== (const DetPlane &lhs, const DetPlane &rhs)
bool operator!= (const DetPlane &lhs, const DetPlane &rhs)
bool operator== (const TrackCand &lhs, const TrackCand &rhs)
bool operator== (const TrackCandHit &lhs, const TrackCandHit &rhs)
std::vector< rave::Track > GFTracksToTracks (const std::vector< genfit::Track * > &GFTracks, std::vector< genfit::MeasuredStateOnPlane * > *GFStates, std::map< int, genfit::trackAndState > &IdGFTrackStateMap, int startID=0)
rave::Track GFTrackToTrack (trackAndState, int id=-1, std::string tag="")
void setData (const rave::Track &orig, MeasuredStateOnPlane *state)
GFRaveVertex * RaveToGFVertex (const rave::Vertex &, const std::map< int, genfit::trackAndState > &IdGFTrackStateMap)
void RaveToGFVertices (std::vector< GFRaveVertex * > *, const std::vector< rave::Vertex > &, const std::map< int, genfit::trackAndState > &IdGFTrackStateMap)
SharedPlanePtr PlaneToGFDetPlane (const ravesurf::Plane &rplane)
TVector3 Point3DToTVector3 (const rave::Point3D &)
TVector3 Vector3DToTVector3 (const rave::Vector3D &)
TMatrixDSym Covariance3DToTMatrixDSym (const rave::Covariance3D &)
TVectorD Vector6DToTVectorD (const rave::Vector6D &)
TMatrixDSym Covariance6DToTMatrixDSym (const rave::Covariance6D &)
rave::Point3D TVector3ToPoint3D (const TVector3 &)
rave::Covariance3D TMatrixDSymToCovariance3D (const TMatrixDSym &)
TEST_F (ConstFieldUninitializedTests, UninitializedBehaviour)
TEST_F (ConstFieldInitializedTests, InitializedBehaviour)
TEST_F (MaterialTests, Constructor01)
TEST_F (MaterialTests, Constructor02)
TEST_F (MaterialTests, ComparisonOperators)
TEST_F (RKMatrixEigenTransformations, VectorTransformation)
TEST_F (RKMatrixEigenTransformations, MatrixTransformation)
TEST_F (RKTrackRepTests, RKStep)
TEST_F (RKTrackRepTests, ExtrapStep)
TEST_F (RKTrackRepTests, RKPropagate01)
Black-Box-Test.
TEST_F (RKTrackRepTests, RKPropagate02)
Black-Box-Test.
TEST_F (RKTrackRepTests, getState7)
White-Box-Test.
TEST_F (RKTrackRepTests, getState5)
White-Box-Test.
TEST_F (RKTrackRepTests, calcJ_pM_5x7)
White-Box-Test.
TEST_F (RKTrackRepTests, transformPM6)
White-Box-Test.
TEST_F (RKTrackRepTests, calcJ_Mp_7x5)
White-Box-Test.
TEST_F (RKTrackRepTests, calcForwardJacobianAndNoise)
White-Box-Test.
TEST_F (RKTrackRepTests, transformM6P)
White-Box-Test.
TEST_F (RKTrackRepTests, RKutta)
White-Box-Test.
TEST_F (RKTrackRepTests, estimateStep)
White-Box-Test.
TEST_F (RKTrackRepTests, Extrap)
White-Box-Test.
TEST_F (RKTrackRepTests, momMag)
White-Box-Test.
TEST_F (RootEigenTransformations, VectorTransformation)
TEST_F (RootEigenTransformations, SymmetricMatrixTransformation)
TEST_F (RootEigenTransformations, MatrixTransformation)
TEST_F (UnitTests, Energy)
double MeanExcEnergy_get (int Z)
double MeanExcEnergy_get (TGeoMaterial *)
double MeanExcEnergy_get (int Z, bool logs=false)
template<unsigned int rows, unsigned int cols>
Eigen::Matrix< double, rows, cols > RKMatrixToEigenMatrix (const RKMatrix< rows, cols > &rkMatrix)
template<unsigned int rows, unsigned int cols>
RKMatrix< rows, cols > eigenMatrixToRKMatrix (const Eigen::Matrix< double, rows, cols > &eigenMatrix)
template<unsigned int dim>
Eigen::Matrix< double, dim, 1 > rootVectorToEigenVector (const TVectorD &rootVector)
template<unsigned int dim>
TVectorD eigenVectorToRootVector (const Eigen::Matrix< double, dim, 1 > &eigenVector)
template<unsigned int dim>
Eigen::Matrix< double, dim, dim > rootMatrixSymToEigenMatrix (const TMatrixDSym &rootMatrix)
template<unsigned int dim>
TMatrixDSym eigenMatrixToRootMatrixSym (const Eigen::Matrix< double, dim, dim > &eigenMatrix)
template<unsigned int rows, unsigned int cols>
Eigen::Matrix< double, rows, cols > rootMatrixToEigenMatrix (const TMatrixD &rootMatrix)
template<unsigned int rows, unsigned int cols>
TMatrixD eigenMatrixToRootMatrix (const Eigen::Matrix< double, rows, cols > &eigenMatrix)
Variables
std::ostream debugOut
std::ostream errorOut
std::ostream printOut
const int MeanExcEnergy_NELEMENTS = 93
const double MeanExcEnergy_vals [MeanExcEnergy_NELEMENTS]
const double MeanExcEnergy_logs [MeanExcEnergy_NELEMENTS]
Detailed Description
Defines for I/O streams used for error and debug printing.
Collection of converter functions.
Namespace for the general broken lines package.
Matrix inversion tools.
Typedef Documentation
typedef RKMatrix<1, 3> genfit::M1x3
Definition at line 57 of file RKTools.h.
View newest version in sPHENIX GitHub at line 57 of file RKTools.h
typedef RKMatrix<1, 4> genfit::M1x4
Definition at line 58 of file RKTools.h.
View newest version in sPHENIX GitHub at line 58 of file RKTools.h
typedef RKMatrix<1, 7> genfit::M1x7
Definition at line 59 of file RKTools.h.
View newest version in sPHENIX GitHub at line 59 of file RKTools.h
typedef RKMatrix<5, 5> genfit::M5x5
Definition at line 60 of file RKTools.h.
View newest version in sPHENIX GitHub at line 60 of file RKTools.h
typedef RKMatrix<5, 6> genfit::M5x6
Definition at line 65 of file RKTools.h.
View newest version in sPHENIX GitHub at line 65 of file RKTools.h
typedef RKMatrix<5, 7> genfit::M5x7
Definition at line 66 of file RKTools.h.
View newest version in sPHENIX GitHub at line 66 of file RKTools.h
typedef RKMatrix<6, 5> genfit::M6x5
Definition at line 63 of file RKTools.h.
View newest version in sPHENIX GitHub at line 63 of file RKTools.h
typedef RKMatrix<6, 6> genfit::M6x6
Definition at line 61 of file RKTools.h.
View newest version in sPHENIX GitHub at line 61 of file RKTools.h
typedef RKMatrix<7, 5> genfit::M7x5
Definition at line 64 of file RKTools.h.
View newest version in sPHENIX GitHub at line 64 of file RKTools.h
typedef RKMatrix<7, 7> genfit::M7x7
Definition at line 62 of file RKTools.h.
View newest version in sPHENIX GitHub at line 62 of file RKTools.h
typedef Eigen::Matrix<Precision, 3, 3> genfit::Matrix3x3
Definition at line 15 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 15 of file EigenMatrixTypedefs.h
typedef Matrix3x3 genfit::Matrix3x3Sym
Definition at line 24 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 24 of file EigenMatrixTypedefs.h
typedef Eigen::Matrix<Precision, 4, 4> genfit::Matrix4x4
Definition at line 16 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 16 of file EigenMatrixTypedefs.h
typedef Matrix4x4 genfit::Matrix4x4Sym
Definition at line 25 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 25 of file EigenMatrixTypedefs.h
typedef Eigen::Matrix<Precision, 5, 5> genfit::Matrix5x5
Definition at line 17 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 17 of file EigenMatrixTypedefs.h
typedef Matrix5x5 genfit::Matrix5x5Sym
Definition at line 26 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 26 of file EigenMatrixTypedefs.h
typedef Eigen::Matrix<Precision, 6, 6> genfit::Matrix6x6
Definition at line 18 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 18 of file EigenMatrixTypedefs.h
typedef Matrix6x6 genfit::Matrix6x6Sym
Definition at line 27 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 27 of file EigenMatrixTypedefs.h
typedef Eigen::Matrix<Precision, 7, 7> genfit::Matrix7x7
Definition at line 19 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 19 of file EigenMatrixTypedefs.h
typedef Matrix7x7 genfit::Matrix7x7Sym
Definition at line 28 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 28 of file EigenMatrixTypedefs.h
typedef Eigen::Matrix<Precision, Eigen::Dynamic, Eigen::Dynamic> genfit::MatrixDynamic
Definition at line 22 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 22 of file EigenMatrixTypedefs.h
typedef double genfit::Precision
Definition at line 6 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 6 of file EigenMatrixTypedefs.h
typedef Precision genfit::Scalar
Definition at line 8 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 8 of file EigenMatrixTypedefs.h
typedef std::shared_ptr< genfit::DetPlane > genfit::SharedPlanePtr
Shared Pointer to a DetPlane.
Ownership can be shared, e.g between multiple StateOnPlane objects. The DetPlane will automatically be deleted, if no owner remains.
Definition at line 40 of file SharedPlanePtr.h.
View newest version in sPHENIX GitHub at line 40 of file SharedPlanePtr.h
typedef Eigen::Matrix<Precision, 3, 1> genfit::Vector3
Definition at line 10 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 10 of file EigenMatrixTypedefs.h
typedef Eigen::Matrix<Precision, 5, 1> genfit::Vector5
Definition at line 11 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 11 of file EigenMatrixTypedefs.h
typedef Eigen::Matrix<Precision, 6, 1> genfit::Vector6
Definition at line 12 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 12 of file EigenMatrixTypedefs.h
typedef Eigen::Matrix<Precision, 7, 1> genfit::Vector7
Definition at line 13 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 13 of file EigenMatrixTypedefs.h
typedef Eigen::Matrix<Precision, Eigen::Dynamic, 1> genfit::VectorDynamic
Definition at line 21 of file EigenMatrixTypedefs.h.
View newest version in sPHENIX GitHub at line 21 of file EigenMatrixTypedefs.h
Enumeration Type Documentation
enum genfit::eFitterType
Enumerator:
SimpleKalman
RefKalman
DafSimple
DafRef
Definition at line 41 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 41 of file EventDisplay.h
enum genfit::eMeasurementType
Enumerator:
Pixel
Spacepoint
ProlateSpacepoint
StripU
StripV
StripUV
Wire
WirePoint
nMeasurementTypes
Definition at line 42 of file MeasurementCreator.h.
View newest version in sPHENIX GitHub at line 42 of file MeasurementCreator.h
enum genfit::eMultipleMeasurementHandling
Enumerator:
weightedAverage
weighted average between measurements; used by DAF
unweightedAverage
average between measurements, all weighted with 1
weightedClosestToReference
closest to reference, weighted with its weight_
unweightedClosestToReference
closest to reference, weighted with 1
weightedClosestToPrediction
closest to prediction, weighted with its weight_
unweightedClosestToPrediction
closest to prediction, weighted with 1
weightedClosestToReferenceWire
if corresponding TrackPoint has one WireMeasurement, select closest to reference, weighted with its weight_. Otherwise use weightedAverage.
unweightedClosestToReferenceWire
if corresponding TrackPoint has one WireMeasurement, select closest to reference, weighted with 1. Otherwise use unweightedAverage.
weightedClosestToPredictionWire
if corresponding TrackPoint has one WireMeasurement, select closest to prediction, weighted with its weight_. Otherwise use weightedAverage.
unweightedClosestToPredictionWire
if corresponding TrackPoint has one WireMeasurement, select closest to prediction, weighted with 1. Otherwise use unweightedAverage. Recommended for KalmanFitter to 'resolve' l/r ambiguities
Definition at line 35 of file AbsKalmanFitter.h.
View newest version in sPHENIX GitHub at line 35 of file AbsKalmanFitter.h
enum genfit::StepLimitType
Enumerator:
stp_noLimit
stp_fieldCurv
stp_momLoss
stp_sMax
stp_sMaxArg
stp_boundary
stp_plane
ENUM_NR_ITEMS
Definition at line 33 of file StepLimits.h.
View newest version in sPHENIX GitHub at line 33 of file StepLimits.h
Function Documentation
MeasuredStateOnPlane genfit::calcAverageState (const MeasuredStateOnPlane & forwardState, const MeasuredStateOnPlane & backwardState)
Calculate weighted average between two MeasuredStateOnPlanes.
Definition at line 76 of file MeasuredStateOnPlane.cc.
View newest version in sPHENIX GitHub at line 76 of file MeasuredStateOnPlane.cc
References A, assert, KFPMath::b, bk(), genfit::StateOnPlane::getAuxInfo(), genfit::MeasuredStateOnPlane::getCov(), genfit::StateOnPlane::getPlane(), genfit::StateOnPlane::getRep(), genfit::StateOnPlane::getState(), i, genfit::tools::invertMatrix(), j, genfit::tools::QR(), genfit::MeasuredStateOnPlane::setCov(), genfit::StateOnPlane::setState(), sum(), and genfit::tools::transposedInvert().
Referenced by genfit::KalmanFitterInfo::getFittedState().
TMatrixDSym genfit::Covariance3DToTMatrixDSym (const rave::Covariance3D & ravecov)
Definition at line 243 of file GFRaveConverters.cc.
View newest version in sPHENIX GitHub at line 243 of file GFRaveConverters.cc
Referenced by RaveToGFVertex().
TMatrixDSym genfit::Covariance6DToTMatrixDSym (const rave::Covariance6D & ravecov)
Definition at line 279 of file GFRaveConverters.cc.
View newest version in sPHENIX GitHub at line 279 of file GFRaveConverters.cc
Referenced by RaveToGFVertex(), and setData().
template<unsigned int rows, unsigned int cols> RKMatrix<rows, cols> genfit::eigenMatrixToRKMatrix (const Eigen::Matrix< double, rows, cols > & eigenMatrix)
Definition at line 23 of file RKMatrixEigenTransformations.h.
View newest version in sPHENIX GitHub at line 23 of file RKMatrixEigenTransformations.h
References col.
template<unsigned int rows, unsigned int cols> TMatrixD genfit::eigenMatrixToRootMatrix (const Eigen::Matrix< double, rows, cols > & eigenMatrix)
Definition at line 82 of file RootEigenTransformations.h.
View newest version in sPHENIX GitHub at line 82 of file RootEigenTransformations.h
References col.
template<unsigned int dim> TMatrixDSym genfit::eigenMatrixToRootMatrixSym (const Eigen::Matrix< double, dim, dim > & eigenMatrix)
Definition at line 54 of file RootEigenTransformations.h.
View newest version in sPHENIX GitHub at line 54 of file RootEigenTransformations.h
References col.
template<unsigned int dim> TVectorD genfit::eigenVectorToRootVector (const Eigen::Matrix< double, dim, 1 > & eigenVector)
Definition at line 25 of file RootEigenTransformations.h.
View newest version in sPHENIX GitHub at line 25 of file RootEigenTransformations.h
std::vector< rave::Track > genfit::GFTracksToTracks (const std::vector< genfit::Track * > & GFTracks, std::vector< genfit::MeasuredStateOnPlane * > * GFStates, std::map< int, genfit::trackAndState > & IdGFTrackStateMap, int startID = 0)
Convert a vector of genfit::Tracks to rave::Tracks also builds a map of unique ids to genfit::Tracks; These ids are stored in the rave::tracks. They are counted from startID. The map has to be passed to the GFRavePropagator, so that it can access the trackreps of the genfit::Tracks corresponding to the rave::tracks. If a vector of MeasuredStateOnPlane is provided, they will be used (instead of the tracks fitted states) to calculate the rave::Track parameters. Ownership over MeasuredStateOnPlane will be taken.
Definition at line 36 of file GFRaveConverters.cc.
View newest version in sPHENIX GitHub at line 36 of file GFRaveConverters.cc
References GFTrackToTrack(), and i.
Referenced by genfit::GFRaveVertexFactory::findVertices(), and PHRaveVertexFactory::findVertices().
rave::Track genfit::GFTrackToTrack (trackAndState trackAndState, int id = -1, std::string tag = "")
Definition at line 83 of file GFRaveConverters.cc.
View newest version in sPHENIX GitHub at line 83 of file GFRaveConverters.cc
References genfit::FitStatus::getCharge(), genfit::FitStatus::getChi2(), genfit::Track::getFitStatus(), genfit::Track::getFittedState(), genfit::FitStatus::getNdf(), genfit::MeasuredStateOnPlane::getPosMomCov(), genfit::FitStatus::isFitConverged(), pos, and genfit::trackAndState::track_.
Referenced by genfit::GFRavePropagator::closestTo(), GFTracksToTracks(), and genfit::GFRavePropagator::to().
double genfit::MeanExcEnergy_get (int Z)
Referenced by genfit::TGeoMaterialInterface::getMaterialParameters(), and MeanExcEnergy_get().
double genfit::MeanExcEnergy_get (TGeoMaterial * mat)
Definition at line 255 of file TGeoMaterialInterface.cc.
View newest version in sPHENIX GitHub at line 255 of file TGeoMaterialInterface.cc
References denom, i, index, and MeanExcEnergy_get().
double genfit::MeanExcEnergy_get (int Z, bool logs = false)
Definition at line 245 of file TGeoMaterialInterface.cc.
View newest version in sPHENIX GitHub at line 245 of file TGeoMaterialInterface.cc
References assert, MeanExcEnergy_logs, MeanExcEnergy_NELEMENTS, MeanExcEnergy_vals, and SVM_v1::Z.
AbsFitterInfo* genfit::new_clone (const AbsFitterInfo & a) inline
Needed for boost cloneability:
Definition at line 108 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 108 of file AbsFitterInfo.h
References genfit::AbsFitterInfo::clone().
bool genfit::operator!= (const Material & lhs, const Material & rhs)
Definition at line 19 of file Material.cc.
View newest version in sPHENIX GitHub at line 19 of file Material.cc
bool genfit::operator!= (const DetPlane & lhs, const DetPlane & rhs)
Definition at line 262 of file DetPlane.cc.
View newest version in sPHENIX GitHub at line 262 of file DetPlane.cc
bool genfit::operator== (const Material & lhs, const Material & rhs)
Definition at line 7 of file Material.cc.
View newest version in sPHENIX GitHub at line 7 of file Material.cc
References genfit::Material::A, genfit::Material::density, genfit::Material::mEE, genfit::Material::radiationLength, and genfit::Material::Z.
bool genfit::operator== (const TrackCandHit & lhs, const TrackCandHit & rhs)
Definition at line 46 of file TrackCandHit.cc.
View newest version in sPHENIX GitHub at line 46 of file TrackCandHit.cc
References genfit::TrackCandHit::detId_, genfit::TrackCandHit::hitId_, and genfit::TrackCandHit::planeId_.
bool genfit::operator== (const TrackCand & lhs, const TrackCand & rhs)
Definition at line 191 of file TrackCand.cc.
View newest version in sPHENIX GitHub at line 191 of file TrackCand.cc
References genfit::TrackCand::getHit(), genfit::TrackCand::getNHits(), and i.
bool genfit::operator== (const DetPlane & lhs, const DetPlane & rhs)
Definition at line 240 of file DetPlane.cc.
View newest version in sPHENIX GitHub at line 240 of file DetPlane.cc
References genfit::DetPlane::o_, genfit::DetPlane::u_, and genfit::DetPlane::v_.
SharedPlanePtr genfit::PlaneToGFDetPlane (const ravesurf::Plane & rplane)
Definition at line 225 of file GFRaveConverters.cc.
View newest version in sPHENIX GitHub at line 225 of file GFRaveConverters.cc
References Point3DToTVector3(), and Vector3DToTVector3().
Referenced by genfit::GFRavePropagator::to().
TVector3 genfit::Point3DToTVector3 (const rave::Point3D & v)
Definition at line 232 of file GFRaveConverters.cc.
View newest version in sPHENIX GitHub at line 232 of file GFRaveConverters.cc
Referenced by genfit::GFRavePropagator::closestTo(), PlaneToGFDetPlane(), and RaveToGFVertex().
GFRaveVertex * genfit::RaveToGFVertex (const rave::Vertex & raveVertex, const std::map< int, genfit::trackAndState > & IdGFTrackStateMap)
Definition at line 141 of file GFRaveConverters.cc.
View newest version in sPHENIX GitHub at line 141 of file GFRaveConverters.cc
References Covariance3DToTMatrixDSym(), Covariance6DToTMatrixDSym(), i, Point3DToTVector3(), and Vector6DToTVectorD().
Referenced by RaveToGFVertices().
void genfit::RaveToGFVertices (std::vector< GFRaveVertex * > * GFVertices, const std::vector< rave::Vertex > & raveVertices, const std::map< int, genfit::trackAndState > & IdGFTrackStateMap)
Definition at line 210 of file GFRaveConverters.cc.
View newest version in sPHENIX GitHub at line 210 of file GFRaveConverters.cc
References i, and RaveToGFVertex().
Referenced by genfit::GFRaveVertexFactory::findVertices(), and PHRaveVertexFactory::findVertices().
template<unsigned int rows, unsigned int cols> Eigen::Matrix<double, rows, cols> genfit::RKMatrixToEigenMatrix (const RKMatrix< rows, cols > & rkMatrix)
Definition at line 9 of file RKMatrixEigenTransformations.h.
View newest version in sPHENIX GitHub at line 9 of file RKMatrixEigenTransformations.h
References col.
template<unsigned int dim> Eigen::Matrix<double, dim, dim> genfit::rootMatrixSymToEigenMatrix (const TMatrixDSym & rootMatrix)
Definition at line 39 of file RootEigenTransformations.h.
View newest version in sPHENIX GitHub at line 39 of file RootEigenTransformations.h
References assert, and col.
template<unsigned int rows, unsigned int cols> Eigen::Matrix<double, rows, cols> genfit::rootMatrixToEigenMatrix (const TMatrixD & rootMatrix)
Definition at line 67 of file RootEigenTransformations.h.
View newest version in sPHENIX GitHub at line 67 of file RootEigenTransformations.h
References assert, and col.
template<unsigned int dim> Eigen::Matrix<double, dim, 1> genfit::rootVectorToEigenVector (const TVectorD & rootVector)
Definition at line 10 of file RootEigenTransformations.h.
View newest version in sPHENIX GitHub at line 10 of file RootEigenTransformations.h
References assert.
void genfit::setData (const rave::Track & orig, MeasuredStateOnPlane * state)
set state and cov of a MeasuredStateOnPlane according to rave track
Definition at line 131 of file GFRaveConverters.cc.
View newest version in sPHENIX GitHub at line 131 of file GFRaveConverters.cc
References Covariance6DToTMatrixDSym(), and genfit::MeasuredStateOnPlane::setPosMomCov().
genfit::TEST_F (UnitTests , Energy)
Definition at line 11 of file TestUnits.cpp.
View newest version in sPHENIX GitHub at line 11 of file TestUnits.cpp
References genfit::Unit::eV, genfit::Unit::GeV, genfit::Unit::keV, and genfit::Unit::MeV.
genfit::TEST_F (MaterialTests , Constructor01)
Definition at line 11 of file TestMaterial.cpp.
View newest version in sPHENIX GitHub at line 11 of file TestMaterial.cpp
References genfit::Material::A, genfit::Material::density, genfit::Material::mEE, genfit::Material::radiationLength, and genfit::Material::Z.
genfit::TEST_F (RootEigenTransformations , VectorTransformation)
Definition at line 14 of file TestRootEigenTransformations.cpp.
View newest version in sPHENIX GitHub at line 14 of file TestRootEigenTransformations.cpp
genfit::TEST_F (RKMatrixEigenTransformations , VectorTransformation)
Definition at line 13 of file TestRKMatrixEigenTransformations.cpp.
View newest version in sPHENIX GitHub at line 13 of file TestRKMatrixEigenTransformations.cpp
genfit::TEST_F (ConstFieldUninitializedTests , UninitializedBehaviour)
Definition at line 15 of file TestConstField.cpp.
View newest version in sPHENIX GitHub at line 15 of file TestConstField.cpp
References genfit::FieldManager::getInstance().
genfit::TEST_F (MaterialTests , Constructor02)
Definition at line 20 of file TestMaterial.cpp.
View newest version in sPHENIX GitHub at line 20 of file TestMaterial.cpp
References genfit::Material::A, genfit::Material::density, genfit::Material::mEE, genfit::Material::radiationLength, and genfit::Material::Z.
genfit::TEST_F (MaterialTests , ComparisonOperators)
Definition at line 29 of file TestMaterial.cpp.
View newest version in sPHENIX GitHub at line 29 of file TestMaterial.cpp
genfit::TEST_F (RKTrackRepTests , RKStep)
Definition at line 30 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 30 of file TestRKTrackRep.cpp
References genfit::RKStep::state7_.
genfit::TEST_F (RKMatrixEigenTransformations , MatrixTransformation)
Definition at line 30 of file TestRKMatrixEigenTransformations.cpp.
View newest version in sPHENIX GitHub at line 30 of file TestRKMatrixEigenTransformations.cpp
genfit::TEST_F (ConstFieldInitializedTests , InitializedBehaviour)
Definition at line 37 of file TestConstField.cpp.
View newest version in sPHENIX GitHub at line 37 of file TestConstField.cpp
References genfit::FieldManager::getInstance().
genfit::TEST_F (RootEigenTransformations , SymmetricMatrixTransformation)
Definition at line 37 of file TestRootEigenTransformations.cpp.
View newest version in sPHENIX GitHub at line 37 of file TestRootEigenTransformations.cpp
References col.
genfit::TEST_F (RKTrackRepTests , ExtrapStep)
Definition at line 42 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 42 of file TestRKTrackRep.cpp
References genfit::ExtrapStep::jac7_, and genfit::ExtrapStep::noise7_.
genfit::TEST_F (RootEigenTransformations , MatrixTransformation)
Definition at line 101 of file TestRootEigenTransformations.cpp.
View newest version in sPHENIX GitHub at line 101 of file TestRootEigenTransformations.cpp
References col.
genfit::TEST_F (RKTrackRepTests , RKPropagate01)
Black-Box-Test.
Definition at line 159 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 159 of file TestRKTrackRep.cpp
References genfit::RKTrackRep::RKPropagate(), and genfit::RKMatrix< nRows, nCols >::vals.
genfit::TEST_F (RKTrackRepTests , RKPropagate02)
Black-Box-Test.
Definition at line 189 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 189 of file TestRKTrackRep.cpp
References genfit::RKTrackRep::RKPropagate(), and genfit::RKMatrix< nRows, nCols >::vals.
genfit::TEST_F (RKTrackRepTests , getState7)
White-Box-Test.
Definition at line 219 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 219 of file TestRKTrackRep.cpp
References genfit::RKTrackRep::getState7(), and genfit::RKMatrix< nRows, nCols >::vals.
genfit::TEST_F (RKTrackRepTests , getState5)
White-Box-Test.
Definition at line 260 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 260 of file TestRKTrackRep.cpp
References genfit::StateOnPlane::getState(), and genfit::RKTrackRep::getState5().
genfit::TEST_F (RKTrackRepTests , calcJ_pM_5x7)
White-Box-Test.
Definition at line 292 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 292 of file TestRKTrackRep.cpp
genfit::TEST_F (RKTrackRepTests , transformPM6)
White-Box-Test.
Definition at line 297 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 297 of file TestRKTrackRep.cpp
genfit::TEST_F (RKTrackRepTests , calcJ_Mp_7x5)
White-Box-Test.
Definition at line 302 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 302 of file TestRKTrackRep.cpp
genfit::TEST_F (RKTrackRepTests , calcForwardJacobianAndNoise)
White-Box-Test.
Definition at line 307 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 307 of file TestRKTrackRep.cpp
References genfit::RKTrackRep::calcForwardJacobianAndNoise(), and genfit::RKTrackRep::ExtrapSteps_.
genfit::TEST_F (RKTrackRepTests , transformM6P)
White-Box-Test.
Definition at line 325 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 325 of file TestRKTrackRep.cpp
genfit::TEST_F (RKTrackRepTests , RKutta)
White-Box-Test.
Definition at line 330 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 330 of file TestRKTrackRep.cpp
genfit::TEST_F (RKTrackRepTests , estimateStep)
White-Box-Test.
Definition at line 335 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 335 of file TestRKTrackRep.cpp
genfit::TEST_F (RKTrackRepTests , Extrap)
White-Box-Test.
Definition at line 340 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 340 of file TestRKTrackRep.cpp
genfit::TEST_F (RKTrackRepTests , momMag)
White-Box-Test.
Definition at line 345 of file TestRKTrackRep.cpp.
View newest version in sPHENIX GitHub at line 345 of file TestRKTrackRep.cpp
References genfit::RKTrackRep::momMag().
rave::Covariance3D genfit::TMatrixDSymToCovariance3D (const TMatrixDSym & matrix)
Definition at line 335 of file GFRaveConverters.cc.
View newest version in sPHENIX GitHub at line 335 of file GFRaveConverters.cc
Referenced by genfit::GFRaveVertexFactory::setBeamspot().
rave::Point3D genfit::TVector3ToPoint3D (const TVector3 & vec)
Definition at line 329 of file GFRaveConverters.cc.
View newest version in sPHENIX GitHub at line 329 of file GFRaveConverters.cc
Referenced by genfit::GFRaveVertexFactory::setBeamspot().
TVector3 genfit::Vector3DToTVector3 (const rave::Vector3D & v)
Definition at line 237 of file GFRaveConverters.cc.
View newest version in sPHENIX GitHub at line 237 of file GFRaveConverters.cc
Referenced by PlaneToGFDetPlane().
TVectorD genfit::Vector6DToTVectorD (const rave::Vector6D & ravevec)
Definition at line 263 of file GFRaveConverters.cc.
View newest version in sPHENIX GitHub at line 263 of file GFRaveConverters.cc
Referenced by RaveToGFVertex().
Variable Documentation
std::ostream genfit::debugOut
Default stream for debug output. Defaults to std::cout. Override destination with debugOut.rdbuf(newStream.rdbuf()).
Referenced by genfit::RKTrackRep::calcForwardJacobianAndNoise(), genfit::DAF::calcWeights(), genfit::RKTrackRep::checkCache(), genfit::Track::deleteBackwardInfo(), genfit::Track::deleteFitterInfo(), genfit::Track::deleteForwardInfo(), genfit::Track::deleteMeasurementInfo(), genfit::Track::deletePoint(), genfit::Track::deleteReferenceInfo(), genfit::MaterialEffects::effects(), genfit::RKTrackRep::estimateStep(), genfit::RKTrackRep::Extrap(), genfit::RKTrackRep::extrapolateBy(), genfit::RKTrackRep::extrapolateToCone(), genfit::RKTrackRep::extrapolateToCylinder(), genfit::RKTrackRep::extrapolateToLine(), genfit::RKTrackRep::extrapolateToPlane(), genfit::RKTrackRep::extrapolateToSphere(), genfit::RKTrackRep::extrapToPoint(), genfit::TGeoMaterialInterface::findNextBoundary(), genfit::KalmanFitterRefTrack::fitTrack(), genfit::KalmanFitter::fitTrack(), genfit::RKTrackRep::getBackwardJacobianAndNoise(), genfit::KalmanFitterInfo::getFittedState(), genfit::RKTrackRep::getForwardJacobianAndNoise(), genfit::Exception::info(), genfit::TGeoMaterialInterface::initTrack(), genfit::Track::insertPoint(), genfit::Track::mergeTrack(), genfit::MaterialEffects::momentumLoss(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitter::processTrackPartially(), genfit::KalmanFitter::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::KalmanFitterRefTrack::processTrackWithRep(), genfit::KalmanFitter::processTrackWithRep(), genfit::DAF::processTrackWithRep(), genfit::Track::prune(), genfit::KalmanFitterRefTrack::removeOutdated(), genfit::RKTrackRep::RKPropagate(), genfit::RKTrackRep::RKutta(), genfit::Track::sort(), genfit::MaterialEffects::stepper(), and genfit::Track::trackHasChanged().
std::ostream genfit::errorOut
Default stream for error output. Defaults to std::cerr. Override destination with errorOut.rdbuf(newStream.rdbuf()).
Referenced by genfit::DAF::calcWeights(), genfit::KalmanFitterInfo::checkConsistency(), genfit::FieldManager::checkInitialized(), genfit::FieldManager::checkInstanciated(), genfit::KalmanFitter::fitTrack(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitterRefTrack::processTrackWithRep(), genfit::KalmanFitter::processTrackWithRep(), genfit::DAF::processTrackWithRep(), genfit::ReferenceStateOnPlane::ReferenceStateOnPlane(), genfit::Track::setCardinalRep(), genfit::MaterialEffects::setMscModel(), and genfit::KalmanFitterInfo::setWeights().
const double genfit::MeanExcEnergy_logs[MeanExcEnergy_NELEMENTS]
Initial value:
= {
  34.5388, 2.95491, 3.7329, 3.68888, 4.15418, 4.33073, 4.35671, 4.40672,
  4.55388, 4.74493, 4.91998, 5.00395, 5.04986, 5.11199, 5.15329, 5.15329,
  5.19296, 5.15906, 5.23644, 5.24702, 5.25227, 5.37528, 5.45104, 5.50126,
  5.54908, 5.6058, 5.65599, 5.69373, 5.73979, 5.77455, 5.79909, 5.81114,
  5.85793, 5.84932, 5.8522, 5.83773, 5.86363, 5.8944, 5.90263, 5.93754,
  5.97381, 6.03309, 6.04973, 6.05912, 6.08904, 6.10702, 6.15273, 6.15273,
  6.1506, 6.19032, 6.19032, 6.18826, 6.18415, 6.19644, 6.17794, 6.19032,
  6.19644, 6.21661, 6.25958, 6.28227, 6.30262, 6.32794, 6.35263, 6.36303,
  6.38182, 6.41999, 6.44254, 6.47697, 6.4892, 6.51323, 6.52796, 6.54247,
  6.5582, 6.57647, 6.58893, 6.60123, 6.61473, 6.62936, 6.67203, 6.67203,
  6.68461, 6.69703, 6.71296, 6.71296, 6.72143, 6.71538, 6.67708, 6.7178,
  6.71659, 6.73459, 6.7417, 6.77765, 6.79122, }
Definition at line 229 of file TGeoMaterialInterface.cc.
View newest version in sPHENIX GitHub at line 229 of file TGeoMaterialInterface.cc
Referenced by MeanExcEnergy_get().
const int genfit::MeanExcEnergy_NELEMENTS = 93
Definition at line 214 of file TGeoMaterialInterface.cc.
View newest version in sPHENIX GitHub at line 214 of file TGeoMaterialInterface.cc
Referenced by MeanExcEnergy_get().
const double genfit::MeanExcEnergy_vals[MeanExcEnergy_NELEMENTS]
Initial value:
= {
  1.e15, 19.2, 41.8, 40.0, 63.7, 76.0, 78., 82.0,
  95.0, 115.0, 137.0, 149.0, 156.0, 166.0, 173.0, 173.0,
  180.0, 174.0, 188.0, 190.0, 191.0, 216.0, 233.0, 245.0,
  257.0, 272.0, 286.0, 297.0, 311.0, 322.0, 330.0, 334.0,
  350.0, 347.0, 348.0, 343.0, 352.0, 363.0, 366.0, 379.0,
  393.0, 417.0, 424.0, 428.0, 441.0, 449.0, 470.0, 470.0,
  469.0, 488.0, 488.0, 487.0, 485.0, 491.0, 482.0, 488.0,
  491.0, 501.0, 523.0, 535.0, 546.0, 560.0, 574.0, 580.0,
  591.0, 614.0, 628.0, 650.0, 658.0, 674.0, 684.0, 694.0,
  705.0, 718.0, 727.0, 736.0, 746.0, 757.0, 790.0, 790.0,
  800.0, 810.0, 823.0, 823.0, 830.0, 825.0, 794.0, 827.0,
  826.0, 841.0, 847.0, 878.0, 890.0, }
Definition at line 215 of file TGeoMaterialInterface.cc.
View newest version in sPHENIX GitHub at line 215 of file TGeoMaterialInterface.cc
Referenced by MeanExcEnergy_get().
std::ostream genfit::printOut
Default stream for output of Print calls. Defaults to std::cout. Override destination with printOut.rdbuf(newStream.rdbuf()).
Referenced by genfit::Material::Print(), genfit::RectangularFinitePlane::Print(), genfit::ThinScatterer::Print(), genfit::HMatrixPhi::Print(), genfit::HMatrixU::Print(), genfit::HMatrixV::Print(), genfit::TrackCandHit::Print(), genfit::PruneFlags::Print(), genfit::HMatrixUnit::Print(), genfit::HMatrixUV::Print(), genfit::WireTrackCandHit::Print(), genfit::KalmanFitStatus::Print(), genfit::MeasurementOnPlane::Print(), genfit::MeasuredStateOnPlane::Print(), genfit::ReferenceStateOnPlane::Print(), genfit::StepLimits::Print(), genfit::AbsMeasurement::Print(), genfit::KalmanFitterInfo::Print(), genfit::TrackPoint::Print(), genfit::DetPlane::Print(), genfit::StateOnPlane::Print(), genfit::FitStatus::Print(), genfit::TrackCand::Print(), genfit::Track::Print(), genfit::AbsTrackRep::Print(), and genfit::RKTools::printDim().