Analysis Software: genfit::TGeoMaterialInterface Class Reference
genfit::TGeoMaterialInterface Class Reference
AbsMaterialInterface implementation for use with ROOT's TGeoManager.
#include <GenFit/blob/master/trackReps/include/TGeoMaterialInterface.h>
Public Member Functions
TGeoMaterialInterface ()
~TGeoMaterialInterface ()
bool initTrack (double posX, double posY, double posZ, double dirX, double dirY, double dirZ) override
Initialize the navigator at given position and with given direction. Returns true if the volume changed.
Material getMaterialParameters () override
double findNextBoundary (const RKTrackRep *rep, const M1x7 &state7, double sMax, bool varField=true) override
Make a step (following the curvature) until step length sMax or the next boundary is reached. After making a step to a boundary, the position has to be beyond the boundary, i.e. the current material has to be that beyond the boundary. The actual step made is returned.
Public Member Functions inherited from genfit::AbsMaterialInterface
AbsMaterialInterface ()
virtual ~AbsMaterialInterface ()
virtual void setDebugLvl (unsigned int lvl=1)
Additional Inherited Members
Protected Attributes inherited from genfit::AbsMaterialInterface
unsigned int debugLvl_
Detailed Description
AbsMaterialInterface implementation for use with ROOT's TGeoManager.
Definition at line 35 of file TGeoMaterialInterface.h.
View newest version in sPHENIX GitHub at line 35 of file TGeoMaterialInterface.h
Constructor & Destructor Documentation
genfit::TGeoMaterialInterface::TGeoMaterialInterface () inline
Definition at line 39 of file TGeoMaterialInterface.h.
View newest version in sPHENIX GitHub at line 39 of file TGeoMaterialInterface.h
genfit::TGeoMaterialInterface::~TGeoMaterialInterface () inline
Definition at line 40 of file TGeoMaterialInterface.h.
View newest version in sPHENIX GitHub at line 40 of file TGeoMaterialInterface.h
Member Function Documentation
double genfit::TGeoMaterialInterface::findNextBoundary (const RKTrackRep * rep, const M1x7 & state7, double sMax, bool varField = true) override virtual
Make a step (following the curvature) until step length sMax or the next boundary is reached. After making a step to a boundary, the position has to be beyond the boundary, i.e. the current material has to be that beyond the boundary. The actual step made is returned.
Implements genfit::AbsMaterialInterface.
Definition at line 70 of file TGeoMaterialInterface.cc.
View newest version in sPHENIX GitHub at line 70 of file TGeoMaterialInterface.cc
References genfit::AbsMaterialInterface::debugLvl_, genfit::debugOut, E, initTrack(), it, max, genfit::RKTrackRep::RKPropagate(), s, genfit::Exception::setFatal(), and step.
Material genfit::TGeoMaterialInterface::getMaterialParameters () override virtual
Implements genfit::AbsMaterialInterface.
Definition at line 61 of file TGeoMaterialInterface.cc.
View newest version in sPHENIX GitHub at line 61 of file TGeoMaterialInterface.cc
References genfit::MeanExcEnergy_get().
bool genfit::TGeoMaterialInterface::initTrack (double posX, double posY, double posZ, double dirX, double dirY, double dirZ) override virtual
Initialize the navigator at given position and with given direction. Returns true if the volume changed.
Implements genfit::AbsMaterialInterface.
Definition at line 38 of file TGeoMaterialInterface.cc.
View newest version in sPHENIX GitHub at line 38 of file TGeoMaterialInterface.cc
References genfit::AbsMaterialInterface::debugLvl_, and genfit::debugOut.
Referenced by findNextBoundary().
The documentation for this class was generated from the following files:
GenFit/blob/master/trackReps/include/TGeoMaterialInterface.h
GenFit/blob/master/trackReps/src/TGeoMaterialInterface.cc