Analysis Software: genfit::mySpacepointMeasurement Class Reference
genfit::mySpacepointMeasurement Class Reference
Example class for a spacepoint measurement which can be created from mySpacepointDetectorHit via the MeasurementFactory.
#include <GenFit/blob/master/utilities/include/mySpacepointMeasurement.h>
Public Member Functions
mySpacepointMeasurement ()
mySpacepointMeasurement (const mySpacepointDetectorHit *detHit, const TrackCandHit *hit)
virtual mySpacepointMeasurement * clone () const
Deep copy ctor for polymorphic class.
Public Member Functions inherited from genfit::SpacepointMeasurement
SpacepointMeasurement (int nDim=3)
SpacepointMeasurement (const TVectorD &rawHitCoords, const TMatrixDSym &rawHitCov, int detId, int hitId, TrackPoint *trackPoint, bool weightedPlaneContruction=true, bool cutCov=true)
virtual ~SpacepointMeasurement ()
virtual SharedPlanePtr constructPlane (const StateOnPlane &state) const override
Contruct the virtual detector plane.
virtual std::vector
< MeasurementOnPlane * > constructMeasurementsOnPlane (const StateOnPlane &state) const override
virtual const AbsHMatrix * constructHMatrix (const AbsTrackRep *) const override
bool getWeightedPlaneConstruction () const
false: project 3D cov onto DetPlane. true: cut 3D cov with DetPlane
void setWeightedPlaneConstruction (bool value)
bool getCutCov () const
false: use POCA to construct DetPlane. true: Use metric G to construct POCA
void setCutCov (bool value)
Public Member Functions inherited from genfit::AbsMeasurement
AbsMeasurement ()
AbsMeasurement (int nDims)
AbsMeasurement (const TVectorD &rawHitCoords, const TMatrixDSym &rawHitCov, int detId, int hitId, TrackPoint *trackPoint)
virtual ~AbsMeasurement ()
TrackPoint * getTrackPoint () const
void setTrackPoint (TrackPoint *tp)
const TVectorD & getRawHitCoords () const
const TMatrixDSym & getRawHitCov () const
TVectorD & getRawHitCoords ()
TMatrixDSym & getRawHitCov ()
int getDetId () const
int getHitId () const
virtual bool isLeftRightMeasurement () const
If the AbsMeasurement is a wire hit, the left/right resolution will be used.
virtual int getLeftRightResolution () const
unsigned int getDim () const
void setRawHitCoords (const TVectorD &coords)
void setRawHitCov (const TMatrixDSym &cov)
void setDetId (int detId)
void setHitId (int hitId)
virtual void Print (const Option_t *="") const
Additional Inherited Members
Protected Member Functions inherited from genfit::SpacepointMeasurement
void initG ()
Protected Attributes inherited from genfit::AbsMeasurement
TVectorD rawHitCoords_
TMatrixDSym rawHitCov_
int detId_
int hitId_
TrackPoint * trackPoint_
Pointer to TrackPoint where the measurement belongs to.
Detailed Description
Example class for a spacepoint measurement which can be created from mySpacepointDetectorHit via the MeasurementFactory.
Author
Johannes Rauch (Technische Universität München, original author)
Definition at line 36 of file mySpacepointMeasurement.h.
View newest version in sPHENIX GitHub at line 36 of file mySpacepointMeasurement.h
Constructor & Destructor Documentation
genfit::mySpacepointMeasurement::mySpacepointMeasurement () inline
Default constructor for ROOT IO.
Definition at line 41 of file mySpacepointMeasurement.h.
View newest version in sPHENIX GitHub at line 41 of file mySpacepointMeasurement.h
Referenced by clone().
genfit::mySpacepointMeasurement::mySpacepointMeasurement (const mySpacepointDetectorHit * detHit, const TrackCandHit * hit) inline
Definition at line 44 of file mySpacepointMeasurement.h.
View newest version in sPHENIX GitHub at line 44 of file mySpacepointMeasurement.h
References genfit::AbsMeasurement::detId_, genfit::mySpacepointDetectorHit::getCov(), genfit::TrackCandHit::getDetId(), genfit::TrackCandHit::getHitId(), genfit::mySpacepointDetectorHit::getPos(), genfit::AbsMeasurement::hitId_, genfit::SpacepointMeasurement::initG(), genfit::AbsMeasurement::rawHitCoords_, and genfit::AbsMeasurement::rawHitCov_.
Member Function Documentation
virtual mySpacepointMeasurement* genfit::mySpacepointMeasurement::clone () const inline virtual
Deep copy ctor for polymorphic class.
Reimplemented from genfit::SpacepointMeasurement.
Definition at line 57 of file mySpacepointMeasurement.h.
View newest version in sPHENIX GitHub at line 57 of file mySpacepointMeasurement.h
References mySpacepointMeasurement().
The documentation for this class was generated from the following file:
GenFit/blob/master/utilities/include/mySpacepointMeasurement.h