Analysis Software: KFParticleFinder Class Reference
KFParticleFinder Class Reference
Class for reconstruction short-lived particles.
#include <KFParticle/blob/master/KFParticle/KFParticleFinder.h>
Public Member Functions
KFParticleFinder ()
~KFParticleFinder ()
void Init (int nPV)
void SetNThreads (short int n)
Sets the number of threads to by run in parallel. Currently not used.
void FindParticles (KFPTrackVector *vRTracks, kfvector_float *ChiToPrimVtx, std::vector< KFParticle > &Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > &PrimVtx, int nPV)
void ExtrapolateToPV (std::vector< KFParticle > &vParticles, KFParticleSIMD &PrimVtx)
void ConstructV0 (KFPTrackVector *vTracks, int iTrTypePos, int iTrTypeNeg, uint_v &idPosDaughters, uint_v &idNegDaughters, int_v &daughterPosPDG, int_v &daughterNegPDG, KFParticleSIMD &mother, KFParticle &mother_temp, const unsigned short NTracks, kfvector_floatv &l, kfvector_floatv &dl, std::vector< KFParticle > &Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > &PrimVtx, const float *cuts, const int_v &pvIndex, const float *secCuts, const float_v &massMotherPDG, const float_v &massMotherPDGSigma, KFParticleSIMD &motherPrimSecCand, int &nPrimSecCand, std::vector< std::vector< KFParticle > > *vMotherPrim=0, std::vector< KFParticle > *vMotherSec=0) __attribute__((always_inline))
void SaveV0PrimSecCand (KFParticleSIMD &mother, int &NParticles, KFParticle &mother_temp, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > &PrimVtx, const float *secCuts, std::vector< std::vector< KFParticle > > *vMotherPrim, std::vector< KFParticle > *vMotherSec)
void ConstructTrackV0Cand (KFPTrackVector &vTracks, uint_v &idTracks, int_v &trackPDG, KFParticle *vV0[], KFParticleSIMD &mother, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > &motherTopo, KFParticle &mother_temp, const unsigned short nElements, kfvector_floatv &l, kfvector_floatv &dl, std::vector< KFParticle > &Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > &PrimVtx, const float_v *cuts, const int_v &pvIndex, const float_v &massMotherPDG, const float_v &massMotherPDGSigma, std::vector< std::vector< KFParticle > > *vMotherPrim, std::vector< KFParticle > *vMotherSec)
void Find2DaughterDecay (KFPTrackVector *vTracks, kfvector_float *ChiToPrimVtx, std::vector< KFParticle > &Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > &PrimVtx, const float *cuts, const float *secCuts, std::vector< std::vector< KFParticle > > *vMotherPrim, std::vector< KFParticle > *vMotherSec)
void ConstructPrimaryBG (KFPTrackVector *vTracks, std::vector< KFParticle > &Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > &PrimVtx, const float *cuts, const float *secCuts, std::vector< std::vector< KFParticle > > *vMotherPrim, std::vector< KFParticle > *vMotherSec)
void NeutralDaughterDecay (KFPTrackVector *vTracks, std::vector< KFParticle > &Particles)
void FindTrackV0Decay (std::vector< KFParticle > &vV0, const int V0PDG, KFPTrackVector &vTracks, const int q, const int firstTrack, const int lastTrack, std::vector< KFParticle > &Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > &PrimVtx, int v0PVIndex=-1, kfvector_float *ChiToPrimVtx=0, std::vector< std::vector< KFParticle > > *vMotherPrim=0, std::vector< KFParticle > *vMotherSec=0)
void SelectParticles (std::vector< KFParticle > &Particles, std::vector< KFParticle > &vCandidates, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > &PrimVtx, const float &cutChi2Topo, const float &cutLdL, const float &mass, const float &massErr, const float &massCut)
void CombinePartPart (std::vector< KFParticle > &particles1, std::vector< KFParticle > &particles2, std::vector< KFParticle > &Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > &PrimVtx, const float *cuts, int iPV, const int MotherPDG, bool isSameInputPart=0, bool saveOnlyPrimary=1, std::vector< std::vector< KFParticle > > *vMotherPrim=0, std::vector< KFParticle > *vMotherSec=0, float massMotherPDG=0.f, float massMotherPDGSigma=0.f)
void SetEmcClusters (KFPEmcCluster *clusters)
Set a pointer to the gamma-clusters from the electromagnetic calorimeter.
void SetMixedEventAnalysis ()
Switch KFParticleFinder to the mixed event mode.
const std::vector< KFParticle > * GetSecondaryCandidates () const
const std::vector< KFParticle > & GetSecondaryK0 () const
const std::vector< KFParticle > & GetSecondaryLambda () const
const std::vector< KFParticle > & GetSecondaryAntiLambda () const
const std::vector< KFParticle > & GetSecondaryGamma () const
const std::vector< KFParticle > & GetSecondaryPi0 () const
const std::vector< std::vector
< KFParticle > > * GetPrimaryCandidates () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryK0 () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryLambda () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryAntiLambda () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryGamma () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryPi0 () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryXi () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryAntiXi () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryOmega () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryAntiOmega () const
const std::vector< std::vector
< KFParticle > > * GetPrimaryTopoCandidates () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoK0 () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoLambda () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoAntiLambda () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoGamma () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoPi0 () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoXi () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoAntiXi () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoOmega () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoAntiOmega () const
const std::vector< std::vector
< KFParticle > > * GetPrimaryTopoMassCandidates () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoMassK0 () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoMassLambda () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoMassAntiLambda () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoMassGamma () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoMassPi0 () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoMassXi () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoMassAntiXi () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoMassOmega () const
const std::vector< std::vector
< KFParticle > > & GetPrimaryTopoMassAntiOmega () const
void AddCandidate (const KFParticle &candidate, int iPV=-1)
void SetNPV (int nPV)
void SetMaxDistanceBetweenParticlesCut (float cut)
Sets cut on the distance between secondary tracks at the DCA point.
void SetLCut (float cut)
Sets cut on the distance to the primary vertex from the decay vertex.
void SetChiPrimaryCut2D (float cut)
Sets cut on of each track for 2-daughter decays.
void SetChi2Cut2D (float cut)
Sets cut on for 2-daughter decays.
void SetLdLCut2D (float cut)
Sets cut on for 2-daughter decays.
void SetSecondaryCuts (const float sigmaMass=3.f, const float chi2Topo=5.f, const float ldl=10.f)
Sets cuts on selection of secondary and primary candidates: , , .
void SetLdLCutXiOmega (float cut)
Sets cut for and .
void SetChi2TopoCutXiOmega (float cut)
Sets cut for and .
void SetChi2CutXiOmega (float cut)
Sets cut for and .
void SetChi2TopoCutResonances (float cut)
Sets cut for resonances.
void SetChi2CutResonances (float cut)
Sets cut for resonances.
void SetPtCutLMVM (float cut)
Sets the cut on transverse momentum of each daughter track of low mass vector mesons.
void SetPCutLMVM (float cut)
Sets the cut on momentum of each daughter track of low mass vector mesons in dimuon channel.
void SetPtCutJPsi (float cut)
Sets the cut on transverse momentum of each daughter track of .
void SetPtCutCharm (float cut)
Sets the cut on transverse momentum of each daughter track of open charm particles.
void SetChiPrimaryCutCharm (float cut)
Sets cut on of each track for open charm particles.
void SetLdLCutCharmManybodyDecays (float cut)
Sets cut for open charm with >=3 daughters.
void SetChi2TopoCutCharmManybodyDecays (float cut)
Sets cut for open charm with >=3 daughters.
void SetChi2CutCharmManybodyDecays (float cut)
Sets cut for open charm with >=3 daughters.
void SetLdLCutCharm2D (float cut)
Sets cut for open charm with 2 daughters.
void SetChi2TopoCutCharm2D (float cut)
Sets cut for open charm with 2 daughters.
void SetChi2CutCharm2D (float cut)
Sets cut for open charm with 2 daughters.
void CopyCuts (const KFParticleFinder *finder)
const float GetMaxDistanceBetweenParticlesCut () const
Returns cut on the distance between secondary tracks at the DCA point.
const float GetLCut () const
Returns cut on the distance to the primary vertex from the decay vertex.
const float GetChiPrimaryCut2D () const
Returns cut on of each track for 2-daughter decays.
const float GetChi2Cut2D () const
Returns cut on for 2-daughter decays.
const float GetLdLCut2D () const
Returns cut on for 2-daughter decays.
const float GetSecondarySigmaMassCut () const
Returns cut for selection of primary and secondary candidates.
const float GetSecondaryChi2TopoCut () const
Returns cut for selection of primary and secondary candidates.
const float GetSecondaryLdLCut () const
Returns cut for selection of primary and secondary candidates.
const float GetLdLCutXiOmega () const
Returns cut for and .
const float GetChi2TopoCutXiOmega () const
Returns cut for and .
const float GetChi2CutXiOmega () const
Returns cut for and .
const float GetChi2TopoCutResonances () const
Returns cut for resonances.
const float GetChi2CutResonances () const
Returns cut for resonances.
const float GetPtCutLMVM () const
Returns cut on transverse momentum of each daughter track of low mass vector mesons.
const float GetPCutLMVM () const
Returns cut on momentum of each daughter track of low mass vector mesons in dimuon channel.
const float GetPtCutJPsi () const
Returns cut on transverse momentum of each daughter track of .
const float GetPtCutCharm () const
Returns the cut on transverse momentum of each daughter track of open charm particles.
const float GetChiPrimaryCutCharm () const
Returns cut on of each track for open charm particles.
const float GetLdLCutCharmManybodyDecays () const
Returns cut for open charm with >=3 daughters.
const float GetChi2TopoCutCharmManybodyDecays () const
Returns cut for open charm with >=3 daughters.
const float GetChi2CutCharmManybodyDecays () const
Returns cut for open charm with >=3 daughters.
const float GetLdLCutCharm2D () const
Returns cut for open charm with 2 daughters.
const float GetChi2TopoCutCharm2D () const
Returns cut for open charm with 2 daughters.
const float GetChi2CutCharm2D () const
Returns cut for open charm with 2 daughters.
void AddDecayToReconstructionList (int pdg)
const std::map< int, bool > GetReconstructionList () const
Returns list of decays to be reconstructed.
void SetReconstructionList (const std::map< int, bool > &decays)
Set enitre reconstruction list.
Static Public Member Functions
static int GetNSecondarySets ()
static int GetNPrimarySets ()
Private Member Functions
KFParticleFinder (const KFParticleFinder &)
Copying is disabled for this class.
KFParticleFinder & operator= (const KFParticleFinder &)
Copying is disabled for this class.
Private Attributes
short int fNPV
Number of primary vertex candidates in the event.
short int fNThreads
Number of threads to be run in parallel. Currently is not used.
float fDistanceCut
Cut on the distance between secondary tracks at the DCA point, is soft and used to speed up the algorithm only.
float fLCut
Cut on the distance to the primary vertex from the decay vertex. Is applied to , , , , hypernuclei and dibaryons.
float fCuts2D [3]
Cuts on 2-daughter decays: , , .
float fSecCuts [3]
Cuts to select secondary and primary particle candidates: , , .
float fCutsTrackV0 [3][3]
Cuts on the combination of track and short-lived particle candidate: , , . Three sets of cuts are defined: 1) for and , 2) for hypernuclei and open charm, 3) for resonances.
float fCutsPartPart [2][3]
Cuts on the combination of two short-lived particle candidates: , , . Two sets are defined: 1) for particles that fly away from the primary vertex and 2) for resonances.
float fCutCharmPt
Cut on transverse momentum of the track for open charm reconstruction.
float fCutCharmChiPrim
Cut on the deviation of the track from the primary vertex for open charm reconstruction.
float fCutsCharm [3]
Cuts on reconstructed 2-daughter charm candidates: , , .
float fCutLVMPt
Cut on transverse momentum of daughter tracks for low mass vector mesons.
float fCutLVMP
Cut on momentum of low mass vector mesons in dimuon channel.
float fCutJPsiPt
Cut on transverse momentum of daughter tracks for .
std::vector< KFParticle > fD0
Vector with temporary D0->K-pi+ candidates.
std::vector< KFParticle > fD0bar
Vector with temporary D0_bar->K+pi- candidates.
std::vector< KFParticle > fD04
Vector with temporary D0->K-pi+pi+pi- candidates.
std::vector< KFParticle > fD04bar
Vector with temporary D0_bar->K+pi+pi-pi- candidates.
std::vector< KFParticle > fD0KK
Vector with temporary D0->K+K- candidates.
std::vector< KFParticle > fD0pipi
Vector with temporary D0->pi+pi- candidates.
std::vector< KFParticle > fDPlus
Vector with temporary D+->K-pi+pi+ candidates.
std::vector< KFParticle > fDMinus
Vector with temporary D–>K+pi-pi- candidates.
std::vector< KFParticle > fDPlus3Pi
Vector with temporary D+->pi+pi+pi- candidates.
std::vector< KFParticle > fDMinus3Pi
Vector with temporary D–>pi+pi-pi- candidates.
std::vector< KFParticle > fDsPlusK2Pi
Vector with temporary Ds+->K+pi+pi- candidates.
std::vector< KFParticle > fDsMinusK2Pi
Vector with temporary Ds–>K-pi+pi- candidates.
std::vector< KFParticle > fLcPlusP2Pi
Vector with temporary Lambda_c->p pi+pi- candidates.
std::vector< KFParticle > fLcMinusP2Pi
Vector with temporary Lambda_c_bar->p-pi+pi- candidates.
std::vector< KFParticle > fLPi
Temporary Lambda pi+ combinations.
std::vector< int > fLPiPIndex
Index of the proton in Labmda for Lambda pi+ combinations.
std::vector< KFParticle > fHe3Pi
Temporary He3+ pi- combinations.
std::vector< KFParticle > fHe3PiBar
Temporary He3- pi+ combinations.
std::vector< KFParticle > fHe4Pi
Temporary He4+ pi- combinations.
std::vector< KFParticle > fHe4PiBar
Temporary He4- pi+ combinations.
std::vector< KFParticle > fHe4L
Vector with temporary He4_Lambda->He3 p pi- candidates.
std::vector< KFParticle > fHe5L
Vector with temporary He4_Lambda->He4 p pi- candidates.
std::vector< KFParticle > fLLn
Vector with temporary H3_Lambda pi- candidates.
std::vector< KFParticle > fH5LL
Vector with temporary H5_LL->He5_Lambda pi- candidates.
std::vector< KFParticle > fSecCandidates [fNSecCandidatesSets]
Array of vectors with secondary candidates: 0) , 1) , 2) , 3) , 4) .
std::vector< std::vector
< KFParticle > > fPrimCandidates [fNPrimCandidatesSets]
Array of vectors with primary candidates for each primary vertex: 0) , 1) , 2) , 3) , 4) , 5) , 6) , 7) , 8) , 9) , 10) .
std::vector< std::vector
< KFParticle > > fPrimCandidatesTopo [fNPrimCandidatesTopoSets]
Array of vectors with primary candidates for each primary vertex with a topological constraint set: 0) , 1) , 2) , 3) , 4) , 5) , 6) , 7) , 8) .
std::vector< std::vector
< KFParticle > > fPrimCandidatesTopoMass [fNPrimCandidatesTopoSets]
Array of vectors with primary candidates for each primary vertex with a topological and mass constraints set: 0) , 1) , 2) , 3) , 4) , 5) , 6) , 7) , 8) .
KFPEmcCluster * fEmcClusters
Pointer to the input gamma-clusters from the electromagnetic calorimeter.
bool fMixedEventAnalysis
Flag defines if the mixed event analysis is run. In mixed event mode limited number of decays is reconstructed.
std::map< int, bool > fDecayReconstructionList
Map defines if the reconstruction of the decay with a certain PDG hypothesis should be run. If the map is empty - all decays are reconstructed. If at least one decay is added - only those decays will be reconstructed which are specified in the list.
Static Private Attributes
static const int fNSecCandidatesSets = 5
Number of sets of secondary particle candidates.
static const int fNPrimCandidatesSets = 11
Number of sets of primary particle candidates.
static const int fNPrimCandidatesTopoSets = 9
Number of sets of primary particle candidates with topological constraint.
Detailed Description
Class for reconstruction short-lived particles.
Author
I.Kisel, M.Zyzak
Date
05.02.2019
Version
1.0
The class reconstructs short-lived particles by combining long-lived and already reconstructed short-lived particles. As an input it requires tracks and primary vertices. All short-lived particles are stored to one array. The default values of cuts are initialised in the constructor.
Definition at line 47 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 47 of file KFParticleFinder.h
Constructor & Destructor Documentation
KFParticleFinder::KFParticleFinder ()
The default constructor. Initialises all cuts to the default values.
Definition at line 30 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 30 of file KFParticleFinder.cxx
References fCutCharmChiPrim, fCuts2D, fCutsCharm, fCutsPartPart, fCutsTrackV0, and fSecCuts.
KFParticleFinder::~KFParticleFinder () inline
Definition at line 52 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 52 of file KFParticleFinder.h
KFParticleFinder::KFParticleFinder (const KFParticleFinder &) private
Copying is disabled for this class.
Member Function Documentation
void KFParticleFinder::AddCandidate (const KFParticle & candidate, int iPV = -1)
Adds an externally found particle to either set of secondary or primary candidates:
1) if iPV is negative the candidate is stored to KFParticleFinder::fSecCandidates;
2) if iPV is not negative and smaller then the set number of primary vertices and NDF=2 the candidate is stored to KFParticleFinder::fPrimCandidates;
3) if iPV is not negative and smaller then the set number of primary vertices and NDF=3 the candidate is stored to KFParticleFinder::fPrimCandidatesTopo;
4) if iPV is not negative and smaller then the set number of primary vertices and NDF=4 the candidate is stored to KFParticleFinder::fPrimCandidatesTopoMass.
Only those particles will be stored which have accepted PDG. Please check the documentation of the corresponding vectors for the list of particles.
Parameters
[in] candidate - candidate to be added
[in] iPV - index of the associated PV
Definition at line 3055 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 3055 of file KFParticleFinder.cxx
References fNPV, fPrimCandidates, fPrimCandidatesTopo, fPrimCandidatesTopoMass, fSecCandidates, KFParticleBase::GetPDG(), and KFParticle::NDF().
Referenced by KFParticleTopoReconstructor::AddCandidate().
void KFParticleFinder::AddDecayToReconstructionList (int pdg) inline
Add decay to the reconstruction list. If at least one is added - only those channels are considered which are in the list. Otherwise all decays are reconstructed.
Parameters
[in] pdg - PDG code of the decay which should be reconstructed
Definition at line 378 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 378 of file KFParticleFinder.h
References fDecayReconstructionList.
void KFParticleFinder::CombinePartPart (std::vector< KFParticle > & particles1, std::vector< KFParticle > & particles2, std::vector< KFParticle > & Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > & PrimVtx, const float * cuts, int iPV, const int MotherPDG, bool isSameInputPart = 0, bool saveOnlyPrimary = 1, std::vector< std::vector< KFParticle > > * vMotherPrim = 0, std::vector< KFParticle > * vMotherSec = 0, float massMotherPDG = 0.f, float massMotherPDGSigma = 0.f)
Combines two already constructed candidates into a new particle.
Parameters
[in] particles1 - vector with the first set of particles.
[in] particles2 - vector with the second set of particles.
[out] Particles - output vector with particles.
[in] PrimVtx - vector with primary vertices.
[in] cuts - set of cuts: , , .
[in] iPV - index of the primary vertex for reconstruction of resonances. Tracks should come from the same vertex.
[in] MotherPDG - PDG hypothesis of the constructed mother particles.
[in] isSameInputPart - shows if vectors of input particles are the same to avoid double reconstruction of the same candidate.
[in] saveOnlyPrimary - defines if only primary particles should be searched and should be applied.
[out] vMotherPrim - array with output primary candidates if any. If pointer is set to NULL - not filled.
[out] vMotherSec - array with output secondary candidates if any. If pointer is set to NULL - not filled.
[in] massMotherPDG - PDG table mass for the mother particle, is used for selection of primary and secondary candidates.
[in] massMotherPDGSigma - sigma of the peak width, is used for selection of primary and secondary candidates.
Definition at line 2526 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 2526 of file KFParticleFinder.cxx
References KFParticleBase::AddDaughterId(), KFParticleSIMD::Chi2(), KFParticleBase::CleanDaughtersId(), KFParticleSIMD::Construct(), KFParticleBase::DaughterIds(), KFParticleBaseSIMD::DaughterIds(), DaughterIds(), fDecayReconstructionList, fLCut, float_vLen, fNPV, KFParticleSIMD::GetChi2(), KFParticleBaseSIMD::GetDistanceToVertexLine(), KFParticleSIMD::GetKFParticle(), KFParticle::GetMass(), KFParticleSIMD::GetNDF(), Id(), KFParticleBase::NDaughters(), KFParticleSIMD::NDF(), KFParticleBaseSIMD::PDG(), KFParticleBase::SetId(), KFParticleBase::SetNonlinearMassConstraint(), KFParticleBaseSIMD::SetPDG(), and KFParticleBaseSIMD::SetProductionVertex().
Referenced by FindParticles().
void KFParticleFinder::ConstructPrimaryBG (KFPTrackVector * vTracks, std::vector< KFParticle > & Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > & PrimVtx, const float * cuts, const float * secCuts, std::vector< std::vector< KFParticle > > * vMotherPrim, std::vector< KFParticle > * vMotherSec)
Constructs same-sign background candidates for 2-daughter resonances.
Parameters
[in] vRTracks - pointer to the array with vectors of tracks:
0) secondary positive at the first hit position;
1) secondary negative at the first hit position;
2) primary positive at the first hit position;
3) primary negative at the first hit position;
4) secondary positive at the last hit position;
5) secondary negative at the last hit position;
6) primary positive at the last hit position;
7) primary negative at the last hit position.
[out] Particles - the output array with the reconstructed particle-candidates.
[in] PrimVtx - vector with primary vertices.
[in] cuts - set of cuts: , , .
[in] secCuts - cuts to select primary and secondary candidates from the reconstructed set: , , .
[out] vMotherPrim - array with output primary candidates. Is provided for consistency with KFParticleFinder::ConstructV0().
[out] vMotherSec - array with output secondary candidates. Is provided for consistency with KFParticleFinder::ConstructV0().
Definition at line 1422 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 1422 of file KFParticleFinder.cxx
References ConstructV0(), fDecayReconstructionList, KFPTrackVector::FirstPion(), float_vLen, fNPV, KFParticleDatabase::GetMotherMass(), KFParticleDatabase::Instance(), KFPTrackVector::LastProton(), KFPTrackVector::PDG(), KFPTrackVector::PVIndex(), SaveV0PrimSecCand(), KFParticleBaseSIMD::SetPDG(), and KFPTrackVector::Size().
Referenced by FindParticles().
void KFParticleFinder::ConstructTrackV0Cand (KFPTrackVector & vTracks, uint_v & idTracks, int_v & trackPDG, KFParticle * vV0[], KFParticleSIMD & mother, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > & motherTopo, KFParticle & mother_temp, const unsigned short nElements, kfvector_floatv & l, kfvector_floatv & dl, std::vector< KFParticle > & Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > & PrimVtx, const float_v * cuts, const int_v & pvIndex, const float_v & massMotherPDG, const float_v & massMotherPDGSigma, std::vector< std::vector< KFParticle > > * vMotherPrim, std::vector< KFParticle > * vMotherSec)
Constructs a candidate from a track and already reconstructed particle candidate.
Parameters
[in] vTracks - vector with tracks.
[in] idTracks - indices of particles from the vector of tracks.
[in] trackPDG - PDG hypothesis of the SIMD vector of tracks.
[in] vV0 - array with already reconstructed particle candidate with the size of SIMD vector.
[out] mother - constructed 2-daughter SIMD-candidate.
[in] motherTopo - preallocated SIMD vector for topological constraint for better performance.
[in] mother_temp - temporary object to extract KFParticle from constructed KFParticleSIMD mother. Preallocated for better performance.
[in] nElements - number of elements in each SIMD vector.
[in] l - SIMD-vector with extracted distance to the primary vertex. Is preallocated for better performance.
[in] dl - SIMD-vector with extracted error of distance to the primary vertex. Is preallocated for better performance.
[out] Particles - the output array with the reconstructed particle-candidates.
[in] PrimVtx - array with primary vertices.
[in] cuts - set of cuts: , , .
[in] pvIndex - index of the primary vertex for reconstruction of resonances. Tracks should come from the same vertex. in case of other particles the value should be "-1".
[in] massMotherPDG - PDG table mass for the mother particle, is used for selection of primary and secondary candidates.
[in] massMotherPDGSigma - sigma of the peak width, is used for selection of primary and secondary candidates.
[out] vMotherPrim - array with output primary candidates if any. If pointer is set to NULL - not filled.
[out] vMotherSec - array with output secondary candidates if any. If pointer is set to NULL - not filled.
Definition at line 1594 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 1594 of file KFParticleFinder.cxx
References KFParticleBase::AddDaughterId(), KFParticleSIMD::Chi2(), KFParticleBase::CleanDaughtersId(), KFParticleSIMD::Construct(), KFParticleBase::DaughterIds(), KFParticleBaseSIMD::DaughterIds(), fD04, fD04bar, fDMinus, fDMinus3Pi, fDPlus, fDPlus3Pi, fDsMinusK2Pi, fDsPlusK2Pi, fH5LL, fLcMinusP2Pi, fLcPlusP2Pi, fLCut, fLLn, float_vLen, fLPi, fLPiPIndex, fNPV, fPrimCandidates, KFParticleSIMD::GetChi2(), KFParticleDatabase::GetD0Mass(), KFParticleDatabase::GetD0MassSigma(), KFParticleBaseSIMD::GetDistanceToVertexLine(), KFParticleDatabase::GetDPlusMass(), KFParticleDatabase::GetDPlusMassSigma(), KFParticleSIMD::GetDStoParticle(), KFParticleSIMD::GetKFParticle(), KFParticle::GetMass(), KFParticleBaseSIMD::GetPDG(), KFPTrackVector::Id(), KFParticleDatabase::Instance(), KFParticleBase::NDaughters(), KFParticleSIMD::NDF(), KFParticleSIMD::Parameters(), KFParticleBaseSIMD::PDG(), KFParticleBase::SetId(), KFParticleBaseSIMD::SetId(), KFParticleBase::SetNonlinearMassConstraint(), KFParticleBase::SetPDG(), KFParticleBaseSIMD::SetPDG(), KFParticleBaseSIMD::SetProductionVertex(), KFParticleBaseSIMD::TransportToDS(), and KFParticleSIMD::TransportToPoint().
Referenced by FindTrackV0Decay().
void KFParticleFinder::ConstructV0 (KFPTrackVector * vTracks, int iTrTypePos, int iTrTypeNeg, uint_v & idPosDaughters, uint_v & idNegDaughters, int_v & daughterPosPDG, int_v & daughterNegPDG, KFParticleSIMD & mother, KFParticle & mother_temp, const unsigned short NTracks, kfvector_floatv & l, kfvector_floatv & dl, std::vector< KFParticle > & Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > & PrimVtx, const float * cuts, const int_v & pvIndex, const float * secCuts, const float_v & massMotherPDG, const float_v & massMotherPDGSigma, KFParticleSIMD & motherPrimSecCand, int & nPrimSecCand, std::vector< std::vector< KFParticle > > * vMotherPrim = 0, std::vector< KFParticle > * vMotherSec = 0) inline
Combines two SIMD vectors of particles into 2-daughter candidate.
Parameters
[in] vRTracks - pointer to the array with vectors of tracks:
0) secondary positive at the first hit position;
1) secondary negative at the first hit position;
2) primary positive at the first hit position;
3) primary negative at the first hit position;
4) secondary positive at the last hit position;
5) secondary negative at the last hit position;
6) primary positive at the last hit position;
7) primary negative at the last hit position.
[in] iTrTypePos - index of the first vector with tracks in the vTracks array.
[in] iTrTypeNeg - index of the second vector with tracks in the vTracks array.
[in] idPosDaughters - indices of particles from the first vector of tracks.
[in] idNegDaughters - indices of particles from the second vector of tracks.
[in] daughterPosPDG - PDG hypothesis of the first SIMD vector of tracks.
[in] daughterNegPDG - PDG hypothesis of the second SIMD vector of tracks.
[out] mother - constructed 2-daughter SIMD-candidate.
[in] mother_temp - temporary object to extract KFParticle from constructed KFParticleSIMD mother. Preallocated for better performance.
[in] NTracks - number of tracks in each SIMD vector.
[in] l - SIMD-vector with extracted distance to the primary vertex. Is preallocated for better performance.
[in] dl - SIMD-vector with extracted error of distance to the primary vertex. Is preallocated for better performance.
[out] Particles - the output array with the reconstructed particle-candidates.
[in] PrimVtx - array with primary vertices.
[in] cuts - set of cuts: , , .
[in] pvIndex - index of the primary vertex for reconstruction of resonances. Tracks should come from the same vertex. in case of other particles the value should be "-1".
[in] secCuts - cuts to select primary and secondary candidates from the reconstructed set: , , .
[in] massMotherPDG - PDG table mass for the mother particle, is used for selection of primary and secondary candidates.
[in] massMotherPDGSigma - sigma of the peak width, is used for selection of primary and secondary candidates.
[out] motherPrimSecCand - a SIMD-particle with possible primary and secondary candidates.
[out] nPrimSecCand - number of possible primary and secondary candidates. Can be "0" if no of them are found.
[out] vMotherPrim - array with output primary candidates if any.
[out] vMotherSec - array with output secondary candidates if any.
Definition at line 639 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 639 of file KFParticleFinder.cxx
References KFParticleSIMD::Chi2(), KFParticleSIMD::Construct(), fCutJPsiPt, fCutLVMPt, fCutsCharm, fD0, fD0bar, fD0KK, fD0pipi, fHe3Pi, fHe3PiBar, fHe4Pi, fHe4PiBar, fLCut, float_vLen, fNPV, KFParticleSIMD::GetChi2(), KFParticleSIMD::GetDecayLength(), KFParticleBaseSIMD::GetDistanceToVertexLine(), KFParticleSIMD::GetDStoParticle(), KFParticleSIMD::GetKFParticle(), KFParticleSIMD::GetMass(), Id(), KFParticleSIMD::NDF(), KFParticleBaseSIMD::PDG(), KFParticleSIMD::Px(), KFParticleSIMD::Py(), SaveV0PrimSecCand(), KFParticleBase::SetId(), KFParticleBaseSIMD::SetId(), KFParticleSIMD::SetOneEntry(), KFParticleBase::SetPDG(), KFParticleBaseSIMD::SetProductionVertex(), and KFParticleBaseSIMD::TransportToDS().
Referenced by ConstructPrimaryBG(), and Find2DaughterDecay().
void KFParticleFinder::CopyCuts (const KFParticleFinder * finder) inline
Copies all cuts from the external KFParticleFinder "finder" to the current object.
Parameters
[in] finder - constant pointer to the external KFParticleFinder object
Definition at line 315 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 315 of file KFParticleFinder.h
References fCutCharmChiPrim, fCutCharmPt, fCutJPsiPt, fCutLVMP, fCutLVMPt, fCuts2D, fCutsCharm, fCutsPartPart, fCutsTrackV0, fDistanceCut, fLCut, and fSecCuts.
Referenced by KFParticleTopoReconstructor::CopyCuts().
void KFParticleFinder::ExtrapolateToPV (std::vector< KFParticle > & vParticles, KFParticleSIMD & PrimVtx)
Extrapolates all particles from the input vector to the DCA point with the primary vertex.
Parameters
[in,out] vParticles - array of particles to be transported.
[in] PrimVtx - the primary vertex, where particles should be transported.
Definition at line 606 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 606 of file KFParticleFinder.cxx
References float_vLen, KFParticleSIMD::GetKFParticle(), KFParticleSIMD::Parameters(), and KFParticleSIMD::TransportToPoint().
Referenced by FindParticles().
void KFParticleFinder::Find2DaughterDecay (KFPTrackVector * vTracks, kfvector_float * ChiToPrimVtx, std::vector< KFParticle > & Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > & PrimVtx, const float * cuts, const float * secCuts, std::vector< std::vector< KFParticle > > * vMotherPrim, std::vector< KFParticle > * vMotherSec)
Reconstructs all 2-daughter decays.
Parameters
[in] vRTracks - pointer to the array with vectors of tracks:
0) secondary positive at the first hit position;
1) secondary negative at the first hit position;
2) primary positive at the first hit position;
3) primary negative at the first hit position;
4) secondary positive at the last hit position;
5) secondary negative at the last hit position;
6) primary positive at the last hit position;
7) primary negative at the last hit position.
[in] ChiToPrimVtx - arrays with vectors of the deviations for track vectors 1) and 2).
[out] Particles - output vector with particles.
[in] PrimVtx - vector with primary vertices.
[in] cuts - set of cuts: , , .
[in] secCuts - cuts to select primary and secondary candidates from the reconstructed set: , , .
[out] vMotherPrim - array with output primary candidates.
[out] vMotherSec - array with output secondary candidates.
Definition at line 972 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 972 of file KFParticleFinder.cxx
References ConstructV0(), dx, dy, fCutCharmChiPrim, fCutCharmPt, fCuts2D, fDecayReconstructionList, fDistanceCut, KFPTrackVector::FirstKaon(), KFPTrackVector::FirstMuon(), KFPTrackVector::FirstPion(), KFPTrackVector::FirstProton(), float_vLen, fMixedEventAnalysis, fNPV, KFParticleSIMD::GetDStoParticleFast(), KFParticleDatabase::GetMotherMass(), KFParticleDatabase::Instance(), KFPTrackVector::LastKaon(), KFPTrackVector::LastMuon(), KFPTrackVector::LastPion(), KFPTrackVector::LastProton(), KFParticleSIMD::Load(), KFPTrackVector::NPixelHits(), KFPTrackVector::PDG(), KFPTrackVector::PVIndex(), KFParticleSIMD::Px(), KFParticleSIMD::Py(), KFParticleSIMD::Rotate(), SaveV0PrimSecCand(), KFParticleBaseSIMD::SetPDG(), KFPTrackVector::Size(), and KFParticleSIMD::TransportFast().
Referenced by FindParticles().
void KFParticleFinder::FindParticles (KFPTrackVector * vRTracks, kfvector_float * ChiToPrimVtx, std::vector< KFParticle > & Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > & PrimVtx, int nPV)
The main interface which runs reconstruction of short-lived particles:
1) a new event is initialised;
2) long-lived particles formed from tracks are stored to the output array "Particles";
3) 2-daughter channels are reconstructed (KFParticleFinder::Find2DaughterDecay());
4) the 2-daughter same-signed background is collected for resonances (KFParticleFinder::ConstructPrimaryBG());
5) found primary candidates of , , and are transported to the point of the closest approach with the corresponding primary vertex (KFParticleFinder::ExtrapolateToPV());
6) reconstruction with the missing mass method (KFParticleFinder::NeutralDaughterDecay());
7) all other decays are reconstructed one after another.
If analysis is run in the mixed event mode only steps 1) and 2) are performed.
Parameters
[in] vRTracks - pointer to the array with vectors of tracks:
0) secondary positive at the first hit position;
1) secondary negative at the first hit position;
2) primary positive at the first hit position;
3) primary negative at the first hit position;
4) secondary positive at the last hit position;
5) secondary negative at the last hit position;
6) primary positive at the last hit position;
7) primary negative at the last hit position.
[in] ChiToPrimVtx - arrays with vectors of the deviations for track vectors 1) and 2).
[out] Particles - output vector with particles.
[in] PrimVtx - vector with primary vertices.
[in] nPV - number of the input primary vertices.
Definition at line 131 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 131 of file KFParticleFinder.cxx
References KFParticleBase::AddDaughterId(), KFParticleBase::CleanDaughtersId(), CombinePartPart(), ConstructPrimaryBG(), ExtrapolateToPV(), fCuts2D, fCutsCharm, fCutsPartPart, fD0, fD04, fD04bar, fD0bar, fD0KK, fD0pipi, fDMinus, fDMinus3Pi, fDPlus, fDPlus3Pi, fDsMinusK2Pi, fDsPlusK2Pi, fEmcClusters, fH5LL, fHe3Pi, fHe3PiBar, fHe4L, fHe4Pi, fHe4PiBar, fHe5L, Find2DaughterDecay(), FindTrackV0Decay(), FirstKaon(), FirstPion(), FirstProton(), fLcMinusP2Pi, fLcPlusP2Pi, fLLn, float_vLen, fLPi, fMixedEventAnalysis, fNPV, fPrimCandidates, fSecCandidates, fSecCuts, KFParticleSIMD::GetKFParticle(), KFParticleDatabase::GetPi0Mass(), KFParticleDatabase::GetPi0MassSigma(), KFPTrackVector::GetTrack(), KFPEmcCluster::Id(), KFPTrack::Id(), Init(), KFParticleDatabase::Instance(), LastKaon(), LastPion(), LastProton(), KFParticleSIMD::Load(), KFPTrackVector::NElectrons(), NeutralDaughterDecay(), KFPTrackVector::NKaons(), KFPTrackVector::NMuons(), KFPTrackVector::NPions(), KFPTrackVector::NProtons(), KFPTrackVector::PDG(), SelectParticles(), KFPTrackVector::SetId(), KFParticleBase::SetId(), SetId(), KFParticleBase::SetPDG(), KFPEmcCluster::Size(), KFPTrackVector::Size(), and Size().
Referenced by KFParticleTopoReconstructor::ReconstructParticles().
void KFParticleFinder::FindTrackV0Decay (std::vector< KFParticle > & vV0, const int V0PDG, KFPTrackVector & vTracks, const int q, const int firstTrack, const int lastTrack, std::vector< KFParticle > & Particles, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > & PrimVtx, int v0PVIndex = -1, kfvector_float * ChiToPrimVtx = 0, std::vector< std::vector< KFParticle > > * vMotherPrim = 0, std::vector< KFParticle > * vMotherSec = 0)
Combines tracks and already reconstructed particle candidate of certain type in the next candidate.
Parameters
[in] vV0 - the input vector with already reconstructed particle candidate.
[in] V0PDG - PDG code of the provided particle candidates.
[in] vTracks - vector with input tracks.
[in] q - charge of the provided tracks.
[in] firstTrack - index of the first track to be used.
[in] lastTrack - index of the last track to be used.
[out] Particles - the output array with the reconstructed particle-candidates.
[in] PrimVtx - array with primary vertices.
[in] v0PVIndex - index of the corresponding primary vertex if the tracks are primary. If not "-1" should be set.
[in] ChiToPrimVtx - vector with the deviations for provided tracks. If tracks are primary NULL pointer is provided.
[out] vMotherPrim - array with output primary candidates.
[out] vMotherSec - array with output secondary candidates.
Definition at line 1971 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 1971 of file KFParticleFinder.cxx
References ConstructTrackV0Cand(), cuts, fCutCharmChiPrim, fCutCharmPt, fCuts2D, fCutsTrackV0, fDecayReconstructionList, fDistanceCut, float_vLen, fLPiPIndex, fNPV, KFParticleBaseSIMD::GetDistanceFromParticle(), KFParticleDatabase::GetMotherMass(), KFPTrackVector::Id(), KFParticleDatabase::Instance(), KFParticleSIMD::Load(), KFPTrackVector::NPixelHits(), KFPTrackVector::PDG(), KFPTrackVector::PVIndex(), KFParticleSIMD::Px(), KFParticleSIMD::Py(), KFParticleBaseSIMD::SetPDG(), and Size().
Referenced by FindParticles().
const float KFParticleFinder::GetChi2Cut2D () const inline
Returns cut on for 2-daughter decays.
Definition at line 346 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 346 of file KFParticleFinder.h
References fCuts2D.
const float KFParticleFinder::GetChi2CutCharm2D () const inline
Returns cut for open charm with 2 daughters.
Definition at line 372 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 372 of file KFParticleFinder.h
References fCutsCharm.
const float KFParticleFinder::GetChi2CutCharmManybodyDecays () const inline
Returns cut for open charm with >=3 daughters.
Definition at line 368 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 368 of file KFParticleFinder.h
References fCutsTrackV0.
const float KFParticleFinder::GetChi2CutResonances () const inline
Returns cut for resonances.
Definition at line 358 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 358 of file KFParticleFinder.h
References fCutsTrackV0.
const float KFParticleFinder::GetChi2CutXiOmega () const inline
Returns cut for and .
Definition at line 355 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 355 of file KFParticleFinder.h
References fCutsTrackV0.
const float KFParticleFinder::GetChi2TopoCutCharm2D () const inline
Returns cut for open charm with 2 daughters.
Definition at line 371 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 371 of file KFParticleFinder.h
References fCutsCharm.
const float KFParticleFinder::GetChi2TopoCutCharmManybodyDecays () const inline
Returns cut for open charm with >=3 daughters.
Definition at line 367 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 367 of file KFParticleFinder.h
References fCutsTrackV0.
const float KFParticleFinder::GetChi2TopoCutResonances () const inline
Returns cut for resonances.
Definition at line 357 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 357 of file KFParticleFinder.h
References fCutsTrackV0.
const float KFParticleFinder::GetChi2TopoCutXiOmega () const inline
Returns cut for and .
Definition at line 354 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 354 of file KFParticleFinder.h
References fCutsTrackV0.
const float KFParticleFinder::GetChiPrimaryCut2D () const inline
Returns cut on of each track for 2-daughter decays.
Definition at line 345 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 345 of file KFParticleFinder.h
References fCuts2D.
const float KFParticleFinder::GetChiPrimaryCutCharm () const inline
Returns cut on of each track for open charm particles.
Definition at line 365 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 365 of file KFParticleFinder.h
References fCutCharmChiPrim.
const float KFParticleFinder::GetLCut () const inline
Returns cut on the distance to the primary vertex from the decay vertex.
Definition at line 343 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 343 of file KFParticleFinder.h
References fLCut.
const float KFParticleFinder::GetLdLCut2D () const inline
Returns cut on for 2-daughter decays.
Definition at line 347 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 347 of file KFParticleFinder.h
References fCuts2D.
const float KFParticleFinder::GetLdLCutCharm2D () const inline
Returns cut for open charm with 2 daughters.
Definition at line 370 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 370 of file KFParticleFinder.h
References fCutsCharm.
const float KFParticleFinder::GetLdLCutCharmManybodyDecays () const inline
Returns cut for open charm with >=3 daughters.
Definition at line 366 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 366 of file KFParticleFinder.h
References fCutsTrackV0.
const float KFParticleFinder::GetLdLCutXiOmega () const inline
Returns cut for and .
Definition at line 353 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 353 of file KFParticleFinder.h
References fCutsTrackV0.
const float KFParticleFinder::GetMaxDistanceBetweenParticlesCut () const inline
Returns cut on the distance between secondary tracks at the DCA point.
Definition at line 342 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 342 of file KFParticleFinder.h
References fDistanceCut.
static int KFParticleFinder::GetNPrimarySets () inline static
Returns number of sets of vectors with primary candidates for different decays.
Definition at line 192 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 192 of file KFParticleFinder.h
References fNPrimCandidatesTopoSets.
static int KFParticleFinder::GetNSecondarySets () inline static
Returns number of sets of vectors with secondary candidates for different decays.
Definition at line 176 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 176 of file KFParticleFinder.h
References fNSecCandidatesSets.
const float KFParticleFinder::GetPCutLMVM () const inline
Returns cut on momentum of each daughter track of low mass vector mesons in dimuon channel.
Definition at line 361 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 361 of file KFParticleFinder.h
References fCutLVMP.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryAntiLambda () const inline
Returns a constant reference to the vector with primary candidates for .
Definition at line 200 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 200 of file KFParticleFinder.h
References fPrimCandidates.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryAntiOmega () const inline
Returns a constant reference to the vector with secondary candidates for .
Definition at line 212 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 212 of file KFParticleFinder.h
References fPrimCandidates.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryAntiXi () const inline
Returns a constant reference to the vector with secondary candidates for .
Definition at line 208 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 208 of file KFParticleFinder.h
References fPrimCandidates.
const std::vector< std::vector<KFParticle> >* KFParticleFinder::GetPrimaryCandidates () const inline
Returns a pointer to array with sets of vectors with primary candidates for different decays.
Definition at line 194 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 194 of file KFParticleFinder.h
References fPrimCandidates.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryGamma () const inline
Returns a constant reference to the vector with primary candidates for conversion.
Definition at line 202 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 202 of file KFParticleFinder.h
References fPrimCandidates.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryK0 () const inline
Returns a constant reference to the vector with primary candidates for .
Definition at line 196 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 196 of file KFParticleFinder.h
References fPrimCandidates.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryLambda () const inline
Returns a constant reference to the vector with primary candidates for .
Definition at line 198 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 198 of file KFParticleFinder.h
References fPrimCandidates.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryOmega () const inline
Returns a constant reference to the vector with secondary candidates for .
Definition at line 210 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 210 of file KFParticleFinder.h
References fPrimCandidates.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryPi0 () const inline
Returns a constant reference to the vector with primary candidates for .
Definition at line 204 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 204 of file KFParticleFinder.h
References fPrimCandidates.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoAntiLambda () const inline
Returns a constant reference to the vector with primary candidates for with topological constraint set on.
Definition at line 225 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 225 of file KFParticleFinder.h
References fPrimCandidatesTopo.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoAntiOmega () const inline
Returns a constant reference to the vector with secondary candidates for with topological constraint set on.
Definition at line 243 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 243 of file KFParticleFinder.h
References fPrimCandidatesTopo.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoAntiXi () const inline
Returns a constant reference to the vector with secondary candidates for with topological constraint set on.
Definition at line 237 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 237 of file KFParticleFinder.h
References fPrimCandidatesTopo.
const std::vector< std::vector<KFParticle> >* KFParticleFinder::GetPrimaryTopoCandidates () const inline
Returns a pointer to array with sets of vectors with primary candidates for different decays with topological constraint set on.
Definition at line 216 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 216 of file KFParticleFinder.h
References fPrimCandidatesTopo.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoGamma () const inline
Returns a constant reference to the vector with primary candidates for conversion with topological constraint set on.
Definition at line 228 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 228 of file KFParticleFinder.h
References fPrimCandidatesTopo.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoK0 () const inline
Returns a constant reference to the vector with primary candidates for with topological constraint set on.
Definition at line 219 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 219 of file KFParticleFinder.h
References fPrimCandidatesTopo.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoLambda () const inline
Returns a constant reference to the vector with primary candidates for with topological constraint set on.
Definition at line 222 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 222 of file KFParticleFinder.h
References fPrimCandidatesTopo.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoMassAntiLambda () const inline
Returns a constant reference to the vector with primary candidates for with topological and mass constraints set on.
Definition at line 256 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 256 of file KFParticleFinder.h
References fPrimCandidatesTopoMass.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoMassAntiOmega () const inline
Returns a constant reference to the vector with secondary candidates for with topological and mass constraints set on.
Definition at line 274 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 274 of file KFParticleFinder.h
References fPrimCandidatesTopoMass.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoMassAntiXi () const inline
Returns a constant reference to the vector with secondary candidates for with topological and mass constraints set on.
Definition at line 268 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 268 of file KFParticleFinder.h
References fPrimCandidatesTopoMass.
const std::vector< std::vector<KFParticle> >* KFParticleFinder::GetPrimaryTopoMassCandidates () const inline
Returns a pointer to array with sets of vectors with primary candidates for different decays with topological and mass constraints set on.
Definition at line 247 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 247 of file KFParticleFinder.h
References fPrimCandidatesTopoMass.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoMassGamma () const inline
Returns a constant reference to the vector with primary candidates for conversion with topological and mass constraints set on.
Definition at line 259 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 259 of file KFParticleFinder.h
References fPrimCandidatesTopoMass.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoMassK0 () const inline
Returns a constant reference to the vector with primary candidates for with topological and mass constraints set on.
Definition at line 250 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 250 of file KFParticleFinder.h
References fPrimCandidatesTopoMass.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoMassLambda () const inline
Returns a constant reference to the vector with primary candidates for with topological and mass constraints set on.
Definition at line 253 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 253 of file KFParticleFinder.h
References fPrimCandidatesTopoMass.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoMassOmega () const inline
Returns a constant reference to the vector with secondary candidates for with topological and mass constraints set on.
Definition at line 271 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 271 of file KFParticleFinder.h
References fPrimCandidatesTopoMass.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoMassPi0 () const inline
Returns a constant reference to the vector with primary candidates for with topological and mass constraints set on.
Definition at line 262 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 262 of file KFParticleFinder.h
References fPrimCandidatesTopoMass.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoMassXi () const inline
Returns a constant reference to the vector with secondary candidates for with topological and mass constraints set on.
Definition at line 265 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 265 of file KFParticleFinder.h
References fPrimCandidatesTopoMass.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoOmega () const inline
Returns a constant reference to the vector with secondary candidates for with topological constraint set on.
Definition at line 240 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 240 of file KFParticleFinder.h
References fPrimCandidatesTopo.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoPi0 () const inline
Returns a constant reference to the vector with primary candidates for with topological constraint set on.
Definition at line 231 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 231 of file KFParticleFinder.h
References fPrimCandidatesTopo.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryTopoXi () const inline
Returns a constant reference to the vector with secondary candidates for with topological constraint set on.
Definition at line 234 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 234 of file KFParticleFinder.h
References fPrimCandidatesTopo.
const std::vector< std::vector<KFParticle> >& KFParticleFinder::GetPrimaryXi () const inline
Returns a constant reference to the vector with secondary candidates for .
Definition at line 206 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 206 of file KFParticleFinder.h
References fPrimCandidates.
const float KFParticleFinder::GetPtCutCharm () const inline
Returns the cut on transverse momentum of each daughter track of open charm particles.
Definition at line 364 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 364 of file KFParticleFinder.h
References fCutCharmPt.
const float KFParticleFinder::GetPtCutJPsi () const inline
Returns cut on transverse momentum of each daughter track of .
Definition at line 362 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 362 of file KFParticleFinder.h
References fCutJPsiPt.
const float KFParticleFinder::GetPtCutLMVM () const inline
Returns cut on transverse momentum of each daughter track of low mass vector mesons.
Definition at line 360 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 360 of file KFParticleFinder.h
References fCutLVMPt.
const std::map<int,bool> KFParticleFinder::GetReconstructionList () const inline
Returns list of decays to be reconstructed.
Definition at line 379 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 379 of file KFParticleFinder.h
References fDecayReconstructionList.
const std::vector<KFParticle>& KFParticleFinder::GetSecondaryAntiLambda () const inline
Returns a constant reference to the vector with secondary candidates for .
Definition at line 184 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 184 of file KFParticleFinder.h
References fSecCandidates.
const std::vector<KFParticle>* KFParticleFinder::GetSecondaryCandidates () const inline
Returns a pointer to array with sets of vectors with secondary candidates for different decays.
Definition at line 178 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 178 of file KFParticleFinder.h
References fSecCandidates.
const float KFParticleFinder::GetSecondaryChi2TopoCut () const inline
Returns cut for selection of primary and secondary candidates.
Definition at line 350 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 350 of file KFParticleFinder.h
References fSecCuts.
const std::vector<KFParticle>& KFParticleFinder::GetSecondaryGamma () const inline
Returns a constant reference to the vector with secondary candidates for conversion.
Definition at line 186 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 186 of file KFParticleFinder.h
References fSecCandidates.
const std::vector<KFParticle>& KFParticleFinder::GetSecondaryK0 () const inline
Returns a constant reference to the vector with secondary candidates for .
Definition at line 180 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 180 of file KFParticleFinder.h
References fSecCandidates.
const std::vector<KFParticle>& KFParticleFinder::GetSecondaryLambda () const inline
Returns a constant reference to the vector with secondary candidates for .
Definition at line 182 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 182 of file KFParticleFinder.h
References fSecCandidates.
const float KFParticleFinder::GetSecondaryLdLCut () const inline
Returns cut for selection of primary and secondary candidates.
Definition at line 351 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 351 of file KFParticleFinder.h
References fSecCuts.
const std::vector<KFParticle>& KFParticleFinder::GetSecondaryPi0 () const inline
Returns a constant reference to the vector with secondary candidates for .
Definition at line 188 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 188 of file KFParticleFinder.h
References fSecCandidates.
const float KFParticleFinder::GetSecondarySigmaMassCut () const inline
Returns cut for selection of primary and secondary candidates.
Definition at line 349 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 349 of file KFParticleFinder.h
References fSecCuts.
void KFParticleFinder::Init (int nPV)
Initialises the new event: all vectors with temporary candidates are cleaned, the number of primary vertices is set to "nPV", vectors with primary candidates are resized correspondingly.
Parameters
[in] nPV - number of primary vertices in the event which will be processed
Definition at line 75 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 75 of file KFParticleFinder.cxx
References fD0, fD04, fD04bar, fD0bar, fD0KK, fD0pipi, fDMinus, fDMinus3Pi, fDPlus, fDPlus3Pi, fDsMinusK2Pi, fDsPlusK2Pi, fH5LL, fHe3Pi, fHe3PiBar, fHe4L, fHe4Pi, fHe4PiBar, fHe5L, fLcMinusP2Pi, fLcPlusP2Pi, fLLn, fLPi, fLPiPIndex, fNPrimCandidatesSets, fNPrimCandidatesTopoSets, fNPV, fNSecCandidatesSets, fPrimCandidates, fPrimCandidatesTopo, fPrimCandidatesTopoMass, and fSecCandidates.
Referenced by FindParticles().
void KFParticleFinder::NeutralDaughterDecay (KFPTrackVector * vTracks, std::vector< KFParticle > & Particles)
Reconstructs particles by the missing mass method.
Parameters
[in] vRTracks - pointer to the array with vectors of tracks:
0) secondary positive at the first hit position;
1) secondary negative at the first hit position;
2) primary positive at the first hit position;
3) primary negative at the first hit position;
4) secondary positive at the last hit position;
5) secondary negative at the last hit position;
6) primary positive at the last hit position;
7) primary negative at the last hit position.
[out] Particles - the output array with the reconstructed particle-candidates.
Definition at line 2766 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 2766 of file KFParticleFinder.cxx
References KFParticleBase::AddDaughterId(), KFParticleBaseSIMD::AddDaughterId(), KFParticleSIMD::Chi2(), KFParticleBase::CleanDaughtersId(), KFParticleSIMD::Construct(), KFParticleSIMD::E(), fCuts2D, fDecayReconstructionList, KFPTrackVector::FirstKaon(), KFPTrackVector::FirstMuon(), KFPTrackVector::FirstPion(), KFPTrackVector::FirstProton(), float_vLen, KFParticleSIMD::GetKFParticle(), KFParticleSIMD::GetPt(), KFParticleSIMD::GetRapidity(), KFPTrackVector::Id(), KFParticleBaseSIMD::Id(), KFPTrackVector::LastKaon(), KFPTrackVector::LastMuon(), KFPTrackVector::LastPion(), KFPTrackVector::LastProton(), KFParticleSIMD::Load(), KFParticleSIMD::NDF(), KFPTrackVector::PDG(), KFPTrackVector::PVIndex(), KFParticleSIMD::Rotate(), KFParticleBase::SetId(), KFParticleBaseSIMD::SetId(), KFParticleBaseSIMD::SetNonlinearMassConstraint(), KFParticleBase::SetPDG(), KFPTrackVector::Size(), KFParticleBaseSIMD::SubtractDaughter(), and KFParticleSIMD::Z().
Referenced by FindParticles().
KFParticleFinder& KFParticleFinder::operator= (const KFParticleFinder &) private
Copying is disabled for this class.
void KFParticleFinder::SaveV0PrimSecCand (KFParticleSIMD & mother, int & NParticles, KFParticle & mother_temp, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > & PrimVtx, const float * secCuts, std::vector< std::vector< KFParticle > > * vMotherPrim, std::vector< KFParticle > * vMotherSec) inline
The function which decides if primary and secondary candidates found by KFParticleFinder::ConstructV0() should be stored and stores them to the provided arrays.
Parameters
[in] mother - constructed SIMD vector of particle candidates.
[in] NParticles - number of particles in the SIMD vector.
[in] mother_temp - temporary object to extract KFParticle from constructed KFParticleSIMD mother. Preallocated for better performance.
[in] PrimVtx - array with primary vertices.
[in] secCuts - cuts to select primary and secondary candidates from the reconstructed set: , , .
[out] vMotherPrim - array with output primary candidates if any.
[out] vMotherSec - array with output secondary candidates if any.
Definition at line 871 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 871 of file KFParticleFinder.cxx
References float_vLen, fNPV, fPrimCandidatesTopo, fPrimCandidatesTopoMass, KFParticleSIMD::GetChi2(), KFParticleSIMD::GetKFParticle(), KFParticleDatabase::GetMotherMass(), KFParticleSIMD::GetNDF(), KFParticleDatabase::Instance(), KFParticleBaseSIMD::PDG(), KFParticleBaseSIMD::SetNonlinearMassConstraint(), and KFParticleBaseSIMD::SetProductionVertex().
Referenced by ConstructPrimaryBG(), ConstructV0(), and Find2DaughterDecay().
void KFParticleFinder::SelectParticles (std::vector< KFParticle > & Particles, std::vector< KFParticle > & vCandidates, std::vector< KFParticleSIMD, KFPSimdAllocator< KFParticleSIMD > > & PrimVtx, const float & cutChi2Topo, const float & cutLdL, const float & mass, const float & massErr, const float & massCut)
Selects particles from a set of candidates "vCandidates" according to the provided cuts on and and stores them to the output array "Particles". Also, "vCandidates" is cleaned, only selected particles with additional cut on are left there.
Parameters
[out] Particles - output vector with particles.
[in,out] vCandidates - vector with the input candidates.
[in] PrimVtx - vector with primary vertices.
[in] cutChi2Topo - cut.
[in] cutLdL - cut.
[in] mass - table mass for the given PDG hypothesis.
[in] massErr - sigma of the peak width for the given PDG hypothesis.
[in] massCut - cut.
Definition at line 2428 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 2428 of file KFParticleFinder.cxx
References float_vLen, fNPV, GetChi2(), KFParticleBaseSIMD::GetDistanceToVertexLine(), GetNDF(), and KFParticleBaseSIMD::SetProductionVertex().
Referenced by FindParticles().
void KFParticleFinder::SetChi2Cut2D (float cut) inline
Sets cut on for 2-daughter decays.
Definition at line 284 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 284 of file KFParticleFinder.h
References fCuts2D.
void KFParticleFinder::SetChi2CutCharm2D (float cut) inline
Sets cut for open charm with 2 daughters.
Definition at line 313 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 313 of file KFParticleFinder.h
References fCutsCharm.
void KFParticleFinder::SetChi2CutCharmManybodyDecays (float cut) inline
Sets cut for open charm with >=3 daughters.
Definition at line 309 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 309 of file KFParticleFinder.h
References fCutsTrackV0.
void KFParticleFinder::SetChi2CutResonances (float cut) inline
Sets cut for resonances.
Definition at line 299 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 299 of file KFParticleFinder.h
References fCutsTrackV0.
void KFParticleFinder::SetChi2CutXiOmega (float cut) inline
Sets cut for and .
Definition at line 296 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 296 of file KFParticleFinder.h
References fCutsTrackV0.
void KFParticleFinder::SetChi2TopoCutCharm2D (float cut) inline
Sets cut for open charm with 2 daughters.
Definition at line 312 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 312 of file KFParticleFinder.h
References fCutsCharm.
void KFParticleFinder::SetChi2TopoCutCharmManybodyDecays (float cut) inline
Sets cut for open charm with >=3 daughters.
Definition at line 308 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 308 of file KFParticleFinder.h
References fCutsTrackV0.
void KFParticleFinder::SetChi2TopoCutResonances (float cut) inline
Sets cut for resonances.
Definition at line 298 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 298 of file KFParticleFinder.h
References fCutsTrackV0.
void KFParticleFinder::SetChi2TopoCutXiOmega (float cut) inline
Sets cut for and .
Definition at line 295 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 295 of file KFParticleFinder.h
References fCutsTrackV0.
void KFParticleFinder::SetChiPrimaryCut2D (float cut) inline
Sets cut on of each track for 2-daughter decays.
Definition at line 283 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 283 of file KFParticleFinder.h
References fCuts2D.
Referenced by KFParticleTopoReconstructor::SetChi2PrimaryCut().
void KFParticleFinder::SetChiPrimaryCutCharm (float cut) inline
Sets cut on of each track for open charm particles.
Definition at line 306 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 306 of file KFParticleFinder.h
References fCutCharmChiPrim.
void KFParticleFinder::SetEmcClusters (KFPEmcCluster * clusters) inline
Set a pointer to the gamma-clusters from the electromagnetic calorimeter.
Definition at line 169 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 169 of file KFParticleFinder.h
References fEmcClusters.
Referenced by KFParticleTopoReconstructor::SetEmcClusters().
void KFParticleFinder::SetLCut (float cut) inline
Sets cut on the distance to the primary vertex from the decay vertex.
Definition at line 281 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 281 of file KFParticleFinder.h
References fLCut.
void KFParticleFinder::SetLdLCut2D (float cut) inline
Sets cut on for 2-daughter decays.
Definition at line 285 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 285 of file KFParticleFinder.h
References fCuts2D.
void KFParticleFinder::SetLdLCutCharm2D (float cut) inline
Sets cut for open charm with 2 daughters.
Definition at line 311 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 311 of file KFParticleFinder.h
References fCutsCharm.
void KFParticleFinder::SetLdLCutCharmManybodyDecays (float cut) inline
Sets cut for open charm with >=3 daughters.
Definition at line 307 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 307 of file KFParticleFinder.h
References fCutsTrackV0.
void KFParticleFinder::SetLdLCutXiOmega (float cut) inline
Sets cut for and .
Definition at line 294 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 294 of file KFParticleFinder.h
References fCutsTrackV0.
void KFParticleFinder::SetMaxDistanceBetweenParticlesCut (float cut) inline
Sets cut on the distance between secondary tracks at the DCA point.
Definition at line 280 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 280 of file KFParticleFinder.h
References fDistanceCut.
void KFParticleFinder::SetMixedEventAnalysis () inline
Switch KFParticleFinder to the mixed event mode.
Definition at line 172 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 172 of file KFParticleFinder.h
References fMixedEventAnalysis.
Referenced by KFParticleTopoReconstructor::SetMixedEventAnalysis().
void KFParticleFinder::SetNPV (int nPV)
Sets the number of primary vertices to "nPV", resizes all vectors with primary candidates correspondingly.
Parameters
[in] nPV - number of the primary vertices in the event to be set.
Definition at line 3101 of file KFParticleFinder.cxx.
View newest version in sPHENIX GitHub at line 3101 of file KFParticleFinder.cxx
References fNPrimCandidatesSets, fNPrimCandidatesTopoSets, fNPV, fPrimCandidates, fPrimCandidatesTopo, and fPrimCandidatesTopoMass.
Referenced by KFParticleTopoReconstructor::AddPV().
void KFParticleFinder::SetNThreads (short int n) inline
Sets the number of threads to by run in parallel. Currently not used.
Definition at line 55 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 55 of file KFParticleFinder.h
References fNThreads, and n.
Referenced by KFParticleTopoReconstructor::KFParticleTopoReconstructor().
void KFParticleFinder::SetPCutLMVM (float cut) inline
Sets the cut on momentum of each daughter track of low mass vector mesons in dimuon channel.
Definition at line 302 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 302 of file KFParticleFinder.h
References fCutLVMP.
void KFParticleFinder::SetPtCutCharm (float cut) inline
Sets the cut on transverse momentum of each daughter track of open charm particles.
Definition at line 305 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 305 of file KFParticleFinder.h
References fCutCharmPt.
void KFParticleFinder::SetPtCutJPsi (float cut) inline
Sets the cut on transverse momentum of each daughter track of .
Definition at line 303 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 303 of file KFParticleFinder.h
References fCutJPsiPt.
void KFParticleFinder::SetPtCutLMVM (float cut) inline
Sets the cut on transverse momentum of each daughter track of low mass vector mesons.
Definition at line 301 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 301 of file KFParticleFinder.h
References fCutLVMPt.
void KFParticleFinder::SetReconstructionList (const std::map< int, bool > & decays) inline
Set enitre reconstruction list.
Definition at line 380 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 380 of file KFParticleFinder.h
References fDecayReconstructionList.
void KFParticleFinder::SetSecondaryCuts (const float sigmaMass = 3.f, const float chi2Topo = 5.f, const float ldl = 10.f) inline
Sets cuts on selection of secondary and primary candidates: , , .
Definition at line 288 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 288 of file KFParticleFinder.h
References fSecCuts.
Member Data Documentation
float KFParticleFinder::fCutCharmChiPrim private
Cut on the deviation of the track from the primary vertex for open charm reconstruction.
Definition at line 401 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 401 of file KFParticleFinder.h
Referenced by CopyCuts(), Find2DaughterDecay(), FindTrackV0Decay(), GetChiPrimaryCutCharm(), KFParticleFinder(), and SetChiPrimaryCutCharm().
float KFParticleFinder::fCutCharmPt private
Cut on transverse momentum of the track for open charm reconstruction.
Definition at line 400 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 400 of file KFParticleFinder.h
Referenced by CopyCuts(), Find2DaughterDecay(), FindTrackV0Decay(), GetPtCutCharm(), and SetPtCutCharm().
float KFParticleFinder::fCutJPsiPt private
Cut on transverse momentum of daughter tracks for .
Definition at line 409 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 409 of file KFParticleFinder.h
Referenced by ConstructV0(), CopyCuts(), GetPtCutJPsi(), and SetPtCutJPsi().
float KFParticleFinder::fCutLVMP private
Cut on momentum of low mass vector mesons in dimuon channel.
Definition at line 406 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 406 of file KFParticleFinder.h
Referenced by CopyCuts(), GetPCutLMVM(), and SetPCutLMVM().
float KFParticleFinder::fCutLVMPt private
Cut on transverse momentum of daughter tracks for low mass vector mesons.
Definition at line 405 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 405 of file KFParticleFinder.h
Referenced by ConstructV0(), CopyCuts(), GetPtCutLMVM(), and SetPtCutLMVM().
float KFParticleFinder::fCuts2D[3] private
Cuts on 2-daughter decays: , , .
Definition at line 390 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 390 of file KFParticleFinder.h
Referenced by CopyCuts(), Find2DaughterDecay(), FindParticles(), FindTrackV0Decay(), GetChi2Cut2D(), GetChiPrimaryCut2D(), GetLdLCut2D(), KFParticleFinder(), NeutralDaughterDecay(), SetChi2Cut2D(), SetChiPrimaryCut2D(), and SetLdLCut2D().
float KFParticleFinder::fCutsCharm[3] private
Cuts on reconstructed 2-daughter charm candidates: , , .
Definition at line 402 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 402 of file KFParticleFinder.h
Referenced by ConstructV0(), CopyCuts(), FindParticles(), GetChi2CutCharm2D(), GetChi2TopoCutCharm2D(), GetLdLCutCharm2D(), KFParticleFinder(), SetChi2CutCharm2D(), SetChi2TopoCutCharm2D(), and SetLdLCutCharm2D().
float KFParticleFinder::fCutsPartPart[2][3] private
Cuts on the combination of two short-lived particle candidates: , , . Two sets are defined: 1) for particles that fly away from the primary vertex and 2) for resonances.
Definition at line 397 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 397 of file KFParticleFinder.h
Referenced by CopyCuts(), FindParticles(), and KFParticleFinder().
float KFParticleFinder::fCutsTrackV0[3][3] private
Cuts on the combination of track and short-lived particle candidate: , , . Three sets of cuts are defined: 1) for and , 2) for hypernuclei and open charm, 3) for resonances.
Definition at line 394 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 394 of file KFParticleFinder.h
Referenced by CopyCuts(), FindTrackV0Decay(), GetChi2CutCharmManybodyDecays(), GetChi2CutResonances(), GetChi2CutXiOmega(), GetChi2TopoCutCharmManybodyDecays(), GetChi2TopoCutResonances(), GetChi2TopoCutXiOmega(), GetLdLCutCharmManybodyDecays(), GetLdLCutXiOmega(), KFParticleFinder(), SetChi2CutCharmManybodyDecays(), SetChi2CutResonances(), SetChi2CutXiOmega(), SetChi2TopoCutCharmManybodyDecays(), SetChi2TopoCutResonances(), SetChi2TopoCutXiOmega(), SetLdLCutCharmManybodyDecays(), and SetLdLCutXiOmega().
std::vector<KFParticle> KFParticleFinder::fD0 private
Vector with temporary D0->K-pi+ candidates.
Definition at line 412 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 412 of file KFParticleFinder.h
Referenced by ConstructV0(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fD04 private
Vector with temporary D0->K-pi+pi+pi- candidates.
Definition at line 414 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 414 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fD04bar private
Vector with temporary D0_bar->K+pi+pi-pi- candidates.
Definition at line 415 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 415 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fD0bar private
Vector with temporary D0_bar->K+pi- candidates.
Definition at line 413 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 413 of file KFParticleFinder.h
Referenced by ConstructV0(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fD0KK private
Vector with temporary D0->K+K- candidates.
Definition at line 416 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 416 of file KFParticleFinder.h
Referenced by ConstructV0(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fD0pipi private
Vector with temporary D0->pi+pi- candidates.
Definition at line 417 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 417 of file KFParticleFinder.h
Referenced by ConstructV0(), FindParticles(), and Init().
std::map<int,bool> KFParticleFinder::fDecayReconstructionList private
Map defines if the reconstruction of the decay with a certain PDG hypothesis should be run. If the map is empty - all decays are reconstructed. If at least one decay is added - only those decays will be reconstructed which are specified in the list.
Definition at line 463 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 463 of file KFParticleFinder.h
Referenced by AddDecayToReconstructionList(), CombinePartPart(), ConstructPrimaryBG(), Find2DaughterDecay(), FindTrackV0Decay(), GetReconstructionList(), NeutralDaughterDecay(), and SetReconstructionList().
float KFParticleFinder::fDistanceCut private
Cut on the distance between secondary tracks at the DCA point, is soft and used to speed up the algorithm only.
Definition at line 387 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 387 of file KFParticleFinder.h
Referenced by CopyCuts(), Find2DaughterDecay(), FindTrackV0Decay(), GetMaxDistanceBetweenParticlesCut(), and SetMaxDistanceBetweenParticlesCut().
std::vector<KFParticle> KFParticleFinder::fDMinus private
Vector with temporary D–>K+pi-pi- candidates.
Definition at line 419 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 419 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fDMinus3Pi private
Vector with temporary D–>pi+pi-pi- candidates.
Definition at line 421 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 421 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fDPlus private
Vector with temporary D+->K-pi+pi+ candidates.
Definition at line 418 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 418 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fDPlus3Pi private
Vector with temporary D+->pi+pi+pi- candidates.
Definition at line 420 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 420 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fDsMinusK2Pi private
Vector with temporary Ds–>K-pi+pi- candidates.
Definition at line 423 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 423 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fDsPlusK2Pi private
Vector with temporary Ds+->K+pi+pi- candidates.
Definition at line 422 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 422 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindParticles(), and Init().
KFPEmcCluster* KFParticleFinder::fEmcClusters private
Pointer to the input gamma-clusters from the electromagnetic calorimeter.
Definition at line 458 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 458 of file KFParticleFinder.h
Referenced by FindParticles(), and SetEmcClusters().
std::vector<KFParticle> KFParticleFinder::fH5LL private
Vector with temporary H5_LL->He5_Lambda pi- candidates.
Definition at line 437 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 437 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fHe3Pi private
Temporary He3+ pi- combinations.
Definition at line 430 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 430 of file KFParticleFinder.h
Referenced by ConstructV0(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fHe3PiBar private
Temporary He3- pi+ combinations.
Definition at line 431 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 431 of file KFParticleFinder.h
Referenced by ConstructV0(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fHe4L private
Vector with temporary He4_Lambda->He3 p pi- candidates.
Definition at line 434 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 434 of file KFParticleFinder.h
Referenced by FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fHe4Pi private
Temporary He4+ pi- combinations.
Definition at line 432 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 432 of file KFParticleFinder.h
Referenced by ConstructV0(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fHe4PiBar private
Temporary He4- pi+ combinations.
Definition at line 433 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 433 of file KFParticleFinder.h
Referenced by ConstructV0(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fHe5L private
Vector with temporary He4_Lambda->He4 p pi- candidates.
Definition at line 435 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 435 of file KFParticleFinder.h
Referenced by FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fLcMinusP2Pi private
Vector with temporary Lambda_c_bar->p-pi+pi- candidates.
Definition at line 425 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 425 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fLcPlusP2Pi private
Vector with temporary Lambda_c->p pi+pi- candidates.
Definition at line 424 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 424 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindParticles(), and Init().
float KFParticleFinder::fLCut private
Cut on the distance to the primary vertex from the decay vertex. Is applied to , , , , hypernuclei and dibaryons.
Definition at line 388 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 388 of file KFParticleFinder.h
Referenced by CombinePartPart(), ConstructTrackV0Cand(), ConstructV0(), CopyCuts(), GetLCut(), and SetLCut().
std::vector<KFParticle> KFParticleFinder::fLLn private
Vector with temporary H3_Lambda pi- candidates.
Definition at line 436 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 436 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindParticles(), and Init().
std::vector<KFParticle> KFParticleFinder::fLPi private
Temporary Lambda pi+ combinations.
Definition at line 428 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 428 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindParticles(), and Init().
std::vector<int> KFParticleFinder::fLPiPIndex private
Index of the proton in Labmda for Lambda pi+ combinations.
Definition at line 429 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 429 of file KFParticleFinder.h
Referenced by ConstructTrackV0Cand(), FindTrackV0Decay(), and Init().
bool KFParticleFinder::fMixedEventAnalysis private
Flag defines if the mixed event analysis is run. In mixed event mode limited number of decays is reconstructed.
Definition at line 460 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 460 of file KFParticleFinder.h
Referenced by Find2DaughterDecay(), FindParticles(), and SetMixedEventAnalysis().
const int KFParticleFinder::fNPrimCandidatesSets = 11 static private
Number of sets of primary particle candidates.
Definition at line 443 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 443 of file KFParticleFinder.h
Referenced by Init(), and SetNPV().
const int KFParticleFinder::fNPrimCandidatesTopoSets = 9 static private
Number of sets of primary particle candidates with topological constraint.
Definition at line 448 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 448 of file KFParticleFinder.h
Referenced by GetNPrimarySets(), Init(), and SetNPV().
short int KFParticleFinder::fNPV private
Number of primary vertex candidates in the event.
Definition at line 384 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 384 of file KFParticleFinder.h
Referenced by AddCandidate(), CombinePartPart(), ConstructPrimaryBG(), ConstructTrackV0Cand(), ConstructV0(), Find2DaughterDecay(), FindParticles(), FindTrackV0Decay(), Init(), SaveV0PrimSecCand(), SelectParticles(), and SetNPV().
const int KFParticleFinder::fNSecCandidatesSets = 5 static private
Number of sets of secondary particle candidates.
Definition at line 440 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 440 of file KFParticleFinder.h
Referenced by GetNSecondarySets(), and Init().
short int KFParticleFinder::fNThreads private
Number of threads to be run in parallel. Currently is not used.
Definition at line 385 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 385 of file KFParticleFinder.h
Referenced by SetNThreads().
std::vector< std::vector<KFParticle> > KFParticleFinder::fPrimCandidates[fNPrimCandidatesSets] private
Array of vectors with primary candidates for each primary vertex: 0) , 1) , 2) , 3) , 4) , 5) , 6) , 7) , 8) , 9) , 10) .
Definition at line 447 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 447 of file KFParticleFinder.h
Referenced by AddCandidate(), ConstructTrackV0Cand(), FindParticles(), GetPrimaryAntiLambda(), GetPrimaryAntiOmega(), GetPrimaryAntiXi(), GetPrimaryCandidates(), GetPrimaryGamma(), GetPrimaryK0(), GetPrimaryLambda(), GetPrimaryOmega(), GetPrimaryPi0(), GetPrimaryXi(), Init(), and SetNPV().
std::vector< std::vector<KFParticle> > KFParticleFinder::fPrimCandidatesTopo[fNPrimCandidatesTopoSets] private
Array of vectors with primary candidates for each primary vertex with a topological constraint set: 0) , 1) , 2) , 3) , 4) , 5) , 6) , 7) , 8) .
Definition at line 452 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 452 of file KFParticleFinder.h
Referenced by AddCandidate(), GetPrimaryTopoAntiLambda(), GetPrimaryTopoAntiOmega(), GetPrimaryTopoAntiXi(), GetPrimaryTopoCandidates(), GetPrimaryTopoGamma(), GetPrimaryTopoK0(), GetPrimaryTopoLambda(), GetPrimaryTopoOmega(), GetPrimaryTopoPi0(), GetPrimaryTopoXi(), Init(), SaveV0PrimSecCand(), and SetNPV().
std::vector< std::vector<KFParticle> > KFParticleFinder::fPrimCandidatesTopoMass[fNPrimCandidatesTopoSets] private
Array of vectors with primary candidates for each primary vertex with a topological and mass constraints set: 0) , 1) , 2) , 3) , 4) , 5) , 6) , 7) , 8) .
Definition at line 456 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 456 of file KFParticleFinder.h
Referenced by AddCandidate(), GetPrimaryTopoMassAntiLambda(), GetPrimaryTopoMassAntiOmega(), GetPrimaryTopoMassAntiXi(), GetPrimaryTopoMassCandidates(), GetPrimaryTopoMassGamma(), GetPrimaryTopoMassK0(), GetPrimaryTopoMassLambda(), GetPrimaryTopoMassOmega(), GetPrimaryTopoMassPi0(), GetPrimaryTopoMassXi(), Init(), SaveV0PrimSecCand(), and SetNPV().
std::vector<KFParticle> KFParticleFinder::fSecCandidates[fNSecCandidatesSets] private
Array of vectors with secondary candidates: 0) , 1) , 2) , 3) , 4) .
Definition at line 442 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 442 of file KFParticleFinder.h
Referenced by AddCandidate(), FindParticles(), GetSecondaryAntiLambda(), GetSecondaryCandidates(), GetSecondaryGamma(), GetSecondaryK0(), GetSecondaryLambda(), GetSecondaryPi0(), and Init().
float KFParticleFinder::fSecCuts[3] private
Cuts to select secondary and primary particle candidates: , , .
Definition at line 391 of file KFParticleFinder.h.
View newest version in sPHENIX GitHub at line 391 of file KFParticleFinder.h
Referenced by CopyCuts(), FindParticles(), GetSecondaryChi2TopoCut(), GetSecondaryLdLCut(), GetSecondarySigmaMassCut(), KFParticleFinder(), and SetSecondaryCuts().
The documentation for this class was generated from the following files:
KFParticle/blob/master/KFParticle/KFParticleFinder.h
KFParticle/blob/master/KFParticle/KFParticleFinder.cxx