Analysis Software: genfit::KalmanFitterInfo Class Reference
genfit::KalmanFitterInfo Class Reference
Collects information needed and produced by a AbsKalmanFitter implementations and is specific to one AbsTrackRep of the Track.
#include <GenFit/blob/master/fitters/include/KalmanFitterInfo.h>
Public Member Functions
KalmanFitterInfo ()
KalmanFitterInfo (const TrackPoint *trackPoint, const AbsTrackRep *rep)
virtual ~KalmanFitterInfo ()
virtual KalmanFitterInfo * clone () const override
Deep copy ctor for polymorphic class.
ReferenceStateOnPlane * getReferenceState () const
MeasuredStateOnPlane * getForwardPrediction () const
MeasuredStateOnPlane * getBackwardPrediction () const
MeasuredStateOnPlane * getPrediction (int direction) const
KalmanFittedStateOnPlane * getForwardUpdate () const
KalmanFittedStateOnPlane * getBackwardUpdate () const
KalmanFittedStateOnPlane * getUpdate (int direction) const
const std::vector
< genfit::MeasurementOnPlane * > & getMeasurementsOnPlane () const
MeasurementOnPlane * getMeasurementOnPlane (int i=0) const
MeasurementOnPlane getAvgWeightedMeasurementOnPlane (bool ignoreWeights=false) const
MeasurementOnPlane * getClosestMeasurementOnPlane (const StateOnPlane *) const
Get measurements which is closest to state.
unsigned int getNumMeasurements () const
std::vector< double > getWeights () const
Get weights of measurements.
bool areWeightsFixed () const
Are the weights fixed?
const MeasuredStateOnPlane & getFittedState (bool biased=true) const override
Get unbiased or biased (default) smoothed state.
MeasurementOnPlane getResidual (unsigned int iMeasurement=0, bool biased=false, bool onlyMeasurementErrors=true) const override
Get unbiased (default) or biased residual from ith measurement.
double getSmoothedChi2 (unsigned int iMeasurement=0) const
bool hasMeasurements () const override
bool hasReferenceState () const override
bool hasForwardPrediction () const override
bool hasBackwardPrediction () const override
bool hasForwardUpdate () const override
bool hasBackwardUpdate () const override
bool hasUpdate (int direction) const override
bool hasPredictionsAndUpdates () const
void setReferenceState (ReferenceStateOnPlane *referenceState)
void setForwardPrediction (MeasuredStateOnPlane *forwardPrediction)
void setBackwardPrediction (MeasuredStateOnPlane *backwardPrediction)
void setPrediction (MeasuredStateOnPlane *prediction, int direction)
void setForwardUpdate (KalmanFittedStateOnPlane *forwardUpdate)
void setBackwardUpdate (KalmanFittedStateOnPlane *backwardUpdate)
void setUpdate (KalmanFittedStateOnPlane *update, int direction)
void setMeasurementsOnPlane (const std::vector< genfit::MeasurementOnPlane * > &measurementsOnPlane)
void addMeasurementOnPlane (MeasurementOnPlane *measurementOnPlane)
void addMeasurementsOnPlane (const std::vector< genfit::MeasurementOnPlane * > &measurementsOnPlane)
void setWeights (const std::vector< double > &)
Set weights of measurements.
void fixWeights (bool arg=true)
void setRep (const AbsTrackRep *rep) override
void deleteForwardInfo () override
void deleteBackwardInfo () override
void deletePredictions ()
void deleteReferenceInfo () override
void deleteMeasurementInfo () override
virtual void Print (const Option_t *="") const override
virtual bool checkConsistency (const genfit::PruneFlags *=nullptr) const override
Public Member Functions inherited from genfit::AbsFitterInfo
AbsFitterInfo ()
AbsFitterInfo (const TrackPoint *trackPoint, const AbsTrackRep *rep)
virtual ~AbsFitterInfo ()
const TrackPoint * getTrackPoint () const
const AbsTrackRep * getRep () const
void setTrackPoint (const TrackPoint *tp)
virtual bool hasPrediction (int direction) const
const SharedPlanePtr & getPlane () const
void setPlane (const SharedPlanePtr &plane)
Private Attributes
std::unique_ptr
< ReferenceStateOnPlane > referenceState_
Reference state. Used by KalmanFitterRefTrack.
std::unique_ptr
< MeasuredStateOnPlane > forwardPrediction_
std::unique_ptr
< KalmanFittedStateOnPlane > forwardUpdate_
std::unique_ptr
< MeasuredStateOnPlane > backwardPrediction_
std::unique_ptr
< KalmanFittedStateOnPlane > backwardUpdate_
std::unique_ptr
< MeasuredStateOnPlane > fittedStateUnbiased_
std::unique_ptr
< MeasuredStateOnPlane > fittedStateBiased_
cache
std::vector< MeasurementOnPlane * > measurementsOnPlane_
cache
bool fixWeights_
Additional Inherited Members
Protected Attributes inherited from genfit::AbsFitterInfo
const TrackPoint * trackPoint_
const AbsTrackRep * rep_
No ownership.
SharedPlanePtr sharedPlane_
No ownership.
Detailed Description
Collects information needed and produced by a AbsKalmanFitter implementations and is specific to one AbsTrackRep of the Track.
Definition at line 44 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 44 of file KalmanFitterInfo.h
Constructor & Destructor Documentation
genfit::KalmanFitterInfo::KalmanFitterInfo ()
Definition at line 37 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 37 of file KalmanFitterInfo.cc
Referenced by clone().
genfit::KalmanFitterInfo::KalmanFitterInfo (const TrackPoint * trackPoint, const AbsTrackRep * rep)
Definition at line 43 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 43 of file KalmanFitterInfo.cc
genfit::KalmanFitterInfo::~KalmanFitterInfo () virtual
Definition at line 49 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 49 of file KalmanFitterInfo.cc
References deleteMeasurementInfo().
Member Function Documentation
void genfit::KalmanFitterInfo::addMeasurementOnPlane (MeasurementOnPlane * measurementOnPlane)
Definition at line 425 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 425 of file KalmanFitterInfo.cc
References genfit::StateOnPlane::getPlane(), measurementsOnPlane_, and genfit::AbsFitterInfo::setPlane().
Referenced by addMeasurementsOnPlane(), clone(), and setMeasurementsOnPlane().
void genfit::KalmanFitterInfo::addMeasurementsOnPlane (const std::vector< genfit::MeasurementOnPlane * > & measurementsOnPlane)
Definition at line 432 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 432 of file KalmanFitterInfo.cc
References addMeasurementOnPlane().
Referenced by genfit::KalmanFitterRefTrack::prepareTrack(), and PHGenFit::Track::updateOneMeasurementKalman().
bool genfit::KalmanFitterInfo::areWeightsFixed () const inline
Are the weights fixed?
Definition at line 72 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 72 of file KalmanFitterInfo.h
References fixWeights_.
Referenced by genfit::DAF::calcWeights(), and genfit::KalmanFitterRefTrack::prepareTrack().
bool genfit::KalmanFitterInfo::checkConsistency (const genfit::PruneFlags * flags = nullptr) const override virtual
Implements genfit::AbsFitterInfo.
Definition at line 539 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 539 of file KalmanFitterInfo.cc
References backwardPrediction_, backwardUpdate_, genfit::errorOut, forwardPrediction_, forwardUpdate_, genfit::AbsTrackRep::getDim(), genfit::AbsFitterInfo::getPlane(), genfit::PruneFlags::hasFlags(), i, it, measurementsOnPlane_, referenceState_, genfit::AbsFitterInfo::rep_, and genfit::AbsFitterInfo::trackPoint_.
Referenced by genfit::AbsKalmanFitter::isTrackFitted(), genfit::AbsKalmanFitter::isTrackPrepared(), genfit::KalmanFitterRefTrack::processTrackPoint(), and genfit::KalmanFitterRefTrack::processTrackPointSqrt().
KalmanFitterInfo * genfit::KalmanFitterInfo::clone () const override virtual
Deep copy ctor for polymorphic class.
Implements genfit::AbsFitterInfo.
Definition at line 54 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 54 of file KalmanFitterInfo.cc
References addMeasurementOnPlane(), fixWeights_, getBackwardPrediction(), getBackwardUpdate(), getForwardPrediction(), getForwardUpdate(), getNumMeasurements(), getReferenceState(), genfit::AbsFitterInfo::getRep(), genfit::AbsFitterInfo::getTrackPoint(), hasBackwardPrediction(), hasBackwardUpdate(), hasForwardPrediction(), hasForwardUpdate(), hasReferenceState(), it, KalmanFitterInfo(), measurementsOnPlane_, setBackwardPrediction(), setBackwardUpdate(), setForwardPrediction(), setForwardUpdate(), and setReferenceState().
void genfit::KalmanFitterInfo::deleteBackwardInfo () override virtual
Implements genfit::AbsFitterInfo.
Definition at line 487 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 487 of file KalmanFitterInfo.cc
References fittedStateBiased_, fittedStateUnbiased_, setBackwardPrediction(), and setBackwardUpdate().
void genfit::KalmanFitterInfo::deleteForwardInfo () override virtual
Implements genfit::AbsFitterInfo.
Definition at line 480 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 480 of file KalmanFitterInfo.cc
References fittedStateBiased_, fittedStateUnbiased_, setForwardPrediction(), and setForwardUpdate().
void genfit::KalmanFitterInfo::deleteMeasurementInfo () override virtual
Implements genfit::AbsFitterInfo.
Definition at line 501 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 501 of file KalmanFitterInfo.cc
References i, and measurementsOnPlane_.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack(), setMeasurementsOnPlane(), and ~KalmanFitterInfo().
void genfit::KalmanFitterInfo::deletePredictions ()
Definition at line 494 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 494 of file KalmanFitterInfo.cc
References fittedStateBiased_, fittedStateUnbiased_, setBackwardPrediction(), and setForwardPrediction().
void genfit::KalmanFitterInfo::deleteReferenceInfo () inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 106 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 106 of file KalmanFitterInfo.h
References setReferenceState().
Referenced by genfit::KalmanFitterRefTrack::prepareTrack(), and genfit::KalmanFitterRefTrack::removeOutdated().
void genfit::KalmanFitterInfo::fixWeights (bool arg = true) inline
Definition at line 100 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 100 of file KalmanFitterInfo.h
References fixWeights_.
Referenced by genfit::Track::fixWeights(), and genfit::KalmanFitterRefTrack::prepareTrack().
MeasurementOnPlane genfit::KalmanFitterInfo::getAvgWeightedMeasurementOnPlane (bool ignoreWeights = false) const
Get weighted mean of all measurements.
Parameters
ignoreWeights If set, the weights of the individual measurements will be ignored (they will be treated as if they all had weight 1)
Definition at line 78 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 78 of file KalmanFitterInfo.cc
References assert, genfit::MeasuredStateOnPlane::getCov(), genfit::AbsFitterInfo::getPlane(), genfit::StateOnPlane::getState(), i, genfit::tools::invertMatrix(), measurementsOnPlane_, and genfit::MeasurementOnPlane::setWeight().
MeasuredStateOnPlane* genfit::KalmanFitterInfo::getBackwardPrediction () const inline
Definition at line 56 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 56 of file KalmanFitterInfo.h
References backwardPrediction_.
Referenced by clone(), genfit::EventDisplay::drawEvent(), and genfit::KalmanFitterRefTrack::processTrackWithRep().
KalmanFittedStateOnPlane* genfit::KalmanFitterInfo::getBackwardUpdate () const inline
Definition at line 59 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 59 of file KalmanFitterInfo.h
References backwardUpdate_.
Referenced by clone(), genfit::EventDisplay::drawEvent(), genfit::AbsKalmanFitter::getChiSquNdf(), and genfit::KalmanFitterRefTrack::prepareTrack().
MeasurementOnPlane * genfit::KalmanFitterInfo::getClosestMeasurementOnPlane (const StateOnPlane * sop) const
Get measurements which is closest to state.
Definition at line 139 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 139 of file KalmanFitterInfo.cc
References getMeasurementOnPlane(), getNumMeasurements(), genfit::StateOnPlane::getState(), H, genfit::AbsHMatrix::Hv(), i, measurementsOnPlane_, norm, and genfit::Exception::setFatal().
Referenced by genfit::AbsKalmanFitter::getMeasurements().
const MeasuredStateOnPlane & genfit::KalmanFitterInfo::getFittedState (bool biased = true) const override virtual
Get unbiased or biased (default) smoothed state.
Implements genfit::AbsFitterInfo.
Definition at line 179 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 179 of file KalmanFitterInfo.cc
References backwardPrediction_, backwardUpdate_, genfit::calcAverageState(), genfit::debugOut, fittedStateBiased_, fittedStateUnbiased_, forwardPrediction_, forwardUpdate_, genfit::Track::getFitStatus(), genfit::Track::getNumPoints(), genfit::Track::getPointWithFitterInfo(), genfit::FitStatus::getPruneFlags(), genfit::AbsFitterInfo::getRep(), genfit::TrackPoint::getTrack(), genfit::AbsFitterInfo::getTrackPoint(), genfit::PruneFlags::hasFlags(), genfit::PruneFlags::isPruned(), genfit::PruneFlags::Print(), and genfit::Exception::setFatal().
Referenced by genfit::EventDisplay::drawEvent(), PHGenFit::Track::get_charge(), PHGenFit::Track::get_mom(), getResidual(), SVReco::MakeSvtxTrack(), PHGenFitTrkFitter::MakeSvtxTrack(), TpcPrototypeGenFitTrkFitter::MakeSvtxTrack(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitter::processTrackPartially(), genfit::KalmanFitter::processTrackWithRep(), genfit::KalmanFitterRefTrack::removeOutdated(), and PHGenFit::Track::updateOneMeasurementKalman().
MeasuredStateOnPlane* genfit::KalmanFitterInfo::getForwardPrediction () const inline
Definition at line 55 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 55 of file KalmanFitterInfo.h
References forwardPrediction_.
Referenced by clone(), and genfit::EventDisplay::drawEvent().
KalmanFittedStateOnPlane* genfit::KalmanFitterInfo::getForwardUpdate () const inline
Definition at line 58 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 58 of file KalmanFitterInfo.h
References forwardUpdate_.
Referenced by clone(), genfit::EventDisplay::drawEvent(), genfit::AbsKalmanFitter::getChiSquNdf(), and genfit::KalmanFitterRefTrack::processTrackWithRep().
MeasurementOnPlane* genfit::KalmanFitterInfo::getMeasurementOnPlane (int i = 0) const inline
Definition at line 62 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 62 of file KalmanFitterInfo.h
References i, and measurementsOnPlane_.
Referenced by genfit::DAF::calcWeights(), genfit::EventDisplay::drawEvent(), getClosestMeasurementOnPlane(), getWeights(), and setWeights().
const std::vector< genfit::MeasurementOnPlane* >& genfit::KalmanFitterInfo::getMeasurementsOnPlane () const inline
Definition at line 61 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 61 of file KalmanFitterInfo.h
References measurementsOnPlane_.
Referenced by genfit::AbsKalmanFitter::getMeasurements(), and PHGenFit::Track::updateOneMeasurementKalman().
unsigned int genfit::KalmanFitterInfo::getNumMeasurements () const inline
Definition at line 68 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 68 of file KalmanFitterInfo.h
References measurementsOnPlane_.
Referenced by genfit::DAF::calcWeights(), clone(), genfit::EventDisplay::drawEvent(), getClosestMeasurementOnPlane(), getWeights(), hasMeasurements(), genfit::KalmanFitterRefTrack::prepareTrack(), and setWeights().
MeasuredStateOnPlane* genfit::KalmanFitterInfo::getPrediction (int direction) const inline
Definition at line 57 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 57 of file KalmanFitterInfo.h
References backwardPrediction_, and forwardPrediction_.
Referenced by genfit::AbsKalmanFitter::getMeasurements(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), and PHGenFit::Track::updateOneMeasurementKalman().
ReferenceStateOnPlane* genfit::KalmanFitterInfo::getReferenceState () const inline
Definition at line 54 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 54 of file KalmanFitterInfo.h
References referenceState_.
Referenced by genfit::Track::checkConsistency(), clone(), genfit::EventDisplay::drawEvent(), genfit::AbsKalmanFitter::getMeasurements(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::GFGbl::processTrackWithRep(), and genfit::KalmanFitterRefTrack::removeOutdated().
MeasurementOnPlane genfit::KalmanFitterInfo::getResidual (unsigned int iMeasurement = 0, bool biased = false, bool onlyMeasurementErrors = true) const override virtual
Get unbiased (default) or biased residual from ith measurement.
Implements genfit::AbsFitterInfo.
Definition at line 314 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 314 of file KalmanFitterInfo.cc
References genfit::AbsHMatrix::clone(), genfit::MeasuredStateOnPlane::getCov(), getFittedState(), genfit::MeasurementOnPlane::getHMatrix(), genfit::StateOnPlane::getPlane(), genfit::StateOnPlane::getRep(), genfit::StateOnPlane::getState(), genfit::MeasurementOnPlane::getWeight(), H, genfit::AbsHMatrix::HMHt(), genfit::AbsHMatrix::Hv(), and measurementsOnPlane_.
Referenced by genfit::DAF::calcWeights(), and getSmoothedChi2().
double genfit::KalmanFitterInfo::getSmoothedChi2 (unsigned int iMeasurement = 0) const
Definition at line 350 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 350 of file KalmanFitterInfo.cc
References genfit::MeasuredStateOnPlane::getCov(), getResidual(), genfit::StateOnPlane::getState(), and genfit::tools::invertMatrix().
KalmanFittedStateOnPlane* genfit::KalmanFitterInfo::getUpdate (int direction) const inline
Definition at line 60 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 60 of file KalmanFitterInfo.h
References backwardUpdate_, and forwardUpdate_.
Referenced by genfit::KalmanFitterRefTrack::fitTrack(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), and PHGenFit::Track::updateOneMeasurementKalman().
std::vector< double > genfit::KalmanFitterInfo::getWeights () const
Get weights of measurements.
Definition at line 168 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 168 of file KalmanFitterInfo.cc
References getMeasurementOnPlane(), getNumMeasurements(), genfit::MeasurementOnPlane::getWeight(), and i.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack().
bool genfit::KalmanFitterInfo::hasBackwardPrediction () const inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 82 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 82 of file KalmanFitterInfo.h
References backwardPrediction_.
Referenced by clone(), genfit::EventDisplay::drawEvent(), hasPredictionsAndUpdates(), and genfit::KalmanFitterRefTrack::processTrackWithRep().
bool genfit::KalmanFitterInfo::hasBackwardUpdate () const inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 84 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 84 of file KalmanFitterInfo.h
References backwardUpdate_.
Referenced by clone(), genfit::EventDisplay::drawEvent(), hasPredictionsAndUpdates(), hasUpdate(), genfit::AbsKalmanFitter::isTrackFitted(), and genfit::KalmanFitterRefTrack::prepareTrack().
bool genfit::KalmanFitterInfo::hasForwardPrediction () const inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 81 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 81 of file KalmanFitterInfo.h
References forwardPrediction_.
Referenced by clone(), genfit::EventDisplay::drawEvent(), hasPredictionsAndUpdates(), and genfit::KalmanFitterRefTrack::prepareTrack().
bool genfit::KalmanFitterInfo::hasForwardUpdate () const inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 83 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 83 of file KalmanFitterInfo.h
References forwardUpdate_.
Referenced by clone(), genfit::EventDisplay::drawEvent(), hasPredictionsAndUpdates(), hasUpdate(), and genfit::AbsKalmanFitter::isTrackFitted().
bool genfit::KalmanFitterInfo::hasMeasurements () const inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 79 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 79 of file KalmanFitterInfo.h
References getNumMeasurements().
bool genfit::KalmanFitterInfo::hasPredictionsAndUpdates () const inline
Definition at line 86 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 86 of file KalmanFitterInfo.h
References hasBackwardPrediction(), hasBackwardUpdate(), hasForwardPrediction(), and hasForwardUpdate().
Referenced by genfit::EventDisplay::drawEvent(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitter::processTrackPartially(), genfit::KalmanFitter::processTrackWithRep(), and genfit::KalmanFitterRefTrack::removeOutdated().
bool genfit::KalmanFitterInfo::hasReferenceState () const inline override virtual
Implements genfit::AbsFitterInfo.
Definition at line 80 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 80 of file KalmanFitterInfo.h
References referenceState_.
Referenced by genfit::Track::checkConsistency(), clone(), genfit::EventDisplay::drawEvent(), genfit::AbsKalmanFitter::getMeasurements(), genfit::AbsKalmanFitter::isTrackPrepared(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::GFGbl::processTrackWithRep(), and genfit::KalmanFitterRefTrack::removeOutdated().
bool genfit::KalmanFitterInfo::hasUpdate (int direction) const inline override virtual
Reimplemented from genfit::AbsFitterInfo.
Definition at line 85 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 85 of file KalmanFitterInfo.h
References hasBackwardUpdate(), and hasForwardUpdate().
Referenced by genfit::KalmanFitterRefTrack::fitTrack().
void genfit::KalmanFitterInfo::Print (const Option_t * = "") const override virtual
Reimplemented from genfit::AbsFitterInfo.
Definition at line 510 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 510 of file KalmanFitterInfo.cc
References backwardPrediction_, backwardUpdate_, fixWeights_, forwardPrediction_, forwardUpdate_, i, measurementsOnPlane_, genfit::printOut, referenceState_, genfit::AbsFitterInfo::rep_, and genfit::AbsFitterInfo::trackPoint_.
void genfit::KalmanFitterInfo::setBackwardPrediction (MeasuredStateOnPlane * backwardPrediction)
Definition at line 391 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 391 of file KalmanFitterInfo.cc
References backwardPrediction_, fittedStateBiased_, fittedStateUnbiased_, and genfit::AbsFitterInfo::setPlane().
Referenced by clone(), deleteBackwardInfo(), deletePredictions(), genfit::KalmanFitterRefTrack::processTrackWithRep(), and setPrediction().
void genfit::KalmanFitterInfo::setBackwardUpdate (KalmanFittedStateOnPlane * backwardUpdate)
Definition at line 407 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 407 of file KalmanFitterInfo.cc
References backwardUpdate_, fittedStateBiased_, fittedStateUnbiased_, and genfit::AbsFitterInfo::setPlane().
Referenced by clone(), deleteBackwardInfo(), and setUpdate().
void genfit::KalmanFitterInfo::setForwardPrediction (MeasuredStateOnPlane * forwardPrediction)
Definition at line 383 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 383 of file KalmanFitterInfo.cc
References fittedStateBiased_, fittedStateUnbiased_, forwardPrediction_, and genfit::AbsFitterInfo::setPlane().
Referenced by clone(), deleteForwardInfo(), deletePredictions(), genfit::KalmanFitterRefTrack::prepareTrack(), and setPrediction().
void genfit::KalmanFitterInfo::setForwardUpdate (KalmanFittedStateOnPlane * forwardUpdate)
Definition at line 399 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 399 of file KalmanFitterInfo.cc
References fittedStateBiased_, fittedStateUnbiased_, forwardUpdate_, and genfit::AbsFitterInfo::setPlane().
Referenced by clone(), deleteForwardInfo(), setUpdate(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
void genfit::KalmanFitterInfo::setMeasurementsOnPlane (const std::vector< genfit::MeasurementOnPlane * > & measurementsOnPlane)
Definition at line 416 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 416 of file KalmanFitterInfo.cc
References addMeasurementOnPlane(), and deleteMeasurementInfo().
void genfit::KalmanFitterInfo::setPrediction (MeasuredStateOnPlane * prediction, int direction) inline
Definition at line 91 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 91 of file KalmanFitterInfo.h
References setBackwardPrediction(), and setForwardPrediction().
Referenced by genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), and PHGenFit::Track::updateOneMeasurementKalman().
void genfit::KalmanFitterInfo::setReferenceState (ReferenceStateOnPlane * referenceState)
Definition at line 359 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 359 of file KalmanFitterInfo.cc
References referenceState_, and genfit::AbsFitterInfo::setPlane().
Referenced by clone(), deleteReferenceInfo(), and genfit::KalmanFitterRefTrack::prepareTrack().
void genfit::KalmanFitterInfo::setRep (const AbsTrackRep * rep) override virtual
Reimplemented from genfit::AbsFitterInfo.
Definition at line 439 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 439 of file KalmanFitterInfo.cc
References backwardPrediction_, backwardUpdate_, forwardPrediction_, forwardUpdate_, it, measurementsOnPlane_, referenceState_, and genfit::AbsFitterInfo::rep_.
void genfit::KalmanFitterInfo::setUpdate (KalmanFittedStateOnPlane * update, int direction) inline
Definition at line 94 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 94 of file KalmanFitterInfo.h
References setBackwardUpdate(), and setForwardUpdate().
Referenced by genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), and PHGenFit::Track::updateOneMeasurementKalman().
void genfit::KalmanFitterInfo::setWeights (const std::vector< double > & weights)
Set weights of measurements.
Definition at line 463 of file KalmanFitterInfo.cc.
View newest version in sPHENIX GitHub at line 463 of file KalmanFitterInfo.cc
References genfit::errorOut, fixWeights_, getMeasurementOnPlane(), getNumMeasurements(), i, and genfit::MeasurementOnPlane::setWeight().
Referenced by genfit::KalmanFitterRefTrack::prepareTrack().
Member Data Documentation
std::unique_ptr<MeasuredStateOnPlane> genfit::KalmanFitterInfo::backwardPrediction_ private
Definition at line 119 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 119 of file KalmanFitterInfo.h
Referenced by checkConsistency(), getBackwardPrediction(), getFittedState(), getPrediction(), hasBackwardPrediction(), Print(), setBackwardPrediction(), and setRep().
std::unique_ptr<KalmanFittedStateOnPlane> genfit::KalmanFitterInfo::backwardUpdate_ private
Definition at line 120 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 120 of file KalmanFitterInfo.h
Referenced by checkConsistency(), getBackwardUpdate(), getFittedState(), getUpdate(), hasBackwardUpdate(), Print(), setBackwardUpdate(), and setRep().
std::unique_ptr<MeasuredStateOnPlane> genfit::KalmanFitterInfo::fittedStateBiased_ mutable private
cache
Definition at line 122 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 122 of file KalmanFitterInfo.h
Referenced by deleteBackwardInfo(), deleteForwardInfo(), deletePredictions(), getFittedState(), setBackwardPrediction(), setBackwardUpdate(), setForwardPrediction(), and setForwardUpdate().
std::unique_ptr<MeasuredStateOnPlane> genfit::KalmanFitterInfo::fittedStateUnbiased_ mutable private
Definition at line 121 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 121 of file KalmanFitterInfo.h
Referenced by deleteBackwardInfo(), deleteForwardInfo(), deletePredictions(), getFittedState(), setBackwardPrediction(), setBackwardUpdate(), setForwardPrediction(), and setForwardUpdate().
bool genfit::KalmanFitterInfo::fixWeights_ private
Definition at line 138 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 138 of file KalmanFitterInfo.h
Referenced by areWeightsFixed(), clone(), fixWeights(), Print(), and setWeights().
std::unique_ptr<MeasuredStateOnPlane> genfit::KalmanFitterInfo::forwardPrediction_ private
Definition at line 117 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 117 of file KalmanFitterInfo.h
Referenced by checkConsistency(), getFittedState(), getForwardPrediction(), getPrediction(), hasForwardPrediction(), Print(), setForwardPrediction(), and setRep().
std::unique_ptr<KalmanFittedStateOnPlane> genfit::KalmanFitterInfo::forwardUpdate_ private
Definition at line 118 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 118 of file KalmanFitterInfo.h
Referenced by checkConsistency(), getFittedState(), getForwardUpdate(), getUpdate(), hasForwardUpdate(), Print(), setForwardUpdate(), and setRep().
std::vector<MeasurementOnPlane*> genfit::KalmanFitterInfo::measurementsOnPlane_ private
cache
Definition at line 137 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 137 of file KalmanFitterInfo.h
Referenced by addMeasurementOnPlane(), checkConsistency(), clone(), deleteMeasurementInfo(), getAvgWeightedMeasurementOnPlane(), getClosestMeasurementOnPlane(), getMeasurementOnPlane(), getMeasurementsOnPlane(), getNumMeasurements(), getResidual(), Print(), and setRep().
std::unique_ptr<ReferenceStateOnPlane> genfit::KalmanFitterInfo::referenceState_ private
Reference state. Used by KalmanFitterRefTrack.
Definition at line 116 of file KalmanFitterInfo.h.
View newest version in sPHENIX GitHub at line 116 of file KalmanFitterInfo.h
Referenced by checkConsistency(), getReferenceState(), hasReferenceState(), Print(), setReferenceState(), and setRep().
The documentation for this class was generated from the following files:
GenFit/blob/master/fitters/include/KalmanFitterInfo.h
GenFit/blob/master/fitters/src/KalmanFitterInfo.cc