Analysis Software: genfit::ReferenceStateOnPlane Class Reference
genfit::ReferenceStateOnPlane Class Reference
StateOnPlane with linearized transport to that ReferenceStateOnPlane from previous and next ReferenceStateOnPlane
#include <GenFit/blob/master/fitters/include/ReferenceStateOnPlane.h>
Public Member Functions
ReferenceStateOnPlane ()
ReferenceStateOnPlane (const TVectorD &state, const SharedPlanePtr &plane, const AbsTrackRep *rep)
ReferenceStateOnPlane (const TVectorD &state, const SharedPlanePtr &plane, const AbsTrackRep *rep, const TVectorD &auxInfo)
ReferenceStateOnPlane (const StateOnPlane &state)
StateOnPlane & operator= (ReferenceStateOnPlane other)
void swap (ReferenceStateOnPlane &other)
virtual ~ReferenceStateOnPlane ()
void setForwardSegmentLength (double len)
void setBackwardSegmentLength (double len)
void setForwardTransportMatrix (const TMatrixD &mat)
void setBackwardTransportMatrix (const TMatrixD &mat)
void setTransportMatrix (const TMatrixD &mat, int direction)
void setForwardNoiseMatrix (const TMatrixDSym &mat)
void setBackwardNoiseMatrix (const TMatrixDSym &mat)
void setNoiseMatrix (const TMatrixDSym &mat, int direction)
void setForwardDeltaState (const TVectorD &mat)
void setBackwardDeltaState (const TVectorD &mat)
void setDeltaState (const TVectorD &mat, int direction)
double getForwardSegmentLength () const
double getBackwardSegmentLength () const
const TMatrixD & getForwardTransportMatrix () const
const TMatrixD & getBackwardTransportMatrix () const
const TMatrixD & getTransportMatrix (int direction) const
const TMatrixDSym & getForwardNoiseMatrix () const
const TMatrixDSym & getBackwardNoiseMatrix () const
const TMatrixDSym & getNoiseMatrix (int direction) const
const TVectorD & getForwardDeltaState () const
const TVectorD & getBackwardDeltaState () const
const TVectorD & getDeltaState (int direction) const
void resetForward ()
void resetBackward ()
virtual void Print (Option_t *option="") const override
Public Member Functions inherited from genfit::StateOnPlane
StateOnPlane (const AbsTrackRep *rep=nullptr)
StateOnPlane (const TVectorD &state, const SharedPlanePtr &plane, const AbsTrackRep *rep)
state is defined by the TrackReps parameterization
StateOnPlane (const TVectorD &state, const SharedPlanePtr &plane, const AbsTrackRep *rep, const TVectorD &auxInfo)
StateOnPlane & operator= (StateOnPlane other)
void swap (StateOnPlane &other)
virtual ~StateOnPlane ()
virtual StateOnPlane * clone () const
const TVectorD & getState () const
TVectorD & getState ()
const TVectorD & getAuxInfo () const
TVectorD & getAuxInfo ()
const SharedPlanePtr & getPlane () const
const AbsTrackRep * getRep () const
void setState (const TVectorD &state)
void setPlane (const SharedPlanePtr &plane)
void setStatePlane (const TVectorD &state, const SharedPlanePtr &plane)
void setAuxInfo (const TVectorD &auxInfo)
void setRep (const AbsTrackRep *rep)
double extrapolateToPlane (const SharedPlanePtr &plane, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToLine (const TVector3 &linePoint, const TVector3 &lineDirection, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToPoint (const TVector3 &point, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToPoint (const TVector3 &point, const TMatrixDSym &G, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToCylinder (double radius, const TVector3 &linePoint=TVector3(0., 0., 0.), const TVector3 &lineDirection=TVector3(0., 0., 1.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToCone (double openingAngle, const TVector3 &conePoint=TVector3(0., 0., 0.), const TVector3 &coneDirection=TVector3(0., 0., 1.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToSphere (double radius, const TVector3 &point=TVector3(0., 0., 0.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateBy (double step, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToMeasurement (const AbsMeasurement *measurement, bool stopAtBoundary=false, bool calcJacobianNoise=false)
TVector3 getPos () const
TVector3 getMom () const
TVector3 getDir () const
void getPosMom (TVector3 &pos, TVector3 &mom) const
void getPosDir (TVector3 &pos, TVector3 &dir) const
TVectorD get6DState () const
double getMomMag () const
int getPDG () const
double getCharge () const
double getQop () const
double getMass () const
double getTime () const
void setPosMom (const TVector3 &pos, const TVector3 &mom)
void setPosMom (const TVectorD &state6)
void setChargeSign (double charge)
void setQop (double qop)
void setTime (double time)
Protected Attributes
double forwardSegmentLength_
double backwardSegmentLength_
TMatrixD forwardTransportMatrix_
TMatrixD backwardTransportMatrix_
TMatrixDSym forwardNoiseMatrix_
TMatrixDSym backwardNoiseMatrix_
TVectorD forwardDeltaState_
TVectorD backwardDeltaState_
Protected Attributes inherited from genfit::StateOnPlane
TVectorD state_
TVectorD auxInfo_
SharedPlanePtr sharedPlane_
Detailed Description
StateOnPlane with linearized transport to that ReferenceStateOnPlane from previous and next ReferenceStateOnPlane
Transport matrices describe transport TO that plane. We have transport matrix F, noise matrix N and delta state c. Now, state p and covariance C follow this mathematics:
p = F * p_old + c C = F * C_old * F^T + N
Definition at line 43 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 43 of file ReferenceStateOnPlane.h
Constructor & Destructor Documentation
genfit::ReferenceStateOnPlane::ReferenceStateOnPlane ()
Definition at line 26 of file ReferenceStateOnPlane.cc.
View newest version in sPHENIX GitHub at line 26 of file ReferenceStateOnPlane.cc
genfit::ReferenceStateOnPlane::ReferenceStateOnPlane (const TVectorD & state, const SharedPlanePtr & plane, const AbsTrackRep * rep)
Definition at line 40 of file ReferenceStateOnPlane.cc.
View newest version in sPHENIX GitHub at line 40 of file ReferenceStateOnPlane.cc
genfit::ReferenceStateOnPlane::ReferenceStateOnPlane (const TVectorD & state, const SharedPlanePtr & plane, const AbsTrackRep * rep, const TVectorD & auxInfo)
Definition at line 56 of file ReferenceStateOnPlane.cc.
View newest version in sPHENIX GitHub at line 56 of file ReferenceStateOnPlane.cc
genfit::ReferenceStateOnPlane::ReferenceStateOnPlane (const StateOnPlane & state)
Definition at line 74 of file ReferenceStateOnPlane.cc.
View newest version in sPHENIX GitHub at line 74 of file ReferenceStateOnPlane.cc
References genfit::errorOut.
virtual genfit::ReferenceStateOnPlane::~ReferenceStateOnPlane () inline virtual
Definition at line 60 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 60 of file ReferenceStateOnPlane.h
Member Function Documentation
const TVectorD& genfit::ReferenceStateOnPlane::getBackwardDeltaState () const inline
Definition at line 84 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 84 of file ReferenceStateOnPlane.h
References backwardDeltaState_.
const TMatrixDSym& genfit::ReferenceStateOnPlane::getBackwardNoiseMatrix () const inline
Definition at line 81 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 81 of file ReferenceStateOnPlane.h
References backwardNoiseMatrix_.
double genfit::ReferenceStateOnPlane::getBackwardSegmentLength () const inline
Definition at line 76 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 76 of file ReferenceStateOnPlane.h
References backwardSegmentLength_.
const TMatrixD& genfit::ReferenceStateOnPlane::getBackwardTransportMatrix () const inline
Definition at line 78 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 78 of file ReferenceStateOnPlane.h
References backwardTransportMatrix_.
const TVectorD& genfit::ReferenceStateOnPlane::getDeltaState (int direction) const inline
Definition at line 85 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 85 of file ReferenceStateOnPlane.h
References backwardDeltaState_, and forwardDeltaState_.
Referenced by genfit::KalmanFitterRefTrack::processTrackPoint(), and genfit::KalmanFitterRefTrack::processTrackPointSqrt().
const TVectorD& genfit::ReferenceStateOnPlane::getForwardDeltaState () const inline
Definition at line 83 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 83 of file ReferenceStateOnPlane.h
References forwardDeltaState_.
const TMatrixDSym& genfit::ReferenceStateOnPlane::getForwardNoiseMatrix () const inline
Definition at line 80 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 80 of file ReferenceStateOnPlane.h
References forwardNoiseMatrix_.
double genfit::ReferenceStateOnPlane::getForwardSegmentLength () const inline
Definition at line 75 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 75 of file ReferenceStateOnPlane.h
References forwardSegmentLength_.
Referenced by genfit::Track::checkConsistency(), and genfit::KalmanFitterRefTrack::prepareTrack().
const TMatrixD& genfit::ReferenceStateOnPlane::getForwardTransportMatrix () const inline
Definition at line 77 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 77 of file ReferenceStateOnPlane.h
References forwardTransportMatrix_.
const TMatrixDSym& genfit::ReferenceStateOnPlane::getNoiseMatrix (int direction) const inline
Definition at line 82 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 82 of file ReferenceStateOnPlane.h
References backwardNoiseMatrix_, and forwardNoiseMatrix_.
Referenced by genfit::KalmanFitterRefTrack::processTrackPoint(), and genfit::KalmanFitterRefTrack::processTrackPointSqrt().
const TMatrixD& genfit::ReferenceStateOnPlane::getTransportMatrix (int direction) const inline
Definition at line 79 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 79 of file ReferenceStateOnPlane.h
References backwardTransportMatrix_, and forwardTransportMatrix_.
Referenced by genfit::KalmanFitterRefTrack::processTrackPoint(), and genfit::KalmanFitterRefTrack::processTrackPointSqrt().
StateOnPlane & genfit::ReferenceStateOnPlane::operator= (ReferenceStateOnPlane other)
Definition at line 90 of file ReferenceStateOnPlane.cc.
View newest version in sPHENIX GitHub at line 90 of file ReferenceStateOnPlane.cc
References swap().
void genfit::ReferenceStateOnPlane::Print (Option_t * option = "") const override virtual
Reimplemented from genfit::StateOnPlane.
Definition at line 129 of file ReferenceStateOnPlane.cc.
View newest version in sPHENIX GitHub at line 129 of file ReferenceStateOnPlane.cc
References backwardDeltaState_, backwardNoiseMatrix_, backwardSegmentLength_, backwardTransportMatrix_, forwardDeltaState_, forwardNoiseMatrix_, forwardSegmentLength_, forwardTransportMatrix_, genfit::StateOnPlane::Print(), and genfit::printOut.
void genfit::ReferenceStateOnPlane::resetBackward ()
Definition at line 121 of file ReferenceStateOnPlane.cc.
View newest version in sPHENIX GitHub at line 121 of file ReferenceStateOnPlane.cc
References backwardDeltaState_, backwardNoiseMatrix_, backwardSegmentLength_, and backwardTransportMatrix_.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack().
void genfit::ReferenceStateOnPlane::resetForward ()
Definition at line 114 of file ReferenceStateOnPlane.cc.
View newest version in sPHENIX GitHub at line 114 of file ReferenceStateOnPlane.cc
References forwardDeltaState_, forwardNoiseMatrix_, forwardSegmentLength_, and forwardTransportMatrix_.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack().
void genfit::ReferenceStateOnPlane::setBackwardDeltaState (const TVectorD & mat) inline
Definition at line 71 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 71 of file ReferenceStateOnPlane.h
References backwardDeltaState_.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack(), and setDeltaState().
void genfit::ReferenceStateOnPlane::setBackwardNoiseMatrix (const TMatrixDSym & mat) inline
Definition at line 68 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 68 of file ReferenceStateOnPlane.h
References backwardNoiseMatrix_.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack(), and setNoiseMatrix().
void genfit::ReferenceStateOnPlane::setBackwardSegmentLength (double len) inline
Definition at line 63 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 63 of file ReferenceStateOnPlane.h
References backwardSegmentLength_.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack().
void genfit::ReferenceStateOnPlane::setBackwardTransportMatrix (const TMatrixD & mat) inline
Definition at line 65 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 65 of file ReferenceStateOnPlane.h
References backwardTransportMatrix_.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack(), and setTransportMatrix().
void genfit::ReferenceStateOnPlane::setDeltaState (const TVectorD & mat, int direction) inline
Definition at line 72 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 72 of file ReferenceStateOnPlane.h
References setBackwardDeltaState(), and setForwardDeltaState().
void genfit::ReferenceStateOnPlane::setForwardDeltaState (const TVectorD & mat) inline
Definition at line 70 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 70 of file ReferenceStateOnPlane.h
References forwardDeltaState_.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack(), and setDeltaState().
void genfit::ReferenceStateOnPlane::setForwardNoiseMatrix (const TMatrixDSym & mat) inline
Definition at line 67 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 67 of file ReferenceStateOnPlane.h
References forwardNoiseMatrix_.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack(), and setNoiseMatrix().
void genfit::ReferenceStateOnPlane::setForwardSegmentLength (double len) inline
Definition at line 62 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 62 of file ReferenceStateOnPlane.h
References forwardSegmentLength_.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack().
void genfit::ReferenceStateOnPlane::setForwardTransportMatrix (const TMatrixD & mat) inline
Definition at line 64 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 64 of file ReferenceStateOnPlane.h
References forwardTransportMatrix_.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack(), and setTransportMatrix().
void genfit::ReferenceStateOnPlane::setNoiseMatrix (const TMatrixDSym & mat, int direction) inline
Definition at line 69 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 69 of file ReferenceStateOnPlane.h
References setBackwardNoiseMatrix(), and setForwardNoiseMatrix().
void genfit::ReferenceStateOnPlane::setTransportMatrix (const TMatrixD & mat, int direction) inline
Definition at line 66 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 66 of file ReferenceStateOnPlane.h
References setBackwardTransportMatrix(), and setForwardTransportMatrix().
void genfit::ReferenceStateOnPlane::swap (ReferenceStateOnPlane & other)
Definition at line 95 of file ReferenceStateOnPlane.cc.
View newest version in sPHENIX GitHub at line 95 of file ReferenceStateOnPlane.cc
References backwardDeltaState_, backwardNoiseMatrix_, backwardSegmentLength_, backwardTransportMatrix_, forwardDeltaState_, forwardNoiseMatrix_, forwardSegmentLength_, forwardTransportMatrix_, genfit::StateOnPlane::swap(), and boost::swap().
Referenced by operator=().
Member Data Documentation
TVectorD genfit::ReferenceStateOnPlane::backwardDeltaState_ protected
c
Definition at line 101 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 101 of file ReferenceStateOnPlane.h
Referenced by getBackwardDeltaState(), getDeltaState(), Print(), resetBackward(), setBackwardDeltaState(), and swap().
TMatrixDSym genfit::ReferenceStateOnPlane::backwardNoiseMatrix_ protected
noise matrix N for transport from next referenceState
Definition at line 99 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 99 of file ReferenceStateOnPlane.h
Referenced by getBackwardNoiseMatrix(), getNoiseMatrix(), Print(), resetBackward(), setBackwardNoiseMatrix(), and swap().
double genfit::ReferenceStateOnPlane::backwardSegmentLength_ protected
Segment length from next referenceState
Definition at line 95 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 95 of file ReferenceStateOnPlane.h
Referenced by getBackwardSegmentLength(), Print(), resetBackward(), setBackwardSegmentLength(), and swap().
TMatrixD genfit::ReferenceStateOnPlane::backwardTransportMatrix_ protected
transport matrix F from next referenceState
Definition at line 97 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 97 of file ReferenceStateOnPlane.h
Referenced by getBackwardTransportMatrix(), getTransportMatrix(), Print(), resetBackward(), setBackwardTransportMatrix(), and swap().
TVectorD genfit::ReferenceStateOnPlane::forwardDeltaState_ protected
c
Definition at line 100 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 100 of file ReferenceStateOnPlane.h
Referenced by getDeltaState(), getForwardDeltaState(), Print(), resetForward(), setForwardDeltaState(), and swap().
TMatrixDSym genfit::ReferenceStateOnPlane::forwardNoiseMatrix_ protected
noise matrix N for transport from previous referenceState
Definition at line 98 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 98 of file ReferenceStateOnPlane.h
Referenced by getForwardNoiseMatrix(), getNoiseMatrix(), Print(), resetForward(), setForwardNoiseMatrix(), and swap().
double genfit::ReferenceStateOnPlane::forwardSegmentLength_ protected
Segment length from previous referenceState
Definition at line 94 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 94 of file ReferenceStateOnPlane.h
Referenced by getForwardSegmentLength(), Print(), resetForward(), setForwardSegmentLength(), and swap().
TMatrixD genfit::ReferenceStateOnPlane::forwardTransportMatrix_ protected
transport matrix F from previous referenceState
Definition at line 96 of file ReferenceStateOnPlane.h.
View newest version in sPHENIX GitHub at line 96 of file ReferenceStateOnPlane.h
Referenced by getForwardTransportMatrix(), getTransportMatrix(), Print(), resetForward(), setForwardTransportMatrix(), and swap().
The documentation for this class was generated from the following files:
GenFit/blob/master/fitters/include/ReferenceStateOnPlane.h
GenFit/blob/master/fitters/src/ReferenceStateOnPlane.cc