Analysis Software: GenFit/blob/master/test/streamerTest/main.cc File Reference
main.cc File Reference
#include <ConstField.h>
#include <Exception.h>
#include <FieldManager.h>
#include <KalmanFitterRefTrack.h>
#include <StateOnPlane.h>
#include <Track.h>
#include <TrackPoint.h>
#include <MaterialEffects.h>
#include <RKTrackRep.h>
#include <TGeoMaterialInterface.h>
#include <EventDisplay.h>
#include <HelixTrackModel.h>
#include <MeasurementCreator.h>
#include <TDatabasePDG.h>
#include <TEveManager.h>
#include <TGeoManager.h>
#include <TRandom.h>
#include <TVector3.h>
#include <vector>
#include <TMath.h>
#include <TFile.h>
#include <TTree.h>
Macros
#define FILENAME "/tmp/streamerTest.root"
Functions
bool emptyTrackTest ()
int main ()
Variables
constexpr bool verbose = false
Macro Definition Documentation
#define FILENAME "/tmp/streamerTest.root"
Definition at line 35 of file main.cc.
View newest version in sPHENIX GitHub at line 35 of file main.cc
Referenced by emptyTrackTest(), and main().
Function Documentation
bool emptyTrackTest ()
Definition at line 39 of file main.cc.
View newest version in sPHENIX GitHub at line 39 of file main.cc
References genfit::Track::checkConsistency(), FILENAME, and t.
Referenced by main().
int main ()
Definition at line 71 of file main.cc.
View newest version in sPHENIX GitHub at line 71 of file main.cc
References genfit::Track::checkConsistency(), genfit::MeasurementCreator::create(), emptyTrackTest(), FILENAME, genfit::AbsTrackRep::get6DStateCov(), genfit::MeasuredStateOnPlane::getCov(), genfit::Exception::getExcString(), genfit::Track::getFittedState(), genfit::MaterialEffects::getInstance(), genfit::FieldManager::getInstance(), genfit::StateOnPlane::getPlane(), genfit::StateOnPlane::getState(), i, genfit::MaterialEffects::init(), genfit::FieldManager::init(), genfit::Track::insertPoint(), nEvents, pos, genfit::DetPlane::Print(), genfit::AbsFitter::processTrack(), genfit::Track::prune(), genfit::AbsTrackRep::setPosMomCov(), genfit::TrackPoint::setScatterer(), genfit::MeasurementCreator::setTrackModel(), verbose, and genfit::Exception::what().
Variable Documentation
constexpr bool verbose = false
Definition at line 37 of file main.cc.
View newest version in sPHENIX GitHub at line 37 of file main.cc
Referenced by checkErrorPropagation(), checkExtrapolateBy(), checkExtrapolateToCylinder(), checkExtrapolateToLine(), checkExtrapolateToPoint(), checkExtrapolateToSphere(), checkSetGetPosMom(), checkStopAtBoundary(), compareForthBackExtrapolation(), compareForthBackJacNoise(), compareMatrices(), PHRandomSeed::GetSeed(), isCovMatrix(), main(), and PHRandomSeed::Verbosity().