Analysis Software: GPUTPCTrackParam Class Reference
GPUTPCTrackParam Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/GPUTPCTrackParam.h>
Classes
struct GPUTPCTrackFitParam
Public Member Functions
const GPUTPCBaseTrackParam & GetParam () const
void SetParam (const GPUTPCBaseTrackParam &v)
void InitParam ()
float X () const
float Y () const
float Z () const
float SinPhi () const
float DzDs () const
float QPt () const
float ZOffset () const
float SignCosPhi () const
float Chi2 () const
int NDF () const
float Err2Y () const
float Err2Z () const
float Err2SinPhi () const
float Err2DzDs () const
float Err2QPt () const
float GetX () const
float GetY () const
float GetZ () const
float GetSinPhi () const
float GetDzDs () const
float GetQPt () const
float GetSignCosPhi () const
float GetChi2 () const
int GetNDF () const
float GetKappa (float Bz) const
float GetCosPhi () const
float GetErr2Y () const
float GetErr2Z () const
float GetErr2SinPhi () const
float GetErr2DzDs () const
float GetErr2QPt () const
const float * Par () const
const float * Cov () const
const float * GetPar () const
float GetPar (int i) const
const float * GetCov () const
float GetCov (int i) const
void SetPar (int i, float v)
void SetCov (int i, float v)
void SetX (float v)
void SetY (float v)
void SetZ (float v)
void SetSinPhi (float v)
void SetDzDs (float v)
void SetQPt (float v)
void SetZOffset (float v)
void SetSignCosPhi (float v)
void SetChi2 (float v)
void SetNDF (int v)
float GetDist2 (const GPUTPCTrackParam &t) const
float GetDistXZ2 (const GPUTPCTrackParam &t) const
float GetS (float x, float y, float Bz) const
void GetDCAPoint (float x, float y, float z, float &px, float &py, float &pz, float Bz) const
bool TransportToX (float x, float Bz, float maxSinPhi=GPUCA_MAX_SIN_PHI)
bool TransportToXWithMaterial (float x, float Bz, float maxSinPhi=GPUCA_MAX_SIN_PHI)
bool TransportToX (float x, GPUTPCTrackLinearisation &t0, float Bz, float maxSinPhi=GPUCA_MAX_SIN_PHI, float *DL=nullptr)
bool TransportToX (float x, float sinPhi0, float cosPhi0, float Bz, float maxSinPhi=GPUCA_MAX_SIN_PHI)
bool TransportToXWithMaterial (float x, GPUTPCTrackLinearisation &t0, GPUTPCTrackFitParam &par, float Bz, float maxSinPhi=GPUCA_MAX_SIN_PHI)
bool TransportToXWithMaterial (float x, GPUTPCTrackFitParam &par, float Bz, float maxSinPhi=GPUCA_MAX_SIN_PHI)
void CalculateFitParameters (GPUTPCTrackFitParam &par, float mass=0.13957f)
bool CorrectForMeanMaterial (float xOverX0, float xTimesRho, const GPUTPCTrackFitParam &par)
bool Rotate (float alpha, float maxSinPhi=GPUCA_MAX_SIN_PHI)
bool Rotate (float alpha, GPUTPCTrackLinearisation &t0, float maxSinPhi=GPUCA_MAX_SIN_PHI)
bool Filter (float y, float z, float err2Y, float err2Z, float maxSinPhi=GPUCA_MAX_SIN_PHI, bool paramOnly=false)
bool CheckNumericalQuality () const
void Print () const
Static Public Member Functions
static float ApproximateBetheBloch (float beta2)
static float BetheBlochGeant (float bg, float kp0=2.33f, float kp1=0.20f, float kp2=3.00f, float kp3=173e-9f, float kp4=0.49848f)
static float BetheBlochSolid (float bg)
static float BetheBlochGas (float bg)
Private Attributes
GPUTPCBaseTrackParam mParam
GPUCA_GPUCODE.
float mC [15]
float mSignCosPhi
float mChi2
int mNDF
Detailed Description
GPUTPCTrackParam class describes the track parametrisation which is used by the GPUTPCTracker slice tracker.
Definition at line 28 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 28 of file GPUTPCTrackParam.h
Member Function Documentation
float GPUTPCTrackParam::ApproximateBetheBloch (float beta2) static
Definition at line 407 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 407 of file GPUTPCTrackParam.cxx
Referenced by CalculateFitParameters().
float GPUTPCTrackParam::BetheBlochGas (float bg) static
Definition at line 389 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 389 of file GPUTPCTrackParam.cxx
References BetheBlochGeant(), and x0.
float GPUTPCTrackParam::BetheBlochGeant (float bg, float kp0 = 2.33f, float kp1 = 0.20f, float kp2 = 3.00f, float kp3 = 173e-9f, float kp4 = 0.49848f) static
Definition at line 338 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 338 of file GPUTPCTrackParam.cxx
References r, x, and x0.
Referenced by BetheBlochGas(), and BetheBlochSolid().
float GPUTPCTrackParam::BetheBlochSolid (float bg) static
Definition at line 377 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 377 of file GPUTPCTrackParam.cxx
References BetheBlochGeant().
void GPUTPCTrackParam::CalculateFitParameters (GPUTPCTrackFitParam & par, float mass = 0.13957f)
Definition at line 424 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 424 of file GPUTPCTrackParam.cxx
References ApproximateBetheBloch(), GPUTPCTrackParam::GPUTPCTrackFitParam::bethe, GPUTPCTrackParam::GPUTPCTrackFitParam::e, GPUTPCTrackParam::GPUTPCTrackFitParam::EP2, GetPar(), k2, GPUTPCTrackParam::GPUTPCTrackFitParam::k22, GPUTPCTrackParam::GPUTPCTrackFitParam::k33, GPUTPCTrackParam::GPUTPCTrackFitParam::k43, GPUTPCTrackParam::GPUTPCTrackFitParam::k44, mC, GPUTPCTrackParam::GPUTPCTrackFitParam::sigmadE2, and GPUTPCTrackParam::GPUTPCTrackFitParam::theta2.
Referenced by TransportToXWithMaterial().
bool GPUTPCTrackParam::CheckNumericalQuality () const
Definition at line 671 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 671 of file GPUTPCTrackParam.cxx
References c, Cov(), GetX(), GPUCA_MAX_SIN_PHI, i, mChi2, mSignCosPhi, Par(), QPt(), and SinPhi().
float GPUTPCTrackParam::Chi2 () const inline
Definition at line 47 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 47 of file GPUTPCTrackParam.h
References mChi2.
bool GPUTPCTrackParam::CorrectForMeanMaterial (float xOverX0, float xTimesRho, const GPUTPCTrackFitParam & par)
Definition at line 458 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 458 of file GPUTPCTrackParam.cxx
References GPUTPCTrackParam::GPUTPCTrackFitParam::bethe, GPUTPCTrackParam::GPUTPCTrackFitParam::e, GPUTPCTrackParam::GPUTPCTrackFitParam::EP2, GetPar(), GPUTPCTrackParam::GPUTPCTrackFitParam::k22, GPUTPCTrackParam::GPUTPCTrackFitParam::k33, GPUTPCTrackParam::GPUTPCTrackFitParam::k43, GPUTPCTrackParam::GPUTPCTrackFitParam::k44, mC, SetPar(), GPUTPCTrackParam::GPUTPCTrackFitParam::sigmadE2, and GPUTPCTrackParam::GPUTPCTrackFitParam::theta2.
Referenced by TransportToXWithMaterial().
const float* GPUTPCTrackParam::Cov () const inline
Definition at line 76 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 76 of file GPUTPCTrackParam.h
References mC.
Referenced by CheckNumericalQuality().
float GPUTPCTrackParam::DzDs () const inline
Definition at line 43 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 43 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::DzDs(), and mParam.
Referenced by Rotate(), and TransportToX().
float GPUTPCTrackParam::Err2DzDs () const inline
Definition at line 53 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 53 of file GPUTPCTrackParam.h
References mC.
float GPUTPCTrackParam::Err2QPt () const inline
Definition at line 54 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 54 of file GPUTPCTrackParam.h
References mC.
float GPUTPCTrackParam::Err2SinPhi () const inline
Definition at line 52 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 52 of file GPUTPCTrackParam.h
References mC.
float GPUTPCTrackParam::Err2Y () const inline
Definition at line 50 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 50 of file GPUTPCTrackParam.h
References mC.
float GPUTPCTrackParam::Err2Z () const inline
Definition at line 51 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 51 of file GPUTPCTrackParam.h
References mC.
bool GPUTPCTrackParam::Filter (float y, float z, float err2Y, float err2Z, float maxSinPhi = GPUCA_MAX_SIN_PHI, bool paramOnly = false)
Definition at line 610 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 610 of file GPUTPCTrackParam.cxx
References GetPar(), mC, mChi2, mNDF, SetPar(), and z1.
Referenced by PHCASeeding::Process().
float GPUTPCTrackParam::GetChi2 () const inline
Definition at line 63 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 63 of file GPUTPCTrackParam.h
References mChi2.
float GPUTPCTrackParam::GetCosPhi () const inline
Definition at line 67 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 67 of file GPUTPCTrackParam.h
References mSignCosPhi, and SinPhi().
Referenced by GetDCAPoint(), GetS(), and Rotate().
const float* GPUTPCTrackParam::GetCov () const inline
Definition at line 80 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 80 of file GPUTPCTrackParam.h
References mC.
float GPUTPCTrackParam::GetCov (int i) const inline
Definition at line 81 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 81 of file GPUTPCTrackParam.h
References i, and mC.
void GPUTPCTrackParam::GetDCAPoint (float x, float y, float z, float & px, float & py, float & pz, float Bz) const
Definition at line 64 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 64 of file GPUTPCTrackParam.cxx
References KFPMath::a, dx, dy, GetCosPhi(), GetDzDs(), GetKappa(), GetS(), GetSinPhi(), GetX(), GetY(), GetZ(), k, M_PI, round(), s, and x0.
float GPUTPCTrackParam::GetDist2 (const GPUTPCTrackParam & t) const
Definition at line 29 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 29 of file GPUTPCTrackParam.cxx
References dx, dy, GetX(), GetY(), and GetZ().
float GPUTPCTrackParam::GetDistXZ2 (const GPUTPCTrackParam & t) const
Definition at line 39 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 39 of file GPUTPCTrackParam.cxx
References dx, GetX(), and GetZ().
float GPUTPCTrackParam::GetDzDs () const inline
Definition at line 60 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 60 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetDzDs(), and mParam.
Referenced by GetDCAPoint(), and Print().
float GPUTPCTrackParam::GetErr2DzDs () const inline
Definition at line 72 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 72 of file GPUTPCTrackParam.h
References mC.
Referenced by Print().
float GPUTPCTrackParam::GetErr2QPt () const inline
Definition at line 73 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 73 of file GPUTPCTrackParam.h
References mC.
Referenced by Print(), and PHCASeeding::Process().
float GPUTPCTrackParam::GetErr2SinPhi () const inline
Definition at line 71 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 71 of file GPUTPCTrackParam.h
References mC.
Referenced by Print().
float GPUTPCTrackParam::GetErr2Y () const inline
Definition at line 69 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 69 of file GPUTPCTrackParam.h
References mC.
Referenced by Print(), and PHCASeeding::Process().
float GPUTPCTrackParam::GetErr2Z () const inline
Definition at line 70 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 70 of file GPUTPCTrackParam.h
References mC.
Referenced by Print(), and PHCASeeding::Process().
float GPUTPCTrackParam::GetKappa (float Bz) const inline
Definition at line 66 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 66 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetKappa(), and mParam.
Referenced by GetDCAPoint(), GetS(), and PHCASeeding::Process().
int GPUTPCTrackParam::GetNDF () const inline
Definition at line 64 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 64 of file GPUTPCTrackParam.h
References mNDF.
Referenced by PHCASeeding::Process().
const float* GPUTPCTrackParam::GetPar () const inline
Definition at line 78 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 78 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetPar(), and mParam.
Referenced by CalculateFitParameters(), CorrectForMeanMaterial(), Filter(), and TransportToX().
float GPUTPCTrackParam::GetPar (int i) const inline
Definition at line 79 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 79 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetPar(), and mParam.
const GPUTPCBaseTrackParam& GPUTPCTrackParam::GetParam () const inline
Definition at line 35 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 35 of file GPUTPCTrackParam.h
References mParam.
float GPUTPCTrackParam::GetQPt () const inline
Definition at line 61 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 61 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetQPt(), and mParam.
Referenced by Print(), and PHCASeeding::Process().
float GPUTPCTrackParam::GetS (float x, float y, float Bz) const
Definition at line 48 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 48 of file GPUTPCTrackParam.cxx
References GetCosPhi(), GetKappa(), GetSinPhi(), GetX(), GetY(), and k.
Referenced by GetDCAPoint().
float GPUTPCTrackParam::GetSignCosPhi () const inline
Definition at line 62 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 62 of file GPUTPCTrackParam.h
References mSignCosPhi.
Referenced by Print().
float GPUTPCTrackParam::GetSinPhi () const inline
Definition at line 59 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 59 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetSinPhi(), and mParam.
Referenced by GetDCAPoint(), GetS(), Print(), and PHCASeeding::Process().
float GPUTPCTrackParam::GetX () const inline
Definition at line 56 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 56 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetX(), and mParam.
Referenced by CheckNumericalQuality(), GetDCAPoint(), GetDist2(), GetDistXZ2(), GetS(), Print(), and PHCASeeding::Process().
float GPUTPCTrackParam::GetY () const inline
Definition at line 57 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 57 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetY(), and mParam.
Referenced by GetDCAPoint(), GetDist2(), GetS(), Print(), and PHCASeeding::Process().
float GPUTPCTrackParam::GetZ () const inline
Definition at line 58 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 58 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetZ(), and mParam.
Referenced by GetDCAPoint(), GetDist2(), GetDistXZ2(), Print(), and PHCASeeding::Process().
void GPUTPCTrackParam::InitParam () inline
Definition at line 147 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 147 of file GPUTPCTrackParam.h
References SetChi2(), SetCov(), SetDzDs(), SetNDF(), SetQPt(), SetSignCosPhi(), SetSinPhi(), and SetZOffset().
Referenced by PHCASeeding::Process().
int GPUTPCTrackParam::NDF () const inline
Definition at line 48 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 48 of file GPUTPCTrackParam.h
References mNDF.
const float* GPUTPCTrackParam::Par () const inline
Definition at line 75 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 75 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::Par().
Referenced by CheckNumericalQuality().
void GPUTPCTrackParam::Print () const
Definition at line 711 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 711 of file GPUTPCTrackParam.cxx
References GetDzDs(), GetErr2DzDs(), GetErr2QPt(), GetErr2SinPhi(), GetErr2Y(), GetErr2Z(), GetQPt(), GetSignCosPhi(), GetSinPhi(), GetX(), GetY(), and GetZ().
float GPUTPCTrackParam::QPt () const inline
Definition at line 44 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 44 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::QPt().
Referenced by CheckNumericalQuality(), Rotate(), and TransportToX().
bool GPUTPCTrackParam::Rotate (float alpha, float maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 507 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 507 of file GPUTPCTrackParam.cxx
References DzDs(), GetCosPhi(), mC, QPt(), SetDzDs(), SetQPt(), SetSignCosPhi(), SetSinPhi(), SetX(), SetY(), SinPhi(), X(), x, Y(), and y.
Referenced by PHCASeeding::Process().
bool GPUTPCTrackParam::Rotate (float alpha, GPUTPCTrackLinearisation & t0, float maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 564 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 564 of file GPUTPCTrackParam.cxx
References GPUTPCTrackLinearisation::CosPhi(), d, mC, GPUTPCTrackLinearisation::SetCosPhi(), GPUTPCTrackLinearisation::SetSinPhi(), SetSinPhi(), SetX(), SetY(), SinPhi(), GPUTPCTrackLinearisation::SinPhi(), X(), x0, and Y().
void GPUTPCTrackParam::SetChi2 (float v) inline
Definition at line 94 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 94 of file GPUTPCTrackParam.h
References mChi2, and v.
Referenced by InitParam().
void GPUTPCTrackParam::SetCov (int i, float v) inline
Definition at line 84 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 84 of file GPUTPCTrackParam.h
References i, mC, and v.
Referenced by InitParam().
void GPUTPCTrackParam::SetDzDs (float v) inline
Definition at line 90 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 90 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetDzDs().
Referenced by InitParam(), PHCASeeding::Process(), and Rotate().
void GPUTPCTrackParam::SetNDF (int v) inline
Definition at line 95 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 95 of file GPUTPCTrackParam.h
References mNDF, and v.
Referenced by InitParam().
void GPUTPCTrackParam::SetPar (int i, float v) inline
Definition at line 83 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 83 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetPar().
Referenced by CorrectForMeanMaterial(), Filter(), and TransportToX().
void GPUTPCTrackParam::SetParam (const GPUTPCBaseTrackParam & v) inline
Definition at line 36 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 36 of file GPUTPCTrackParam.h
References mParam, and v.
void GPUTPCTrackParam::SetQPt (float v) inline
Definition at line 91 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 91 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetQPt().
Referenced by InitParam(), and Rotate().
void GPUTPCTrackParam::SetSignCosPhi (float v) inline
Definition at line 93 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 93 of file GPUTPCTrackParam.h
References mSignCosPhi.
Referenced by InitParam(), and Rotate().
void GPUTPCTrackParam::SetSinPhi (float v) inline
Definition at line 89 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 89 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetSinPhi().
Referenced by InitParam(), PHCASeeding::Process(), and Rotate().
void GPUTPCTrackParam::SetX (float v) inline
Definition at line 86 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 86 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetX().
Referenced by PHCASeeding::Process(), Rotate(), and TransportToX().
void GPUTPCTrackParam::SetY (float v) inline
Definition at line 87 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 87 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetY().
Referenced by PHCASeeding::Process(), and Rotate().
void GPUTPCTrackParam::SetZ (float v) inline
Definition at line 88 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 88 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetZ().
Referenced by PHCASeeding::Process().
void GPUTPCTrackParam::SetZOffset (float v) inline
Definition at line 92 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 92 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetZOffset().
Referenced by InitParam().
float GPUTPCTrackParam::SignCosPhi () const inline
Definition at line 46 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 46 of file GPUTPCTrackParam.h
References mSignCosPhi.
Referenced by GPUTPCTrackLinearisation::GPUTPCTrackLinearisation().
float GPUTPCTrackParam::SinPhi () const inline
Definition at line 42 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 42 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SinPhi().
Referenced by CheckNumericalQuality(), GetCosPhi(), Rotate(), and TransportToX().
bool GPUTPCTrackParam::TransportToX (float x, float Bz, float maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 294 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 294 of file GPUTPCTrackParam.cxx
Referenced by PHCASeeding::Process(), and TransportToXWithMaterial().
bool GPUTPCTrackParam::TransportToX (float x, GPUTPCTrackLinearisation & t0, float Bz, float maxSinPhi = GPUCA_MAX_SIN_PHI, float * DL = nullptr)
Definition at line 94 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 94 of file GPUTPCTrackParam.cxx
References GPUTPCTrackLinearisation::CosPhi(), d, dx, dy, GPUTPCTrackLinearisation::DzDs(), GetPar(), h2, k, mC, GPUTPCTrackLinearisation::QPt(), GPUTPCTrackLinearisation::SetCosPhi(), SetPar(), GPUTPCTrackLinearisation::SetSinPhi(), SetX(), GPUTPCTrackLinearisation::SinPhi(), X(), Y(), and Z().
bool GPUTPCTrackParam::TransportToX (float x, float sinPhi0, float cosPhi0, float Bz, float maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 214 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 214 of file GPUTPCTrackParam.cxx
References dx, DzDs(), GetPar(), h2, max, mC, QPt(), SetPar(), SetX(), SinPhi(), and X().
bool GPUTPCTrackParam::TransportToXWithMaterial (float x, float Bz, float maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 326 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 326 of file GPUTPCTrackParam.cxx
References CalculateFitParameters().
Referenced by TransportToXWithMaterial().
bool GPUTPCTrackParam::TransportToXWithMaterial (float x, GPUTPCTrackLinearisation & t0, GPUTPCTrackFitParam & par, float Bz, float maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 301 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 301 of file GPUTPCTrackParam.cxx
References CorrectForMeanMaterial(), and TransportToX().
bool GPUTPCTrackParam::TransportToXWithMaterial (float x, GPUTPCTrackFitParam & par, float Bz, float maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 318 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 318 of file GPUTPCTrackParam.cxx
References TransportToXWithMaterial().
float GPUTPCTrackParam::X () const inline
Definition at line 39 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 39 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::X().
Referenced by Rotate(), and TransportToX().
float GPUTPCTrackParam::Y () const inline
Definition at line 40 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 40 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::Y().
Referenced by Rotate(), and TransportToX().
float GPUTPCTrackParam::Z () const inline
Definition at line 41 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 41 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::Z().
Referenced by TransportToX().
float GPUTPCTrackParam::ZOffset () const inline
Definition at line 45 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 45 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::ZOffset().
Member Data Documentation
float GPUTPCTrackParam::mC[15] private
Definition at line 141 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 141 of file GPUTPCTrackParam.h
Referenced by CalculateFitParameters(), CorrectForMeanMaterial(), Cov(), Err2DzDs(), Err2QPt(), Err2SinPhi(), Err2Y(), Err2Z(), Filter(), GetCov(), GetErr2DzDs(), GetErr2QPt(), GetErr2SinPhi(), GetErr2Y(), GetErr2Z(), Rotate(), SetCov(), and TransportToX().
float GPUTPCTrackParam::mChi2 private
Definition at line 143 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 143 of file GPUTPCTrackParam.h
Referenced by CheckNumericalQuality(), Chi2(), Filter(), GetChi2(), and SetChi2().
int GPUTPCTrackParam::mNDF private
Definition at line 144 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 144 of file GPUTPCTrackParam.h
Referenced by Filter(), GetNDF(), NDF(), and SetNDF().
GPUTPCBaseTrackParam GPUTPCTrackParam::mParam private
GPUCA_GPUCODE.
Definition at line 135 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 135 of file GPUTPCTrackParam.h
Referenced by DzDs(), GetDzDs(), GetKappa(), GetPar(), GetParam(), GetQPt(), GetSinPhi(), GetX(), GetY(), GetZ(), Par(), QPt(), SetDzDs(), SetPar(), SetParam(), SetQPt(), SetSinPhi(), SetX(), SetY(), SetZ(), SetZOffset(), SinPhi(), X(), Y(), Z(), and ZOffset().
float GPUTPCTrackParam::mSignCosPhi private
Definition at line 142 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 142 of file GPUTPCTrackParam.h
Referenced by CheckNumericalQuality(), GetCosPhi(), GetSignCosPhi(), SetSignCosPhi(), and SignCosPhi().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/GPUTPCTrackParam.h
coresoftware/blob/master/offline/packages/trackreco/GPUTPCTrackParam.cxx