Analysis Software: genfit::TrackCandHit Class Reference
genfit::TrackCandHit Class Reference
Hit object for use in TrackCand. Provides IDs and sorting parameters.
#include <GenFit/blob/master/core/include/TrackCandHit.h>
Public Member Functions
TrackCandHit (int detId=-1, int hitId=-1, int planeId=-1, double sortingParameter=0.)
virtual ~TrackCandHit ()
virtual TrackCandHit * clone () const
int getDetId () const
int getHitId () const
int getPlaneId () const
double getSortingParameter () const
void setSortingParameter (double sortingParameter)
virtual void Print (Option_t *option="") const
Protected Member Functions
TrackCandHit (const TrackCandHit &other)
protect from calling copy c'tor from outside the class. Use clone() if you want a copy!
TrackCandHit & operator= (const TrackCandHit &)
protect from calling assignment operator from outside the class. Use clone() instead!
Protected Attributes
int detId_
int hitId_
int planeId_
double sortingParameter_
Friends
bool operator== (const TrackCandHit &lhs, const TrackCandHit &rhs)
Equality operator. Does not check sortingParameter.
bool operator!= (const TrackCandHit &lhs, const TrackCandHit &rhs)
bool operator< (const TrackCandHit &lhs, const TrackCandHit &rhs)
Compare sortingParameter, needed for sorting.
Detailed Description
Hit object for use in TrackCand. Provides IDs and sorting parameters.
Definition at line 34 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 34 of file TrackCandHit.h
Constructor & Destructor Documentation
genfit::TrackCandHit::TrackCandHit (int detId = -1, int hitId = -1, int planeId = -1, double sortingParameter = 0.)
Definition at line 25 of file TrackCandHit.cc.
View newest version in sPHENIX GitHub at line 25 of file TrackCandHit.cc
Referenced by clone().
virtual genfit::TrackCandHit::~TrackCandHit () inline virtual
Definition at line 43 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 43 of file TrackCandHit.h
genfit::TrackCandHit::TrackCandHit (const TrackCandHit & other) inline protected
protect from calling copy c'tor from outside the class. Use clone() if you want a copy!
Definition at line 75 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 75 of file TrackCandHit.h
Member Function Documentation
virtual TrackCandHit* genfit::TrackCandHit::clone () const inline virtual
Reimplemented in genfit::WireTrackCandHit.
Definition at line 45 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 45 of file TrackCandHit.h
References TrackCandHit().
Referenced by genfit::TrackCand::append().
int genfit::TrackCandHit::getDetId () const inline
Definition at line 48 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 48 of file TrackCandHit.h
References detId_.
Referenced by genfit::MeasurementFactory< measurement_T >::createMany(), and genfit::mySpacepointMeasurement::mySpacepointMeasurement().
int genfit::TrackCandHit::getHitId () const inline
Definition at line 49 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 49 of file TrackCandHit.h
References hitId_.
Referenced by genfit::MeasurementFactory< measurement_T >::createMany(), and genfit::mySpacepointMeasurement::mySpacepointMeasurement().
int genfit::TrackCandHit::getPlaneId () const inline
Definition at line 50 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 50 of file TrackCandHit.h
References planeId_.
double genfit::TrackCandHit::getSortingParameter () const inline
Definition at line 51 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 51 of file TrackCandHit.h
References sortingParameter_.
Referenced by genfit::Track::createMeasurements().
TrackCandHit& genfit::TrackCandHit::operator= (const TrackCandHit &) protected
protect from calling assignment operator from outside the class. Use clone() instead!
void genfit::TrackCandHit::Print (Option_t * option = "") const virtual
Reimplemented in genfit::WireTrackCandHit.
Definition at line 38 of file TrackCandHit.cc.
View newest version in sPHENIX GitHub at line 38 of file TrackCandHit.cc
References detId_, hitId_, planeId_, genfit::printOut, and sortingParameter_.
void genfit::TrackCandHit::setSortingParameter (double sortingParameter) inline
Definition at line 54 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 54 of file TrackCandHit.h
References sortingParameter_.
Friends And Related Function Documentation
bool operator!= (const TrackCandHit & lhs, const TrackCandHit & rhs) friend
Definition at line 62 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 62 of file TrackCandHit.h
bool operator< (const TrackCandHit & lhs, const TrackCandHit & rhs) friend
Compare sortingParameter, needed for sorting.
Definition at line 68 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 68 of file TrackCandHit.h
bool operator== (const TrackCandHit & lhs, const TrackCandHit & rhs) friend
Equality operator. Does not check sortingParameter.
Definition at line 46 of file TrackCandHit.cc.
View newest version in sPHENIX GitHub at line 46 of file TrackCandHit.cc
Member Data Documentation
int genfit::TrackCandHit::detId_ protected
Definition at line 82 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 82 of file TrackCandHit.h
Referenced by getDetId(), genfit::operator==(), Print(), and genfit::WireTrackCandHit::Print().
int genfit::TrackCandHit::hitId_ protected
Definition at line 83 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 83 of file TrackCandHit.h
Referenced by getHitId(), genfit::operator==(), Print(), and genfit::WireTrackCandHit::Print().
int genfit::TrackCandHit::planeId_ protected
Definition at line 84 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 84 of file TrackCandHit.h
Referenced by getPlaneId(), genfit::operator==(), Print(), and genfit::WireTrackCandHit::Print().
double genfit::TrackCandHit::sortingParameter_ protected
Definition at line 85 of file TrackCandHit.h.
View newest version in sPHENIX GitHub at line 85 of file TrackCandHit.h
Referenced by getSortingParameter(), Print(), genfit::WireTrackCandHit::Print(), and setSortingParameter().
The documentation for this class was generated from the following files:
GenFit/blob/master/core/include/TrackCandHit.h
GenFit/blob/master/core/src/TrackCandHit.cc