Analysis Software: genfit::AbsFitterInfo Class Reference
genfit::AbsFitterInfo Class Reference abstract
This class collects all information needed and produced by a specific AbsFitter and is specific to one AbsTrackRep of the Track.
#include <GenFit/blob/master/core/include/AbsFitterInfo.h>
Public Member Functions
AbsFitterInfo ()
AbsFitterInfo (const TrackPoint *trackPoint, const AbsTrackRep *rep)
virtual ~AbsFitterInfo ()
virtual AbsFitterInfo * clone () const =0
Deep copy ctor for polymorphic class.
const TrackPoint * getTrackPoint () const
const AbsTrackRep * getRep () const
void setTrackPoint (const TrackPoint *tp)
virtual void setRep (const AbsTrackRep *rep)
virtual bool hasMeasurements () const =0
virtual bool hasReferenceState () const =0
virtual bool hasForwardPrediction () const =0
virtual bool hasBackwardPrediction () const =0
virtual bool hasPrediction (int direction) const
virtual bool hasForwardUpdate () const =0
virtual bool hasBackwardUpdate () const =0
virtual bool hasUpdate (int direction) const
virtual void deleteForwardInfo ()=0
virtual void deleteBackwardInfo ()=0
virtual void deleteReferenceInfo ()=0
virtual void deleteMeasurementInfo ()=0
const SharedPlanePtr & getPlane () const
virtual const
MeasuredStateOnPlane & getFittedState (bool biased=true) const =0
virtual MeasurementOnPlane getResidual (unsigned int iMeasurement=0, bool biased=true, bool onlyMeasurementErrors=false) const =0
void setPlane (const SharedPlanePtr &plane)
virtual void Print (const Option_t *="") const
virtual bool checkConsistency (const PruneFlags *=nullptr) const =0
Protected Attributes
const TrackPoint * trackPoint_
const AbsTrackRep * rep_
No ownership.
SharedPlanePtr sharedPlane_
No ownership.
Private Member Functions
AbsFitterInfo (const AbsFitterInfo &)
Shared ownership. '!' shuts up ROOT.
AbsFitterInfo & operator= (const AbsFitterInfo &)
Detailed Description
This class collects all information needed and produced by a specific AbsFitter and is specific to one AbsTrackRep of the Track.
Definition at line 42 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 42 of file AbsFitterInfo.h
Constructor & Destructor Documentation
genfit::AbsFitterInfo::AbsFitterInfo ()
Definition at line 27 of file AbsFitterInfo.cc.
View newest version in sPHENIX GitHub at line 27 of file AbsFitterInfo.cc
genfit::AbsFitterInfo::AbsFitterInfo (const TrackPoint * trackPoint, const AbsTrackRep * rep)
Definition at line 34 of file AbsFitterInfo.cc.
View newest version in sPHENIX GitHub at line 34 of file AbsFitterInfo.cc
virtual genfit::AbsFitterInfo::~AbsFitterInfo () inline virtual
Definition at line 49 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 49 of file AbsFitterInfo.h
genfit::AbsFitterInfo::AbsFitterInfo (const AbsFitterInfo &) private
Shared ownership. '!' shuts up ROOT.
Member Function Documentation
virtual bool genfit::AbsFitterInfo::checkConsistency (const PruneFlags * = nullptr) const pure virtual
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
virtual AbsFitterInfo* genfit::AbsFitterInfo::clone () const pure virtual
Deep copy ctor for polymorphic class.
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
Referenced by genfit::new_clone().
virtual void genfit::AbsFitterInfo::deleteBackwardInfo () pure virtual
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
virtual void genfit::AbsFitterInfo::deleteForwardInfo () pure virtual
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
virtual void genfit::AbsFitterInfo::deleteMeasurementInfo () pure virtual
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
virtual void genfit::AbsFitterInfo::deleteReferenceInfo () pure virtual
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
virtual const MeasuredStateOnPlane& genfit::AbsFitterInfo::getFittedState (bool biased = true) const pure virtual
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
Referenced by genfit::Track::getFittedState(), and genfit::Track::getTOF().
const SharedPlanePtr& genfit::AbsFitterInfo::getPlane () const inline
Definition at line 74 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 74 of file AbsFitterInfo.h
References sharedPlane_.
Referenced by genfit::KalmanFitterInfo::checkConsistency(), genfit::KalmanFitterInfo::getAvgWeightedMeasurementOnPlane(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::GFGbl::processTrackWithRep(), and genfit::GblFitterInfo::recalculateJacobian().
const AbsTrackRep* genfit::AbsFitterInfo::getRep () const inline
Definition at line 55 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 55 of file AbsFitterInfo.h
References rep_.
Referenced by genfit::KalmanFitterInfo::clone(), genfit::GblFitterInfo::clone(), genfit::KalmanFitterInfo::getFittedState(), genfit::GblFitterInfo::getResidual(), genfit::GblFitterInfo::Print(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), and genfit::TrackPoint::setFitterInfo().
virtual MeasurementOnPlane genfit::AbsFitterInfo::getResidual (unsigned int iMeasurement = 0, bool biased = true, bool onlyMeasurementErrors = false) const pure virtual
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
const TrackPoint* genfit::AbsFitterInfo::getTrackPoint () const inline
Definition at line 54 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 54 of file AbsFitterInfo.h
References trackPoint_.
Referenced by genfit::KalmanFitterInfo::clone(), genfit::GblFitterInfo::clone(), genfit::KalmanFitterInfo::getFittedState(), genfit::KalmanFitterRefTrack::processTrackPoint(), and genfit::KalmanFitterRefTrack::processTrackPointSqrt().
virtual bool genfit::AbsFitterInfo::hasBackwardPrediction () const pure virtual
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
Referenced by hasPrediction(), and genfit::Track::Print().
virtual bool genfit::AbsFitterInfo::hasBackwardUpdate () const pure virtual
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
Referenced by hasUpdate(), and genfit::Track::Print().
virtual bool genfit::AbsFitterInfo::hasForwardPrediction () const pure virtual
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
Referenced by hasPrediction(), and genfit::Track::Print().
virtual bool genfit::AbsFitterInfo::hasForwardUpdate () const pure virtual
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
Referenced by hasUpdate(), and genfit::Track::Print().
virtual bool genfit::AbsFitterInfo::hasMeasurements () const pure virtual
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
Referenced by genfit::Track::Print().
virtual bool genfit::AbsFitterInfo::hasPrediction (int direction) const inline virtual
Definition at line 64 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 64 of file AbsFitterInfo.h
References hasBackwardPrediction(), and hasForwardPrediction().
Referenced by genfit::AbsKalmanFitter::getMeasurements(), genfit::KalmanFitterRefTrack::processTrackPoint(), and genfit::KalmanFitterRefTrack::processTrackPointSqrt().
virtual bool genfit::AbsFitterInfo::hasReferenceState () const pure virtual
Implemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
Referenced by genfit::Track::Print().
virtual bool genfit::AbsFitterInfo::hasUpdate (int direction) const inline virtual
Reimplemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
Definition at line 67 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 67 of file AbsFitterInfo.h
References hasBackwardUpdate(), and hasForwardUpdate().
AbsFitterInfo& genfit::AbsFitterInfo::operator= (const AbsFitterInfo &) private
virtual void genfit::AbsFitterInfo::Print (const Option_t * = "") const inline virtual
Reimplemented in genfit::GblFitterInfo, and genfit::KalmanFitterInfo.
Definition at line 80 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 80 of file AbsFitterInfo.h
void genfit::AbsFitterInfo::setPlane (const SharedPlanePtr & plane) inline
Definition at line 78 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 78 of file AbsFitterInfo.h
References sharedPlane_.
Referenced by genfit::KalmanFitterInfo::addMeasurementOnPlane(), genfit::GblFitterInfo::clone(), genfit::KalmanFitterInfo::setBackwardPrediction(), genfit::KalmanFitterInfo::setBackwardUpdate(), genfit::KalmanFitterInfo::setForwardPrediction(), genfit::KalmanFitterInfo::setForwardUpdate(), genfit::KalmanFitterInfo::setReferenceState(), and genfit::GblFitterInfo::updateMeasurementAndPlane().
virtual void genfit::AbsFitterInfo::setRep (const AbsTrackRep * rep) inline virtual
Reimplemented in genfit::KalmanFitterInfo.
Definition at line 58 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 58 of file AbsFitterInfo.h
References rep_.
Referenced by genfit::TrackPoint::TrackPoint().
void genfit::AbsFitterInfo::setTrackPoint (const TrackPoint * tp) inline
Definition at line 57 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 57 of file AbsFitterInfo.h
References trackPoint_.
Referenced by genfit::TrackPoint::TrackPoint().
Member Data Documentation
const AbsTrackRep* genfit::AbsFitterInfo::rep_ protected
No ownership.
Pointer to AbsTrackRep with respect to which the FitterInfo is defined
Definition at line 92 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 92 of file AbsFitterInfo.h
Referenced by genfit::KalmanFitterInfo::checkConsistency(), genfit::GblFitterInfo::constructGblPoint(), genfit::GblFitterInfo::getFittedState(), genfit::GblFitterInfo::getKink(), genfit::GblFitterInfo::getMeasurement(), genfit::GblFitterInfo::getReferenceState(), getRep(), genfit::GblFitterInfo::getResidual(), genfit::KalmanFitterInfo::Print(), genfit::GblFitterInfo::Print(), genfit::GblFitterInfo::recalculateJacobian(), genfit::GblFitterInfo::setReferenceState(), setRep(), genfit::KalmanFitterInfo::setRep(), and genfit::GblFitterInfo::updateFitResults().
SharedPlanePtr genfit::AbsFitterInfo::sharedPlane_ protected
No ownership.
Definition at line 94 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 94 of file AbsFitterInfo.h
Referenced by genfit::GblFitterInfo::clone(), genfit::GblFitterInfo::constructGblPoint(), genfit::GblFitterInfo::getFittedState(), genfit::GblFitterInfo::getKink(), genfit::GblFitterInfo::getMeasurement(), getPlane(), genfit::GblFitterInfo::getReferenceState(), genfit::GblFitterInfo::getResidual(), genfit::GblFitterInfo::Print(), genfit::GblFitterInfo::recalculateJacobian(), setPlane(), genfit::GblFitterInfo::setReferenceState(), and genfit::GblFitterInfo::updateFitResults().
const TrackPoint* genfit::AbsFitterInfo::trackPoint_ protected
Pointer to TrackPoint where the FitterInfo belongs to
Definition at line 88 of file AbsFitterInfo.h.
View newest version in sPHENIX GitHub at line 88 of file AbsFitterInfo.h
Referenced by genfit::KalmanFitterInfo::checkConsistency(), genfit::GblFitterInfo::constructGblPoint(), genfit::GblFitterInfo::getMeasurement(), genfit::GblFitterInfo::getResidual(), getTrackPoint(), genfit::GblFitterInfo::hasMeasurements(), genfit::KalmanFitterInfo::Print(), genfit::GblFitterInfo::Print(), genfit::GblFitterInfo::recalculateJacobian(), genfit::GblFitterInfo::setReferenceState(), setTrackPoint(), genfit::GblFitterInfo::updateFitResults(), and genfit::GblFitterInfo::updateMeasurementAndPlane().
The documentation for this class was generated from the following files:
GenFit/blob/master/core/include/AbsFitterInfo.h
GenFit/blob/master/core/src/AbsFitterInfo.cc