Analysis Software: KFParticle/blob/master/KFParticle/KFPTrackVector.h File Reference
KFPTrackVector.h File Reference
#include "KFPTrack.h"
#include "KFParticleDef.h"
Classes
class KFPTrackVector
A class to store vectors of input tracks in the cartesian parametrisation.
Functions
class KFPTrackVector __attribute__ ((aligned(sizeof(float_v))))
KFPTrackVector ()
~KFPTrackVector ()
int Size () const
int DataSize () const
void Resize (const int n)
void Set (KFPTrackVector &v, int vSize, int offset)
void SetTracks (const KFPTrackVector &track, const kfvector_uint &trackIndex, const int nIndexes)
void GetTrack (KFPTrack &track, const int n)
const kfvector_float & X () const
Returns constant reference to the vector with X coordinates.
const kfvector_float & Y () const
Returns constant reference to the vector with Y coordinates.
const kfvector_float & Z () const
Returns constant reference to the vector with Z coordinates.
const kfvector_float & Px () const
Returns constant reference to the vector with Px components of momentum.
const kfvector_float & Py () const
Returns constant reference to the vector with Py components of momentum.
const kfvector_float & Pz () const
Returns constant reference to the vector with Pz components of momentum.
const kfvector_float & Parameter (const int i) const
Returns constant reference to the track parameter vector with index "i".
const kfvector_float & Covariance (const int i) const
Returns constant reference to the vector of the covariance matrix elements with index "i".
const kfvector_int & Id () const
Returns constant reference to the vector with track Id KFPTrackVector::fId.
const kfvector_int & PDG () const
Returns constant reference to the vector with assigned PDG hypothesis KFPTrackVector::fPDG.
const kfvector_int & Q () const
Returns constant reference to the vector with charge KFPTrackVector::fQ.
const kfvector_int & PVIndex () const
Returns constant reference to the vector with indices of corresponding primary vertex KFPTrackVector::fPVIndex.
const kfvector_int & NPixelHits () const
Returns constant reference to the vector with the number of precise measurements KFPTrackVector::fNPixelHits.
float Pt (const int n) const
Returns transverse momentum of the track with index "n".
float P (const int n) const
Returns momentum of the track with index "n".
void SetParameter (float value, int iP, int iTr)
Sets the "value" of the parameter "iP" of the track with index "iTr".
void SetCovariance (float value, int iC, int iTr)
Sets the "value" of the element of covariance matrix "iC" of the track with index "iTr".
void SetParameter (const float_v &value, int iP, int iTr)
void SetCovariance (const float_v &value, int iC, int iTr)
void SetId (int value, int iTr)
Sets Id of the track with index "iTr".
void SetPDG (int value, int iTr)
Sets PDG hypothesis of the track with index "iTr".
void SetQ (int value, int iTr)
Sets charge of the track with index "iTr".
void SetPVIndex (int value, int iTr)
Sets index of the corresponding primary vertex of the track with index "iTr".
void SetNPixelHits (int value, int iTr)
Sets number of precise measurement of the track with index "iTr".
void SetLastElectron (int n)
Sets index of the last electron.
void SetLastMuon (int n)
Sets index of the last muon.
void SetLastPion (int n)
Sets index of the last pion.
void SetLastKaon (int n)
Sets index of the last kaon.
void SetLastProton (int n)
Sets index of the last proton.
void SetLastDeuteron (int n)
Sets index of the last deuteron.
void SetLastTritium (int n)
Sets index of the last triton.
void SetLastHe3 (int n)
Sets index of the last He3.
void SetLastHe4 (int n)
Sets index of the last He4.
void RecalculateLastIndex ()
int FirstElectron ()
Returns index of the first electron.
const int & LastElectron () const
Returns index of the last electron.
int NElectrons ()
Returns number of electrons.
int FirstMuon ()
Returns index of the first element of the SIMD vector with the first muon.
const int & LastMuon () const
Returns index of the last muon.
int NMuons ()
Returns number of muons.
int FirstPion ()
Returns index of the first element of the SIMD vector with the first pion.
const int & LastPion () const
Returns index of the last pion.
int NPions ()
Returns number of pions.
int FirstKaon ()
Returns index of the first element of the SIMD vector with the first kaon.
const int & LastKaon () const
Returns index of the last kaon.
int NKaons ()
Returns number of kaons.
int FirstProton ()
Returns index of the first element of the SIMD vector with the first proton.
const int & LastProton () const
Returns index of the last proton.
int NProtons ()
Returns number of protons.
int FirstDeuteron ()
Returns index of the first element of the SIMD vector with the first deuteron.
const int & LastDeuteron () const
Returns index of the last deuteron.
int NDeuterons ()
Returns number of deuterons.
int FirstTritium ()
Returns index of the first element of the SIMD vector with the first triton.
const int & LastTritium () const
Returns index of the last triton.
int NTritiums ()
Returns number of tritons.
int FirstHe3 ()
Returns index of the first element of the SIMD vector with the first He3.
const int & LastHe3 () const
Returns index of the last He3.
int NHe3s ()
Returns number of He3 tracks.
int FirstHe4 ()
Returns index of the first element of the SIMD vector with the first He4.
const int & LastHe4 () const
Returns index of the last He4.
int NHe4s ()
Returns number of He4 tracks.
void AddElectron ()
Increases by one index of the last electron.
void AddMuon ()
Increases by one index of the last muon.
void AddPion ()
Increases by one index of the last pion.
void AddKaon ()
Increases by one index of the last kaon.
void AddProton ()
Increases by one index of the last proton.
void AddDeuteron ()
Increases by one index of the last deuteron.
void AddTririum ()
Increases by one index of the last triton.
void AddHe3 ()
Increases by one index of the last He3.
void AddHe4 ()
Increases by one index of the last He4.
void RotateXY (float_v alpha, int firstElement)
void PrintTrack (int n)
void Print ()
const KFPTrackVector & operator= (const KFPTrackVector &track)
void SetDataToVector (int *data, int &offset)
void ReadDataFromVector (int *data, int &offset)
void * operator new (size_t size)
new operator for allocation of the SIMD-alligned dynamic memory allocation
void * operator new[] (size_t size)
new operator for allocation of the SIMD-alligned dynamic memory allocation
void * operator new (size_t size, void *ptr)
new operator for allocation of the SIMD-alligned dynamic memory allocation
void * operator new[] (size_t size, void *ptr)
new operator for allocation of the SIMD-alligned dynamic memory allocation
void operator delete (void *ptr, size_t)
delete operator for the SIMD-alligned dynamic memory release
void operator delete[] (void *ptr, size_t)
delete operator for the SIMD-alligned dynamic memory release
Variables
kfvector_float fP [6]
Vectors with parameters of the track : X, Y, Z, Px, Py, Pz.
kfvector_float fC [21]
Vectors with covariance matrix of the track parameters stroed in a lower triangular form.
kfvector_int fId
Vector with the unique Id of tracks.
kfvector_int fPDG
Vector with the PDG hypothesis.
kfvector_int fQ
Vector with the charge of the tracks.
kfvector_int fPVIndex
Vector with the index of the corresponding primary vertex. If track is considered secondary "-1" is stored.
kfvector_int fNPixelHits
Vector with the number of hits from precise detectors (like MVD in CBM, HFT in STAR, ITS in ALICE, etc.)
int fNE
Index of the last electron.
int fNMu
Index of the last muon.
int fNPi
Index of the last pion (plus tracks without PID).
int fNK
Index of the last kaon.
int fNP
Index of the last proton.
int fND
Index of the last deuteron.
int fNT
Index of the last triton.
int fNHe3
Index of the last He3.
int fNHe4
Index of the last He4.
Function Documentation
class KFPTrackVector __attribute__ ((aligned(sizeof(float_v))))
void __attribute__::AddDeuteron ()
Increases by one index of the last deuteron.
Definition at line 536 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 536 of file KFPTrackVector.h
void __attribute__::AddElectron ()
Increases by one index of the last electron.
Definition at line 531 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 531 of file KFPTrackVector.h
void __attribute__::AddHe3 ()
Increases by one index of the last He3.
Definition at line 538 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 538 of file KFPTrackVector.h
void __attribute__::AddHe4 ()
Increases by one index of the last He4.
Definition at line 539 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 539 of file KFPTrackVector.h
void __attribute__::AddKaon ()
Increases by one index of the last kaon.
Definition at line 534 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 534 of file KFPTrackVector.h
void __attribute__::AddMuon ()
Increases by one index of the last muon.
Definition at line 532 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 532 of file KFPTrackVector.h
void __attribute__::AddPion ()
Increases by one index of the last pion.
Definition at line 533 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 533 of file KFPTrackVector.h
void __attribute__::AddProton ()
Increases by one index of the last proton.
Definition at line 535 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 535 of file KFPTrackVector.h
void __attribute__::AddTririum ()
Increases by one index of the last triton.
Definition at line 537 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 537 of file KFPTrackVector.h
const kfvector_float& __attribute__::Covariance (const int i) const
Returns constant reference to the vector of the covariance matrix elements with index "i".
Definition at line 437 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 437 of file KFPTrackVector.h
int __attribute__::DataSize () const
Returns size of the memory in floats (4 bytes or 32 bits) allocated by the current object.
Definition at line 412 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 412 of file KFPTrackVector.h
Referenced by KFPInputData::SetDataToVector().
int __attribute__::FirstDeuteron ()
Returns index of the first element of the SIMD vector with the first deuteron.
Definition at line 518 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 518 of file KFPTrackVector.h
int __attribute__::FirstElectron ()
Returns index of the first electron.
Definition at line 503 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 503 of file KFPTrackVector.h
int __attribute__::FirstHe3 ()
Returns index of the first element of the SIMD vector with the first He3.
Definition at line 524 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 524 of file KFPTrackVector.h
int __attribute__::FirstHe4 ()
Returns index of the first element of the SIMD vector with the first He4.
Definition at line 527 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 527 of file KFPTrackVector.h
int __attribute__::FirstKaon ()
Returns index of the first element of the SIMD vector with the first kaon.
Definition at line 512 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 512 of file KFPTrackVector.h
Referenced by KFParticleFinder::FindParticles().
int __attribute__::FirstMuon ()
Returns index of the first element of the SIMD vector with the first muon.
Definition at line 506 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 506 of file KFPTrackVector.h
int __attribute__::FirstPion ()
Returns index of the first element of the SIMD vector with the first pion.
Definition at line 509 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 509 of file KFPTrackVector.h
Referenced by KFParticleFinder::FindParticles().
int __attribute__::FirstProton ()
Returns index of the first element of the SIMD vector with the first proton.
Definition at line 515 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 515 of file KFPTrackVector.h
Referenced by KFParticleFinder::FindParticles().
int __attribute__::FirstTritium ()
Returns index of the first element of the SIMD vector with the first triton.
Definition at line 521 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 521 of file KFPTrackVector.h
void __attribute__::GetTrack (KFPTrack & track, const int n)
const kfvector_int& __attribute__::Id () const
Returns constant reference to the vector with track Id KFPTrackVector::fId.
Definition at line 442 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 442 of file KFPTrackVector.h
__attribute__::KFPTrackVector ()
Definition at line 407 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 407 of file KFPTrackVector.h
const int& __attribute__::LastDeuteron () const
Returns index of the last deuteron.
Definition at line 519 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 519 of file KFPTrackVector.h
const int& __attribute__::LastElectron () const
Returns index of the last electron.
Definition at line 504 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 504 of file KFPTrackVector.h
const int& __attribute__::LastHe3 () const
Returns index of the last He3.
Definition at line 525 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 525 of file KFPTrackVector.h
const int& __attribute__::LastHe4 () const
Returns index of the last He4.
Definition at line 528 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 528 of file KFPTrackVector.h
const int& __attribute__::LastKaon () const
Returns index of the last kaon.
Definition at line 513 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 513 of file KFPTrackVector.h
Referenced by KFParticleFinder::FindParticles().
const int& __attribute__::LastMuon () const
Returns index of the last muon.
Definition at line 507 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 507 of file KFPTrackVector.h
const int& __attribute__::LastPion () const
Returns index of the last pion.
Definition at line 510 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 510 of file KFPTrackVector.h
Referenced by KFParticleFinder::FindParticles().
const int& __attribute__::LastProton () const
Returns index of the last proton.
Definition at line 516 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 516 of file KFPTrackVector.h
Referenced by KFParticleFinder::FindParticles().
const int& __attribute__::LastTritium () const
Returns index of the last triton.
Definition at line 522 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 522 of file KFPTrackVector.h
int __attribute__::NDeuterons ()
Returns number of deuterons.
Definition at line 520 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 520 of file KFPTrackVector.h
int __attribute__::NElectrons ()
Returns number of electrons.
Definition at line 505 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 505 of file KFPTrackVector.h
int __attribute__::NHe3s ()
Returns number of He3 tracks.
Definition at line 526 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 526 of file KFPTrackVector.h
int __attribute__::NHe4s ()
Returns number of He4 tracks.
Definition at line 529 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 529 of file KFPTrackVector.h
int __attribute__::NKaons ()
Returns number of kaons.
Definition at line 514 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 514 of file KFPTrackVector.h
int __attribute__::NMuons ()
Returns number of muons.
Definition at line 508 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 508 of file KFPTrackVector.h
int __attribute__::NPions ()
Returns number of pions.
Definition at line 511 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 511 of file KFPTrackVector.h
const kfvector_int& __attribute__::NPixelHits () const
Returns constant reference to the vector with the number of precise measurements KFPTrackVector::fNPixelHits.
Definition at line 446 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 446 of file KFPTrackVector.h
int __attribute__::NProtons ()
Returns number of protons.
Definition at line 517 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 517 of file KFPTrackVector.h
int __attribute__::NTritiums ()
Returns number of tritons.
Definition at line 523 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 523 of file KFPTrackVector.h
void __attribute__::operator delete (void * ptr, size_t)
delete operator for the SIMD-alligned dynamic memory release
Definition at line 723 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 723 of file KFPTrackVector.h
void __attribute__::operator delete[] (void * ptr, size_t)
delete operator for the SIMD-alligned dynamic memory release
Definition at line 724 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 724 of file KFPTrackVector.h
void* __attribute__::operator new (size_t size)
new operator for allocation of the SIMD-alligned dynamic memory allocation
Definition at line 719 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 719 of file KFPTrackVector.h
void* __attribute__::operator new (size_t size, void * ptr)
new operator for allocation of the SIMD-alligned dynamic memory allocation
Definition at line 721 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 721 of file KFPTrackVector.h
void* __attribute__::operator new[] (size_t size)
new operator for allocation of the SIMD-alligned dynamic memory allocation
Definition at line 720 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 720 of file KFPTrackVector.h
void* __attribute__::operator new[] (size_t size, void * ptr)
new operator for allocation of the SIMD-alligned dynamic memory allocation
Definition at line 722 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 722 of file KFPTrackVector.h
const KFPTrackVector& __attribute__::operator= (const KFPTrackVector & track)
Operator to copy one KFPTrackVector object to another. Makes one-to-one copy.
Definition at line 546 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 546 of file KFPTrackVector.h
float __attribute__::P (const int n) const
Returns momentum of the track with index "n".
Definition at line 449 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 449 of file KFPTrackVector.h
Referenced by KFPMath::__attribute__(), KFParticle::Create(), GetResolution(), hijfst_(), and PHG4GDMLWriteStructure::TraverseVolumeTree().
const kfvector_float& __attribute__::Parameter (const int i) const
Returns constant reference to the track parameter vector with index "i".
Definition at line 436 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 436 of file KFPTrackVector.h
const kfvector_int& __attribute__::PDG () const
Returns constant reference to the vector with assigned PDG hypothesis KFPTrackVector::fPDG.
Definition at line 443 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 443 of file KFPTrackVector.h
void __attribute__::Print ()
Prints all fields of the current object.
Definition at line 516 of file KFPInputData.h.
View newest version in sPHENIX GitHub at line 516 of file KFPInputData.h
void __attribute__::PrintTrack (int n)
float __attribute__::Pt (const int n) const
Returns transverse momentum of the track with index "n".
Definition at line 448 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 448 of file KFPTrackVector.h
const kfvector_int& __attribute__::PVIndex () const
Returns constant reference to the vector with indices of corresponding primary vertex KFPTrackVector::fPVIndex.
Definition at line 445 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 445 of file KFPTrackVector.h
Referenced by KFParticleTopoReconstructor::SaveInputParticles(), and KFParticleTopoReconstructor::SortTracks().
const kfvector_float& __attribute__::Px () const
Returns constant reference to the vector with Px components of momentum.
Definition at line 432 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 432 of file KFPTrackVector.h
const kfvector_float& __attribute__::Py () const
Returns constant reference to the vector with Py components of momentum.
Definition at line 433 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 433 of file KFPTrackVector.h
const kfvector_float& __attribute__::Pz () const
Returns constant reference to the vector with Pz components of momentum.
Definition at line 434 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 434 of file KFPTrackVector.h
const kfvector_int& __attribute__::Q () const
Returns constant reference to the vector with charge KFPTrackVector::fQ.
Definition at line 444 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 444 of file KFPTrackVector.h
void __attribute__::ReadDataFromVector (int * data, int & offset)
Copies entire vector from the provided memory starting form the position "offset". The function is used in KFPInputData::ReadDataFromVector().
Parameters
[in] data - pointer to the memory with the track vectors; since all fields of KFPTrackVector are of the same size (int or float) pointer can be safely casted to int*
[in,out] offset - starting position of the memory to be copied; after all vectors are copied the offset is shifted on the size of the read object so the next KFPTrackVector object can be copied
Definition at line 663 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 663 of file KFPTrackVector.h
void __attribute__::RecalculateLastIndex ()
Recalculate the last index of each track specie. Should be called after track sorting.
Definition at line 476 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 476 of file KFPTrackVector.h
Referenced by KFParticleTopoReconstructor::SortTracks().
void __attribute__::Resize (const int n)
void __attribute__::RotateXY (float_v alpha, int firstElement)
void __attribute__::Set (KFPTrackVector & v, int vSize, int offset)
void __attribute__::SetCovariance (float value, int iC, int iTr)
Sets the "value" of the element of covariance matrix "iC" of the track with index "iTr".
Definition at line 453 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 453 of file KFPTrackVector.h
Referenced by KFParticleTopoReconstructor::Init(), and KFParticleTopoReconstructor::TransportPVTracksToPrimVertex().
void __attribute__::SetCovariance (const float_v & value, int iC, int iTr)
void __attribute__::SetDataToVector (int * data, int & offset)
Copies entire vector to the provided memory starting form the position "offset". The function is used in KFPInputData::SetDataToVector().
Parameters
[out] data - pointer to the memory where the track vectors should be copied; since all fields of KFPTrackVector are of the same size (int or float) pointer can be safely casted to int*
[in,out] offset - starting position in "data" where vectors should be copied; after all vectors are copied the offset is shifted on the size of the written object so the next KFPTrackVector object can be copied to the "data"
Definition at line 607 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 607 of file KFPTrackVector.h
void __attribute__::SetId (int value, int iTr)
Sets Id of the track with index "iTr".
Definition at line 461 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 461 of file KFPTrackVector.h
void __attribute__::SetLastDeuteron (int n)
Sets index of the last deuteron.
Definition at line 471 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 471 of file KFPTrackVector.h
void __attribute__::SetLastElectron (int n)
Sets index of the last electron.
Definition at line 466 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 466 of file KFPTrackVector.h
void __attribute__::SetLastHe3 (int n)
Sets index of the last He3.
Definition at line 473 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 473 of file KFPTrackVector.h
void __attribute__::SetLastHe4 (int n)
Sets index of the last He4.
Definition at line 474 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 474 of file KFPTrackVector.h
void __attribute__::SetLastKaon (int n)
Sets index of the last kaon.
Definition at line 469 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 469 of file KFPTrackVector.h
void __attribute__::SetLastMuon (int n)
Sets index of the last muon.
Definition at line 467 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 467 of file KFPTrackVector.h
void __attribute__::SetLastPion (int n)
Sets index of the last pion.
Definition at line 468 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 468 of file KFPTrackVector.h
void __attribute__::SetLastProton (int n)
Sets index of the last proton.
Definition at line 470 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 470 of file KFPTrackVector.h
void __attribute__::SetLastTritium (int n)
Sets index of the last triton.
Definition at line 472 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 472 of file KFPTrackVector.h
void __attribute__::SetNPixelHits (int value, int iTr)
Sets number of precise measurement of the track with index "iTr".
Definition at line 465 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 465 of file KFPTrackVector.h
void __attribute__::SetParameter (float value, int iP, int iTr)
Sets the "value" of the parameter "iP" of the track with index "iTr".
Definition at line 452 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 452 of file KFPTrackVector.h
Referenced by KFParticleTopoReconstructor::Init(), and KFParticleTopoReconstructor::TransportPVTracksToPrimVertex().
void __attribute__::SetParameter (const float_v & value, int iP, int iTr)
void __attribute__::SetPDG (int value, int iTr)
Sets PDG hypothesis of the track with index "iTr".
Definition at line 462 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 462 of file KFPTrackVector.h
void __attribute__::SetPVIndex (int value, int iTr)
Sets index of the corresponding primary vertex of the track with index "iTr".
Definition at line 464 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 464 of file KFPTrackVector.h
Referenced by KFParticleTopoReconstructor::FillPVIndices(), and KFParticleTopoReconstructor::ReconstructPrimVertex().
void __attribute__::SetQ (int value, int iTr)
Sets charge of the track with index "iTr".
Definition at line 463 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 463 of file KFPTrackVector.h
void __attribute__::SetTracks (const KFPTrackVector & track, const kfvector_uint & trackIndex, const int nIndexes)
Referenced by KFParticleTopoReconstructor::SortTracks().
int __attribute__::Size () const
Returns size of the vectors. All data vectors have the same size.
Definition at line 411 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 411 of file KFPTrackVector.h
Referenced by KFParticleFinder::FindParticles(), KFParticleFinder::FindTrackV0Decay(), KFParticleTopoReconstructor::Init(), KFPTrackVector::SetCovariance(), KFPInputData::SetDataToVector(), KFPTrackVector::SetParameter(), and KFParticleTopoReconstructor::SortTracks().
const kfvector_float& __attribute__::X () const
Returns constant reference to the vector with X coordinates.
Definition at line 429 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 429 of file KFPTrackVector.h
const kfvector_float& __attribute__::Y () const
Returns constant reference to the vector with Y coordinates.
Definition at line 430 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 430 of file KFPTrackVector.h
const kfvector_float& __attribute__::Z () const
Returns constant reference to the vector with Z coordinates.
Definition at line 431 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 431 of file KFPTrackVector.h
__attribute__::~KFPTrackVector ()
Definition at line 408 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 408 of file KFPTrackVector.h
Variable Documentation
kfvector_float fC[21]
Vectors with covariance matrix of the track parameters stroed in a lower triangular form.
Definition at line 728 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 728 of file KFPTrackVector.h
kfvector_int fId
Vector with the unique Id of tracks.
Definition at line 730 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 730 of file KFPTrackVector.h
int fND
Index of the last deuteron.
Definition at line 754 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 754 of file KFPTrackVector.h
int fNE
Index of the last electron.
The coefficients of the field approximation of each field component along the track trajectory using parabolas:
cx0 = fField[0], cx1 = fField[1], cx2 = fField[2] - coefficients of the Bx approximation;
cy0 = fField[3], cy1 = fField[4], cy2 = fField[5] - coefficients of the By approximation;
cz0 = fField[6], cz1 = fField[7], cz2 = fField[8] - coefficients of the Bz approximation;
z0 = fField[9] - reference Z coordinate.
Bx(z) = cx0 + cx1*(z-z0) + cx2*(z-z0)^2
By(z) = cy0 + cy1*(z-z0) + cy2*(z-z0)^2
Bz(z) = cz0 + cz1*(z-z0) + cz2*(z-z0)^2
Definition at line 749 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 749 of file KFPTrackVector.h
int fNHe3
Index of the last He3.
Definition at line 756 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 756 of file KFPTrackVector.h
int fNHe4
Index of the last He4.
Definition at line 757 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 757 of file KFPTrackVector.h
int fNK
Index of the last kaon.
Definition at line 752 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 752 of file KFPTrackVector.h
int fNMu
Index of the last muon.
Definition at line 750 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 750 of file KFPTrackVector.h
int fNP
Index of the last proton.
Definition at line 753 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 753 of file KFPTrackVector.h
int fNPi
Index of the last pion (plus tracks without PID).
Definition at line 751 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 751 of file KFPTrackVector.h
kfvector_int fNPixelHits
Vector with the number of hits from precise detectors (like MVD in CBM, HFT in STAR, ITS in ALICE, etc.)
Definition at line 734 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 734 of file KFPTrackVector.h
int fNT
Index of the last triton.
Definition at line 755 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 755 of file KFPTrackVector.h
kfvector_float fP[6]
Vectors with parameters of the track : X, Y, Z, Px, Py, Pz.
Definition at line 727 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 727 of file KFPTrackVector.h
kfvector_int fPDG
Vector with the PDG hypothesis.
Definition at line 731 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 731 of file KFPTrackVector.h
kfvector_int fPVIndex
Vector with the index of the corresponding primary vertex. If track is considered secondary "-1" is stored.
Definition at line 733 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 733 of file KFPTrackVector.h
kfvector_int fQ
Vector with the charge of the tracks.
Definition at line 732 of file KFPTrackVector.h.
View newest version in sPHENIX GitHub at line 732 of file KFPTrackVector.h