Analysis Software: GPUTPCTrackLinearisation Class Reference
GPUTPCTrackLinearisation Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/GPUTPCTrackLinearisation.h>
Public Member Functions
GPUTPCTrackLinearisation ()
GPUTPCTrackLinearisation (float SinPhi1, float CosPhi1, float DzDs1, float QPt1)
GPUTPCTrackLinearisation (const GPUTPCTrackParam &t)
void Set (float SinPhi1, float CosPhi1, float DzDs1, float QPt1)
float SinPhi () const
float CosPhi () const
float DzDs () const
float QPt () const
float GetSinPhi () const
float GetCosPhi () const
float GetDzDs () const
float GetQPt () const
void SetSinPhi (float v)
void SetCosPhi (float v)
void SetDzDs (float v)
void SetQPt (float v)
Private Attributes
float mSinPhi
float mCosPhi
float mDzDs
float mQPt
Detailed Description
GPUTPCTrackLinearisation class describes the parameters which are used to linearise the transport equations for the track trajectory.
The class is used during track (re)fit, when the AliHLTTPCTrackParam track is only partially fitted, and there is some apriory knowledge about trajectory. This apriory knowledge is used to linearise the transport equations.
In case the track is fully fitted, the best linearisation point is the track trajectory itself (GPUTPCTrackLinearisation = AliHLTTPCTrackParam).
Definition at line 33 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 33 of file GPUTPCTrackLinearisation.h
Constructor & Destructor Documentation
GPUTPCTrackLinearisation::GPUTPCTrackLinearisation () inline
Definition at line 36 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 36 of file GPUTPCTrackLinearisation.h
GPUTPCTrackLinearisation::GPUTPCTrackLinearisation (float SinPhi1, float CosPhi1, float DzDs1, float QPt1) inline
Definition at line 37 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 37 of file GPUTPCTrackLinearisation.h
GPUTPCTrackLinearisation::GPUTPCTrackLinearisation (const GPUTPCTrackParam & t) inline
Definition at line 65 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 65 of file GPUTPCTrackLinearisation.h
References GPUCA_MAX_SIN_PHI, mCosPhi, mSinPhi, and GPUTPCTrackParam::SignCosPhi().
Member Function Documentation
float GPUTPCTrackLinearisation::CosPhi () const inline
Definition at line 44 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 44 of file GPUTPCTrackLinearisation.h
References mCosPhi.
Referenced by GPUTPCTrackParam::Rotate(), and GPUTPCTrackParam::TransportToX().
float GPUTPCTrackLinearisation::DzDs () const inline
Definition at line 45 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 45 of file GPUTPCTrackLinearisation.h
References mDzDs.
Referenced by GPUTPCTrackParam::TransportToX().
float GPUTPCTrackLinearisation::GetCosPhi () const inline
Definition at line 49 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 49 of file GPUTPCTrackLinearisation.h
References mCosPhi.
float GPUTPCTrackLinearisation::GetDzDs () const inline
Definition at line 50 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 50 of file GPUTPCTrackLinearisation.h
References mDzDs.
float GPUTPCTrackLinearisation::GetQPt () const inline
Definition at line 51 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 51 of file GPUTPCTrackLinearisation.h
References mQPt.
float GPUTPCTrackLinearisation::GetSinPhi () const inline
Definition at line 48 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 48 of file GPUTPCTrackLinearisation.h
References mSinPhi.
float GPUTPCTrackLinearisation::QPt () const inline
Definition at line 46 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 46 of file GPUTPCTrackLinearisation.h
References mQPt.
Referenced by GPUTPCTrackParam::TransportToX().
void GPUTPCTrackLinearisation::Set (float SinPhi1, float CosPhi1, float DzDs1, float QPt1)
Definition at line 78 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 78 of file GPUTPCTrackLinearisation.h
References SetCosPhi(), SetDzDs(), SetQPt(), and SetSinPhi().
void GPUTPCTrackLinearisation::SetCosPhi (float v) inline
Definition at line 54 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 54 of file GPUTPCTrackLinearisation.h
References mCosPhi, and v.
Referenced by GPUTPCTrackParam::Rotate(), Set(), and GPUTPCTrackParam::TransportToX().
void GPUTPCTrackLinearisation::SetDzDs (float v) inline
Definition at line 55 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 55 of file GPUTPCTrackLinearisation.h
References mDzDs, and v.
Referenced by Set().
void GPUTPCTrackLinearisation::SetQPt (float v) inline
Definition at line 56 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 56 of file GPUTPCTrackLinearisation.h
References mQPt, and v.
Referenced by Set().
void GPUTPCTrackLinearisation::SetSinPhi (float v) inline
Definition at line 53 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 53 of file GPUTPCTrackLinearisation.h
References mSinPhi, and v.
Referenced by GPUTPCTrackParam::Rotate(), Set(), and GPUTPCTrackParam::TransportToX().
float GPUTPCTrackLinearisation::SinPhi () const inline
Definition at line 43 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 43 of file GPUTPCTrackLinearisation.h
References mSinPhi.
Referenced by GPUTPCTrackParam::Rotate(), and GPUTPCTrackParam::TransportToX().
Member Data Documentation
float GPUTPCTrackLinearisation::mCosPhi private
Definition at line 60 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 60 of file GPUTPCTrackLinearisation.h
Referenced by CosPhi(), GetCosPhi(), GPUTPCTrackLinearisation(), and SetCosPhi().
float GPUTPCTrackLinearisation::mDzDs private
Definition at line 61 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 61 of file GPUTPCTrackLinearisation.h
Referenced by DzDs(), GetDzDs(), and SetDzDs().
float GPUTPCTrackLinearisation::mQPt private
Definition at line 62 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 62 of file GPUTPCTrackLinearisation.h
Referenced by GetQPt(), QPt(), and SetQPt().
float GPUTPCTrackLinearisation::mSinPhi private
Definition at line 59 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 59 of file GPUTPCTrackLinearisation.h
Referenced by GetSinPhi(), GPUTPCTrackLinearisation(), SetSinPhi(), and SinPhi().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackreco/GPUTPCTrackLinearisation.h