Analysis Software: coresoftware/blob/master/offline/packages/trackreco/PHRTreeSeeding.cc File Reference
PHRTreeSeeding.cc File Reference
#include "PHRTreeSeeding.h"
#include <trackbase_historic/SvtxTrackMap.h>
#include <trackbase_historic/SvtxTrack_v1.h>
#include <trackbase_historic/SvtxVertex.h>
#include <trackbase_historic/SvtxVertexMap.h>
#include <trackbase/TrkrCluster.h>
#include <trackbase/TrkrClusterContainer.h>
#include <trackbase/TrkrDefs.h>
#include <g4detectors/PHG4CylinderCellGeom.h>
#include <g4detectors/PHG4CylinderCellGeomContainer.h>
#include <g4detectors/PHG4CylinderGeom.h>
#include <g4detectors/PHG4CylinderGeomContainer.h>
#include <fun4all/Fun4AllReturnCodes.h>
#include <phool/PHTimer.h>
#include <phool/getClass.h>
#include <phool/phool.h>
#include <TFile.h>
#include <TNtuple.h>
#include <TVector3.h>
#include <boost/geometry.hpp>
#include <boost/geometry/geometries/box.hpp>
#include <boost/geometry/geometries/point.hpp>
#include <boost/geometry/index/rtree.hpp>
#include <algorithm>
#include <cmath>
#include <iostream>
#include <numeric>
#include <utility>
#include <vector>
Macros
#define LogDebug(exp) std::cout << "DEBUG: " << __FILE__ << ": " << __LINE__ << ": " << exp
#define LogError(exp) std::cout << "ERROR: " << __FILE__ << ": " << __LINE__ << ": " << exp
#define LogWarning(exp) std::cout << "WARNING: " << __FILE__ << ": " << __LINE__ << ": " << exp
Typedefs
typedef bg::model::point
< float, 3, bg::cs::cartesian > point
typedef bg::model::box< point > box
typedef std::pair< point,
TrkrDefs::cluskey > pointKey
Functions
bool comparing (TrkrCluster *tc1, TrkrCluster *tc2)
bool largeintersection (const vector< TrkrCluster * > &v1, const vector< TrkrCluster * > &v2)
vector< TrkrCluster * > yunion (const vector< TrkrCluster * > &v1, const vector< TrkrCluster * > &v2)
bool issuperset (const vector< TrkrCluster * > &larger, const vector< TrkrCluster * > &smaller)
void changetounion (vector< TrkrCluster * > &v1, const vector< TrkrCluster * > &v2)
double RosenBrock (const double *xx)
double costfunction (const double *xx)
Variables
vector< TrkrCluster * > clusterpoints
SvtxVertex * _vertex
Macro Definition Documentation
#define LogDebug (exp) std::cout << "DEBUG: " << __FILE__ << ": " << __LINE__ << ": " << exp
Definition at line 62 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 62 of file PHRTreeSeeding.cc
#define LogError (exp) std::cout << "ERROR: " << __FILE__ << ": " << __LINE__ << ": " << exp
Definition at line 63 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 63 of file PHRTreeSeeding.cc
#define LogWarning (exp) std::cout << "WARNING: " << __FILE__ << ": " << __LINE__ << ": " << exp
Definition at line 64 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 64 of file PHRTreeSeeding.cc
Typedef Documentation
typedef bg::model::box<point> box
Definition at line 59 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 59 of file PHRTreeSeeding.cc
typedef bg::model::point<float, 3, bg::cs::cartesian> point
Definition at line 54 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 54 of file PHRTreeSeeding.cc
typedef std::pair<point, TrkrDefs::cluskey> pointKey
Definition at line 60 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 60 of file PHRTreeSeeding.cc
Function Documentation
void changetounion (vector< TrkrCluster * > & v1, const vector< TrkrCluster * > & v2)
Definition at line 300 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 300 of file PHRTreeSeeding.cc
References yunion().
bool comparing (TrkrCluster * tc1, TrkrCluster * tc2)
Definition at line 235 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 235 of file PHRTreeSeeding.cc
References TrkrCluster::getClusKey(), and TrkrDefs::getLayer().
Referenced by issuperset(), largeintersection(), and yunion().
double costfunction (const double * xx)
Definition at line 394 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 394 of file PHRTreeSeeding.cc
bool issuperset (const vector< TrkrCluster * > & larger, const vector< TrkrCluster * > & smaller)
Definition at line 290 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 290 of file PHRTreeSeeding.cc
References comparing(), and i.
bool largeintersection (const vector< TrkrCluster * > & v1, const vector< TrkrCluster * > & v2)
Definition at line 246 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 246 of file PHRTreeSeeding.cc
References comparing(), TrkrDefs::getLayer(), max, and v3.
double RosenBrock (const double * xx)
Definition at line 307 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 307 of file PHRTreeSeeding.cc
References _vertex, clusterpoints, SvtxVertex::get_error(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), TrkrCluster::getError(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), i, and M_PI.
vector<TrkrCluster *> yunion (const vector< TrkrCluster * > & v1, const vector< TrkrCluster * > & v2)
Definition at line 277 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 277 of file PHRTreeSeeding.cc
References comparing(), and v3.
Referenced by changetounion().
Variable Documentation
SvtxVertex* _vertex
Definition at line 72 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 72 of file PHRTreeSeeding.cc
Referenced by PHRTreeSeeding::FillTree(), PHRTreeSeeding::Process(), and RosenBrock().
vector<TrkrCluster *> clusterpoints
Definition at line 71 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 71 of file PHRTreeSeeding.cc
Referenced by PHRTreeSeeding::chisq(), and RosenBrock().