Analysis Software: genfit::MeasurementFactory< measurement_T > Class Template Reference
genfit::MeasurementFactory< measurement_T > Class Template Reference
Factory object to create AbsMeasurement objects from digitized and clustered data.
#include <GenFit/blob/master/core/include/MeasurementFactory.h>
Public Member Functions
MeasurementFactory ()
virtual ~MeasurementFactory ()
void addProducer (int detID, AbsMeasurementProducer< measurement_T > *hitProd)
Register a producer module to the factory.
void clear ()
Clear all hit producers.
measurement_T * createOne (int detID, int index, const TrackCandHit *hit) const
Create a Measurement.
std::vector< measurement_T * > createMany (const TrackCand &cand) const
Create a collection of Measurements.
Private Attributes
std::map< int,
AbsMeasurementProducer
< measurement_T > * > hitProdMap_
Detailed Description
template<class measurement_T>
class genfit::MeasurementFactory< measurement_T >
Factory object to create AbsMeasurement objects from digitized and clustered data.
The MeasurementFactory is used to automatically fill Track objects with hit data. For each detector type used an AbsMeasurementProducer has to be registered in the factory. The factory can then use the index information from a TrackCand object to load the indexed hits into the Track.
See Also
AbsMeasurementProducer
TrackCand
Definition at line 51 of file MeasurementFactory.h.
View newest version in sPHENIX GitHub at line 51 of file MeasurementFactory.h
Constructor & Destructor Documentation
template<class measurement_T> genfit::MeasurementFactory< measurement_T >::MeasurementFactory () inline
Definition at line 57 of file MeasurementFactory.h.
View newest version in sPHENIX GitHub at line 57 of file MeasurementFactory.h
template<class measurement_T> virtual genfit::MeasurementFactory< measurement_T >::~MeasurementFactory () inline virtual
Definition at line 58 of file MeasurementFactory.h.
View newest version in sPHENIX GitHub at line 58 of file MeasurementFactory.h
References genfit::MeasurementFactory< measurement_T >::clear().
Member Function Documentation
template<class measurement_T > void genfit::MeasurementFactory< measurement_T >::addProducer (int detID, AbsMeasurementProducer< measurement_T > * hitProd)
Register a producer module to the factory.
For each type of hit a separate producer is needed. The type of hit is identified by the detector ID (detID). This index corresponds to the detector ID that is stored in the TrackCand.
Definition at line 97 of file MeasurementFactory.h.
View newest version in sPHENIX GitHub at line 97 of file MeasurementFactory.h
References it, genfit::Exception::setFatal(), and genfit::Exception::setNumbers().
Referenced by main().
template<class measurement_T > void genfit::MeasurementFactory< measurement_T >::clear ()
Clear all hit producers.
Definition at line 112 of file MeasurementFactory.h.
View newest version in sPHENIX GitHub at line 112 of file MeasurementFactory.h
References it.
Referenced by genfit::MeasurementFactory< measurement_T >::~MeasurementFactory().
template<class measurement_T > std::vector< measurement_T * > genfit::MeasurementFactory< measurement_T >::createMany (const TrackCand & cand) const
Create a collection of Measurements.
This is the standard way to prepare the hit collection for a Track. The resulting collection can contain hits from several detectors. The order of the hits is the same as in the TrackCand. It is assumed that this order is already along the Track.
Measurements have to implement a constructor which takes the cluster object from which the Measurement is built as the only parameter.
See Also
AbsMeasurementProducer
Definition at line 138 of file MeasurementFactory.h.
View newest version in sPHENIX GitHub at line 138 of file MeasurementFactory.h
References genfit::TrackCandHit::getDetId(), genfit::TrackCand::getHit(), genfit::TrackCandHit::getHitId(), genfit::TrackCand::getNHits(), i, and index.
Referenced by genfit::Track::createMeasurements().
template<class measurement_T > measurement_T * genfit::MeasurementFactory< measurement_T >::createOne (int detID, int index, const TrackCandHit * hit) const
Create a Measurement.
Measurements have to implement a Constructor which takes the cluster object from which the Measurement is built as the only parameter.
See Also
AbsMeasurementProducer
Definition at line 122 of file MeasurementFactory.h.
View newest version in sPHENIX GitHub at line 122 of file MeasurementFactory.h
References it, genfit::Exception::setFatal(), and genfit::Exception::setNumbers().
Member Data Documentation
template<class measurement_T> std::map<int, AbsMeasurementProducer<measurement_T>*> genfit::MeasurementFactory< measurement_T >::hitProdMap_ private
Definition at line 53 of file MeasurementFactory.h.
View newest version in sPHENIX GitHub at line 53 of file MeasurementFactory.h
The documentation for this class was generated from the following file:
GenFit/blob/master/core/include/MeasurementFactory.h