Analysis Software: genfit::KalmanFittedStateOnPlane Class Reference
genfit::KalmanFittedStateOnPlane Class Reference
MeasuredStateOnPlane with additional info produced by a Kalman filter or DAF.
#include <GenFit/blob/master/fitters/include/KalmanFittedStateOnPlane.h>
Public Member Functions
KalmanFittedStateOnPlane ()
KalmanFittedStateOnPlane (const TVectorD &state, const TMatrixDSym &cov, const SharedPlanePtr &plane, const AbsTrackRep *rep, double chiSquareIncrement, double ndf)
KalmanFittedStateOnPlane (const TVectorD &state, const TMatrixDSym &cov, const SharedPlanePtr &plane, const AbsTrackRep *rep, const TVectorD &auxInfo, double chiSquareIncrement, double ndf)
KalmanFittedStateOnPlane (const MeasuredStateOnPlane &state, double chiSquareIncrement, double ndf)
KalmanFittedStateOnPlane & operator= (KalmanFittedStateOnPlane other)
void swap (KalmanFittedStateOnPlane &other)
virtual ~KalmanFittedStateOnPlane ()
double getChiSquareIncrement () const
double getNdf () const
void setChiSquareIncrement (double chiSquareIncrement)
void setNdf (double ndf)
Public Member Functions inherited from genfit::MeasuredStateOnPlane
MeasuredStateOnPlane (const AbsTrackRep *rep=nullptr)
MeasuredStateOnPlane (const TVectorD &state, const TMatrixDSym &cov, const genfit::SharedPlanePtr &plane, const AbsTrackRep *rep)
MeasuredStateOnPlane (const TVectorD &state, const TMatrixDSym &cov, const genfit::SharedPlanePtr &plane, const AbsTrackRep *rep, const TVectorD &auxInfo)
MeasuredStateOnPlane (const MeasuredStateOnPlane &o)
MeasuredStateOnPlane (const StateOnPlane &state, const TMatrixDSym &cov)
MeasuredStateOnPlane & operator= (MeasuredStateOnPlane other)
void swap (MeasuredStateOnPlane &other)
virtual ~MeasuredStateOnPlane ()
virtual MeasuredStateOnPlane * clone () const override
const TMatrixDSym & getCov () const
TMatrixDSym & getCov ()
void blowUpCov (double blowUpFac, bool resetOffDiagonals=true, double maxVal=-1.)
Blow up covariance matrix with blowUpFac. Per default, off diagonals are reset to 0 and the maximum values are limited to maxVal.
void setStateCov (const TVectorD &state, const TMatrixDSym &cov)
void setStateCovPlane (const TVectorD &state, const TMatrixDSym &cov, const SharedPlanePtr &plane)
void setCov (const TMatrixDSym &cov)
TMatrixDSym get6DCov () const
void getPosMomCov (TVector3 &pos, TVector3 &mom, TMatrixDSym &cov) const
void get6DStateCov (TVectorD &stateVec, TMatrixDSym &cov) const
double getMomVar () const
void setPosMomErr (const TVector3 &pos, const TVector3 &mom, const TVector3 &posErr, const TVector3 &momErr)
void setPosMomCov (const TVector3 &pos, const TVector3 &mom, const TMatrixDSym &cov6x6)
void setPosMomCov (const TVectorD &state6, const TMatrixDSym &cov6x6)
virtual void Print (Option_t *option="") const override
Public Member Functions inherited from genfit::StateOnPlane
StateOnPlane (const AbsTrackRep *rep=nullptr)
StateOnPlane (const TVectorD &state, const SharedPlanePtr &plane, const AbsTrackRep *rep)
state is defined by the TrackReps parameterization
StateOnPlane (const TVectorD &state, const SharedPlanePtr &plane, const AbsTrackRep *rep, const TVectorD &auxInfo)
StateOnPlane & operator= (StateOnPlane other)
void swap (StateOnPlane &other)
virtual ~StateOnPlane ()
const TVectorD & getState () const
TVectorD & getState ()
const TVectorD & getAuxInfo () const
TVectorD & getAuxInfo ()
const SharedPlanePtr & getPlane () const
const AbsTrackRep * getRep () const
void setState (const TVectorD &state)
void setPlane (const SharedPlanePtr &plane)
void setStatePlane (const TVectorD &state, const SharedPlanePtr &plane)
void setAuxInfo (const TVectorD &auxInfo)
void setRep (const AbsTrackRep *rep)
double extrapolateToPlane (const SharedPlanePtr &plane, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToLine (const TVector3 &linePoint, const TVector3 &lineDirection, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToPoint (const TVector3 &point, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToPoint (const TVector3 &point, const TMatrixDSym &G, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToCylinder (double radius, const TVector3 &linePoint=TVector3(0., 0., 0.), const TVector3 &lineDirection=TVector3(0., 0., 1.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToCone (double openingAngle, const TVector3 &conePoint=TVector3(0., 0., 0.), const TVector3 &coneDirection=TVector3(0., 0., 1.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToSphere (double radius, const TVector3 &point=TVector3(0., 0., 0.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateBy (double step, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToMeasurement (const AbsMeasurement *measurement, bool stopAtBoundary=false, bool calcJacobianNoise=false)
TVector3 getPos () const
TVector3 getMom () const
TVector3 getDir () const
void getPosMom (TVector3 &pos, TVector3 &mom) const
void getPosDir (TVector3 &pos, TVector3 &dir) const
TVectorD get6DState () const
double getMomMag () const
int getPDG () const
double getCharge () const
double getQop () const
double getMass () const
double getTime () const
void setPosMom (const TVector3 &pos, const TVector3 &mom)
void setPosMom (const TVectorD &state6)
void setChargeSign (double charge)
void setQop (double qop)
void setTime (double time)
Protected Attributes
double chiSquareIncrement_
double ndf_
Degrees of freedom. Needs to be a double because of DAF.
Protected Attributes inherited from genfit::MeasuredStateOnPlane
TMatrixDSym cov_
Protected Attributes inherited from genfit::StateOnPlane
TVectorD state_
TVectorD auxInfo_
SharedPlanePtr sharedPlane_
Detailed Description
MeasuredStateOnPlane with additional info produced by a Kalman filter or DAF.
Definition at line 35 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 35 of file KalmanFittedStateOnPlane.h
Constructor & Destructor Documentation
genfit::KalmanFittedStateOnPlane::KalmanFittedStateOnPlane () inline
Definition at line 71 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 71 of file KalmanFittedStateOnPlane.h
genfit::KalmanFittedStateOnPlane::KalmanFittedStateOnPlane (const TVectorD & state, const TMatrixDSym & cov, const SharedPlanePtr & plane, const AbsTrackRep * rep, double chiSquareIncrement, double ndf) inline
Definition at line 77 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 77 of file KalmanFittedStateOnPlane.h
genfit::KalmanFittedStateOnPlane::KalmanFittedStateOnPlane (const TVectorD & state, const TMatrixDSym & cov, const SharedPlanePtr & plane, const AbsTrackRep * rep, const TVectorD & auxInfo, double chiSquareIncrement, double ndf) inline
Definition at line 83 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 83 of file KalmanFittedStateOnPlane.h
genfit::KalmanFittedStateOnPlane::KalmanFittedStateOnPlane (const MeasuredStateOnPlane & state, double chiSquareIncrement, double ndf) inline
Definition at line 89 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 89 of file KalmanFittedStateOnPlane.h
virtual genfit::KalmanFittedStateOnPlane::~KalmanFittedStateOnPlane () inline virtual
Definition at line 47 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 47 of file KalmanFittedStateOnPlane.h
Member Function Documentation
double genfit::KalmanFittedStateOnPlane::getChiSquareIncrement () const inline
Definition at line 49 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 49 of file KalmanFittedStateOnPlane.h
References chiSquareIncrement_.
Referenced by genfit::KalmanFitterRefTrack::fitTrack(), and genfit::AbsKalmanFitter::getChiSquNdf().
double genfit::KalmanFittedStateOnPlane::getNdf () const inline
Definition at line 50 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 50 of file KalmanFittedStateOnPlane.h
References ndf_.
Referenced by genfit::KalmanFitterRefTrack::fitTrack(), and genfit::AbsKalmanFitter::getChiSquNdf().
KalmanFittedStateOnPlane & genfit::KalmanFittedStateOnPlane::operator= (KalmanFittedStateOnPlane other) inline
Definition at line 95 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 95 of file KalmanFittedStateOnPlane.h
References swap().
void genfit::KalmanFittedStateOnPlane::setChiSquareIncrement (double chiSquareIncrement) inline
Definition at line 52 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 52 of file KalmanFittedStateOnPlane.h
References chiSquareIncrement_.
void genfit::KalmanFittedStateOnPlane::setNdf (double ndf) inline
Definition at line 53 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 53 of file KalmanFittedStateOnPlane.h
References ndf_.
void genfit::KalmanFittedStateOnPlane::swap (KalmanFittedStateOnPlane & other) inline
Definition at line 100 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 100 of file KalmanFittedStateOnPlane.h
References chiSquareIncrement_, ndf_, genfit::MeasuredStateOnPlane::swap(), and boost::swap().
Referenced by operator=().
Member Data Documentation
double genfit::KalmanFittedStateOnPlane::chiSquareIncrement_ protected
Definition at line 58 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 58 of file KalmanFittedStateOnPlane.h
Referenced by getChiSquareIncrement(), setChiSquareIncrement(), and swap().
double genfit::KalmanFittedStateOnPlane::ndf_ protected
Degrees of freedom. Needs to be a double because of DAF.
Definition at line 61 of file KalmanFittedStateOnPlane.h.
View newest version in sPHENIX GitHub at line 61 of file KalmanFittedStateOnPlane.h
Referenced by getNdf(), setNdf(), and swap().
The documentation for this class was generated from the following file:
GenFit/blob/master/fitters/include/KalmanFittedStateOnPlane.h