Analysis Software: genfit::RKTools Namespace Reference
genfit::RKTools Namespace Reference
Array matrix multiplications used in RKTrackRep.
Functions
void J_pMTxcov5xJ_pM (const M5x7 &J_pM, const M5x5 &cov5, M7x7 &out7)
void J_MpTxcov7xJ_Mp (const M7x5 &J_Mp, const M7x7 &cov7, M5x5 &out5)
void J_MpTxcov6xJ_Mp (const M6x5 &J_Mp, const M6x6 &cov6, M5x5 &out5)
void J_pMTTxJ_MMTTxJ_MpTT (const M7x5 &J_pMT, const M7x7 &J_MMT, const M5x7 &J_MpT, M5x5 &J_pp)
void Np_N_NpT (const M7x7 &Np, M7x7 &N)
void printDim (const double *mat, unsigned int dimX, unsigned int dimY)
Detailed Description
Array matrix multiplications used in RKTrackRep.
Function Documentation
void genfit::RKTools::J_MpTxcov6xJ_Mp (const M6x5 & J_Mp, const M6x6 & cov6, M5x5 & out5)
Definition at line 261 of file RKTools.cc.
View newest version in sPHENIX GitHub at line 261 of file RKTools.cc
References i.
Referenced by genfit::RKTrackRep::transformM6P().
void genfit::RKTools::J_MpTxcov7xJ_Mp (const M7x5 & J_Mp, const M7x7 & cov7, M5x5 & out5)
Definition at line 189 of file RKTools.cc.
View newest version in sPHENIX GitHub at line 189 of file RKTools.cc
References i.
Referenced by genfit::RKTrackRep::calcForwardJacobianAndNoise().
void genfit::RKTools::J_pMTTxJ_MMTTxJ_MpTT (const M7x5 & J_pMT, const M7x7 & J_MMT, const M5x7 & J_MpT, M5x5 & J_pp)
Definition at line 335 of file RKTools.cc.
View newest version in sPHENIX GitHub at line 335 of file RKTools.cc
Referenced by genfit::RKTrackRep::calcForwardJacobianAndNoise().
void genfit::RKTools::J_pMTxcov5xJ_pM (const M5x7 & J_pM, const M5x5 & cov5, M7x7 & out7)
Definition at line 31 of file RKTools.cc.
View newest version in sPHENIX GitHub at line 31 of file RKTools.cc
References i.
Referenced by genfit::RKTrackRep::transformPM6().
void genfit::RKTools::Np_N_NpT (const M7x7 & Np, M7x7 & N)
Definition at line 432 of file RKTools.cc.
View newest version in sPHENIX GitHub at line 432 of file RKTools.cc
Referenced by genfit::RKTrackRep::Extrap().
void genfit::RKTools::printDim (const double * mat, unsigned int dimX, unsigned int dimY)
Definition at line 497 of file RKTools.cc.
View newest version in sPHENIX GitHub at line 497 of file RKTools.cc
References i, j, printf(), and genfit::printOut.
Referenced by genfit::RKTrackRep::Extrap(), and genfit::RKMatrix< nRows, nCols >::print().