Analysis Software: KFPVertex Class Reference
KFPVertex Class Reference
A scalar class for storage of the vertex in the cartesian parametrisation.
#include <KFParticle/blob/master/KFParticle/KFPVertex.h>
Public Member Functions
KFPVertex ()
~KFPVertex ()
float GetX () const
Returns X coordinate of the vertex.
float GetY () const
Returns Y coordinate of the vertex.
float GetZ () const
Returns Z coordinate of the vertex.
void GetXYZ (float *position) const
void GetXYZ (double *position) const
void GetCovarianceMatrix (float *covmatrix) const
void GetCovarianceMatrix (double *covmatrix) const
float GetChi2perNDF () const
Returns Chi2/NDF of the vertex, NDF is a number of degrees of freedom.
float GetChi2 () const
Returns Chi2 of the vertex fit.
int GetNDF () const
Returns number of degrees of freedom of the vertex.
int GetNContributors () const
Returns number of tracks which were used for construction of the vertex.
float GetParameter (int i) const
Returns parameter "i" of the vertex.
float GetCovariance (int i) const
Returns element of the covariance matrix "i" of the vertex.
void SetXYZ (float *position)
void SetXYZ (float x, float y, float z)
void SetX (float x)
Sets X coordinate of the vertex.
void SetY (float y)
Sets Y coordinate of the vertex.
void SetZ (float z)
Sets Z coordinate of the vertex.
void SetChi2 (float chi)
Sets Chi2 of the vertex.
void SetNDF (int ndf)
Sets number of degrees of freedom of the vertex.
void SetNContributors (int nc)
Sets number of tracks which were used for construction of the vertex.
void SetCovarianceMatrix (float *C)
void SetCovarianceMatrix (float C00, float C10, float C11, float C20, float C21, float C22)
Private Attributes
float fP [3]
Coordinates of the vertex.
float fC [6]
Covariance matrix of the vertex parameters.
float fChi2
Chi-square of the vertex fit.
int fNContributors
Number of tracks, from which the vertex was built.
int fNDF
Number of degrees of freedom of the vertex fit.
Detailed Description
A scalar class for storage of the vertex in the cartesian parametrisation.
Author
M.Zyzak, I.Kisel
Date
05.02.2019
Version
1.0
A vertex is described with the state vector { X, Y, Z } and the corresponding covariance matrix. Also contains chi2 of the fit, corresponding number of degrees of freedom, and number of tracks which were used to construct current vertex. The class is used to provide an external vertex through the interfaces to the KF Particle package.
Definition at line 39 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 39 of file KFPVertex.h
Constructor & Destructor Documentation
KFPVertex::KFPVertex ()
Definition at line 24 of file KFPVertex.cxx.
View newest version in sPHENIX GitHub at line 24 of file KFPVertex.cxx
References fC, and fP.
KFPVertex::~KFPVertex () inline
Definition at line 43 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 43 of file KFPVertex.h
Member Function Documentation
float KFPVertex::GetChi2 () const inline
Returns Chi2 of the vertex fit.
Definition at line 74 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 74 of file KFPVertex.h
References fChi2.
Referenced by KFParticle::KFParticle(), KFParticleSIMD::KFParticleSIMD(), and KFVertex::KFVertex().
float KFPVertex::GetChi2perNDF () const inline
Returns Chi2/NDF of the vertex, NDF is a number of degrees of freedom.
Definition at line 73 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 73 of file KFPVertex.h
References fChi2, and fNDF.
float KFPVertex::GetCovariance (int i) const inline
Returns element of the covariance matrix "i" of the vertex.
Parameters
[in] i - index of the element to be returned
Definition at line 79 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 79 of file KFPVertex.h
References fC, and i.
void KFPVertex::GetCovarianceMatrix (float * covmatrix) const inline
Copies the covariance matrix of the vertex to the array of floats.
Parameters
[out] covmatrix[6] - the output array, where the covariance matrix is copied
Definition at line 56 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 56 of file KFPVertex.h
References fC, and i.
Referenced by KFParticle::KFParticle(), KFParticleSIMD::KFParticleSIMD(), and KFVertex::KFVertex().
void KFPVertex::GetCovarianceMatrix (double * covmatrix) const inline
Copies the covariance matrix of the vertex to the array of doubles.
Parameters
[out] covmatrix[6] - the output array, where the covariance matrix is copied
Definition at line 64 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 64 of file KFPVertex.h
References fC, and i.
int KFPVertex::GetNContributors () const inline
Returns number of tracks which were used for construction of the vertex.
Definition at line 76 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 76 of file KFPVertex.h
References fNContributors.
Referenced by KFParticle::KFParticle(), KFParticleSIMD::KFParticleSIMD(), and KFVertex::KFVertex().
int KFPVertex::GetNDF () const inline
Returns number of degrees of freedom of the vertex.
Definition at line 75 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 75 of file KFPVertex.h
References fNDF.
float KFPVertex::GetParameter (int i) const inline
Returns parameter "i" of the vertex.
Parameters
[in] i - index of the parameter to be returned
Definition at line 78 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 78 of file KFPVertex.h
References fP, and i.
float KFPVertex::GetX () const inline
Returns X coordinate of the vertex.
Definition at line 48 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 48 of file KFPVertex.h
References fP.
void KFPVertex::GetXYZ (float * position) const inline
Copies position of the vertex to the output array of floats.
Parameters
[out] position - the output array with the position of the vertex
Definition at line 53 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 53 of file KFPVertex.h
References fP.
Referenced by KFParticle::KFParticle(), KFParticleSIMD::KFParticleSIMD(), and KFVertex::KFVertex().
void KFPVertex::GetXYZ (double * position) const inline
Copies position of the vertex to the output array of doubles.
Parameters
[out] position - the output array with the position of the vertex
Definition at line 55 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 55 of file KFPVertex.h
References fP.
float KFPVertex::GetY () const inline
Returns Y coordinate of the vertex.
Definition at line 49 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 49 of file KFPVertex.h
References fP.
float KFPVertex::GetZ () const inline
Returns Z coordinate of the vertex.
Definition at line 50 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 50 of file KFPVertex.h
References fP.
void KFPVertex::SetChi2 (float chi) inline
Sets Chi2 of the vertex.
Definition at line 94 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 94 of file KFPVertex.h
References fChi2.
Referenced by KFParticlePVReconstructor::ReconstructPrimVertex(), and KFParticleTest::RunTestSingle().
void KFPVertex::SetCovarianceMatrix (float * C) inline
Sets the covariance matrix from the input array of floats.
Parameters
[in] C[6] - array with the input elements of the covariance matrix stored in the lower triangular form
Definition at line 98 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 98 of file KFPVertex.h
References fC, and i.
Referenced by KFParticlePVReconstructor::ReconstructPrimVertex(), and KFParticleTest::RunTestSingle().
void KFPVertex::SetCovarianceMatrix (float C00, float C10, float C11, float C20, float C21, float C22) inline
Sets the covariance matrix from the input array of floats.
Parameters
[in] C00 - Cxx
[in] C10 - Cxy = Cyx
[in] C11 - Cyy
[in] C20 - Cxz = Czx
[in] C21 - Cyz = Czy
[in] C22 - Czz
Definition at line 107 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 107 of file KFPVertex.h
References fC.
void KFPVertex::SetNContributors (int nc) inline
Sets number of tracks which were used for construction of the vertex.
Definition at line 96 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 96 of file KFPVertex.h
References fNContributors.
Referenced by KFParticlePVReconstructor::ReconstructPrimVertex(), and KFParticleTest::RunTestSingle().
void KFPVertex::SetNDF (int ndf) inline
Sets number of degrees of freedom of the vertex.
Definition at line 95 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 95 of file KFPVertex.h
References fNDF.
void KFPVertex::SetX (float x) inline
Sets X coordinate of the vertex.
Definition at line 91 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 91 of file KFPVertex.h
References fP, and x.
void KFPVertex::SetXYZ (float * position) inline
Sets position { X, Y, Z } of the vertex from the input array of doubles.
Parameters
[in] position - input array with the vertex parameters
Definition at line 84 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 84 of file KFPVertex.h
References fP.
Referenced by KFParticlePVReconstructor::ReconstructPrimVertex(), and KFParticleTest::RunTestSingle().
void KFPVertex::SetXYZ (float x, float y, float z) inline
Sets position { X, Y, Z } of the vertex.
Parameters
[in] x - X coordinate to be set
[in] y - Y coordinate to be set
[in] z - Z coordinate to be set
Definition at line 90 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 90 of file KFPVertex.h
References fP, x, y, and z.
void KFPVertex::SetY (float y) inline
Sets Y coordinate of the vertex.
Definition at line 92 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 92 of file KFPVertex.h
References fP, and y.
void KFPVertex::SetZ (float z) inline
Sets Z coordinate of the vertex.
Definition at line 93 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 93 of file KFPVertex.h
References fP, and z.
Member Data Documentation
float KFPVertex::fC[6] private
Covariance matrix of the vertex parameters.
Definition at line 128 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 128 of file KFPVertex.h
Referenced by GetCovariance(), GetCovarianceMatrix(), KFPVertex(), and SetCovarianceMatrix().
float KFPVertex::fChi2 private
Chi-square of the vertex fit.
Definition at line 129 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 129 of file KFPVertex.h
Referenced by GetChi2(), GetChi2perNDF(), and SetChi2().
int KFPVertex::fNContributors private
Number of tracks, from which the vertex was built.
Definition at line 130 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 130 of file KFPVertex.h
Referenced by GetNContributors(), and SetNContributors().
int KFPVertex::fNDF private
Number of degrees of freedom of the vertex fit.
Definition at line 131 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 131 of file KFPVertex.h
Referenced by GetChi2perNDF(), GetNDF(), and SetNDF().
float KFPVertex::fP[3] private
Coordinates of the vertex.
Definition at line 127 of file KFPVertex.h.
View newest version in sPHENIX GitHub at line 127 of file KFPVertex.h
Referenced by GetParameter(), GetX(), GetXYZ(), GetY(), GetZ(), KFPVertex(), SetX(), SetXYZ(), SetY(), and SetZ().
The documentation for this class was generated from the following files:
KFParticle/blob/master/KFParticle/KFPVertex.h
KFParticle/blob/master/KFParticle/KFPVertex.cxx