Analysis Software: PHGenFit::Fitter Class Reference
PHGenFit::Fitter Class Reference
#include <coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/Fitter.h>
Public Types
enum FitterType { KalmanFitter, KalmanFitterRefTrack, DafSimple, DafRef }
enum TrackRepType { RKTrackRep }
Public Member Functions
Fitter (const std::string &tgeo_file_name, const PHField *field, const std::string &fitter_choice="KalmanFitterRefTrack", const std::string &track_rep_choice="RKTrackRep", const bool doEventDisplay=false)
Default constructor.
Fitter (TGeoManager *tgeo_manager, genfit::AbsBField *fieldMap, const std::string &fitter_choice="KalmanFitterRefTrack", const std::string &track_rep_choice="RKTrackRep", const bool doEventDisplay=false)
Fitter (TGeoManager *tgeo_manager, genfit::AbsBField *fieldMap, const PHGenFit::Fitter::FitterType &fitter_choice=PHGenFit::Fitter::KalmanFitter, const PHGenFit::Fitter::TrackRepType &track_rep_choice=PHGenFit::Fitter::RKTrackRep, const bool doEventDisplay=false)
~Fitter ()
Default destructor.
int processTrack (PHGenFit::Track *track, const bool save_to_evt_disp=false)
int displayEvent ()
bool is_do_Event_Display () const
void set_do_Event_Display (bool doEventDisplay)
genfit::EventDisplay * getEventDisplay ()
int get_verbosity () const
void set_verbosity (int verbosity)
Static Public Member Functions
static Fitter * getInstance (const std::string &tgeo_file_name, const PHField *field, const std::string &fitter_choice="KalmanFitterRefTrack", const std::string &track_rep_choice="RKTrackRep", const bool doEventDisplay=false)
static Fitter * getInstance (TGeoManager *tgeo_manager, const PHField *field, const std::string &fitter_choice="KalmanFitterRefTrack", const std::string &track_rep_choice="RKTrackRep", const bool doEventDisplay=false)
static Fitter * getInstance (TGeoManager *tgeo_manager, const PHField *field, const PHGenFit::Fitter::FitterType &fitter_choice=PHGenFit::Fitter::KalmanFitter, const PHGenFit::Fitter::TrackRepType &track_rep_choice=PHGenFit::Fitter::RKTrackRep, const bool doEventDisplay=false)
Private Attributes
int verbosity
TGeoManager * _tgeo_manager
bool _doEventDisplay
genfit::EventDisplay * _display
genfit::AbsKalmanFitter * _fitter
Detailed Description
Definition at line 45 of file Fitter.h.
View newest version in sPHENIX GitHub at line 45 of file Fitter.h
Member Enumeration Documentation
enum PHGenFit::Fitter::FitterType
Enumerator:
KalmanFitter
KalmanFitterRefTrack
DafSimple
DafRef
Definition at line 48 of file Fitter.h.
View newest version in sPHENIX GitHub at line 48 of file Fitter.h
enum PHGenFit::Fitter::TrackRepType
Enumerator:
RKTrackRep
Definition at line 55 of file Fitter.h.
View newest version in sPHENIX GitHub at line 55 of file Fitter.h
Constructor & Destructor Documentation
PHGenFit::Fitter::Fitter (const std::string & tgeo_file_name, const PHField * field, const std::string & fitter_choice = "KalmanFitterRefTrack", const std::string & track_rep_choice = "RKTrackRep", const bool doEventDisplay = false)
Default constructor.
Definition at line 44 of file Fitter.cc.
View newest version in sPHENIX GitHub at line 44 of file Fitter.cc
References _display, _doEventDisplay, _fitter, _tgeo_manager, assert, genfit::MaterialEffects::getInstance(), genfit::EventDisplay::getInstance(), genfit::FieldManager::getInstance(), genfit::MaterialEffects::init(), genfit::FieldManager::init(), and genfit::Exception::quiet().
Referenced by getInstance().
PHGenFit::Fitter::Fitter (TGeoManager * tgeo_manager, genfit::AbsBField * fieldMap, const std::string & fitter_choice = "KalmanFitterRefTrack", const std::string & track_rep_choice = "RKTrackRep", const bool doEventDisplay = false)
Definition at line 238 of file Fitter.cc.
View newest version in sPHENIX GitHub at line 238 of file Fitter.cc
References _display, _doEventDisplay, _fitter, genfit::MaterialEffects::getInstance(), genfit::EventDisplay::getInstance(), genfit::FieldManager::getInstance(), genfit::MaterialEffects::init(), genfit::FieldManager::init(), and LogERROR.
PHGenFit::Fitter::Fitter (TGeoManager * tgeo_manager, genfit::AbsBField * fieldMap, const PHGenFit::Fitter::FitterType & fitter_choice = PHGenFit::Fitter::KalmanFitter, const PHGenFit::Fitter::TrackRepType & track_rep_choice = PHGenFit::Fitter::RKTrackRep, const bool doEventDisplay = false)
Definition at line 187 of file Fitter.cc.
View newest version in sPHENIX GitHub at line 187 of file Fitter.cc
References _display, _doEventDisplay, _fitter, DafRef, DafSimple, genfit::MaterialEffects::getInstance(), genfit::EventDisplay::getInstance(), genfit::FieldManager::getInstance(), genfit::MaterialEffects::init(), genfit::FieldManager::init(), KalmanFitter, KalmanFitterRefTrack, and LogERROR.
PHGenFit::Fitter::~Fitter ()
Default destructor.
Definition at line 85 of file Fitter.cc.
View newest version in sPHENIX GitHub at line 85 of file Fitter.cc
References _display, _fitter, and _tgeo_manager.
Member Function Documentation
int PHGenFit::Fitter::displayEvent ()
Definition at line 272 of file Fitter.cc.
View newest version in sPHENIX GitHub at line 272 of file Fitter.cc
References _display, LogERROR, genfit::EventDisplay::open(), and verbosity.
Referenced by TpcPrototypeGenFitTrkFinder::End(), PHGenFitTrkProp::End(), PHG4TrackFastSim::End(), TpcPrototypeGenFitTrkFitter::End(), and PHGenFitTrkFitter::End().
int PHGenFit::Fitter::get_verbosity () const inline
Definition at line 121 of file Fitter.h.
View newest version in sPHENIX GitHub at line 121 of file Fitter.h
References verbosity.
genfit::EventDisplay* PHGenFit::Fitter::getEventDisplay () inline
Definition at line 116 of file Fitter.h.
View newest version in sPHENIX GitHub at line 116 of file Fitter.h
References _display.
Referenced by TpcPrototypeGenFitTrkFinder::End(), TpcPrototypeGenFitTrkFitter::End(), PHGenFitTrkProp::KalmanTrkProp(), PHG4TrackFastSim::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), and PHGenFitTrkFitter::process_event().
Fitter * PHGenFit::Fitter::getInstance (const std::string & tgeo_file_name, const PHField * field, const std::string & fitter_choice = "KalmanFitterRefTrack", const std::string & track_rep_choice = "RKTrackRep", const bool doEventDisplay = false) static
Definition at line 170 of file Fitter.cc.
View newest version in sPHENIX GitHub at line 170 of file Fitter.cc
References assert, Fitter(), and LogERROR.
Referenced by PHGenFitTrkProp::InitializePHGenFit(), PHGenFitTrackProjection::InitRun(), TpcPrototypeGenFitTrkFinder::InitRun(), SVReco::InitRun(), GenFitTrackProp::InitRun(), PHRaveVertexing::InitRun(), BDiJetModule::InitRun(), PHG4TrackFastSim::InitRun(), TpcPrototypeGenFitTrkFitter::InitRun(), PHGenFitTrkFitter::InitRun(), TrackProjectorPid::TrackProjectorPid(), and TrackProjectorPlaneECAL::TrackProjectorPlaneECAL().
Fitter * PHGenFit::Fitter::getInstance (TGeoManager * tgeo_manager, const PHField * field, const std::string & fitter_choice = "KalmanFitterRefTrack", const std::string & track_rep_choice = "RKTrackRep", const bool doEventDisplay = false) static
Definition at line 222 of file Fitter.cc.
View newest version in sPHENIX GitHub at line 222 of file Fitter.cc
References assert, Fitter(), and LogERROR.
Fitter * PHGenFit::Fitter::getInstance (TGeoManager * tgeo_manager, const PHField * field, const PHGenFit::Fitter::FitterType & fitter_choice = PHGenFit::Fitter::KalmanFitter, const PHGenFit::Fitter::TrackRepType & track_rep_choice = PHGenFit::Fitter::RKTrackRep, const bool doEventDisplay = false) static
Definition at line 282 of file Fitter.cc.
View newest version in sPHENIX GitHub at line 282 of file Fitter.cc
References assert, Fitter(), and LogERROR.
bool PHGenFit::Fitter::is_do_Event_Display () const inline
Definition at line 104 of file Fitter.h.
View newest version in sPHENIX GitHub at line 104 of file Fitter.h
References _doEventDisplay.
int PHGenFit::Fitter::processTrack (PHGenFit::Track * track, const bool save_to_evt_disp = false)
Definition at line 96 of file Fitter.cc.
View newest version in sPHENIX GitHub at line 96 of file Fitter.cc
References _display, _fitter, genfit::EventDisplay::addEvent(), genfit::Track::checkConsistency(), genfit::Track::getCardinalRep(), genfit::Track::getFitStatus(), PHGenFit::Track::getGenFitTrack(), genfit::FitStatus::isFitConverged(), LogWARNING, genfit::AbsFitter::processTrack(), verbosity, and genfit::Exception::what().
Referenced by TpcPrototypeGenFitTrkFitter::DisplayCluster(), TpcPrototypeGenFitTrkFinder::getChi2Ndf(), main(), BDiJetModule::MakeGenFitTrack(), SVReco::MakeGenFitTrack(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), PHGenFitTrkProp::OutputPHGenFitTrack(), PHG4TrackFastSim::process_event(), PHGenFitTrkFitter::ReFitTrack(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkProp::SvtxTrackToPHGenFitTracks().
void PHGenFit::Fitter::set_do_Event_Display (bool doEventDisplay) inline
Definition at line 109 of file Fitter.h.
View newest version in sPHENIX GitHub at line 109 of file Fitter.h
References _display, _doEventDisplay, and genfit::EventDisplay::getInstance().
void PHGenFit::Fitter::set_verbosity (int verbosity) inline
Definition at line 126 of file Fitter.h.
View newest version in sPHENIX GitHub at line 126 of file Fitter.h
References genfit::Exception::quiet(), and verbosity.
Referenced by PHGenFitTrkProp::InitializePHGenFit(), PHGenFitTrackProjection::InitRun(), TpcPrototypeGenFitTrkFinder::InitRun(), GenFitTrackProp::InitRun(), PHRaveVertexing::InitRun(), PHG4TrackFastSim::InitRun(), TpcPrototypeGenFitTrkFitter::InitRun(), PHGenFitTrkFitter::InitRun(), TrackProjectorPid::TrackProjectorPid(), and TrackProjectorPlaneECAL::TrackProjectorPlaneECAL().
Member Data Documentation
genfit::EventDisplay* PHGenFit::Fitter::_display private
Definition at line 150 of file Fitter.h.
View newest version in sPHENIX GitHub at line 150 of file Fitter.h
Referenced by displayEvent(), Fitter(), getEventDisplay(), processTrack(), set_do_Event_Display(), and ~Fitter().
bool PHGenFit::Fitter::_doEventDisplay private
Definition at line 148 of file Fitter.h.
View newest version in sPHENIX GitHub at line 148 of file Fitter.h
Referenced by Fitter(), is_do_Event_Display(), and set_do_Event_Display().
genfit::AbsKalmanFitter* PHGenFit::Fitter::_fitter private
Definition at line 151 of file Fitter.h.
View newest version in sPHENIX GitHub at line 151 of file Fitter.h
Referenced by Fitter(), processTrack(), and ~Fitter().
TGeoManager* PHGenFit::Fitter::_tgeo_manager private
Definition at line 146 of file Fitter.h.
View newest version in sPHENIX GitHub at line 146 of file Fitter.h
Referenced by Fitter(), and ~Fitter().
int PHGenFit::Fitter::verbosity private
Verbose control: -1: Silient 0: Minimum 1: Errors only 2: Errors and Warnings 3: Verbose mode, long term debugging
Definition at line 144 of file Fitter.h.
View newest version in sPHENIX GitHub at line 144 of file Fitter.h
Referenced by displayEvent(), get_verbosity(), processTrack(), and set_verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/Fitter.h
coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/Fitter.cc