Analysis Software: genfit::AbsMaterialInterface Class Reference
genfit::AbsMaterialInterface Class Reference abstract
Abstract base class for geometry interfacing.
#include <GenFit/blob/master/trackReps/include/AbsMaterialInterface.h>
Public Member Functions
AbsMaterialInterface ()
virtual ~AbsMaterialInterface ()
virtual bool initTrack (double posX, double posY, double posZ, double dirX, double dirY, double dirZ)=0
Initialize the navigator at given position and with given direction. Return true if volume changed.
virtual Material getMaterialParameters ()=0
virtual double findNextBoundary (const RKTrackRep *rep, const M1x7 &state7, double sMax, bool varField=true)=0
Make a step until maxStep or the next boundary is reached.
virtual void setDebugLvl (unsigned int lvl=1)
Protected Attributes
unsigned int debugLvl_
Detailed Description
Abstract base class for geometry interfacing.
Definition at line 39 of file AbsMaterialInterface.h.
View newest version in sPHENIX GitHub at line 39 of file AbsMaterialInterface.h
Constructor & Destructor Documentation
genfit::AbsMaterialInterface::AbsMaterialInterface () inline
Definition at line 43 of file AbsMaterialInterface.h.
View newest version in sPHENIX GitHub at line 43 of file AbsMaterialInterface.h
virtual genfit::AbsMaterialInterface::~AbsMaterialInterface () inline virtual
Definition at line 44 of file AbsMaterialInterface.h.
View newest version in sPHENIX GitHub at line 44 of file AbsMaterialInterface.h
Member Function Documentation
virtual double genfit::AbsMaterialInterface::findNextBoundary (const RKTrackRep * rep, const M1x7 & state7, double sMax, bool varField = true) pure virtual
Make a step until maxStep or the next boundary is reached.
After making a step to a boundary, the position has to be beyond the boundary, i.e. in the current material has to be that beyond the boundary. The actual step made is returned.
Implemented in genfit::TGeoMaterialInterface.
Referenced by genfit::MaterialEffects::stepper().
virtual Material genfit::AbsMaterialInterface::getMaterialParameters () pure virtual
Implemented in genfit::TGeoMaterialInterface.
Referenced by genfit::MaterialEffects::drawdEdx(), and genfit::MaterialEffects::stepper().
virtual bool genfit::AbsMaterialInterface::initTrack (double posX, double posY, double posZ, double dirX, double dirY, double dirZ) pure virtual
Initialize the navigator at given position and with given direction. Return true if volume changed.
Implemented in genfit::TGeoMaterialInterface.
Referenced by genfit::MaterialEffects::drawdEdx(), and genfit::MaterialEffects::stepper().
virtual void genfit::AbsMaterialInterface::setDebugLvl (unsigned int lvl = 1) inline virtual
Definition at line 68 of file AbsMaterialInterface.h.
View newest version in sPHENIX GitHub at line 68 of file AbsMaterialInterface.h
References debugLvl_.
Referenced by genfit::MaterialEffects::setDebugLvl().
Member Data Documentation
unsigned int genfit::AbsMaterialInterface::debugLvl_ protected
Definition at line 71 of file AbsMaterialInterface.h.
View newest version in sPHENIX GitHub at line 71 of file AbsMaterialInterface.h
Referenced by genfit::TGeoMaterialInterface::findNextBoundary(), genfit::TGeoMaterialInterface::initTrack(), and setDebugLvl().
The documentation for this class was generated from the following file:
GenFit/blob/master/trackReps/include/AbsMaterialInterface.h