Analysis Software: GenFit/blob/master/test/measurementFactoryExample/main.cc File Reference
main.cc File Reference
#include <ConstField.h>
#include <Exception.h>
#include <FieldManager.h>
#include <KalmanFitterRefTrack.h>
#include <StateOnPlane.h>
#include <Track.h>
#include <TrackCand.h>
#include <TrackPoint.h>
#include <MeasurementProducer.h>
#include <MeasurementFactory.h>
#include "mySpacepointDetectorHit.h"
#include "mySpacepointMeasurement.h"
#include <MaterialEffects.h>
#include <RKTrackRep.h>
#include <TGeoMaterialInterface.h>
#include <EventDisplay.h>
#include <HelixTrackModel.h>
#include <MeasurementCreator.h>
#include <TDatabasePDG.h>
#include <TEveManager.h>
#include <TGeoManager.h>
#include <TRandom.h>
#include <TVector3.h>
#include <vector>
#include <TMath.h>
Functions
int main ()
Function Documentation
int main ()
Definition at line 38 of file main.cc.
View newest version in sPHENIX GitHub at line 38 of file main.cc
References genfit::EventDisplay::addEvent(), genfit::TrackCand::addHit(), genfit::MeasurementFactory< measurement_T >::addProducer(), genfit::Track::checkConsistency(), genfit::MaterialEffects::getInstance(), genfit::EventDisplay::getInstance(), genfit::FieldManager::getInstance(), genfit::HelixTrackModel::getPos(), i, genfit::MaterialEffects::init(), genfit::FieldManager::init(), genfit::EventDisplay::open(), pos, genfit::AbsFitter::processTrack(), genfit::TrackCand::setCovSeed(), genfit::TrackCand::setPosMomSeedAndPdgCode(), genfit::MeasurementCreator::setTrackModel(), and genfit::Exception::what().