Analysis Software: genfit::MeasuredStateOnPlane Class Reference
genfit::MeasuredStateOnPlane Class Reference
StateOnPlane with additional covariance matrix.
#include <GenFit/blob/master/core/include/MeasuredStateOnPlane.h>
Public Member Functions
MeasuredStateOnPlane (const AbsTrackRep *rep=nullptr)
MeasuredStateOnPlane (const TVectorD &state, const TMatrixDSym &cov, const genfit::SharedPlanePtr &plane, const AbsTrackRep *rep)
MeasuredStateOnPlane (const TVectorD &state, const TMatrixDSym &cov, const genfit::SharedPlanePtr &plane, const AbsTrackRep *rep, const TVectorD &auxInfo)
MeasuredStateOnPlane (const MeasuredStateOnPlane &o)
MeasuredStateOnPlane (const StateOnPlane &state, const TMatrixDSym &cov)
MeasuredStateOnPlane & operator= (MeasuredStateOnPlane other)
void swap (MeasuredStateOnPlane &other)
virtual ~MeasuredStateOnPlane ()
virtual MeasuredStateOnPlane * clone () const override
const TMatrixDSym & getCov () const
TMatrixDSym & getCov ()
void blowUpCov (double blowUpFac, bool resetOffDiagonals=true, double maxVal=-1.)
Blow up covariance matrix with blowUpFac. Per default, off diagonals are reset to 0 and the maximum values are limited to maxVal.
void setStateCov (const TVectorD &state, const TMatrixDSym &cov)
void setStateCovPlane (const TVectorD &state, const TMatrixDSym &cov, const SharedPlanePtr &plane)
void setCov (const TMatrixDSym &cov)
TMatrixDSym get6DCov () const
void getPosMomCov (TVector3 &pos, TVector3 &mom, TMatrixDSym &cov) const
void get6DStateCov (TVectorD &stateVec, TMatrixDSym &cov) const
double getMomVar () const
void setPosMomErr (const TVector3 &pos, const TVector3 &mom, const TVector3 &posErr, const TVector3 &momErr)
void setPosMomCov (const TVector3 &pos, const TVector3 &mom, const TMatrixDSym &cov6x6)
void setPosMomCov (const TVectorD &state6, const TMatrixDSym &cov6x6)
virtual void Print (Option_t *option="") const override
Public Member Functions inherited from genfit::StateOnPlane
StateOnPlane (const AbsTrackRep *rep=nullptr)
StateOnPlane (const TVectorD &state, const SharedPlanePtr &plane, const AbsTrackRep *rep)
state is defined by the TrackReps parameterization
StateOnPlane (const TVectorD &state, const SharedPlanePtr &plane, const AbsTrackRep *rep, const TVectorD &auxInfo)
StateOnPlane & operator= (StateOnPlane other)
void swap (StateOnPlane &other)
virtual ~StateOnPlane ()
const TVectorD & getState () const
TVectorD & getState ()
const TVectorD & getAuxInfo () const
TVectorD & getAuxInfo ()
const SharedPlanePtr & getPlane () const
const AbsTrackRep * getRep () const
void setState (const TVectorD &state)
void setPlane (const SharedPlanePtr &plane)
void setStatePlane (const TVectorD &state, const SharedPlanePtr &plane)
void setAuxInfo (const TVectorD &auxInfo)
void setRep (const AbsTrackRep *rep)
double extrapolateToPlane (const SharedPlanePtr &plane, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToLine (const TVector3 &linePoint, const TVector3 &lineDirection, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToPoint (const TVector3 &point, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToPoint (const TVector3 &point, const TMatrixDSym &G, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToCylinder (double radius, const TVector3 &linePoint=TVector3(0., 0., 0.), const TVector3 &lineDirection=TVector3(0., 0., 1.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToCone (double openingAngle, const TVector3 &conePoint=TVector3(0., 0., 0.), const TVector3 &coneDirection=TVector3(0., 0., 1.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToSphere (double radius, const TVector3 &point=TVector3(0., 0., 0.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateBy (double step, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToMeasurement (const AbsMeasurement *measurement, bool stopAtBoundary=false, bool calcJacobianNoise=false)
TVector3 getPos () const
TVector3 getMom () const
TVector3 getDir () const
void getPosMom (TVector3 &pos, TVector3 &mom) const
void getPosDir (TVector3 &pos, TVector3 &dir) const
TVectorD get6DState () const
double getMomMag () const
int getPDG () const
double getCharge () const
double getQop () const
double getMass () const
double getTime () const
void setPosMom (const TVector3 &pos, const TVector3 &mom)
void setPosMom (const TVectorD &state6)
void setChargeSign (double charge)
void setQop (double qop)
void setTime (double time)
Protected Attributes
TMatrixDSym cov_
Protected Attributes inherited from genfit::StateOnPlane
TVectorD state_
TVectorD auxInfo_
SharedPlanePtr sharedPlane_
Detailed Description
StateOnPlane with additional covariance matrix.
Definition at line 39 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 39 of file MeasuredStateOnPlane.h
Constructor & Destructor Documentation
genfit::MeasuredStateOnPlane::MeasuredStateOnPlane (const AbsTrackRep * rep = nullptr) inline
Definition at line 101 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 101 of file MeasuredStateOnPlane.h
References cov_, and genfit::AbsTrackRep::getDim().
Referenced by clone().
genfit::MeasuredStateOnPlane::MeasuredStateOnPlane (const TVectorD & state, const TMatrixDSym & cov, const genfit::SharedPlanePtr & plane, const AbsTrackRep * rep) inline
Definition at line 109 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 109 of file MeasuredStateOnPlane.h
References assert.
genfit::MeasuredStateOnPlane::MeasuredStateOnPlane (const TVectorD & state, const TMatrixDSym & cov, const genfit::SharedPlanePtr & plane, const AbsTrackRep * rep, const TVectorD & auxInfo) inline
Definition at line 116 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 116 of file MeasuredStateOnPlane.h
References assert.
genfit::MeasuredStateOnPlane::MeasuredStateOnPlane (const MeasuredStateOnPlane & o) inline
Definition at line 123 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 123 of file MeasuredStateOnPlane.h
genfit::MeasuredStateOnPlane::MeasuredStateOnPlane (const StateOnPlane & state, const TMatrixDSym & cov) inline
Definition at line 128 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 128 of file MeasuredStateOnPlane.h
virtual genfit::MeasuredStateOnPlane::~MeasuredStateOnPlane () inline virtual
Definition at line 52 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 52 of file MeasuredStateOnPlane.h
Member Function Documentation
void genfit::MeasuredStateOnPlane::blowUpCov (double blowUpFac, bool resetOffDiagonals = true, double maxVal = -1.)
Blow up covariance matrix with blowUpFac. Per default, off diagonals are reset to 0 and the maximum values are limited to maxVal.
Definition at line 48 of file MeasuredStateOnPlane.cc.
View newest version in sPHENIX GitHub at line 48 of file MeasuredStateOnPlane.cc
References cov_, i, j, and min.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitterRefTrack::processTrackWithRep(), and PHGenFit::Track::updateOneMeasurementKalman().
virtual MeasuredStateOnPlane* genfit::MeasuredStateOnPlane::clone () const inline override virtual
Reimplemented from genfit::StateOnPlane.
Definition at line 53 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 53 of file MeasuredStateOnPlane.h
References MeasuredStateOnPlane().
Referenced by PHGenFit::Track::updateOneMeasurementKalman().
TMatrixDSym genfit::MeasuredStateOnPlane::get6DCov () const inline
Definition at line 67 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 67 of file MeasuredStateOnPlane.h
References genfit::AbsTrackRep::get6DCov(), and genfit::StateOnPlane::getRep().
Referenced by PHG4TrackFastSim::MakeSvtxTrack(), PHGenFitTrkProp::OutputPHGenFitTrack(), PHGenFitTrkProp::TrackPropPatRec(), PHRaveVertexing::TranslateSvtxToGenFitTrack(), and genfit::Track::udpateSeed().
void genfit::MeasuredStateOnPlane::get6DStateCov (TVectorD & stateVec, TMatrixDSym & cov) const inline
Definition at line 69 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 69 of file MeasuredStateOnPlane.h
References genfit::AbsTrackRep::get6DStateCov(), and genfit::StateOnPlane::getRep().
Referenced by main(), and PHGenFit::Track::Track().
const TMatrixDSym& genfit::MeasuredStateOnPlane::getCov () const inline
Definition at line 56 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 56 of file MeasuredStateOnPlane.h
References cov_.
Referenced by genfit::calcAverageState(), genfit::DAF::calcWeights(), checkErrorPropagation(), compareForthBackJacNoise(), genfit::GblFitterInfo::constructGblPoint(), genfit::WirePointMeasurement::constructMeasurementsOnPlane(), genfit::SpacepointMeasurement::constructMeasurementsOnPlane(), genfit::EventDisplay::drawEvent(), genfit::KalmanFitterInfo::getAvgWeightedMeasurementOnPlane(), genfit::RKTrackRep::getMomVar(), genfit::KalmanFitterInfo::getResidual(), genfit::KalmanFitterInfo::getSmoothedChi2(), main(), PHG4TrackFastSim::MakeSvtxTrack(), genfit::KalmanFitter::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::KalmanFitterRefTrack::removeOutdated(), genfit::RKTrackRep::setPosMomErr(), genfit::RKTrackRep::transformM6P(), genfit::RKTrackRep::transformPM6(), and PHGenFit::Track::updateOneMeasurementKalman().
TMatrixDSym& genfit::MeasuredStateOnPlane::getCov () inline
Definition at line 57 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 57 of file MeasuredStateOnPlane.h
References cov_.
double genfit::MeasuredStateOnPlane::getMomVar () const inline
Definition at line 70 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 70 of file MeasuredStateOnPlane.h
References genfit::AbsTrackRep::getMomVar(), and genfit::StateOnPlane::getRep().
void genfit::MeasuredStateOnPlane::getPosMomCov (TVector3 & pos, TVector3 & mom, TMatrixDSym & cov) const inline
Definition at line 68 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 68 of file MeasuredStateOnPlane.h
References genfit::AbsTrackRep::getPosMomCov(), and genfit::StateOnPlane::getRep().
Referenced by genfit::GFTrackToTrack(), and PHG4TrackFastSim::process_event().
MeasuredStateOnPlane & genfit::MeasuredStateOnPlane::operator= (MeasuredStateOnPlane other) inline
Definition at line 134 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 134 of file MeasuredStateOnPlane.h
References swap().
void genfit::MeasuredStateOnPlane::Print (Option_t * option = "") const override virtual
Reimplemented from genfit::StateOnPlane.
Reimplemented in genfit::MeasurementOnPlane.
Definition at line 32 of file MeasuredStateOnPlane.cc.
View newest version in sPHENIX GitHub at line 32 of file MeasuredStateOnPlane.cc
References cov_, genfit::AbsTrackRep::getPosMomCov(), genfit::StateOnPlane::getRep(), pos, genfit::printOut, genfit::StateOnPlane::sharedPlane_, and genfit::StateOnPlane::state_.
Referenced by checkErrorPropagation(), genfit::EventDisplay::drawEvent(), main(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
void genfit::MeasuredStateOnPlane::setCov (const TMatrixDSym & cov) inline
Definition at line 64 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 64 of file MeasuredStateOnPlane.h
References cov_.
Referenced by genfit::calcAverageState(), setStateCov(), and setStateCovPlane().
void genfit::MeasuredStateOnPlane::setPosMomCov (const TVector3 & pos, const TVector3 & mom, const TMatrixDSym & cov6x6) inline
Definition at line 73 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 73 of file MeasuredStateOnPlane.h
References genfit::StateOnPlane::getRep(), and genfit::AbsTrackRep::setPosMomCov().
Referenced by GenFitTrackProp::fill_tree(), main(), genfit::setData(), PHGenFit::Track::Track(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
void genfit::MeasuredStateOnPlane::setPosMomCov (const TVectorD & state6, const TMatrixDSym & cov6x6) inline
Definition at line 74 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 74 of file MeasuredStateOnPlane.h
References genfit::StateOnPlane::getRep(), and genfit::AbsTrackRep::setPosMomCov().
void genfit::MeasuredStateOnPlane::setPosMomErr (const TVector3 & pos, const TVector3 & mom, const TVector3 & posErr, const TVector3 & momErr) inline
Definition at line 72 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 72 of file MeasuredStateOnPlane.h
References genfit::StateOnPlane::getRep(), and genfit::AbsTrackRep::setPosMomErr().
void genfit::MeasuredStateOnPlane::setStateCov (const TVectorD & state, const TMatrixDSym & cov) inline
Definition at line 62 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 62 of file MeasuredStateOnPlane.h
References setCov(), and genfit::StateOnPlane::setState().
void genfit::MeasuredStateOnPlane::setStateCovPlane (const TVectorD & state, const TMatrixDSym & cov, const SharedPlanePtr & plane) inline
Definition at line 63 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 63 of file MeasuredStateOnPlane.h
References setCov(), and genfit::StateOnPlane::setStatePlane().
Referenced by PHGenFit::Track::updateOneMeasurementKalman().
void genfit::MeasuredStateOnPlane::swap (MeasuredStateOnPlane & other) inline
Definition at line 95 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 95 of file MeasuredStateOnPlane.h
References cov_, genfit::StateOnPlane::swap(), and boost::swap().
Referenced by operator=(), genfit::KalmanFittedStateOnPlane::swap(), and genfit::MeasurementOnPlane::swap().
Member Data Documentation
TMatrixDSym genfit::MeasuredStateOnPlane::cov_ protected
Definition at line 81 of file MeasuredStateOnPlane.h.
View newest version in sPHENIX GitHub at line 81 of file MeasuredStateOnPlane.h
Referenced by blowUpCov(), getCov(), genfit::MeasurementOnPlane::getWeightedCov(), MeasuredStateOnPlane(), genfit::MeasurementOnPlane::Print(), Print(), setCov(), and swap().
The documentation for this class was generated from the following files:
GenFit/blob/master/core/include/MeasuredStateOnPlane.h
GenFit/blob/master/core/src/MeasuredStateOnPlane.cc