Analysis Software: genfit::GFRaveVertexFactory Class Reference
genfit::GFRaveVertexFactory Class Reference
Vertex factory for producing GFRaveVertex objects from Track objects.
#include <GenFit/blob/master/GFRave/include/GFRaveVertexFactory.h>
Public Member Functions
GFRaveVertexFactory (int verbosity=0, bool useVacuumPropagator=false)
~GFRaveVertexFactory ()
void findVertices (std::vector< genfit::GFRaveVertex * > *, const std::vector< genfit::Track * > &, bool use_beamspot=false)
void findVertices (std::vector< genfit::GFRaveVertex * > *, const std::vector< genfit::Track * > &, std::vector< genfit::MeasuredStateOnPlane * > &, bool use_beamspot=false)
MeasuredStateOnPlanes will be used (instead of the tracks fitted states) to calculate the rave::Track parameters. takes ownership of MeasuredStateOnPlanes.
void setBeamspot (const TVector3 &pos, const TMatrixDSym &cov)
void setMethod (const std::string &method)
Private Member Functions
void clearMap ()
Private Attributes
std::map< int,
genfit::trackAndState > IdGFTrackStateMap_
rave::VertexFactory * factory_
rave::MagneticField * magneticField_
rave::Propagator * propagator_
Detailed Description
Vertex factory for producing GFRaveVertex objects from Track objects.
The GFRaveVertexFactory is basically a wrapper around the rave::VertexFactory. It takes care of initializing the rave::VertexFactory, building the necessary maps, convert GENFIT to rave objects and vice versa.
Definition at line 64 of file GFRaveVertexFactory.h.
View newest version in sPHENIX GitHub at line 64 of file GFRaveVertexFactory.h
Constructor & Destructor Documentation
genfit::GFRaveVertexFactory::GFRaveVertexFactory (int verbosity = 0, bool useVacuumPropagator = false)
Definition at line 40 of file GFRaveVertexFactory.cc.
View newest version in sPHENIX GitHub at line 40 of file GFRaveVertexFactory.cc
References factory_, IdGFTrackStateMap_, magneticField_, propagator_, and verbosity.
genfit::GFRaveVertexFactory::~GFRaveVertexFactory ()
Definition at line 58 of file GFRaveVertexFactory.cc.
View newest version in sPHENIX GitHub at line 58 of file GFRaveVertexFactory.cc
References clearMap(), factory_, magneticField_, and propagator_.
Member Function Documentation
void genfit::GFRaveVertexFactory::clearMap () private
Definition at line 130 of file GFRaveVertexFactory.cc.
View newest version in sPHENIX GitHub at line 130 of file GFRaveVertexFactory.cc
References i, and IdGFTrackStateMap_.
Referenced by findVertices(), and ~GFRaveVertexFactory().
void genfit::GFRaveVertexFactory::findVertices (std::vector< genfit::GFRaveVertex * > * GFvertices, const std::vector< genfit::Track * > & GFTracks, bool use_beamspot = false)
Definition at line 67 of file GFRaveVertexFactory.cc.
View newest version in sPHENIX GitHub at line 67 of file GFRaveVertexFactory.cc
References clearMap(), factory_, genfit::GFTracksToTracks(), IdGFTrackStateMap_, genfit::RaveToGFVertices(), and genfit::Exception::what().
Referenced by SVReco::findSecondaryVertex(), main(), PHRaveVertexing::process_event(), BDiJetModule::process_event(), PHG4TrackFastSim::process_event(), and PHGenFitTrkFitter::process_event().
void genfit::GFRaveVertexFactory::findVertices (std::vector< genfit::GFRaveVertex * > * GFvertices, const std::vector< genfit::Track * > & GFTracks, std::vector< genfit::MeasuredStateOnPlane * > & GFStates, bool use_beamspot = false)
MeasuredStateOnPlanes will be used (instead of the tracks fitted states) to calculate the rave::Track parameters. takes ownership of MeasuredStateOnPlanes.
Definition at line 89 of file GFRaveVertexFactory.cc.
View newest version in sPHENIX GitHub at line 89 of file GFRaveVertexFactory.cc
References clearMap(), factory_, genfit::GFTracksToTracks(), IdGFTrackStateMap_, genfit::RaveToGFVertices(), and genfit::Exception::what().
void genfit::GFRaveVertexFactory::setBeamspot (const TVector3 & pos, const TMatrixDSym & cov)
Definition at line 112 of file GFRaveVertexFactory.cc.
View newest version in sPHENIX GitHub at line 112 of file GFRaveVertexFactory.cc
References factory_, genfit::TMatrixDSymToCovariance3D(), and genfit::TVector3ToPoint3D().
void genfit::GFRaveVertexFactory::setMethod (const std::string & method)
Set the reconstruction method. See http://projects.hepforge.org/rave/trac/wiki/RaveMethods Smoothing has to be turned on! e.g. kalman-smoothing:1
Definition at line 119 of file GFRaveVertexFactory.cc.
View newest version in sPHENIX GitHub at line 119 of file GFRaveVertexFactory.cc
References factory_.
Referenced by SVReco::findSecondaryVertex(), SVReco::InitRun(), PHRaveVertexing::InitRun(), BDiJetModule::InitRun(), PHG4TrackFastSim::InitRun(), TpcPrototypeGenFitTrkFitter::InitRun(), PHGenFitTrkFitter::InitRun(), main(), and BDiJetModule::process_event().
Member Data Documentation
rave::VertexFactory* genfit::GFRaveVertexFactory::factory_ private
Definition at line 89 of file GFRaveVertexFactory.h.
View newest version in sPHENIX GitHub at line 89 of file GFRaveVertexFactory.h
Referenced by findVertices(), GFRaveVertexFactory(), setBeamspot(), setMethod(), and ~GFRaveVertexFactory().
std::map<int, genfit::trackAndState> genfit::GFRaveVertexFactory::IdGFTrackStateMap_ private
Definition at line 88 of file GFRaveVertexFactory.h.
View newest version in sPHENIX GitHub at line 88 of file GFRaveVertexFactory.h
Referenced by clearMap(), findVertices(), and GFRaveVertexFactory().
rave::MagneticField* genfit::GFRaveVertexFactory::magneticField_ private
Definition at line 90 of file GFRaveVertexFactory.h.
View newest version in sPHENIX GitHub at line 90 of file GFRaveVertexFactory.h
Referenced by GFRaveVertexFactory(), and ~GFRaveVertexFactory().
rave::Propagator* genfit::GFRaveVertexFactory::propagator_ private
Definition at line 91 of file GFRaveVertexFactory.h.
View newest version in sPHENIX GitHub at line 91 of file GFRaveVertexFactory.h
Referenced by GFRaveVertexFactory(), and ~GFRaveVertexFactory().
The documentation for this class was generated from the following files:
GenFit/blob/master/GFRave/include/GFRaveVertexFactory.h
GenFit/blob/master/GFRave/src/GFRaveVertexFactory.cc