Analysis Software: genfit::AbsFitter Class Reference
genfit::AbsFitter Class Reference abstract
Abstract base class for fitters.
#include <GenFit/blob/master/core/include/AbsFitter.h>
Public Member Functions
AbsFitter ()
virtual ~AbsFitter ()
virtual void processTrackWithRep (Track *, const AbsTrackRep *, bool resortHits=false)=0
void processTrack (Track *, bool resortHits=false)
virtual void setDebugLvl (unsigned int lvl=1)
Protected Attributes
unsigned int debugLvl_
Detailed Description
Abstract base class for fitters.
Definition at line 35 of file AbsFitter.h.
View newest version in sPHENIX GitHub at line 35 of file AbsFitter.h
Constructor & Destructor Documentation
genfit::AbsFitter::AbsFitter () inline
Definition at line 37 of file AbsFitter.h.
View newest version in sPHENIX GitHub at line 37 of file AbsFitter.h
virtual genfit::AbsFitter::~AbsFitter () inline virtual
Definition at line 38 of file AbsFitter.h.
View newest version in sPHENIX GitHub at line 38 of file AbsFitter.h
Member Function Documentation
void genfit::AbsFitter::processTrack (Track * tr, bool resortHits = false)
Process all reps. Start with the cardinalRep and resort the hits if necessary (and supported by the fitter)
Definition at line 25 of file AbsFitter.cc.
View newest version in sPHENIX GitHub at line 25 of file AbsFitter.cc
References genfit::Track::checkConsistency(), genfit::Track::getCardinalRep(), genfit::Track::getNumReps(), genfit::Track::getTrackRep(), i, and processTrackWithRep().
Referenced by main(), and PHGenFit::Fitter::processTrack().
virtual void genfit::AbsFitter::processTrackWithRep (Track * , const AbsTrackRep * , bool resortHits = false) pure virtual
Process Track with one AbsTrackRep of the Track. Optionally resort the hits if necessary (and supported by the fitter)
Implemented in genfit::GblFitter, genfit::GFGbl, genfit::DAF, genfit::KalmanFitter, and genfit::KalmanFitterRefTrack.
Referenced by processTrack().
virtual void genfit::AbsFitter::setDebugLvl (unsigned int lvl = 1) inline virtual
Reimplemented in genfit::DAF.
Definition at line 50 of file AbsFitter.h.
View newest version in sPHENIX GitHub at line 50 of file AbsFitter.h
References debugLvl_.
Referenced by genfit::DAF::setDebugLvl().
Member Data Documentation
unsigned int genfit::AbsFitter::debugLvl_ protected
Definition at line 55 of file AbsFitter.h.
View newest version in sPHENIX GitHub at line 55 of file AbsFitter.h
Referenced by genfit::DAF::calcWeights(), genfit::KalmanFitterRefTrack::fitTrack(), genfit::KalmanFitter::fitTrack(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitter::processTrackPartially(), genfit::KalmanFitter::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::KalmanFitterRefTrack::processTrackWithRep(), genfit::KalmanFitter::processTrackWithRep(), genfit::DAF::processTrackWithRep(), genfit::KalmanFitterRefTrack::removeOutdated(), and setDebugLvl().
The documentation for this class was generated from the following files:
GenFit/blob/master/core/include/AbsFitter.h
GenFit/blob/master/core/src/AbsFitter.cc