Analysis Software: genfit::FullMeasurement Class Reference
genfit::FullMeasurement Class Reference
Measurement class implementing a measurement of all track parameters.
#include <GenFit/blob/master/measurements/include/FullMeasurement.h>
Public Member Functions
FullMeasurement (int nDim=5)
FullMeasurement (const MeasuredStateOnPlane &, int detId=-1, int hitId=-1, TrackPoint *trackPoint=nullptr)
virtual ~FullMeasurement ()
virtual AbsMeasurement * clone () const override
Deep copy ctor for polymorphic class.
virtual SharedPlanePtr constructPlane (const StateOnPlane &state) const override
virtual std::vector
< MeasurementOnPlane * > constructMeasurementsOnPlane (const StateOnPlane &state) const override
virtual const AbsHMatrix * constructHMatrix (const AbsTrackRep *) const override
Public Member Functions inherited from genfit::AbsMeasurement
AbsMeasurement ()
AbsMeasurement (int nDims)
AbsMeasurement (const TVectorD &rawHitCoords, const TMatrixDSym &rawHitCov, int detId, int hitId, TrackPoint *trackPoint)
virtual ~AbsMeasurement ()
TrackPoint * getTrackPoint () const
void setTrackPoint (TrackPoint *tp)
const TVectorD & getRawHitCoords () const
const TMatrixDSym & getRawHitCov () const
TVectorD & getRawHitCoords ()
TMatrixDSym & getRawHitCov ()
int getDetId () const
int getHitId () const
virtual bool isLeftRightMeasurement () const
If the AbsMeasurement is a wire hit, the left/right resolution will be used.
virtual int getLeftRightResolution () const
unsigned int getDim () const
void setRawHitCoords (const TVectorD &coords)
void setRawHitCov (const TMatrixDSym &cov)
void setDetId (int detId)
void setHitId (int hitId)
virtual void Print (const Option_t *="") const
Protected Attributes
SharedPlanePtr plane_
Protected Attributes inherited from genfit::AbsMeasurement
TVectorD rawHitCoords_
TMatrixDSym rawHitCov_
int detId_
int hitId_
TrackPoint * trackPoint_
Pointer to TrackPoint where the measurement belongs to.
Additional Inherited Members
Protected Member Functions inherited from genfit::AbsMeasurement
AbsMeasurement (const AbsMeasurement &)
protect from calling copy c'tor from outside the class. Use clone() if you want a copy!
Detailed Description
Measurement class implementing a measurement of all track parameters.
Author
Johannes Rauch (Technische Universität München, original author)
This class can e.g. be used, if the fitted track parameters measured in one subdetector should be put into one "measurement".
Definition at line 42 of file FullMeasurement.h.
View newest version in sPHENIX GitHub at line 42 of file FullMeasurement.h
Constructor & Destructor Documentation
genfit::FullMeasurement::FullMeasurement (int nDim = 5)
Definition at line 31 of file FullMeasurement.cc.
View newest version in sPHENIX GitHub at line 31 of file FullMeasurement.cc
References assert.
Referenced by clone().
genfit::FullMeasurement::FullMeasurement (const MeasuredStateOnPlane & state, int detId = -1, int hitId = -1, TrackPoint * trackPoint = nullptr)
Definition at line 38 of file FullMeasurement.cc.
View newest version in sPHENIX GitHub at line 38 of file FullMeasurement.cc
References assert, genfit::AbsTrackRep::getDim(), genfit::StateOnPlane::getRep(), and genfit::AbsMeasurement::rawHitCoords_.
virtual genfit::FullMeasurement::~FullMeasurement () inline virtual
Definition at line 48 of file FullMeasurement.h.
View newest version in sPHENIX GitHub at line 48 of file FullMeasurement.h
Member Function Documentation
virtual AbsMeasurement* genfit::FullMeasurement::clone () const inline override virtual
Deep copy ctor for polymorphic class.
Implements genfit::AbsMeasurement.
Definition at line 50 of file FullMeasurement.h.
View newest version in sPHENIX GitHub at line 50 of file FullMeasurement.h
References FullMeasurement().
const AbsHMatrix * genfit::FullMeasurement::constructHMatrix (const AbsTrackRep *) const override virtual
Returns a new AbsHMatrix object. Caller must take ownership.
Implements genfit::AbsMeasurement.
Definition at line 66 of file FullMeasurement.cc.
View newest version in sPHENIX GitHub at line 66 of file FullMeasurement.cc
Referenced by constructMeasurementsOnPlane().
std::vector< MeasurementOnPlane * > genfit::FullMeasurement::constructMeasurementsOnPlane (const StateOnPlane & state) const override virtual
Construct MeasurementOnPlane on plane of the state and wrt the states TrackRep. The state will usually be the prediction or reference state, and has to be defined AT the measurement. The AbsMeasurement will be projected onto the plane. It's possible to make corrections to the coordinates here (e.g. by using the state coordinates). Usually the vector will contain only one element. But in the case of e.g. a WireMeasurement, it will be 2 (left and right).
Implements genfit::AbsMeasurement.
Definition at line 54 of file FullMeasurement.cc.
View newest version in sPHENIX GitHub at line 54 of file FullMeasurement.cc
References constructHMatrix(), genfit::StateOnPlane::getPlane(), genfit::StateOnPlane::getRep(), genfit::AbsMeasurement::rawHitCoords_, and genfit::AbsMeasurement::rawHitCov_.
SharedPlanePtr genfit::FullMeasurement::constructPlane (const StateOnPlane & state) const override virtual
Construct (virtual) detector plane (use state's AbsTrackRep). It's possible to make corrections to the plane here. The state should be defined somewhere near the measurement. For virtual planes, the state will be extrapolated to the POCA to point (SpacepointMeasurement) or line (WireMeasurement), and from this info the plane will be constructed.
Implements genfit::AbsMeasurement.
Definition at line 45 of file FullMeasurement.cc.
View newest version in sPHENIX GitHub at line 45 of file FullMeasurement.cc
References plane_.
Member Data Documentation
SharedPlanePtr genfit::FullMeasurement::plane_ protected
Definition at line 59 of file FullMeasurement.h.
View newest version in sPHENIX GitHub at line 59 of file FullMeasurement.h
Referenced by constructPlane().
The documentation for this class was generated from the following files:
GenFit/blob/master/measurements/include/FullMeasurement.h
GenFit/blob/master/measurements/src/FullMeasurement.cc