Analysis Software: KFPHistogramSet Class Reference
KFPHistogramSet Class Reference
A set of histograms collected at the external devise.
#include <KFParticle/blob/master/KFParticlePerformance/KFPHistogram/KFPHistogramSet.h>
Public Member Functions
KFPHistogramSet (int iPart=0)
~KFPHistogramSet ()
void Fill (const KFParticle &particle)
int GetNHisto1D () const
Returns a number of one dimensional histograms in the set.
int DataSize () const
Returns the size of the memory in blocks of integer (or 4 bytes, or 32 bits) to be allocated for the histogram set.
KFPHistogram1D GetHistogram1D (int iHistogram) const
Returns one dimensional histogram with index "iHistogram".
void SetHisto1DBinContent (int iHisto, int iBin, int value)
void operator+= (const KFPHistogramSet &h)
Adds all histograms bin-by-bin from the histogram set "h" to the current set.
void SetHistogramMemory (int *pointer)
Private Attributes
KFPHistogram1D fKFPHistogram1D [NHisto1D]
A set of the one dimensional histograms.
Static Private Attributes
static const int NHisto1D = 17
Number of histogram per each particle specie.
Detailed Description
A set of histograms collected at the external devise.
Author
M.Zyzak, I.Kisel
Date
05.02.2019
Version
1.0
The class defines a set of histograms to be collect in the environment, where ROOT is not available, for example at Intel Xeon Phi cards. It contains a set of one-dimensional histograms. Also,Calculates the needed amount of memory to be allocated
Definition at line 40 of file KFPHistogramSet.h.
View newest version in sPHENIX GitHub at line 40 of file KFPHistogramSet.h
Constructor & Destructor Documentation
KFPHistogramSet::KFPHistogramSet (int iPart = 0)
Creates a set of histograms for the given particle specie.
Parameters
[in] iPart - number of the particle specie in the KF Particle Finder scheme
See Also
KFPartEfficiencies for the definition of "iPart".
Definition at line 25 of file KFPHistogramSet.cxx.
View newest version in sPHENIX GitHub at line 25 of file KFPHistogramSet.cxx
References fKFPHistogram1D, NHisto1D, KFPartEfficiencies::partMaxMult, KFPartEfficiencies::partMHistoMax, and KFPartEfficiencies::partMHistoMin.
KFPHistogramSet::~KFPHistogramSet () inline
Definition at line 44 of file KFPHistogramSet.h.
View newest version in sPHENIX GitHub at line 44 of file KFPHistogramSet.h
Member Function Documentation
int KFPHistogramSet::DataSize () const inline
Returns the size of the memory in blocks of integer (or 4 bytes, or 32 bits) to be allocated for the histogram set.
See Also
KFPHistogram, where memory is allocated.
Definition at line 49 of file KFPHistogramSet.h.
View newest version in sPHENIX GitHub at line 49 of file KFPHistogramSet.h
References fKFPHistogram1D, i, and NHisto1D.
Referenced by KFPHistogram::KFPHistogram().
void KFPHistogramSet::Fill (const KFParticle & particle)
Fill all possible histograms using parameters of the provided KFParticle object.
Parameters
[in] particle - KFParticle object
Definition at line 154 of file KFPHistogramSet.cxx.
View newest version in sPHENIX GitHub at line 154 of file KFPHistogramSet.cxx
References KFPHistogram1D::Fill(), fKFPHistogram1D, KFParticle::GetChi2(), KFParticle::GetMass(), KFParticle::GetMomentum(), KFParticle::GetNDF(), KFParticle::GetPt(), KFParticle::GetRapidity(), r, KFParticle::X(), KFParticle::Y(), and KFParticle::Z().
Referenced by KFPHistogram::Fill().
KFPHistogram1D KFPHistogramSet::GetHistogram1D (int iHistogram) const inline
Returns one dimensional histogram with index "iHistogram".
Definition at line 56 of file KFPHistogramSet.h.
View newest version in sPHENIX GitHub at line 56 of file KFPHistogramSet.h
References fKFPHistogram1D.
Referenced by KFPHistogram::GetHistogram().
int KFPHistogramSet::GetNHisto1D () const inline
Returns a number of one dimensional histograms in the set.
Definition at line 48 of file KFPHistogramSet.h.
View newest version in sPHENIX GitHub at line 48 of file KFPHistogramSet.h
References NHisto1D.
Referenced by KFPHistogram::FillFromFile().
void KFPHistogramSet::operator+= (const KFPHistogramSet & h) inline
Adds all histograms bin-by-bin from the histogram set "h" to the current set.
Definition at line 65 of file KFPHistogramSet.h.
View newest version in sPHENIX GitHub at line 65 of file KFPHistogramSet.h
References fKFPHistogram1D, i, and NHisto1D.
void KFPHistogramSet::SetHisto1DBinContent (int iHisto, int iBin, int value) inline
Sets bin content of the histogram "iHisto" to a given value.
Parameters
[in] iHisto - index of the histogram in the set
[in] iBin - number of the bin
[in] value - value to be set
Definition at line 63 of file KFPHistogramSet.h.
View newest version in sPHENIX GitHub at line 63 of file KFPHistogramSet.h
References fKFPHistogram1D, and KFPHistogram1D::SetBinContent().
Referenced by KFPHistogram::FillFromFile().
void KFPHistogramSet::SetHistogramMemory (int * pointer)
Sets a pointer to the memory allocated externally for the current set of histograms.
Parameters
[in] pointer - pointer to the memory
Definition at line 142 of file KFPHistogramSet.cxx.
View newest version in sPHENIX GitHub at line 142 of file KFPHistogramSet.cxx
References KFPHistogram1D::DataSize(), fKFPHistogram1D, i, NHisto1D, and KFPHistogram1D::SetHistogramMemory().
Referenced by KFPHistogram::KFPHistogram().
Member Data Documentation
KFPHistogram1D KFPHistogramSet::fKFPHistogram1D[NHisto1D] private
A set of the one dimensional histograms.
Definition at line 75 of file KFPHistogramSet.h.
View newest version in sPHENIX GitHub at line 75 of file KFPHistogramSet.h
Referenced by DataSize(), Fill(), GetHistogram1D(), KFPHistogramSet(), operator+=(), SetHisto1DBinContent(), and SetHistogramMemory().
const int KFPHistogramSet::NHisto1D = 17 static private
Number of histogram per each particle specie.
Definition at line 74 of file KFPHistogramSet.h.
View newest version in sPHENIX GitHub at line 74 of file KFPHistogramSet.h
Referenced by DataSize(), GetNHisto1D(), KFPHistogramSet(), operator+=(), and SetHistogramMemory().
The documentation for this class was generated from the following files:
KFParticle/blob/master/KFParticlePerformance/KFPHistogram/KFPHistogramSet.h
KFParticle/blob/master/KFParticlePerformance/KFPHistogram/KFPHistogramSet.cxx