Analysis Software: genfit::GFRaveTrackParameters Class Reference
genfit::GFRaveTrackParameters Class Reference
GFRaveTrackParameters class Contains a pointer to the original genfit::Track, the weight of the track in the vertex, and smoothed (with the vertex information) state and covariance of the track.
#include <GenFit/blob/master/GFRave/include/GFRaveTrackParameters.h>
Public Member Functions
GFRaveTrackParameters ()
GFRaveTrackParameters (const Track *track, MeasuredStateOnPlane *originalState, double weight, const TVectorD &state6, const TMatrixDSym &cov6x6, bool isSmoothed)
GFRaveTrackParameters (const Track *track, MeasuredStateOnPlane *originalState, double weight)
double getWeight () const
bool hasTrack () const
const Track * getTrack () const
UInt_t GetUniqueID () const
bool hasSmoothedData () const
TVectorD getState () const
TVector3 getPos () const
TVector3 getMom () const
const TMatrixDSym & getCov () const
double getCharge () const
double getPdg () const
void Print (const Option_t *="") const
Private Attributes
const TRef originalTrack_
double weight_
TVectorD state_
TMatrixDSym cov_
bool hasSmoothedData_
Detailed Description
GFRaveTrackParameters class Contains a pointer to the original genfit::Track, the weight of the track in the vertex, and smoothed (with the vertex information) state and covariance of the track.
Definition at line 51 of file GFRaveTrackParameters.h.
View newest version in sPHENIX GitHub at line 51 of file GFRaveTrackParameters.h
Constructor & Destructor Documentation
genfit::GFRaveTrackParameters::GFRaveTrackParameters ()
Definition at line 31 of file GFRaveTrackParameters.cc.
View newest version in sPHENIX GitHub at line 31 of file GFRaveTrackParameters.cc
genfit::GFRaveTrackParameters::GFRaveTrackParameters (const Track * track, MeasuredStateOnPlane * originalState, double weight, const TVectorD & state6, const TMatrixDSym & cov6x6, bool isSmoothed)
Definition at line 42 of file GFRaveTrackParameters.cc.
View newest version in sPHENIX GitHub at line 42 of file GFRaveTrackParameters.cc
References cov_, and state_.
genfit::GFRaveTrackParameters::GFRaveTrackParameters (const Track * track, MeasuredStateOnPlane * originalState, double weight)
Definition at line 61 of file GFRaveTrackParameters.cc.
View newest version in sPHENIX GitHub at line 61 of file GFRaveTrackParameters.cc
Member Function Documentation
double genfit::GFRaveTrackParameters::getCharge () const
Definition at line 85 of file GFRaveTrackParameters.cc.
View newest version in sPHENIX GitHub at line 85 of file GFRaveTrackParameters.cc
References genfit::FitStatus::getCharge(), genfit::Track::getFitStatus(), and getTrack().
const TMatrixDSym& genfit::GFRaveTrackParameters::getCov () const inline
Definition at line 71 of file GFRaveTrackParameters.h.
View newest version in sPHENIX GitHub at line 71 of file GFRaveTrackParameters.h
References cov_.
Referenced by Print().
TVector3 genfit::GFRaveTrackParameters::getMom () const
Definition at line 79 of file GFRaveTrackParameters.cc.
View newest version in sPHENIX GitHub at line 79 of file GFRaveTrackParameters.cc
References state_.
Referenced by SVReco::FillVertexMap(), BDiJetModule::GetSVMass_mom(), and SVReco::GetSVMass_mom().
double genfit::GFRaveTrackParameters::getPdg () const
Definition at line 91 of file GFRaveTrackParameters.cc.
View newest version in sPHENIX GitHub at line 91 of file GFRaveTrackParameters.cc
References genfit::Track::getCardinalRep(), genfit::AbsTrackRep::getPDG(), getTrack(), and hasTrack().
TVector3 genfit::GFRaveTrackParameters::getPos () const
Definition at line 73 of file GFRaveTrackParameters.cc.
View newest version in sPHENIX GitHub at line 73 of file GFRaveTrackParameters.cc
References state_.
TVectorD genfit::GFRaveTrackParameters::getState () const inline
Definition at line 68 of file GFRaveTrackParameters.h.
View newest version in sPHENIX GitHub at line 68 of file GFRaveTrackParameters.h
References state_.
Referenced by Print().
const Track* genfit::GFRaveTrackParameters::getTrack () const inline
Definition at line 63 of file GFRaveTrackParameters.h.
View newest version in sPHENIX GitHub at line 63 of file GFRaveTrackParameters.h
References originalTrack_.
Referenced by PHGenFitTrkFitter::FillSvtxVertexMap(), TpcPrototypeGenFitTrkFitter::FillSvtxVertexMap(), SVReco::FillVertexMap(), getCharge(), getPdg(), SVReco::GetSVMass_mom(), SVReco::GFRVVtxToSvtxVertex(), and Print().
UInt_t genfit::GFRaveTrackParameters::GetUniqueID () const inline
Definition at line 65 of file GFRaveTrackParameters.h.
View newest version in sPHENIX GitHub at line 65 of file GFRaveTrackParameters.h
References originalTrack_.
Referenced by main().
double genfit::GFRaveTrackParameters::getWeight () const inline
Definition at line 60 of file GFRaveTrackParameters.h.
View newest version in sPHENIX GitHub at line 60 of file GFRaveTrackParameters.h
References weight_.
Referenced by SVReco::FillVertexMap(), BDiJetModule::GetSVMass_mom(), SVReco::GetSVMass_mom(), and Print().
bool genfit::GFRaveTrackParameters::hasSmoothedData () const inline
Definition at line 67 of file GFRaveTrackParameters.h.
View newest version in sPHENIX GitHub at line 67 of file GFRaveTrackParameters.h
References hasSmoothedData_.
bool genfit::GFRaveTrackParameters::hasTrack () const inline
Definition at line 62 of file GFRaveTrackParameters.h.
View newest version in sPHENIX GitHub at line 62 of file GFRaveTrackParameters.h
References originalTrack_.
Referenced by getPdg(), main(), and Print().
void genfit::GFRaveTrackParameters::Print (const Option_t * = "") const
Definition at line 102 of file GFRaveTrackParameters.cc.
View newest version in sPHENIX GitHub at line 102 of file GFRaveTrackParameters.cc
References getCov(), getState(), getTrack(), getWeight(), hasSmoothedData_, hasTrack(), and genfit::Track::Print().
Referenced by genfit::GFRaveVertex::Print().
Member Data Documentation
TMatrixDSym genfit::GFRaveTrackParameters::cov_ private
Definition at line 84 of file GFRaveTrackParameters.h.
View newest version in sPHENIX GitHub at line 84 of file GFRaveTrackParameters.h
Referenced by getCov(), and GFRaveTrackParameters().
bool genfit::GFRaveTrackParameters::hasSmoothedData_ private
Definition at line 85 of file GFRaveTrackParameters.h.
View newest version in sPHENIX GitHub at line 85 of file GFRaveTrackParameters.h
Referenced by hasSmoothedData(), and Print().
const TRef genfit::GFRaveTrackParameters::originalTrack_ private
Definition at line 80 of file GFRaveTrackParameters.h.
View newest version in sPHENIX GitHub at line 80 of file GFRaveTrackParameters.h
Referenced by getTrack(), GetUniqueID(), and hasTrack().
TVectorD genfit::GFRaveTrackParameters::state_ private
Definition at line 83 of file GFRaveTrackParameters.h.
View newest version in sPHENIX GitHub at line 83 of file GFRaveTrackParameters.h
Referenced by getMom(), getPos(), getState(), and GFRaveTrackParameters().
double genfit::GFRaveTrackParameters::weight_ private
Definition at line 82 of file GFRaveTrackParameters.h.
View newest version in sPHENIX GitHub at line 82 of file GFRaveTrackParameters.h
Referenced by getWeight().
The documentation for this class was generated from the following files:
GenFit/blob/master/GFRave/include/GFRaveTrackParameters.h
GenFit/blob/master/GFRave/src/GFRaveTrackParameters.cc