Analysis Software: GenFit/blob/master/test/unitTests/main.cc File Reference
main.cc File Reference
#include <iostream>
#include <execinfo.h>
#include <signal.h>
#include <stdlib.h>
#include <AbsFinitePlane.h>
#include <AbsFitterInfo.h>
#include <AbsMeasurement.h>
#include <AbsTrackRep.h>
#include <ConstField.h>
#include <DetPlane.h>
#include <Exception.h>
#include <FieldManager.h>
#include <KalmanFittedStateOnPlane.h>
#include <KalmanFitterInfo.h>
#include <MeasuredStateOnPlane.h>
#include <MeasurementOnPlane.h>
#include <PlanarMeasurement.h>
#include <ProlateSpacepointMeasurement.h>
#include <RectangularFinitePlane.h>
#include <ReferenceStateOnPlane.h>
#include <SharedPlanePtr.h>
#include <SpacepointMeasurement.h>
#include <StateOnPlane.h>
#include <Tools.h>
#include <TrackCand.h>
#include <TrackCandHit.h>
#include <Track.h>
#include <TrackPoint.h>
#include <WireMeasurement.h>
#include <WirePointMeasurement.h>
#include <MaterialEffects.h>
#include <RKTools.h>
#include <RKTrackRep.h>
#include <StepLimits.h>
#include <TGeoMaterialInterface.h>
#include <TApplication.h>
#include <TCanvas.h>
#include <TDatabasePDG.h>
#include <TEveManager.h>
#include <TGeoManager.h>
#include <TH1D.h>
#include <TH2D.h>
#include <TRandom.h>
#include <TStyle.h>
#include <TVector3.h>
#include <vector>
#include <map>
#include <stdio.h>
#include <TROOT.h>
#include <TFile.h>
#include <TTree.h>
#include <TMath.h>
#include <TString.h>
Classes
struct TestCase
Enumerations
enum e_testStatus { kPassed, kFailed, kException }
Functions
void handler (int sig)
int randomPdg ()
int randomSign ()
e_testStatus compareMatrices (const TMatrixTBase< double > &A, const TMatrixTBase< double > &B, double maxRelErr)
e_testStatus isCovMatrix (TMatrixTBase< double > &cov)
e_testStatus checkSetGetPosMom (bool writeHisto=false)
e_testStatus compareForthBackExtrapolation (bool writeHisto=false)
e_testStatus compareForthBackJacNoise (bool writeHisto=false)
e_testStatus checkStopAtBoundary (bool writeHisto=false)
e_testStatus checkErrorPropagation (bool writeHisto=false)
e_testStatus checkExtrapolateToLine (bool writeHisto=false)
e_testStatus checkExtrapolateToPoint (bool writeHisto=false)
e_testStatus checkExtrapolateToCylinder (bool writeHisto=false)
e_testStatus checkExtrapolateToSphere (bool writeHisto=false)
e_testStatus checkExtrapolateBy (bool writeHisto=false)
int main ()
Variables
constexpr bool verbose = false
Enumeration Type Documentation
enum e_testStatus
Enumerator:
kPassed
kFailed
kException
Definition at line 65 of file main.cc.
View newest version in sPHENIX GitHub at line 65 of file main.cc
Function Documentation
e_testStatus checkErrorPropagation (bool writeHisto = false)
Definition at line 695 of file main.cc.
View newest version in sPHENIX GitHub at line 695 of file main.cc
References genfit::AbsTrackRep::extrapolateToPlane(), genfit::MeasuredStateOnPlane::getCov(), genfit::StateOnPlane::getPlane(), isCovMatrix(), kException, kFailed, kPassed, pos, genfit::MeasuredStateOnPlane::Print(), randomPdg(), randomSign(), genfit::AbsTrackRep::setPosMom(), verbose, and genfit::Exception::what().
Referenced by main().
e_testStatus checkExtrapolateBy (bool writeHisto = false)
Definition at line 1000 of file main.cc.
View newest version in sPHENIX GitHub at line 1000 of file main.cc
References genfit::AbsTrackRep::extrapolateBy(), genfit::StateOnPlane::getPlane(), genfit::StateOnPlane::getPos(), kException, kFailed, kPassed, pos, genfit::StateOnPlane::Print(), randomPdg(), randomSign(), genfit::AbsTrackRep::setPosMom(), step, and verbose.
Referenced by main().
e_testStatus checkExtrapolateToCylinder (bool writeHisto = false)
Definition at line 870 of file main.cc.
View newest version in sPHENIX GitHub at line 870 of file main.cc
References genfit::AbsTrackRep::extrapolateToCylinder(), genfit::StateOnPlane::getPlane(), genfit::AbsTrackRep::getPos(), kException, kFailed, kPassed, pos, genfit::StateOnPlane::Print(), randomPdg(), randomSign(), genfit::AbsTrackRep::setPosMom(), t, verbose, and genfit::Exception::what().
Referenced by main().
e_testStatus checkExtrapolateToLine (bool writeHisto = false)
Definition at line 749 of file main.cc.
View newest version in sPHENIX GitHub at line 749 of file main.cc
References genfit::AbsTrackRep::extrapolateToLine(), genfit::AbsTrackRep::getMom(), genfit::StateOnPlane::getPlane(), kException, kFailed, kPassed, pos, genfit::StateOnPlane::Print(), randomPdg(), randomSign(), genfit::AbsTrackRep::setPosMom(), verbose, and genfit::Exception::what().
Referenced by main().
e_testStatus checkExtrapolateToPoint (bool writeHisto = false)
Definition at line 812 of file main.cc.
View newest version in sPHENIX GitHub at line 812 of file main.cc
References genfit::AbsTrackRep::extrapolateToPoint(), genfit::AbsTrackRep::getMom(), genfit::StateOnPlane::getPlane(), kException, kFailed, kPassed, pos, genfit::StateOnPlane::Print(), randomPdg(), randomSign(), genfit::AbsTrackRep::setPosMom(), verbose, and genfit::Exception::what().
Referenced by main().
e_testStatus checkExtrapolateToSphere (bool writeHisto = false)
Definition at line 938 of file main.cc.
View newest version in sPHENIX GitHub at line 938 of file main.cc
References genfit::AbsTrackRep::extrapolateToSphere(), genfit::StateOnPlane::getPlane(), genfit::AbsTrackRep::getPos(), kException, kFailed, kPassed, pos, genfit::StateOnPlane::Print(), randomPdg(), randomSign(), genfit::AbsTrackRep::setPosMom(), verbose, and genfit::Exception::what().
Referenced by main().
e_testStatus checkSetGetPosMom (bool writeHisto = false)
Definition at line 181 of file main.cc.
View newest version in sPHENIX GitHub at line 181 of file main.cc
References genfit::AbsTrackRep::getMom(), genfit::StateOnPlane::getPlane(), genfit::AbsTrackRep::getPos(), kFailed, kPassed, pos, genfit::StateOnPlane::Print(), randomPdg(), randomSign(), genfit::AbsTrackRep::setPosMom(), v, and verbose.
Referenced by main().
e_testStatus checkStopAtBoundary (bool writeHisto = false)
Definition at line 635 of file main.cc.
View newest version in sPHENIX GitHub at line 635 of file main.cc
References genfit::AbsTrackRep::extrapolateToPlane(), genfit::StateOnPlane::getPlane(), genfit::AbsTrackRep::getPos(), kException, kFailed, kPassed, pos, genfit::StateOnPlane::Print(), randomPdg(), randomSign(), genfit::AbsTrackRep::setPosMom(), verbose, and genfit::Exception::what().
Referenced by main().
e_testStatus compareForthBackExtrapolation (bool writeHisto = false)
Definition at line 252 of file main.cc.
View newest version in sPHENIX GitHub at line 252 of file main.cc
References genfit::AbsTrackRep::extrapolateToPlane(), genfit::AbsTrackRep::getMom(), genfit::AbsTrackRep::getPos(), i, kException, kFailed, kPassed, pos, genfit::StateOnPlane::Print(), randomPdg(), randomSign(), genfit::AbsTrackRep::setPosMom(), verbose, and genfit::Exception::what().
Referenced by main().
e_testStatus compareForthBackJacNoise (bool writeHisto = false)
Definition at line 413 of file main.cc.
View newest version in sPHENIX GitHub at line 413 of file main.cc
References genfit::AbsTrackRep::calcJacobianNumerically(), compareMatrices(), genfit::AbsTrackRep::extrapolateToPlane(), genfit::AbsTrackRep::getBackwardJacobianAndNoise(), genfit::MeasuredStateOnPlane::getCov(), genfit::AbsTrackRep::getForwardJacobianAndNoise(), genfit::MaterialEffects::getInstance(), genfit::StateOnPlane::getState(), isCovMatrix(), kException, kFailed, kPassed, pos, Print(), randomPdg(), randomSign(), genfit::DetPlane::rotate(), genfit::MaterialEffects::setNoEffects(), genfit::AbsTrackRep::setPosMom(), verbose, and genfit::Exception::what().
Referenced by main().
e_testStatus compareMatrices (const TMatrixTBase< double > & A, const TMatrixTBase< double > & B, double maxRelErr)
Definition at line 119 of file main.cc.
View newest version in sPHENIX GitHub at line 119 of file main.cc
References A, i, j, kFailed, kPassed, max, and verbose.
Referenced by compareForthBackJacNoise().
void handler (int sig)
Definition at line 73 of file main.cc.
View newest version in sPHENIX GitHub at line 73 of file main.cc
References TauVsDIS_MachineLearning_Differentiation::array, and fprintf().
e_testStatus isCovMatrix (TMatrixTBase< double > & cov)
Definition at line 150 of file main.cc.
View newest version in sPHENIX GitHub at line 150 of file main.cc
References i, j, kFailed, kPassed, and verbose.
Referenced by checkErrorPropagation(), and compareForthBackJacNoise().
int main ()
Definition at line 1081 of file main.cc.
View newest version in sPHENIX GitHub at line 1081 of file main.cc
References checkErrorPropagation(), checkExtrapolateBy(), checkExtrapolateToCylinder(), checkExtrapolateToLine(), checkExtrapolateToPoint(), checkExtrapolateToSphere(), checkSetGetPosMom(), checkStopAtBoundary(), compareForthBackExtrapolation(), compareForthBackJacNoise(), genfit::MaterialEffects::getInstance(), genfit::FieldManager::getInstance(), handler(), i, genfit::MaterialEffects::init(), genfit::FieldManager::init(), j, kException, kFailed, kPassed, and signal().
int randomPdg ()
Definition at line 86 of file main.cc.
View newest version in sPHENIX GitHub at line 86 of file main.cc
int randomSign ()
Definition at line 112 of file main.cc.
View newest version in sPHENIX GitHub at line 112 of file main.cc
Variable Documentation
constexpr bool verbose = false
Definition at line 71 of file main.cc.
View newest version in sPHENIX GitHub at line 71 of file main.cc