Analysis Software: genfit::KalmanFitStatus Class Reference
genfit::KalmanFitStatus Class Reference
FitStatus for use with AbsKalmanFitter implementations.
#include <GenFit/blob/master/fitters/include/KalmanFitStatus.h>
Public Member Functions
KalmanFitStatus ()
virtual ~KalmanFitStatus ()
virtual FitStatus * clone () const override
unsigned int getNumIterations () const
bool isFittedWithDaf () const
bool isFittedWithReferenceTrack () const
double getTrackLen () const
double getForwardChi2 () const
double getBackwardChi2 () const
double getForwardNdf () const
double getBackwardNdf () const
double getForwardPVal () const
double getBackwardPVal () const
void setNumIterations (unsigned int numIterations)
void setIsFittedWithDaf (bool fittedWithDaf=true)
void setIsFittedWithReferenceTrack (bool fittedWithReferenceTrack=true)
void setTrackLen (double trackLen)
void setForwardChi2 (double fChi2)
void setBackwardChi2 (double bChi2)
void setForwardNdf (double fNdf)
void setBackwardNdf (double bNdf)
virtual void Print (const Option_t *="") const override
Public Member Functions inherited from genfit::FitStatus
FitStatus ()
virtual ~FitStatus ()
bool isFitted () const
Has the track been fitted?
bool isFitConverged (bool inAllPoints=true) const
Did the fit converge (in all Points or only partially)?
bool isFitConvergedFully () const
bool isFitConvergedPartially () const
int getNFailedPoints () const
bool hasTrackChanged () const
Has anything in the Track been changed since the fit?
bool isTrackPruned () const
Has the track been pruned after the fit?
double getCharge () const
Get the fitted charge.
double getChi2 () const
Get chi^2 of the fit.
double getNdf () const
Get the degrees of freedom of the fit.
virtual double getPVal () const
Get the p value of the fit.
void setIsFitted (bool fitted=true)
void setIsFitConvergedFully (bool fitConverged=true)
void setIsFitConvergedPartially (bool fitConverged=true)
void setNFailedPoints (int nFailedPoints)
void setHasTrackChanged (bool trackChanged=true)
void setCharge (double charge)
PruneFlags & getPruneFlags ()
void setChi2 (const double &chi2)
void setNdf (const double &ndf)
Protected Attributes
unsigned int numIterations_
bool fittedWithDaf_
bool fittedWithReferenceTrack_
double trackLen_
double fChi2_
double fNdf_
double fPval_
Protected Attributes inherited from genfit::FitStatus
bool isFitted_
has the track been fitted?
bool isFitConvergedFully_
did the fit converge with all TrackPoints?
bool isFitConvergedPartially_
did the fit converge with a subset of all TrackPoints?
int nFailedPoints_
Number of failed TrackPoints.
bool trackHasChanged_
has anything in the Track been changed since the fit? -> fit isn't valid anymore
PruneFlags pruneFlags_
Prune flags.
double charge_
fitted charge
double chi2_
double ndf_
Additional Inherited Members
Protected Member Functions inherited from genfit::FitStatus
ClassDef (FitStatus, 3)
Detailed Description
FitStatus for use with AbsKalmanFitter implementations.
Definition at line 36 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 36 of file KalmanFitStatus.h
Constructor & Destructor Documentation
genfit::KalmanFitStatus::KalmanFitStatus () inline
Definition at line 40 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 40 of file KalmanFitStatus.h
Referenced by clone().
virtual genfit::KalmanFitStatus::~KalmanFitStatus () inline virtual
Definition at line 44 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 44 of file KalmanFitStatus.h
Member Function Documentation
virtual FitStatus* genfit::KalmanFitStatus::clone () const inline override virtual
Reimplemented from genfit::FitStatus.
Definition at line 46 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 46 of file KalmanFitStatus.h
References KalmanFitStatus().
double genfit::KalmanFitStatus::getBackwardChi2 () const inline
Definition at line 53 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 53 of file KalmanFitStatus.h
References genfit::FitStatus::getChi2().
double genfit::KalmanFitStatus::getBackwardNdf () const inline
Definition at line 55 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 55 of file KalmanFitStatus.h
References genfit::FitStatus::getNdf().
double genfit::KalmanFitStatus::getBackwardPVal () const inline
Definition at line 58 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 58 of file KalmanFitStatus.h
References genfit::FitStatus::getPVal().
Referenced by Print(), and genfit::DAF::processTrackWithRep().
double genfit::KalmanFitStatus::getForwardChi2 () const inline
Definition at line 52 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 52 of file KalmanFitStatus.h
References fChi2_.
double genfit::KalmanFitStatus::getForwardNdf () const inline
Definition at line 54 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 54 of file KalmanFitStatus.h
References fNdf_.
double genfit::KalmanFitStatus::getForwardPVal () const inline
Definition at line 57 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 57 of file KalmanFitStatus.h
References fChi2_, fNdf_, and max.
Referenced by Print(), and genfit::DAF::processTrackWithRep().
unsigned int genfit::KalmanFitStatus::getNumIterations () const inline
Definition at line 48 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 48 of file KalmanFitStatus.h
References numIterations_.
double genfit::KalmanFitStatus::getTrackLen () const inline
Definition at line 51 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 51 of file KalmanFitStatus.h
References trackLen_.
bool genfit::KalmanFitStatus::isFittedWithDaf () const inline
Definition at line 49 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 49 of file KalmanFitStatus.h
References fittedWithDaf_.
bool genfit::KalmanFitStatus::isFittedWithReferenceTrack () const inline
Definition at line 50 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 50 of file KalmanFitStatus.h
References fittedWithReferenceTrack_.
void genfit::KalmanFitStatus::Print (const Option_t * = "") const override virtual
Reimplemented from genfit::FitStatus.
Definition at line 27 of file KalmanFitStatus.cc.
View newest version in sPHENIX GitHub at line 27 of file KalmanFitStatus.cc
References fChi2_, fittedWithDaf_, fittedWithReferenceTrack_, fNdf_, getBackwardPVal(), genfit::FitStatus::getChi2(), getForwardPVal(), genfit::FitStatus::getNdf(), genfit::FitStatus::isFitted_, numIterations_, genfit::FitStatus::Print(), genfit::printOut, and trackLen_.
Referenced by genfit::KalmanFitterRefTrack::processTrackWithRep().
void genfit::KalmanFitStatus::setBackwardChi2 (double bChi2) inline
Definition at line 65 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 65 of file KalmanFitStatus.h
References genfit::FitStatus::setChi2().
Referenced by genfit::KalmanFitterRefTrack::processTrackWithRep(), and genfit::KalmanFitter::processTrackWithRep().
void genfit::KalmanFitStatus::setBackwardNdf (double bNdf) inline
Definition at line 67 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 67 of file KalmanFitStatus.h
References genfit::FitStatus::setNdf().
Referenced by genfit::KalmanFitterRefTrack::processTrackWithRep(), and genfit::KalmanFitter::processTrackWithRep().
void genfit::KalmanFitStatus::setForwardChi2 (double fChi2) inline
Definition at line 64 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 64 of file KalmanFitStatus.h
References fChi2, and fChi2_.
Referenced by genfit::KalmanFitterRefTrack::processTrackWithRep(), and genfit::KalmanFitter::processTrackWithRep().
void genfit::KalmanFitStatus::setForwardNdf (double fNdf) inline
Definition at line 66 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 66 of file KalmanFitStatus.h
References fNdf_.
Referenced by genfit::KalmanFitterRefTrack::processTrackWithRep(), and genfit::KalmanFitter::processTrackWithRep().
void genfit::KalmanFitStatus::setIsFittedWithDaf (bool fittedWithDaf = true) inline
Definition at line 61 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 61 of file KalmanFitStatus.h
References fittedWithDaf_.
Referenced by genfit::DAF::processTrackWithRep().
void genfit::KalmanFitStatus::setIsFittedWithReferenceTrack (bool fittedWithReferenceTrack = true) inline
Definition at line 62 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 62 of file KalmanFitStatus.h
References fittedWithReferenceTrack_.
Referenced by genfit::KalmanFitterRefTrack::processTrackWithRep().
void genfit::KalmanFitStatus::setNumIterations (unsigned int numIterations) inline
Definition at line 60 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 60 of file KalmanFitStatus.h
References numIterations_.
Referenced by genfit::KalmanFitterRefTrack::processTrackWithRep(), genfit::KalmanFitter::processTrackWithRep(), and genfit::DAF::processTrackWithRep().
void genfit::KalmanFitStatus::setTrackLen (double trackLen) inline
Definition at line 63 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 63 of file KalmanFitStatus.h
References trackLen_.
Referenced by genfit::KalmanFitterRefTrack::prepareTrack().
Member Data Documentation
double genfit::KalmanFitStatus::fChi2_ protected
Definition at line 79 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 79 of file KalmanFitStatus.h
Referenced by getForwardChi2(), getForwardPVal(), Print(), and setForwardChi2().
bool genfit::KalmanFitStatus::fittedWithDaf_ protected
Definition at line 74 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 74 of file KalmanFitStatus.h
Referenced by isFittedWithDaf(), Print(), and setIsFittedWithDaf().
bool genfit::KalmanFitStatus::fittedWithReferenceTrack_ protected
Definition at line 75 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 75 of file KalmanFitStatus.h
Referenced by isFittedWithReferenceTrack(), Print(), and setIsFittedWithReferenceTrack().
double genfit::KalmanFitStatus::fNdf_ protected
Definition at line 80 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 80 of file KalmanFitStatus.h
Referenced by getForwardNdf(), getForwardPVal(), Print(), and setForwardNdf().
double genfit::KalmanFitStatus::fPval_ protected
Definition at line 81 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 81 of file KalmanFitStatus.h
unsigned int genfit::KalmanFitStatus::numIterations_ protected
Definition at line 73 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 73 of file KalmanFitStatus.h
Referenced by getNumIterations(), Print(), and setNumIterations().
double genfit::KalmanFitStatus::trackLen_ protected
Definition at line 77 of file KalmanFitStatus.h.
View newest version in sPHENIX GitHub at line 77 of file KalmanFitStatus.h
Referenced by getTrackLen(), Print(), and setTrackLen().
The documentation for this class was generated from the following files:
GenFit/blob/master/fitters/include/KalmanFitStatus.h
GenFit/blob/master/fitters/src/KalmanFitStatus.cc