Analysis Software: genfit::EventDisplay Class Reference
genfit::EventDisplay Class Reference
Event display designed to run with Genfit.
#include <GenFit/blob/master/eventDisplay/include/EventDisplay.h>
Public Member Functions
~EventDisplay ()
void reset ()
Drop all events.
void addEvent (std::vector< genfit::Track * > &tracks)
Add new event.
void addEvent (std::vector< const genfit::Track * > &tracks)
void addEvent (const Track *tr)
Add new event.
void next (unsigned int stp=1)
Go to the next event or step a certain number of events ahead.
void prev (unsigned int stp=1)
Go to the previous event or step a certain number of events back.
void gotoEvent (unsigned int id)
Go to event with index id.
int getNEvents ()
Get the total number of events stored.
void setOptions (std::string opts)
Set the display options.
void setErrScale (double errScale=1.)
Set the scaling factor for the visualization of the errors.
double getErrScale ()
Get the error scaling factor.
void open ()
Open the event display.
void guiGoto ()
void guiGoto2 ()
void guiSetDrawParams ()
void guiSelectFitterId (int val)
void guiSelectMmHandling (int val)
Static Public Member Functions
static EventDisplay * getInstance ()
Private Member Functions
EventDisplay ()
void makeGui ()
Build the buttons for event navigation.
void drawEvent (unsigned int id, bool resetCam=true)
Draw an event.
TEveBox * boxCreator (TVector3 o, TVector3 u, TVector3 v, float ud, float vd, float depth)
Create a box around o, oriented along u and v with widths ud, vd and depth and return a pointer to the box object.
void makeLines (const StateOnPlane *prevState, const StateOnPlane *state, const AbsTrackRep *rep, const Color_t &color, const Style_t &style, bool drawMarkers, bool drawErrors, double lineWidth=2, int markerPos=1)
Private Attributes
unsigned int eventId_
double errorScale_
std::vector< std::vector
< genfit::Track * > * > events_
TGNumberEntry * guiEvent
TGNumberEntry * guiEvent2
TGCheckButton * guiDrawGeometry_
bool drawGeometry_
TGCheckButton * guiDrawDetectors_
bool drawDetectors_
TGCheckButton * guiDrawHits_
bool drawHits_
TGCheckButton * guiDrawErrors_
bool drawErrors_
TGCheckButton * guiDrawPlanes_
bool drawPlanes_
TGCheckButton * guiDrawTrackMarkers_
bool drawTrackMarkers_
TGCheckButton * guiDrawTrack_
bool drawTrack_
TGCheckButton * guiDrawRefTrack_
bool drawRefTrack_
TGCheckButton * guiDrawForward_
bool drawForward_
TGCheckButton * guiDrawBackward_
bool drawBackward_
TGCheckButton * guiDrawAutoScale_
bool drawAutoScale_
TGCheckButton * guiDrawScaleMan_
bool drawScaleMan_
TGNumberEntry * guiErrorScale_
bool drawSilent_
TGCheckButton * guiDrawCardinalRep_
bool drawCardinalRep_
TGNumberEntry * guiRepId_
unsigned int repId_
TGCheckButton * guiDrawAllTracks_
bool drawAllTracks_
TGNumberEntry * guiTrackId_
unsigned int trackId_
TGCheckButton * guiRefit_
bool refit_
TGNumberEntry * guiDebugLvl_
unsigned int debugLvl_
TGButtonGroup * guiFitterId_
eFitterType fitterId_
TGButtonGroup * guiMmHandling_
eMultipleMeasurementHandling mmHandling_
TGCheckButton * guiSquareRootFormalism_
bool squareRootFormalism_
TGNumberEntry * guiDPVal_
double dPVal_
TGNumberEntry * guiRelChi2_
double dRelChi2_
TGNumberEntry * guiDChi2Ref_
double dChi2Ref_
TGNumberEntry * guiNMinIter_
unsigned int nMinIter_
TGNumberEntry * guiNMaxIter_
unsigned int nMaxIter_
TGNumberEntry * guiNMaxFailed_
int nMaxFailed_
TGCheckButton * guiResort_
bool resort_
Static Private Attributes
static EventDisplay * eventDisplay_ = nullptr
Detailed Description
Event display designed to run with Genfit.
Author
Karl Bicker (Technische Universität München, original author)
The EventDisplay class is a singelton used to visualize the events processed with Genfit. The event display uses the EVE event visualization package to visualize Tracks which are bundled in a vector and which form one event. The information about the tracks is supplied in Track objects. To use the event display, the geometry (TGeoManager)and magnetic field (FieldManager) have to be initialized and gApplication and gEve have to exist.
Definition at line 59 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 59 of file EventDisplay.h
Constructor & Destructor Documentation
genfit::EventDisplay::EventDisplay () private
Definition at line 64 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 64 of file EventDisplay.cc
References eventId_.
Referenced by getInstance().
genfit::EventDisplay::~EventDisplay ()
Definition at line 146 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 146 of file EventDisplay.cc
References reset().
Member Function Documentation
void genfit::EventDisplay::addEvent (std::vector< genfit::Track * > & tracks)
Add new event.
Add a new event. An event is a collection of Tracks which are displayed at the the same time. The tracks are copied.
Definition at line 164 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 164 of file EventDisplay.cc
References events_, and i.
Referenced by PHGenFitTrkProp::KalmanTrkProp(), main(), PHG4TrackFastSim::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), PHGenFitTrkFitter::process_event(), and PHGenFit::Fitter::processTrack().
void genfit::EventDisplay::addEvent (std::vector< const genfit::Track * > & tracks)
Definition at line 176 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 176 of file EventDisplay.cc
References events_, and i.
void genfit::EventDisplay::addEvent (const Track * tr)
Add new event.
Add a new event consisting of one track.
Definition at line 188 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 188 of file EventDisplay.cc
References events_.
TEveBox * genfit::EventDisplay::boxCreator (TVector3 o, TVector3 u, TVector3 v, float ud, float vd, float depth) private
Create a box around o, oriented along u and v with widths ud, vd and depth and return a pointer to the box object.
Definition at line 936 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 936 of file EventDisplay.cc
References k, norm, and v.
Referenced by drawEvent().
void genfit::EventDisplay::drawEvent (unsigned int id, bool resetCam = true) private
Draw an event.
Definition at line 271 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 271 of file EventDisplay.cc
References assert, boxCreator(), genfit::Track::checkConsistency(), genfit::DafRef, genfit::DafSimple, dChi2Ref_, debugLvl_, double(), dPVal_, drawAllTracks_, drawAutoScale_, drawBackward_, drawCardinalRep_, drawDetectors_, drawErrors_, drawForward_, drawGeometry_, drawHits_, drawPlanes_, drawRefTrack_, drawScaleMan_, drawTrack_, drawTrackMarkers_, dRelChi2_, errorScale_, events_, genfit::StateOnPlane::extrapolateBy(), fitterId_, genfit::KalmanFitterInfo::getBackwardPrediction(), genfit::KalmanFitterInfo::getBackwardUpdate(), genfit::Track::getCardinalRep(), genfit::StateOnPlane::getCharge(), genfit::MeasuredStateOnPlane::getCov(), genfit::AbsMeasurement::getDim(), genfit::AbsTrackRep::getDim(), genfit::Exception::getExcString(), genfit::Track::getFitStatus(), genfit::KalmanFitterInfo::getFittedState(), genfit::Track::getFittedState(), genfit::TrackPoint::getFitterInfo(), genfit::KalmanFitterInfo::getForwardPrediction(), genfit::KalmanFitterInfo::getForwardUpdate(), genfit::MeasurementOnPlane::getHMatrix(), genfit::AbsHMatrix::getMatrix(), genfit::KalmanFitterInfo::getMeasurementOnPlane(), genfit::KalmanFitterInfo::getNumMeasurements(), genfit::Track::getNumPointsWithMeasurement(), genfit::TrackPoint::getNumRawMeasurements(), genfit::Track::getNumReps(), genfit::StateOnPlane::getPlane(), genfit::Track::getPointWithMeasurement(), genfit::StateOnPlane::getPos(), genfit::AbsMeasurement::getRawHitCov(), genfit::TrackPoint::getRawMeasurement(), genfit::KalmanFitterInfo::getReferenceState(), genfit::StateOnPlane::getState(), genfit::Track::getTrackRep(), H, genfit::KalmanFitterInfo::hasBackwardPrediction(), genfit::KalmanFitterInfo::hasBackwardUpdate(), genfit::TrackPoint::hasFitterInfo(), genfit::KalmanFitterInfo::hasForwardPrediction(), genfit::KalmanFitterInfo::hasForwardUpdate(), genfit::KalmanFitterInfo::hasPredictionsAndUpdates(), genfit::TrackPoint::hasRawMeasurements(), genfit::KalmanFitterInfo::hasReferenceState(), i, genfit::FitStatus::isFitted(), genfit::AbsMeasurement::isLeftRightMeasurement(), j, makeLines(), max, min, mmHandling_, nMaxFailed_, nMaxIter_, nMinIter_, norm, genfit::MeasuredStateOnPlane::Print(), genfit::FitStatus::Print(), genfit::Track::Print(), refit_, genfit::RefKalman, repId_, resort_, genfit::AbsTrackRep::setPropDir(), genfit::SimpleKalman, squareRootFormalism_, trackId_, v, and genfit::Exception::what().
Referenced by gotoEvent(), and open().
double genfit::EventDisplay::getErrScale ()
Get the error scaling factor.
Definition at line 135 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 135 of file EventDisplay.cc
References errorScale_.
EventDisplay * genfit::EventDisplay::getInstance () static
Definition at line 137 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 137 of file EventDisplay.cc
References EventDisplay(), and eventDisplay_.
Referenced by PHGenFit::Fitter::Fitter(), main(), makeGui(), and PHGenFit::Fitter::set_do_Event_Display().
int genfit::EventDisplay::getNEvents ()
Get the total number of events stored.
Definition at line 213 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 213 of file EventDisplay.cc
References events_.
Referenced by open().
void genfit::EventDisplay::gotoEvent (unsigned int id)
Go to event with index id.
Definition at line 216 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 216 of file EventDisplay.cc
References drawEvent(), errorScale_, eventId_, and events_.
Referenced by guiGoto(), guiGoto2(), guiSelectFitterId(), guiSelectMmHandling(), guiSetDrawParams(), next(), open(), and prev().
void genfit::EventDisplay::guiGoto ()
Definition at line 1585 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 1585 of file EventDisplay.cc
References gotoEvent(), guiEvent, guiEvent2, and n.
void genfit::EventDisplay::guiGoto2 ()
Definition at line 1591 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 1591 of file EventDisplay.cc
References gotoEvent(), guiEvent, guiEvent2, and n.
void genfit::EventDisplay::guiSelectFitterId (int val)
Definition at line 1640 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 1640 of file EventDisplay.cc
References eventId_, fitterId_, and gotoEvent().
void genfit::EventDisplay::guiSelectMmHandling (int val)
Definition at line 1645 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 1645 of file EventDisplay.cc
References eventId_, gotoEvent(), and mmHandling_.
void genfit::EventDisplay::guiSetDrawParams ()
Definition at line 1598 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 1598 of file EventDisplay.cc
References dChi2Ref_, debugLvl_, dPVal_, drawAllTracks_, drawAutoScale_, drawBackward_, drawCardinalRep_, drawDetectors_, drawErrors_, drawForward_, drawGeometry_, drawHits_, drawPlanes_, drawRefTrack_, drawScaleMan_, drawTrack_, drawTrackMarkers_, dRelChi2_, errorScale_, eventId_, gotoEvent(), guiDChi2Ref_, guiDebugLvl_, guiDPVal_, guiDrawAllTracks_, guiDrawAutoScale_, guiDrawBackward_, guiDrawCardinalRep_, guiDrawDetectors_, guiDrawErrors_, guiDrawForward_, guiDrawGeometry_, guiDrawHits_, guiDrawPlanes_, guiDrawRefTrack_, guiDrawScaleMan_, guiDrawTrack_, guiDrawTrackMarkers_, guiErrorScale_, guiNMaxFailed_, guiNMaxIter_, guiNMinIter_, guiRefit_, guiRelChi2_, guiRepId_, guiResort_, guiSquareRootFormalism_, guiTrackId_, nMaxFailed_, nMaxIter_, nMinIter_, refit_, repId_, resort_, squareRootFormalism_, and trackId_.
void genfit::EventDisplay::makeGui () private
Build the buttons for event navigation.
Definition at line 1195 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 1195 of file EventDisplay.cc
References dChi2Ref_, debugLvl_, dPVal_, drawAllTracks_, drawAutoScale_, drawBackward_, drawCardinalRep_, drawDetectors_, drawErrors_, drawForward_, drawGeometry_, drawHits_, drawPlanes_, drawRefTrack_, drawScaleMan_, drawTrack_, drawTrackMarkers_, dRelChi2_, E, errorScale_, getInstance(), guiDChi2Ref_, guiDebugLvl_, guiDPVal_, guiDrawAllTracks_, guiDrawAutoScale_, guiDrawBackward_, guiDrawCardinalRep_, guiDrawDetectors_, guiDrawErrors_, guiDrawForward_, guiDrawGeometry_, guiDrawHits_, guiDrawPlanes_, guiDrawRefTrack_, guiDrawScaleMan_, guiDrawTrack_, guiDrawTrackMarkers_, guiErrorScale_, guiEvent, guiEvent2, guiFitterId_, guiMmHandling_, guiNMaxFailed_, guiNMaxIter_, guiNMinIter_, guiRefit_, guiRelChi2_, guiRepId_, guiResort_, guiSquareRootFormalism_, guiTrackId_, nMaxFailed_, nMaxIter_, nMinIter_, refit_, repId_, resort_, squareRootFormalism_, and trackId_.
Referenced by open().
void genfit::EventDisplay::makeLines (const StateOnPlane * prevState, const StateOnPlane * state, const AbsTrackRep * rep, const Color_t & color, const Style_t & style, bool drawMarkers, bool drawErrors, double lineWidth = 2, int markerPos = 1) private
Definition at line 986 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 986 of file EventDisplay.cc
References assert, genfit::AbsTrackRep::extrapolateToPlane(), genfit::StateOnPlane::getPlane(), genfit::AbsTrackRep::getPosDir(), genfit::AbsTrackRep::getPosMomCov(), i, k, min, pos, position, genfit::DetPlane::setO(), genfit::Exception::what(), TauVsDIS_MachineLearning_Differentiation::X, TauVsDIS_MachineLearning_Differentiation::Y, and SVM_v1::Z.
Referenced by drawEvent().
void genfit::EventDisplay::next (unsigned int stp = 1)
Go to the next event or step a certain number of events ahead.
Definition at line 196 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 196 of file EventDisplay.cc
References eventId_, and gotoEvent().
void genfit::EventDisplay::open ()
Open the event display.
Definition at line 246 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 246 of file EventDisplay.cc
References drawEvent(), drawSilent_, errorScale_, getNEvents(), gotoEvent(), and makeGui().
Referenced by PHGenFit::Fitter::displayEvent(), and main().
void genfit::EventDisplay::prev (unsigned int stp = 1)
Go to the previous event or step a certain number of events back.
Definition at line 202 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 202 of file EventDisplay.cc
References eventId_, events_, and gotoEvent().
Referenced by lustrf(), pyprep(), and pystrf().
void genfit::EventDisplay::reset ()
Drop all events.
Definition at line 148 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 148 of file EventDisplay.cc
References events_, i, and j.
Referenced by main(), and ~EventDisplay().
void genfit::EventDisplay::setErrScale (double errScale = 1.)
Set the scaling factor for the visualization of the errors.
Definition at line 133 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 133 of file EventDisplay.cc
References errorScale_.
void genfit::EventDisplay::setOptions (std::string opts)
Set the display options.
        The option string lets you steer the way the events are displayed. The following
        options are available:\n
        \n
        'A': Autoscale errors. The representation of hits are scaled with the error found
             their covariance matrix. This can lead to hits not being displayed beause the
             errors are too small. Autoscaling ensures that the errors are scaled up
             sufficiently to ensure all hits are displayed. However, this can lead to unwanted
             results if there are only a few hits with very small errors, as all hits are scaled
             by the same factor to ensure consistency.\n\n
        'B': Draw Backward Fit (track segments start at updates and end at predictions)\n\n
        'D': Draw detectors. This causes a simple representation for all detectors to be drawn. For
             planar detectors, this is a plane with the same position and orientation of the real
             detector plane, but with different size. For wires, this is a tube whose diameter
             is equal to the value measured by the wire. Spacepoint hits are not affected by this
             option.\n\n
        'E': Draw Error cones (position and direction uncertainties) around the track.\n\n
'F': Draw Forward Fit (track segments start at updates and end at predictions) 'H': Draw hits. This causes the hits to be visualized. Normally, the size of the hit representation is connected to the covariance matrix of the hit, scaled by the value set in setErrScale which is normally 1. See also option 'A' and 'S'. Normally used in connection with 'D'.
'G': Draw geometry. Draw also the geometry in the gGeoManager. This feature is experimental and may lead to strang things being drawn.
'M': Draw track markers. Draw the intersection points between the track and the virtual (and/or real) detector planes. Can only be used in connection with 'T'.
'P': Draw detector planes. Draws the virtual (and/or real) detector planes.
'S': Scale manually. This leads to the spacepoint hits (and only them up to now!) being drawn as spheres with radius 0.5 scaled with the error scale factor. Can be used if the scaling with errors leads to problems.
'T': Draw Track. Draw the track as lines between the virtual (and/or real) detector planes.
'X': Draw silent. Does not run the TApplication.
Definition at line 112 of file EventDisplay.cc.
View newest version in sPHENIX GitHub at line 112 of file EventDisplay.cc
References drawAutoScale_, drawBackward_, drawDetectors_, drawErrors_, drawForward_, drawGeometry_, drawHits_, drawPlanes_, drawScaleMan_, drawSilent_, drawTrack_, drawTrackMarkers_, and i.
Referenced by TpcPrototypeGenFitTrkFinder::End(), TpcPrototypeGenFitTrkFitter::End(), and main().
Member Data Documentation
double genfit::EventDisplay::dChi2Ref_ private
Definition at line 234 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 234 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
unsigned int genfit::EventDisplay::debugLvl_ private
Definition at line 221 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 221 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
double genfit::EventDisplay::dPVal_ private
Definition at line 230 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 230 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
bool genfit::EventDisplay::drawAllTracks_ private
Definition at line 214 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 214 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
bool genfit::EventDisplay::drawAutoScale_ private
Definition at line 201 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 201 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), makeGui(), and setOptions().
bool genfit::EventDisplay::drawBackward_ private
Definition at line 198 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 198 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), makeGui(), and setOptions().
bool genfit::EventDisplay::drawCardinalRep_ private
Definition at line 209 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 209 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
bool genfit::EventDisplay::drawDetectors_ private
Definition at line 180 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 180 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), makeGui(), and setOptions().
bool genfit::EventDisplay::drawErrors_ private
Definition at line 184 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 184 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), makeGui(), and setOptions().
bool genfit::EventDisplay::drawForward_ private
Definition at line 196 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 196 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), makeGui(), and setOptions().
bool genfit::EventDisplay::drawGeometry_ private
Definition at line 178 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 178 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), makeGui(), and setOptions().
bool genfit::EventDisplay::drawHits_ private
Definition at line 182 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 182 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), makeGui(), and setOptions().
bool genfit::EventDisplay::drawPlanes_ private
Definition at line 187 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 187 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), makeGui(), and setOptions().
bool genfit::EventDisplay::drawRefTrack_ private
Definition at line 194 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 194 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
bool genfit::EventDisplay::drawScaleMan_ private
Definition at line 203 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 203 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), makeGui(), and setOptions().
bool genfit::EventDisplay::drawSilent_ private
Definition at line 206 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 206 of file EventDisplay.h
Referenced by open(), and setOptions().
bool genfit::EventDisplay::drawTrack_ private
Definition at line 192 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 192 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), makeGui(), and setOptions().
bool genfit::EventDisplay::drawTrackMarkers_ private
Definition at line 189 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 189 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), makeGui(), and setOptions().
double genfit::EventDisplay::dRelChi2_ private
Definition at line 232 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 232 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
double genfit::EventDisplay::errorScale_ private
Definition at line 170 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 170 of file EventDisplay.h
Referenced by drawEvent(), getErrScale(), gotoEvent(), guiSetDrawParams(), makeGui(), open(), and setErrScale().
EventDisplay * genfit::EventDisplay::eventDisplay_ = nullptr static private
Definition at line 168 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 168 of file EventDisplay.h
Referenced by getInstance().
unsigned int genfit::EventDisplay::eventId_ private
Definition at line 169 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 169 of file EventDisplay.h
Referenced by EventDisplay(), gotoEvent(), guiSelectFitterId(), guiSelectMmHandling(), guiSetDrawParams(), next(), and prev().
std::vector< std::vector<genfit::Track*>* > genfit::EventDisplay::events_ private
Definition at line 171 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 171 of file EventDisplay.h
Referenced by addEvent(), drawEvent(), getNEvents(), gotoEvent(), prev(), and reset().
eFitterType genfit::EventDisplay::fitterId_ private
Definition at line 223 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 223 of file EventDisplay.h
Referenced by drawEvent(), and guiSelectFitterId().
TGNumberEntry* genfit::EventDisplay::guiDChi2Ref_ private
Definition at line 233 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 233 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGNumberEntry* genfit::EventDisplay::guiDebugLvl_ private
Definition at line 220 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 220 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGNumberEntry* genfit::EventDisplay::guiDPVal_ private
Definition at line 229 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 229 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawAllTracks_ private
Definition at line 213 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 213 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawAutoScale_ private
Definition at line 200 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 200 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawBackward_ private
Definition at line 197 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 197 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawCardinalRep_ private
Definition at line 208 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 208 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawDetectors_ private
Definition at line 179 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 179 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawErrors_ private
Definition at line 183 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 183 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawForward_ private
Definition at line 195 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 195 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawGeometry_ private
Definition at line 177 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 177 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawHits_ private
Definition at line 181 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 181 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawPlanes_ private
Definition at line 186 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 186 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawRefTrack_ private
Definition at line 193 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 193 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawScaleMan_ private
Definition at line 202 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 202 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawTrack_ private
Definition at line 191 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 191 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiDrawTrackMarkers_ private
Definition at line 188 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 188 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGNumberEntry* genfit::EventDisplay::guiErrorScale_ private
Definition at line 204 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 204 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGNumberEntry* genfit::EventDisplay::guiEvent private
Definition at line 174 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 174 of file EventDisplay.h
Referenced by guiGoto(), guiGoto2(), and makeGui().
TGNumberEntry* genfit::EventDisplay::guiEvent2 private
Definition at line 175 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 175 of file EventDisplay.h
Referenced by guiGoto(), guiGoto2(), and makeGui().
TGButtonGroup* genfit::EventDisplay::guiFitterId_ private
Definition at line 222 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 222 of file EventDisplay.h
Referenced by makeGui().
TGButtonGroup* genfit::EventDisplay::guiMmHandling_ private
Definition at line 224 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 224 of file EventDisplay.h
Referenced by makeGui().
TGNumberEntry* genfit::EventDisplay::guiNMaxFailed_ private
Definition at line 239 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 239 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGNumberEntry* genfit::EventDisplay::guiNMaxIter_ private
Definition at line 237 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 237 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGNumberEntry* genfit::EventDisplay::guiNMinIter_ private
Definition at line 235 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 235 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiRefit_ private
Definition at line 218 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 218 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGNumberEntry* genfit::EventDisplay::guiRelChi2_ private
Definition at line 231 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 231 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGNumberEntry* genfit::EventDisplay::guiRepId_ private
Definition at line 210 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 210 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiResort_ private
Definition at line 241 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 241 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGCheckButton* genfit::EventDisplay::guiSquareRootFormalism_ private
Definition at line 227 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 227 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
TGNumberEntry* genfit::EventDisplay::guiTrackId_ private
Definition at line 215 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 215 of file EventDisplay.h
Referenced by guiSetDrawParams(), and makeGui().
eMultipleMeasurementHandling genfit::EventDisplay::mmHandling_ private
Definition at line 225 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 225 of file EventDisplay.h
Referenced by drawEvent(), and guiSelectMmHandling().
int genfit::EventDisplay::nMaxFailed_ private
Definition at line 240 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 240 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
unsigned int genfit::EventDisplay::nMaxIter_ private
Definition at line 238 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 238 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
unsigned int genfit::EventDisplay::nMinIter_ private
Definition at line 236 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 236 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
bool genfit::EventDisplay::refit_ private
Definition at line 219 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 219 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
unsigned int genfit::EventDisplay::repId_ private
Definition at line 211 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 211 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
bool genfit::EventDisplay::resort_ private
Definition at line 242 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 242 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
bool genfit::EventDisplay::squareRootFormalism_ private
Definition at line 228 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 228 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
unsigned int genfit::EventDisplay::trackId_ private
Definition at line 216 of file EventDisplay.h.
View newest version in sPHENIX GitHub at line 216 of file EventDisplay.h
Referenced by drawEvent(), guiSetDrawParams(), and makeGui().
The documentation for this class was generated from the following files:
GenFit/blob/master/eventDisplay/include/EventDisplay.h
GenFit/blob/master/eventDisplay/src/EventDisplay.cc