Analysis Software: genfit::GFRaveMagneticField Class Reference
genfit::GFRaveMagneticField Class Reference
GFRaveMagneticField class Uses the FieldManager to provide a magnetic field to rave.
#include <GenFit/blob/master/GFRave/include/GFRaveMagneticField.h>
Public Member Functions
GFRaveMagneticField ()
virtual GFRaveMagneticField * copy () const
virtual ~GFRaveMagneticField ()
virtual rave::Vector3D inTesla (const rave::Point3D &) const
Detailed Description
GFRaveMagneticField class Uses the FieldManager to provide a magnetic field to rave.
Definition at line 40 of file GFRaveMagneticField.h.
View newest version in sPHENIX GitHub at line 40 of file GFRaveMagneticField.h
Constructor & Destructor Documentation
genfit::GFRaveMagneticField::GFRaveMagneticField () inline
Definition at line 42 of file GFRaveMagneticField.h.
View newest version in sPHENIX GitHub at line 42 of file GFRaveMagneticField.h
Referenced by copy().
virtual genfit::GFRaveMagneticField::~GFRaveMagneticField () inline virtual
Definition at line 44 of file GFRaveMagneticField.h.
View newest version in sPHENIX GitHub at line 44 of file GFRaveMagneticField.h
Member Function Documentation
GFRaveMagneticField * genfit::GFRaveMagneticField::copy () const virtual
Definition at line 30 of file GFRaveMagneticField.cc.
View newest version in sPHENIX GitHub at line 30 of file GFRaveMagneticField.cc
References GFRaveMagneticField().
rave::Vector3D genfit::GFRaveMagneticField::inTesla (const rave::Point3D & position) const virtual
Definition at line 36 of file GFRaveMagneticField.cc.
View newest version in sPHENIX GitHub at line 36 of file GFRaveMagneticField.cc
References genfit::FieldManager::getFieldVal(), genfit::FieldManager::getInstance(), and pos.
The documentation for this class was generated from the following files:
GenFit/blob/master/GFRave/include/GFRaveMagneticField.h
GenFit/blob/master/GFRave/src/GFRaveMagneticField.cc