Analysis Software: KFParticleDatabase Class Reference
KFParticleDatabase Class Reference
The class stores information about particle masses and expected width of the peacks.
#include <KFParticle/blob/master/KFParticle/KFParticleDatabase.h>
Public Member Functions
KFParticleDatabase ()
~KFParticleDatabase ()
float GetMass (const int pdg) const
Vc::float_v GetMass (const Vc::int_v &pdg) const
void GetMotherMass (const Vc::int_v &pdg, Vc::float_v &massMotherPDG, Vc::float_v &massMotherPDGSigma) const
void GetMotherMass (const int pdg, float &massMotherPDG, float &massMotherPDGSigma) const
const float & GetPi0Mass () const
Returns the table PDG pi0 mass.
const float & GetPi0MassSigma () const
Returns expected width of the pi0 peak.
const float & GetD0Mass () const
Returns the table PDG D0 mass.
const float & GetD0MassSigma () const
Returns expected width of the D0 peak.
const float & GetDPlusMass () const
Returns the table PDG D+ mass.
const float & GetDPlusMassSigma () const
Returns expected width of the D+ peak.
Static Public Member Functions
static const KFParticleDatabase * Instance ()
Returns a pointer to the singleton object.
Private Attributes
float fMass [13]
float fMassSecPDG [8]
float fMassSecPDGSigma [8]
float fMassPi0PDG
Table mass of pi0.
float fMassPi0PDGSigma
Expected width of the pi0 peak.
float fMassD0PDG
Table mass of D0.
float fMassD0PDGSigma
Expected width of the D0 peak.
float fMassDPlusPDG
Table mass of D+.
float fMassDPlusPDGSigma
Expected width of the D+ peak.
Static Private Attributes
static KFParticleDatabase * fDatabase = 0
A singleton object.
Detailed Description
The class stores information about particle masses and expected width of the peacks.
Author
M.Zyzak, I.Kisel
Date
05.02.2019
Version
1.0
The class contains information required for the reconstruction of decay trees:
masses of the stable particles;
masses of the intermediate daughter particles (like Lambda, K0, Xi, D0, etc.);
expected widths of the peaks.
Definition at line 40 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 40 of file KFParticleDatabase.h
Constructor & Destructor Documentation
KFParticleDatabase::KFParticleDatabase ()
The default constructor. Initialises masses and widths of the peaks. Be aware, that widths of the peaks are experiment specific.
Definition at line 26 of file KFParticleDatabase.cxx.
View newest version in sPHENIX GitHub at line 26 of file KFParticleDatabase.cxx
References fDatabase, fMass, fMassSecPDG, and fMassSecPDGSigma.
KFParticleDatabase::~KFParticleDatabase () inline
Definition at line 45 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 45 of file KFParticleDatabase.h
Member Function Documentation
const float& KFParticleDatabase::GetD0Mass () const inline
Returns the table PDG D0 mass.
Definition at line 155 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 155 of file KFParticleDatabase.h
References fMassD0PDG.
Referenced by KFParticleFinder::ConstructTrackV0Cand().
const float& KFParticleDatabase::GetD0MassSigma () const inline
Returns expected width of the D0 peak.
Definition at line 156 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 156 of file KFParticleDatabase.h
References fMassD0PDGSigma.
Referenced by KFParticleFinder::ConstructTrackV0Cand().
const float& KFParticleDatabase::GetDPlusMass () const inline
Returns the table PDG D+ mass.
Definition at line 157 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 157 of file KFParticleDatabase.h
References fMassDPlusPDG.
Referenced by KFParticleFinder::ConstructTrackV0Cand().
const float& KFParticleDatabase::GetDPlusMassSigma () const inline
Returns expected width of the D+ peak.
Definition at line 158 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 158 of file KFParticleDatabase.h
References fMassDPlusPDGSigma.
Referenced by KFParticleFinder::ConstructTrackV0Cand().
float KFParticleDatabase::GetMass (const int pdg) const inline
Returns scalar float variable with the mass of the stable particle with the given PDG code. If the given PDG code is not the list of the current database mass of the pion is returned.
Parameters
[in] pdg - the input PDG code
Definition at line 47 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 47 of file KFParticleDatabase.h
References fMass.
Referenced by KFParticleSIMD::Create(), KFParticle::KFParticle(), KFParticleSIMD::KFParticleSIMD(), and KFParticleSIMD::Load().
Vc::float_v KFParticleDatabase::GetMass (const Vc::int_v & pdg) const inline
Returns vector float variable with the mass of the stable particles with the given PDG codes. If the given PDG code is not in the list of the current database mass of the pion is returned.
Parameters
[in] pdg - the input PDG codes of a set of particles in the SIMD-vector format
Definition at line 76 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 76 of file KFParticleDatabase.h
References fMass.
void KFParticleDatabase::GetMotherMass (const Vc::int_v & pdg, Vc::float_v & massMotherPDG, Vc::float_v & massMotherPDGSigma) const inline
Returns vector float variable with the mass of the short-lived particles with the given PDG codes and the expected widths of the corresponding peaks. If the given PDG code is not in the list of the current database mass of K0s is returned.
Parameters
[in] pdg - the input PDG code
[out] massMotherPDG - the output table mass for the given PDG code
[out] massMotherPDGSigma - expected width of the corresponding peak
Definition at line 101 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 101 of file KFParticleDatabase.h
References fMassSecPDG, and fMassSecPDGSigma.
Referenced by KFParticleFinder::ConstructPrimaryBG(), KFParticleFinder::Find2DaughterDecay(), KFParticleFinder::FindTrackV0Decay(), KFParticleFinder::SaveV0PrimSecCand(), and KFParticleTopoReconstructor::SelectParticleCandidates().
void KFParticleDatabase::GetMotherMass (const int pdg, float & massMotherPDG, float & massMotherPDGSigma) const inline
Returns scalar float variables with the mass of the short-lived particle with the given PDG code and the expected width of the corresponding peak. If the given PDG code is not in the list of the current database mass of K0s is returned.
Parameters
[in] pdg - the input PDG code
[out] massMotherPDG - the output table mass for the given PDG code
[out] massMotherPDGSigma - expected width of the corresponding peak
Definition at line 125 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 125 of file KFParticleDatabase.h
References fMassSecPDG, and fMassSecPDGSigma.
const float& KFParticleDatabase::GetPi0Mass () const inline
Returns the table PDG pi0 mass.
Definition at line 153 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 153 of file KFParticleDatabase.h
References fMassPi0PDG.
Referenced by KFParticleFinder::FindParticles().
const float& KFParticleDatabase::GetPi0MassSigma () const inline
Returns expected width of the pi0 peak.
Definition at line 154 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 154 of file KFParticleDatabase.h
References fMassPi0PDGSigma.
Referenced by KFParticleFinder::FindParticles().
static const KFParticleDatabase* KFParticleDatabase::Instance () inline static
Returns a pointer to the singleton object.
Definition at line 160 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 160 of file KFParticleDatabase.h
References fDatabase.
Referenced by KFParticleFinder::ConstructPrimaryBG(), KFParticleFinder::ConstructTrackV0Cand(), KFParticleSIMD::Create(), KFParticleFinder::Find2DaughterDecay(), KFParticleFinder::FindParticles(), KFParticleFinder::FindTrackV0Decay(), KFParticle::KFParticle(), KFParticleSIMD::KFParticleSIMD(), KFParticleSIMD::Load(), KFParticleFinder::SaveV0PrimSecCand(), and KFParticleTopoReconstructor::SelectParticleCandidates().
Member Data Documentation
KFParticleDatabase * KFParticleDatabase::fDatabase = 0 static private
A singleton object.
Definition at line 183 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 183 of file KFParticleDatabase.h
Referenced by Instance(), and KFParticleDatabase().
float KFParticleDatabase::fMass[13] private
Table PDG masses of particles, which can be registered by the tracking detector directly:
[ 0] - electron;
[ 1] - muon;
[ 2] - pion;
[ 3] - kaon;
[ 4] - proton;
[ 5] - deutron;
[ 6] - triton;
[ 7] - He3;
[ 8] - He4;
[ 9] - Sigma-;
[10] - Sigma+;
[11] - Xi;
[12] - Omega.
Definition at line 166 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 166 of file KFParticleDatabase.h
Referenced by GetMass(), and KFParticleDatabase().
float KFParticleDatabase::fMassD0PDG private
Table mass of D0.
Definition at line 178 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 178 of file KFParticleDatabase.h
Referenced by GetD0Mass().
float KFParticleDatabase::fMassD0PDGSigma private
Expected width of the D0 peak.
Definition at line 179 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 179 of file KFParticleDatabase.h
Referenced by GetD0MassSigma().
float KFParticleDatabase::fMassDPlusPDG private
Table mass of D+.
Definition at line 180 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 180 of file KFParticleDatabase.h
Referenced by GetDPlusMass().
float KFParticleDatabase::fMassDPlusPDGSigma private
Expected width of the D+ peak.
Definition at line 181 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 181 of file KFParticleDatabase.h
Referenced by GetDPlusMassSigma().
float KFParticleDatabase::fMassPi0PDG private
Table mass of pi0.
Definition at line 175 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 175 of file KFParticleDatabase.h
Referenced by GetPi0Mass().
float KFParticleDatabase::fMassPi0PDGSigma private
Expected width of the pi0 peak.
Definition at line 176 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 176 of file KFParticleDatabase.h
Referenced by GetPi0MassSigma().
float KFParticleDatabase::fMassSecPDG[8] private
Table PDG masses of short-lived particles, which are used for reconstruction of the decay trees:
[ 0] - K0s;
[ 1] - Lambda;
[ 2] - Xi;
[ 3] - gamma;
[ 4] - Omega;
[ 5] - H3Lambda;
[ 6] - He4Lambda;
[ 7] - He5Lambda.
Definition at line 170 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 170 of file KFParticleDatabase.h
Referenced by GetMotherMass(), and KFParticleDatabase().
float KFParticleDatabase::fMassSecPDGSigma[8] private
Expected widths of peaks of short-lived particles, which are used for reconstruction of the decay trees:
[ 0] - K0s;
[ 1] - Lambda;
[ 2] - Xi;
[ 3] - gamma;
[ 4] - Omega;
[ 5] - H3Lambda;
[ 6] - He4Lambda;
[ 7] - He5Lambda.
Definition at line 173 of file KFParticleDatabase.h.
View newest version in sPHENIX GitHub at line 173 of file KFParticleDatabase.h
Referenced by GetMotherMass(), and KFParticleDatabase().
The documentation for this class was generated from the following files:
KFParticle/blob/master/KFParticle/KFParticleDatabase.h
KFParticle/blob/master/KFParticle/KFParticleDatabase.cxx