Analysis Software: genfit::AbsHMatrix Class Reference
genfit::AbsHMatrix Class Reference abstract
HMatrix for projecting from AbsTrackRep parameters to measured parameters in a DetPlane.
#include <GenFit/blob/master/core/include/AbsHMatrix.h>
Public Member Functions
AbsHMatrix ()
virtual ~AbsHMatrix ()
virtual const TMatrixD & getMatrix () const =0
Get the actual matrix representation.
virtual TVectorD Hv (const TVectorD &v) const
H*v.
virtual TMatrixD MHt (const TMatrixDSym &M) const
M*H^t.
virtual TMatrixD MHt (const TMatrixD &M) const
virtual void HMHt (TMatrixDSym &M) const
similarity: H*M*H^t
virtual AbsHMatrix * clone () const =0
bool operator== (const AbsHMatrix &other) const
bool operator!= (const AbsHMatrix &other) const
virtual bool isEqual (const AbsHMatrix &other) const =0
virtual void Print (const Option_t *="") const
Protected Member Functions
AbsHMatrix (const AbsHMatrix &o)
AbsHMatrix & operator= (const AbsHMatrix &)
Detailed Description
HMatrix for projecting from AbsTrackRep parameters to measured parameters in a DetPlane.
Definition at line 37 of file AbsHMatrix.h.
View newest version in sPHENIX GitHub at line 37 of file AbsHMatrix.h
Constructor & Destructor Documentation
genfit::AbsHMatrix::AbsHMatrix () inline
Definition at line 41 of file AbsHMatrix.h.
View newest version in sPHENIX GitHub at line 41 of file AbsHMatrix.h
virtual genfit::AbsHMatrix::~AbsHMatrix () inline virtual
Definition at line 43 of file AbsHMatrix.h.
View newest version in sPHENIX GitHub at line 43 of file AbsHMatrix.h
genfit::AbsHMatrix::AbsHMatrix (const AbsHMatrix & o) inline protected
Definition at line 68 of file AbsHMatrix.h.
View newest version in sPHENIX GitHub at line 68 of file AbsHMatrix.h
Member Function Documentation
virtual AbsHMatrix* genfit::AbsHMatrix::clone () const pure virtual
Implemented in genfit::HMatrixUnit, genfit::HMatrixUV, genfit::HMatrixPhi, genfit::HMatrixU, and genfit::HMatrixV.
Referenced by genfit::KalmanFitterInfo::getResidual().
virtual const TMatrixD& genfit::AbsHMatrix::getMatrix () const pure virtual
Get the actual matrix representation.
Implemented in genfit::HMatrixUnit, genfit::HMatrixUV, genfit::HMatrixPhi, genfit::HMatrixU, and genfit::HMatrixV.
Referenced by genfit::EventDisplay::drawEvent(), HMHt(), Hv(), and MHt().
virtual void genfit::AbsHMatrix::HMHt (TMatrixDSym & M) const inline virtual
similarity: H*M*H^t
Reimplemented in genfit::HMatrixUnit, genfit::HMatrixUV, genfit::HMatrixPhi, genfit::HMatrixU, and genfit::HMatrixV.
Definition at line 56 of file AbsHMatrix.h.
View newest version in sPHENIX GitHub at line 56 of file AbsHMatrix.h
References getMatrix().
Referenced by genfit::KalmanFitterInfo::getResidual().
virtual TVectorD genfit::AbsHMatrix::Hv (const TVectorD & v) const inline virtual
H*v.
Reimplemented in genfit::HMatrixUnit, genfit::HMatrixUV, genfit::HMatrixPhi, genfit::HMatrixU, and genfit::HMatrixV.
Definition at line 49 of file AbsHMatrix.h.
View newest version in sPHENIX GitHub at line 49 of file AbsHMatrix.h
References getMatrix(), and v.
Referenced by genfit::KalmanFitterInfo::getClosestMeasurementOnPlane(), and genfit::KalmanFitterInfo::getResidual().
virtual bool genfit::AbsHMatrix::isEqual (const AbsHMatrix & other) const pure virtual
Implemented in genfit::HMatrixUnit, genfit::HMatrixUV, genfit::HMatrixPhi, genfit::HMatrixU, and genfit::HMatrixV.
Referenced by operator!=(), operator==(), genfit::GblFitterInfo::Print(), and genfit::GFGbl::processTrackWithRep().
virtual TMatrixD genfit::AbsHMatrix::MHt (const TMatrixDSym & M) const inline virtual
M*H^t.
Reimplemented in genfit::HMatrixUnit, genfit::HMatrixUV, genfit::HMatrixPhi, genfit::HMatrixU, and genfit::HMatrixV.
Definition at line 52 of file AbsHMatrix.h.
View newest version in sPHENIX GitHub at line 52 of file AbsHMatrix.h
References getMatrix().
Referenced by genfit::tools::kalmanUpdateSqrt().
virtual TMatrixD genfit::AbsHMatrix::MHt (const TMatrixD & M) const inline virtual
Reimplemented in genfit::HMatrixUnit, genfit::HMatrixUV, genfit::HMatrixPhi, genfit::HMatrixU, and genfit::HMatrixV.
Definition at line 53 of file AbsHMatrix.h.
View newest version in sPHENIX GitHub at line 53 of file AbsHMatrix.h
References getMatrix().
bool genfit::AbsHMatrix::operator!= (const AbsHMatrix & other) const inline
Definition at line 61 of file AbsHMatrix.h.
View newest version in sPHENIX GitHub at line 61 of file AbsHMatrix.h
References isEqual().
AbsHMatrix& genfit::AbsHMatrix::operator= (const AbsHMatrix &) protected
bool genfit::AbsHMatrix::operator== (const AbsHMatrix & other) const inline
Definition at line 60 of file AbsHMatrix.h.
View newest version in sPHENIX GitHub at line 60 of file AbsHMatrix.h
References isEqual().
virtual void genfit::AbsHMatrix::Print (const Option_t * = "") const inline virtual
Reimplemented in genfit::HMatrixUnit, genfit::HMatrixUV, genfit::HMatrixPhi, genfit::HMatrixU, and genfit::HMatrixV.
Definition at line 64 of file AbsHMatrix.h.
View newest version in sPHENIX GitHub at line 64 of file AbsHMatrix.h
The documentation for this class was generated from the following file:
GenFit/blob/master/core/include/AbsHMatrix.h