Analysis Software: genfit::MeasurementOnPlane Class Reference
genfit::MeasurementOnPlane Class Reference
Measured coordinates on a plane.
#include <GenFit/blob/master/core/include/MeasurementOnPlane.h>
Public Member Functions
MeasurementOnPlane (const AbsTrackRep *rep=nullptr)
MeasurementOnPlane (const TVectorD &state, const TMatrixDSym &cov, SharedPlanePtr plane, const AbsTrackRep *rep, const AbsHMatrix *hMatrix, double weight=1.)
MeasurementOnPlane (const MeasurementOnPlane &other)
copy constructor
MeasurementOnPlane & operator= (MeasurementOnPlane other)
assignment operator
void swap (MeasurementOnPlane &other)
virtual ~MeasurementOnPlane ()
const AbsHMatrix * getHMatrix () const
double getWeight () const
TMatrixDSym getWeightedCov ()
void setHMatrix (const AbsHMatrix *hMatrix)
void setWeight (double weight)
void Print (Option_t *option="") const override
Public Member Functions inherited from genfit::MeasuredStateOnPlane
MeasuredStateOnPlane (const AbsTrackRep *rep=nullptr)
MeasuredStateOnPlane (const TVectorD &state, const TMatrixDSym &cov, const genfit::SharedPlanePtr &plane, const AbsTrackRep *rep)
MeasuredStateOnPlane (const TVectorD &state, const TMatrixDSym &cov, const genfit::SharedPlanePtr &plane, const AbsTrackRep *rep, const TVectorD &auxInfo)
MeasuredStateOnPlane (const MeasuredStateOnPlane &o)
MeasuredStateOnPlane (const StateOnPlane &state, const TMatrixDSym &cov)
MeasuredStateOnPlane & operator= (MeasuredStateOnPlane other)
void swap (MeasuredStateOnPlane &other)
virtual ~MeasuredStateOnPlane ()
virtual MeasuredStateOnPlane * clone () const override
const TMatrixDSym & getCov () const
TMatrixDSym & getCov ()
void blowUpCov (double blowUpFac, bool resetOffDiagonals=true, double maxVal=-1.)
Blow up covariance matrix with blowUpFac. Per default, off diagonals are reset to 0 and the maximum values are limited to maxVal.
void setStateCov (const TVectorD &state, const TMatrixDSym &cov)
void setStateCovPlane (const TVectorD &state, const TMatrixDSym &cov, const SharedPlanePtr &plane)
void setCov (const TMatrixDSym &cov)
TMatrixDSym get6DCov () const
void getPosMomCov (TVector3 &pos, TVector3 &mom, TMatrixDSym &cov) const
void get6DStateCov (TVectorD &stateVec, TMatrixDSym &cov) const
double getMomVar () const
void setPosMomErr (const TVector3 &pos, const TVector3 &mom, const TVector3 &posErr, const TVector3 &momErr)
void setPosMomCov (const TVector3 &pos, const TVector3 &mom, const TMatrixDSym &cov6x6)
void setPosMomCov (const TVectorD &state6, const TMatrixDSym &cov6x6)
Public Member Functions inherited from genfit::StateOnPlane
StateOnPlane (const AbsTrackRep *rep=nullptr)
StateOnPlane (const TVectorD &state, const SharedPlanePtr &plane, const AbsTrackRep *rep)
state is defined by the TrackReps parameterization
StateOnPlane (const TVectorD &state, const SharedPlanePtr &plane, const AbsTrackRep *rep, const TVectorD &auxInfo)
StateOnPlane & operator= (StateOnPlane other)
void swap (StateOnPlane &other)
virtual ~StateOnPlane ()
const TVectorD & getState () const
TVectorD & getState ()
const TVectorD & getAuxInfo () const
TVectorD & getAuxInfo ()
const SharedPlanePtr & getPlane () const
const AbsTrackRep * getRep () const
void setState (const TVectorD &state)
void setPlane (const SharedPlanePtr &plane)
void setStatePlane (const TVectorD &state, const SharedPlanePtr &plane)
void setAuxInfo (const TVectorD &auxInfo)
void setRep (const AbsTrackRep *rep)
double extrapolateToPlane (const SharedPlanePtr &plane, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToLine (const TVector3 &linePoint, const TVector3 &lineDirection, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToPoint (const TVector3 &point, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToPoint (const TVector3 &point, const TMatrixDSym &G, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToCylinder (double radius, const TVector3 &linePoint=TVector3(0., 0., 0.), const TVector3 &lineDirection=TVector3(0., 0., 1.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToCone (double openingAngle, const TVector3 &conePoint=TVector3(0., 0., 0.), const TVector3 &coneDirection=TVector3(0., 0., 1.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToSphere (double radius, const TVector3 &point=TVector3(0., 0., 0.), bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateBy (double step, bool stopAtBoundary=false, bool calcJacobianNoise=false)
double extrapolateToMeasurement (const AbsMeasurement *measurement, bool stopAtBoundary=false, bool calcJacobianNoise=false)
TVector3 getPos () const
TVector3 getMom () const
TVector3 getDir () const
void getPosMom (TVector3 &pos, TVector3 &mom) const
void getPosDir (TVector3 &pos, TVector3 &dir) const
TVectorD get6DState () const
double getMomMag () const
int getPDG () const
double getCharge () const
double getQop () const
double getMass () const
double getTime () const
void setPosMom (const TVector3 &pos, const TVector3 &mom)
void setPosMom (const TVectorD &state6)
void setChargeSign (double charge)
void setQop (double qop)
void setTime (double time)
Protected Attributes
std::unique_ptr< const AbsHMatrix > hMatrix_
double weight_
Protected Attributes inherited from genfit::MeasuredStateOnPlane
TMatrixDSym cov_
Protected Attributes inherited from genfit::StateOnPlane
TVectorD state_
TVectorD auxInfo_
SharedPlanePtr sharedPlane_
Private Member Functions
TVector3 getPos () const
TVector3 getMom () const
TVector3 getDir () const
void getPosMom (TVector3 &pos, TVector3 &mom) const
void getPosDir (TVector3 &pos, TVector3 &dir) const
TVectorD get6DState () const
double getMomMag () const
int getPDG () const
double getCharge () const
double getQop () const
double getMass () const
double getTime () const
void setPosMom (const TVector3 &pos, const TVector3 &mom)
void setPosMom (const TVectorD &state6)
void setChargeSign (double charge)
void setQop (double qop)
void setTime (double time)
Detailed Description
Measured coordinates on a plane.
The dimensionality will usually be 1 or 2. The HMatrix corresponds to a projection matrix, which is used to project the track parameters with the original dimensionality down to the measured dimensionality.
Definition at line 46 of file MeasurementOnPlane.h.
View newest version in sPHENIX GitHub at line 46 of file MeasurementOnPlane.h
Constructor & Destructor Documentation
genfit::MeasurementOnPlane::MeasurementOnPlane (const AbsTrackRep * rep = nullptr) inline
Definition at line 50 of file MeasurementOnPlane.h.
View newest version in sPHENIX GitHub at line 50 of file MeasurementOnPlane.h
genfit::MeasurementOnPlane::MeasurementOnPlane (const TVectorD & state, const TMatrixDSym & cov, SharedPlanePtr plane, const AbsTrackRep * rep, const AbsHMatrix * hMatrix, double weight = 1.) inline
Definition at line 52 of file MeasurementOnPlane.h.
View newest version in sPHENIX GitHub at line 52 of file MeasurementOnPlane.h
genfit::MeasurementOnPlane::MeasurementOnPlane (const MeasurementOnPlane & other)
copy constructor
Definition at line 29 of file MeasurementOnPlane.cc.
View newest version in sPHENIX GitHub at line 29 of file MeasurementOnPlane.cc
References hMatrix_.
virtual genfit::MeasurementOnPlane::~MeasurementOnPlane () inline virtual
Definition at line 61 of file MeasurementOnPlane.h.
View newest version in sPHENIX GitHub at line 61 of file MeasurementOnPlane.h
Member Function Documentation
TVectorD genfit::MeasurementOnPlane::get6DState () const private
double genfit::MeasurementOnPlane::getCharge () const private
TVector3 genfit::MeasurementOnPlane::getDir () const private
const AbsHMatrix* genfit::MeasurementOnPlane::getHMatrix () const inline
Definition at line 63 of file MeasurementOnPlane.h.
View newest version in sPHENIX GitHub at line 63 of file MeasurementOnPlane.h
References hMatrix_.
Referenced by genfit::EventDisplay::drawEvent(), genfit::KalmanFitterInfo::getResidual(), genfit::KalmanFitter::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), and PHGenFit::Track::updateOneMeasurementKalman().
double genfit::MeasurementOnPlane::getMass () const private
TVector3 genfit::MeasurementOnPlane::getMom () const private
double genfit::MeasurementOnPlane::getMomMag () const private
int genfit::MeasurementOnPlane::getPDG () const private
TVector3 genfit::MeasurementOnPlane::getPos () const private
void genfit::MeasurementOnPlane::getPosDir (TVector3 & pos, TVector3 & dir) const private
void genfit::MeasurementOnPlane::getPosMom (TVector3 & pos, TVector3 & mom) const private
double genfit::MeasurementOnPlane::getQop () const private
double genfit::MeasurementOnPlane::getTime () const private
double genfit::MeasurementOnPlane::getWeight () const inline
Definition at line 64 of file MeasurementOnPlane.h.
View newest version in sPHENIX GitHub at line 64 of file MeasurementOnPlane.h
References weight_.
Referenced by genfit::DAF::calcWeights(), genfit::KalmanFitterInfo::getResidual(), genfit::KalmanFitterInfo::getWeights(), genfit::KalmanFitter::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPoint(), and genfit::KalmanFitterRefTrack::processTrackPointSqrt().
TMatrixDSym genfit::MeasurementOnPlane::getWeightedCov () inline
Definition at line 66 of file MeasurementOnPlane.h.
View newest version in sPHENIX GitHub at line 66 of file MeasurementOnPlane.h
References genfit::MeasuredStateOnPlane::cov_, and weight_.
MeasurementOnPlane & genfit::MeasurementOnPlane::operator= (MeasurementOnPlane other)
assignment operator
Definition at line 37 of file MeasurementOnPlane.cc.
View newest version in sPHENIX GitHub at line 37 of file MeasurementOnPlane.cc
References swap().
void genfit::MeasurementOnPlane::Print (Option_t * option = "") const override virtual
Reimplemented from genfit::MeasuredStateOnPlane.
Definition at line 50 of file MeasurementOnPlane.cc.
View newest version in sPHENIX GitHub at line 50 of file MeasurementOnPlane.cc
References genfit::MeasuredStateOnPlane::cov_, hMatrix_, genfit::printOut, genfit::StateOnPlane::sharedPlane_, genfit::StateOnPlane::state_, and weight_.
void genfit::MeasurementOnPlane::setChargeSign (double charge) private
void genfit::MeasurementOnPlane::setHMatrix (const AbsHMatrix * hMatrix) inline
Definition at line 68 of file MeasurementOnPlane.h.
View newest version in sPHENIX GitHub at line 68 of file MeasurementOnPlane.h
References hMatrix_.
void genfit::MeasurementOnPlane::setPosMom (const TVector3 & pos, const TVector3 & mom) private
void genfit::MeasurementOnPlane::setPosMom (const TVectorD & state6) private
void genfit::MeasurementOnPlane::setQop (double qop) private
void genfit::MeasurementOnPlane::setTime (double time) private
void genfit::MeasurementOnPlane::setWeight (double weight) inline
Definition at line 69 of file MeasurementOnPlane.h.
View newest version in sPHENIX GitHub at line 69 of file MeasurementOnPlane.h
References E, and weight_.
Referenced by genfit::DAF::calcWeights(), genfit::WirePointMeasurement::constructMeasurementsOnPlane(), genfit::WireMeasurement::constructMeasurementsOnPlane(), genfit::WireMeasurementNew::constructMeasurementsOnPlane(), genfit::KalmanFitterInfo::getAvgWeightedMeasurementOnPlane(), and genfit::KalmanFitterInfo::setWeights().
void genfit::MeasurementOnPlane::swap (MeasurementOnPlane & other)
Definition at line 43 of file MeasurementOnPlane.cc.
View newest version in sPHENIX GitHub at line 43 of file MeasurementOnPlane.cc
References hMatrix_, genfit::MeasuredStateOnPlane::swap(), boost::swap(), and weight_.
Referenced by operator=().
Member Data Documentation
std::unique_ptr<const AbsHMatrix> genfit::MeasurementOnPlane::hMatrix_ protected
Definition at line 96 of file MeasurementOnPlane.h.
View newest version in sPHENIX GitHub at line 96 of file MeasurementOnPlane.h
Referenced by getHMatrix(), MeasurementOnPlane(), Print(), setHMatrix(), and swap().
double genfit::MeasurementOnPlane::weight_ protected
Definition at line 97 of file MeasurementOnPlane.h.
View newest version in sPHENIX GitHub at line 97 of file MeasurementOnPlane.h
Referenced by getWeight(), getWeightedCov(), Print(), setWeight(), and swap().
The documentation for this class was generated from the following files:
GenFit/blob/master/core/include/MeasurementOnPlane.h
GenFit/blob/master/core/src/MeasurementOnPlane.cc