Analysis Software: genfit::GblFitStatus Class Reference
genfit::GblFitStatus Class Reference
FitStatus for use with GblFitter.
#include <GenFit/blob/master/GBL/include/GblFitStatus.h>
Public Member Functions
GblFitStatus ()
virtual ~GblFitStatus ()
virtual FitStatus * clone () const override
void setCurvature (bool useCurvature)
bool hasCurvature ()
void setMaxLocalFitParams (unsigned maxLocalFitParams)
bool getMaxLocalFitParams ()
unsigned int getNumIterations () const
bool isFittedWithReferenceTrack () const
double getTrackLen () const
void setNumIterations (unsigned int numIterations)
void setIsFittedWithReferenceTrack (bool fittedWithReferenceTrack=true)
void setTrackLen (double trackLen)
virtual void Print (const Option_t *="") const override
Public Member Functions inherited from genfit::FitStatus
FitStatus ()
virtual ~FitStatus ()
bool isFitted () const
Has the track been fitted?
bool isFitConverged (bool inAllPoints=true) const
Did the fit converge (in all Points or only partially)?
bool isFitConvergedFully () const
bool isFitConvergedPartially () const
int getNFailedPoints () const
bool hasTrackChanged () const
Has anything in the Track been changed since the fit?
bool isTrackPruned () const
Has the track been pruned after the fit?
double getCharge () const
Get the fitted charge.
double getChi2 () const
Get chi^2 of the fit.
double getNdf () const
Get the degrees of freedom of the fit.
virtual double getPVal () const
Get the p value of the fit.
void setIsFitted (bool fitted=true)
void setIsFitConvergedFully (bool fitConverged=true)
void setIsFitConvergedPartially (bool fitConverged=true)
void setNFailedPoints (int nFailedPoints)
void setHasTrackChanged (bool trackChanged=true)
void setCharge (double charge)
PruneFlags & getPruneFlags ()
void setChi2 (const double &chi2)
void setNdf (const double &ndf)
Protected Attributes
unsigned int numIterations_
bool fittedWithReferenceTrack_
double trackLen_
bool curvatureFlag_
int maxLocalFitParams_
Protected Attributes inherited from genfit::FitStatus
bool isFitted_
has the track been fitted?
bool isFitConvergedFully_
did the fit converge with all TrackPoints?
bool isFitConvergedPartially_
did the fit converge with a subset of all TrackPoints?
int nFailedPoints_
Number of failed TrackPoints.
bool trackHasChanged_
has anything in the Track been changed since the fit? -> fit isn't valid anymore
PruneFlags pruneFlags_
Prune flags.
double charge_
fitted charge
double chi2_
double ndf_
Additional Inherited Members
Protected Member Functions inherited from genfit::FitStatus
ClassDef (FitStatus, 3)
Detailed Description
FitStatus for use with GblFitter.
Definition at line 39 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 39 of file GblFitStatus.h
Constructor & Destructor Documentation
genfit::GblFitStatus::GblFitStatus () inline
Definition at line 43 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 43 of file GblFitStatus.h
Referenced by clone().
virtual genfit::GblFitStatus::~GblFitStatus () inline virtual
Definition at line 47 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 47 of file GblFitStatus.h
Member Function Documentation
virtual FitStatus* genfit::GblFitStatus::clone () const inline override virtual
Reimplemented from genfit::FitStatus.
Definition at line 49 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 49 of file GblFitStatus.h
References GblFitStatus().
bool genfit::GblFitStatus::getMaxLocalFitParams () inline
Definition at line 54 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 54 of file GblFitStatus.h
References maxLocalFitParams_.
Referenced by genfit::GblFitterInfo::constructGblPoint(), and genfit::GblFitterInfo::updateFitResults().
unsigned int genfit::GblFitStatus::getNumIterations () const inline
Definition at line 56 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 56 of file GblFitStatus.h
References numIterations_.
double genfit::GblFitStatus::getTrackLen () const inline
Definition at line 58 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 58 of file GblFitStatus.h
References trackLen_.
bool genfit::GblFitStatus::hasCurvature () inline
Definition at line 52 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 52 of file GblFitStatus.h
References curvatureFlag_.
Referenced by genfit::GblFitter::processTrackWithRep().
bool genfit::GblFitStatus::isFittedWithReferenceTrack () const inline
Definition at line 57 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 57 of file GblFitStatus.h
References fittedWithReferenceTrack_.
virtual void genfit::GblFitStatus::Print (const Option_t * = "") const inline override virtual
Reimplemented from genfit::FitStatus.
Definition at line 65 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 65 of file GblFitStatus.h
void genfit::GblFitStatus::setCurvature (bool useCurvature) inline
Definition at line 51 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 51 of file GblFitStatus.h
References curvatureFlag_.
Referenced by genfit::GblFitter::processTrackWithRep().
void genfit::GblFitStatus::setIsFittedWithReferenceTrack (bool fittedWithReferenceTrack = true) inline
Definition at line 62 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 62 of file GblFitStatus.h
References fittedWithReferenceTrack_.
Referenced by genfit::GblFitter::processTrackWithRep().
void genfit::GblFitStatus::setMaxLocalFitParams (unsigned maxLocalFitParams) inline
Definition at line 53 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 53 of file GblFitStatus.h
References maxLocalFitParams_.
Referenced by genfit::GblFitterInfo::constructGblPoint().
void genfit::GblFitStatus::setNumIterations (unsigned int numIterations) inline
Definition at line 61 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 61 of file GblFitStatus.h
References numIterations_.
Referenced by genfit::GblFitter::processTrackWithRep().
void genfit::GblFitStatus::setTrackLen (double trackLen) inline
Definition at line 63 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 63 of file GblFitStatus.h
References trackLen_.
Referenced by genfit::GblFitter::processTrackWithRep().
Member Data Documentation
bool genfit::GblFitStatus::curvatureFlag_ protected
Definition at line 73 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 73 of file GblFitStatus.h
Referenced by hasCurvature(), and setCurvature().
bool genfit::GblFitStatus::fittedWithReferenceTrack_ protected
Definition at line 70 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 70 of file GblFitStatus.h
Referenced by isFittedWithReferenceTrack(), and setIsFittedWithReferenceTrack().
int genfit::GblFitStatus::maxLocalFitParams_ protected
Definition at line 74 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 74 of file GblFitStatus.h
Referenced by getMaxLocalFitParams(), and setMaxLocalFitParams().
unsigned int genfit::GblFitStatus::numIterations_ protected
Definition at line 69 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 69 of file GblFitStatus.h
Referenced by getNumIterations(), and setNumIterations().
double genfit::GblFitStatus::trackLen_ protected
Definition at line 72 of file GblFitStatus.h.
View newest version in sPHENIX GitHub at line 72 of file GblFitStatus.h
Referenced by getTrackLen(), and setTrackLen().
The documentation for this class was generated from the following file:
GenFit/blob/master/GBL/include/GblFitStatus.h