Analysis Software: genfit::AbsMeasurement Class Reference
genfit::AbsMeasurement Class Reference abstract
Contains the measurement and covariance in raw detector coordinates.
#include <GenFit/blob/master/core/include/AbsMeasurement.h>
Public Member Functions
AbsMeasurement ()
AbsMeasurement (int nDims)
AbsMeasurement (const TVectorD &rawHitCoords, const TMatrixDSym &rawHitCov, int detId, int hitId, TrackPoint *trackPoint)
virtual ~AbsMeasurement ()
virtual AbsMeasurement * clone () const =0
Deep copy ctor for polymorphic class.
TrackPoint * getTrackPoint () const
void setTrackPoint (TrackPoint *tp)
const TVectorD & getRawHitCoords () const
const TMatrixDSym & getRawHitCov () const
TVectorD & getRawHitCoords ()
TMatrixDSym & getRawHitCov ()
int getDetId () const
int getHitId () const
virtual bool isLeftRightMeasurement () const
If the AbsMeasurement is a wire hit, the left/right resolution will be used.
virtual int getLeftRightResolution () const
unsigned int getDim () const
void setRawHitCoords (const TVectorD &coords)
void setRawHitCov (const TMatrixDSym &cov)
void setDetId (int detId)
void setHitId (int hitId)
virtual SharedPlanePtr constructPlane (const StateOnPlane &state) const =0
virtual std::vector
< genfit::MeasurementOnPlane * > constructMeasurementsOnPlane (const StateOnPlane &state) const =0
virtual const AbsHMatrix * constructHMatrix (const AbsTrackRep *) const =0
virtual void Print (const Option_t *="") const
Protected Member Functions
AbsMeasurement (const AbsMeasurement &)
protect from calling copy c'tor from outside the class. Use clone() if you want a copy!
Protected Attributes
TVectorD rawHitCoords_
TMatrixDSym rawHitCov_
int detId_
int hitId_
TrackPoint * trackPoint_
Pointer to TrackPoint where the measurement belongs to.
Private Member Functions
AbsMeasurement & operator= (const AbsMeasurement &)
protect from calling assignment operator from outside the class. Use clone() if you want a copy!
Detailed Description
Contains the measurement and covariance in raw detector coordinates.
Detector and hit ids can be used to point back to the original detector hits (clusters etc.).
Definition at line 42 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 42 of file AbsMeasurement.h
Constructor & Destructor Documentation
genfit::AbsMeasurement::AbsMeasurement () inline
Definition at line 46 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 46 of file AbsMeasurement.h
genfit::AbsMeasurement::AbsMeasurement (int nDims) inline
Definition at line 47 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 47 of file AbsMeasurement.h
genfit::AbsMeasurement::AbsMeasurement (const TVectorD & rawHitCoords, const TMatrixDSym & rawHitCov, int detId, int hitId, TrackPoint * trackPoint)
Definition at line 28 of file AbsMeasurement.cc.
View newest version in sPHENIX GitHub at line 28 of file AbsMeasurement.cc
References assert, rawHitCoords_, and rawHitCov_.
genfit::AbsMeasurement::~AbsMeasurement () virtual
Definition at line 47 of file AbsMeasurement.cc.
View newest version in sPHENIX GitHub at line 47 of file AbsMeasurement.cc
genfit::AbsMeasurement::AbsMeasurement (const AbsMeasurement & o) protected
protect from calling copy c'tor from outside the class. Use clone() if you want a copy!
Definition at line 35 of file AbsMeasurement.cc.
View newest version in sPHENIX GitHub at line 35 of file AbsMeasurement.cc
Member Function Documentation
virtual AbsMeasurement* genfit::AbsMeasurement::clone () const pure virtual
Deep copy ctor for polymorphic class.
Implemented in genfit::WireMeasurementNew, genfit::WireMeasurement, genfit::WirePointMeasurement, genfit::mySpacepointMeasurement, genfit::SpacepointMeasurement, genfit::ProlateSpacepointMeasurement, genfit::PlanarMeasurement, and genfit::FullMeasurement.
Referenced by genfit::TrackPoint::TrackPoint().
virtual const AbsHMatrix* genfit::AbsMeasurement::constructHMatrix (const AbsTrackRep *) const pure virtual
Returns a new AbsHMatrix object. Caller must take ownership.
Implemented in genfit::WireMeasurementNew, genfit::WireMeasurement, genfit::SpacepointMeasurement, genfit::WirePointMeasurement, genfit::PlanarMeasurement, and genfit::FullMeasurement.
Referenced by genfit::GblFitterInfo::getMeasurement(), genfit::GblFitterInfo::getResidual(), genfit::GblFitterInfo::Print(), and genfit::GFGbl::processTrackWithRep().
virtual std::vector<genfit::MeasurementOnPlane*> genfit::AbsMeasurement::constructMeasurementsOnPlane (const StateOnPlane & state) const pure virtual
Construct MeasurementOnPlane on plane of the state and wrt the states TrackRep. The state will usually be the prediction or reference state, and has to be defined AT the measurement. The AbsMeasurement will be projected onto the plane. It's possible to make corrections to the coordinates here (e.g. by using the state coordinates). Usually the vector will contain only one element. But in the case of e.g. a WireMeasurement, it will be 2 (left and right).
Implemented in genfit::WireMeasurementNew, genfit::WireMeasurement, genfit::SpacepointMeasurement, genfit::WirePointMeasurement, genfit::PlanarMeasurement, and genfit::FullMeasurement.
Referenced by genfit::GblFitterInfo::updateMeasurementAndPlane().
virtual SharedPlanePtr genfit::AbsMeasurement::constructPlane (const StateOnPlane & state) const pure virtual
Construct (virtual) detector plane (use state's AbsTrackRep). It's possible to make corrections to the plane here. The state should be defined somewhere near the measurement. For virtual planes, the state will be extrapolated to the POCA to point (SpacepointMeasurement) or line (WireMeasurement), and from this info the plane will be constructed.
Implemented in genfit::SpacepointMeasurement, genfit::WireMeasurementNew, genfit::WireMeasurement, genfit::WirePointMeasurement, genfit::PlanarMeasurement, genfit::ProlateSpacepointMeasurement, and genfit::FullMeasurement.
Referenced by genfit::GblFitter::constructGblInfo(), genfit::AbsTrackRep::extrapolateToMeasurement(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::GblFitterInfo::recalculateJacobian(), and genfit::GblFitter::sortHits().
int genfit::AbsMeasurement::getDetId () const inline
Definition at line 62 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 62 of file AbsMeasurement.h
References detId_.
Referenced by genfit::Track::constructTrackCand(), and genfit::GFGbl::processTrackWithRep().
unsigned int genfit::AbsMeasurement::getDim () const inline
Definition at line 69 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 69 of file AbsMeasurement.h
References rawHitCoords_.
Referenced by genfit::EventDisplay::drawEvent(), and genfit::GFGbl::processTrackWithRep().
int genfit::AbsMeasurement::getHitId () const inline
Definition at line 63 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 63 of file AbsMeasurement.h
References hitId_.
Referenced by genfit::Track::constructTrackCand(), and genfit::GFGbl::processTrackWithRep().
virtual int genfit::AbsMeasurement::getLeftRightResolution () const inline virtual
Reimplemented in genfit::WireMeasurementNew, and genfit::WireMeasurement.
Definition at line 67 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 67 of file AbsMeasurement.h
Referenced by genfit::Track::constructTrackCand().
const TVectorD& genfit::AbsMeasurement::getRawHitCoords () const inline
Definition at line 58 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 58 of file AbsMeasurement.h
References rawHitCoords_.
Referenced by genfit::WireMeasurementNew::constructMeasurementsOnPlane(), and genfit::GFGbl::processTrackWithRep().
TVectorD& genfit::AbsMeasurement::getRawHitCoords () inline
Definition at line 60 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 60 of file AbsMeasurement.h
References rawHitCoords_.
const TMatrixDSym& genfit::AbsMeasurement::getRawHitCov () const inline
Definition at line 59 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 59 of file AbsMeasurement.h
References rawHitCov_.
Referenced by genfit::WireMeasurementNew::constructMeasurementsOnPlane(), genfit::EventDisplay::drawEvent(), and genfit::GFGbl::processTrackWithRep().
TMatrixDSym& genfit::AbsMeasurement::getRawHitCov () inline
Definition at line 61 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 61 of file AbsMeasurement.h
References rawHitCov_.
TrackPoint* genfit::AbsMeasurement::getTrackPoint () const inline
Definition at line 55 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 55 of file AbsMeasurement.h
References trackPoint_.
virtual bool genfit::AbsMeasurement::isLeftRightMeasurement () const inline virtual
If the AbsMeasurement is a wire hit, the left/right resolution will be used.
Reimplemented in genfit::WireMeasurement.
Definition at line 66 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 66 of file AbsMeasurement.h
Referenced by genfit::Track::constructTrackCand(), genfit::EventDisplay::drawEvent(), and genfit::AbsKalmanFitter::getMeasurements().
AbsMeasurement & genfit::AbsMeasurement::operator= (const AbsMeasurement &) private
protect from calling assignment operator from outside the class. Use clone() if you want a copy!
Definition at line 53 of file AbsMeasurement.cc.
View newest version in sPHENIX GitHub at line 53 of file AbsMeasurement.cc
void genfit::AbsMeasurement::Print (const Option_t * = "") const virtual
Definition at line 60 of file AbsMeasurement.cc.
View newest version in sPHENIX GitHub at line 60 of file AbsMeasurement.cc
References detId_, hitId_, genfit::printOut, rawHitCoords_, and rawHitCov_.
Referenced by PHGenFitTrkFitter::ReFitTrack(), and TpcPrototypeGenFitTrkFitter::ReFitTrack().
void genfit::AbsMeasurement::setDetId (int detId) inline
Definition at line 73 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 73 of file AbsMeasurement.h
References detId_.
Referenced by genfit::WireMeasurementNew::WireMeasurementNew().
void genfit::AbsMeasurement::setHitId (int hitId) inline
Definition at line 74 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 74 of file AbsMeasurement.h
References hitId_.
Referenced by genfit::WireMeasurementNew::WireMeasurementNew().
void genfit::AbsMeasurement::setRawHitCoords (const TVectorD & coords) inline
Definition at line 71 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 71 of file AbsMeasurement.h
References rawHitCoords_.
Referenced by genfit::WireMeasurementNew::WireMeasurementNew().
void genfit::AbsMeasurement::setRawHitCov (const TMatrixDSym & cov) inline
Definition at line 72 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 72 of file AbsMeasurement.h
References rawHitCov_.
Referenced by genfit::WireMeasurementNew::WireMeasurementNew().
void genfit::AbsMeasurement::setTrackPoint (TrackPoint * tp) inline
Definition at line 56 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 56 of file AbsMeasurement.h
References trackPoint_.
Referenced by genfit::TrackPoint::addRawMeasurement(), and genfit::WireMeasurementNew::WireMeasurementNew().
Member Data Documentation
int genfit::AbsMeasurement::detId_ protected
Definition at line 115 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 115 of file AbsMeasurement.h
Referenced by getDetId(), genfit::mySpacepointMeasurement::mySpacepointMeasurement(), Print(), and setDetId().
int genfit::AbsMeasurement::hitId_ protected
Definition at line 116 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 116 of file AbsMeasurement.h
Referenced by getHitId(), genfit::mySpacepointMeasurement::mySpacepointMeasurement(), Print(), and setHitId().
TVectorD genfit::AbsMeasurement::rawHitCoords_ protected
Definition at line 113 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 113 of file AbsMeasurement.h
Referenced by AbsMeasurement(), genfit::PlanarMeasurement::constructHMatrix(), genfit::FullMeasurement::constructMeasurementsOnPlane(), genfit::PlanarMeasurement::constructMeasurementsOnPlane(), genfit::WirePointMeasurement::constructMeasurementsOnPlane(), genfit::SpacepointMeasurement::constructMeasurementsOnPlane(), genfit::WireMeasurement::constructMeasurementsOnPlane(), genfit::ProlateSpacepointMeasurement::constructPlane(), genfit::WirePointMeasurement::constructPlane(), genfit::WireMeasurement::constructPlane(), genfit::SpacepointMeasurement::constructPlane(), genfit::FullMeasurement::FullMeasurement(), getDim(), getRawHitCoords(), genfit::mySpacepointMeasurement::mySpacepointMeasurement(), genfit::PlanarMeasurement::PlanarMeasurement(), Print(), setRawHitCoords(), genfit::SpacepointMeasurement::SpacepointMeasurement(), genfit::WireMeasurement::WireMeasurement(), and genfit::WirePointMeasurement::WirePointMeasurement().
TMatrixDSym genfit::AbsMeasurement::rawHitCov_ protected
Definition at line 114 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 114 of file AbsMeasurement.h
Referenced by AbsMeasurement(), genfit::FullMeasurement::constructMeasurementsOnPlane(), genfit::PlanarMeasurement::constructMeasurementsOnPlane(), genfit::WirePointMeasurement::constructMeasurementsOnPlane(), genfit::SpacepointMeasurement::constructMeasurementsOnPlane(), genfit::WireMeasurement::constructMeasurementsOnPlane(), getRawHitCov(), genfit::SpacepointMeasurement::initG(), genfit::mySpacepointMeasurement::mySpacepointMeasurement(), Print(), and setRawHitCov().
TrackPoint* genfit::AbsMeasurement::trackPoint_ protected
Pointer to TrackPoint where the measurement belongs to.
Definition at line 119 of file AbsMeasurement.h.
View newest version in sPHENIX GitHub at line 119 of file AbsMeasurement.h
Referenced by getTrackPoint(), and setTrackPoint().
The documentation for this class was generated from the following files:
GenFit/blob/master/core/include/AbsMeasurement.h
GenFit/blob/master/core/src/AbsMeasurement.cc