Analysis Software: genfit::FitStatus Class Reference
genfit::FitStatus Class Reference
Class where important numbers and properties of a fit can be stored.
#include <GenFit/blob/master/core/include/FitStatus.h>
Public Member Functions
FitStatus ()
virtual ~FitStatus ()
virtual FitStatus * clone () const
bool isFitted () const
Has the track been fitted?
bool isFitConverged (bool inAllPoints=true) const
Did the fit converge (in all Points or only partially)?
bool isFitConvergedFully () const
bool isFitConvergedPartially () const
int getNFailedPoints () const
bool hasTrackChanged () const
Has anything in the Track been changed since the fit?
bool isTrackPruned () const
Has the track been pruned after the fit?
double getCharge () const
Get the fitted charge.
double getChi2 () const
Get chi^2 of the fit.
double getNdf () const
Get the degrees of freedom of the fit.
virtual double getPVal () const
Get the p value of the fit.
void setIsFitted (bool fitted=true)
void setIsFitConvergedFully (bool fitConverged=true)
void setIsFitConvergedPartially (bool fitConverged=true)
void setNFailedPoints (int nFailedPoints)
void setHasTrackChanged (bool trackChanged=true)
void setCharge (double charge)
PruneFlags & getPruneFlags ()
void setChi2 (const double &chi2)
void setNdf (const double &ndf)
virtual void Print (const Option_t *="") const
Protected Member Functions
ClassDef (FitStatus, 3)
Protected Attributes
bool isFitted_
has the track been fitted?
bool isFitConvergedFully_
did the fit converge with all TrackPoints?
bool isFitConvergedPartially_
did the fit converge with a subset of all TrackPoints?
int nFailedPoints_
Number of failed TrackPoints.
bool trackHasChanged_
has anything in the Track been changed since the fit? -> fit isn't valid anymore
PruneFlags pruneFlags_
Prune flags.
double charge_
fitted charge
double chi2_
double ndf_
Detailed Description
Class where important numbers and properties of a fit can be stored.
Author
Johannes Rauch (Technische Universität München, original author)
Definition at line 80 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 80 of file FitStatus.h
Constructor & Destructor Documentation
genfit::FitStatus::FitStatus () inline
Definition at line 84 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 84 of file FitStatus.h
Referenced by clone().
virtual genfit::FitStatus::~FitStatus () inline virtual
Definition at line 89 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 89 of file FitStatus.h
Member Function Documentation
genfit::FitStatus::ClassDef (FitStatus , 3) protected
virtual FitStatus* genfit::FitStatus::clone () const inline virtual
Reimplemented in genfit::GblFitStatus, and genfit::KalmanFitStatus.
Definition at line 91 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 91 of file FitStatus.h
References FitStatus().
double genfit::FitStatus::getCharge () const inline
Get the fitted charge.
Definition at line 118 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 118 of file FitStatus.h
References charge_.
Referenced by genfit::GFRaveTrackParameters::getCharge(), genfit::GFTrackToTrack(), and PHG4TrackFastSim::process_event().
double genfit::FitStatus::getChi2 () const inline
Get chi^2 of the fit.
Definition at line 120 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 120 of file FitStatus.h
References chi2_.
Referenced by PHGenFit::Track::get_chi2(), genfit::KalmanFitStatus::getBackwardChi2(), genfit::GFTrackToTrack(), genfit::KalmanFitStatus::Print(), and PHG4TrackFastSim::process_event().
double genfit::FitStatus::getNdf () const inline
Get the degrees of freedom of the fit.
Definition at line 122 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 122 of file FitStatus.h
References ndf_.
Referenced by PHGenFit::Track::get_ndf(), genfit::KalmanFitStatus::getBackwardNdf(), genfit::GFTrackToTrack(), genfit::KalmanFitStatus::Print(), and PHG4TrackFastSim::process_event().
int genfit::FitStatus::getNFailedPoints () const inline
Definition at line 112 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 112 of file FitStatus.h
References nFailedPoints_.
Referenced by genfit::DAF::processTrackWithRep().
PruneFlags& genfit::FitStatus::getPruneFlags () inline
Definition at line 137 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 137 of file FitStatus.h
References pruneFlags_.
Referenced by genfit::KalmanFitterInfo::getFittedState(), and main().
virtual double genfit::FitStatus::getPVal () const inline virtual
Get the p value of the fit.
Virtual, because the fitter may use a different probability distribution.
Definition at line 128 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 128 of file FitStatus.h
References chi2_, max, and ndf_.
Referenced by genfit::KalmanFitStatus::getBackwardPVal(), and main().
bool genfit::FitStatus::hasTrackChanged () const inline
Has anything in the Track been changed since the fit?
Definition at line 114 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 114 of file FitStatus.h
References trackHasChanged_.
bool genfit::FitStatus::isFitConverged (bool inAllPoints = true) const inline
Did the fit converge (in all Points or only partially)?
Per default, this function will only be true, if all TrackPoints (with measurements) have been used in the fit, and the fit has converged.
If one or more TrackPoints have been skipped (e.g. plane could not be constructed or extrapolation to plane failed), but the fit otherwise met the convergence criteria, isFitConverged(false) will return true.
Definition at line 105 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 105 of file FitStatus.h
References isFitConvergedFully_, and isFitConvergedPartially_.
Referenced by genfit::GFTrackToTrack(), main(), and PHGenFit::Fitter::processTrack().
bool genfit::FitStatus::isFitConvergedFully () const inline
Definition at line 110 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 110 of file FitStatus.h
References isFitConvergedFully_.
bool genfit::FitStatus::isFitConvergedPartially () const inline
Definition at line 111 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 111 of file FitStatus.h
References isFitConvergedPartially_.
bool genfit::FitStatus::isFitted () const inline
Has the track been fitted?
Definition at line 94 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 94 of file FitStatus.h
References isFitted_.
Referenced by genfit::EventDisplay::drawEvent(), genfit::AbsKalmanFitter::isTrackFitted(), and genfit::DAF::processTrackWithRep().
bool genfit::FitStatus::isTrackPruned () const inline
Has the track been pruned after the fit?
Definition at line 116 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 116 of file FitStatus.h
References genfit::PruneFlags::isPruned(), and pruneFlags_.
Referenced by genfit::KalmanFitter::processTrackPartially(), genfit::KalmanFitterRefTrack::processTrackWithRep(), and genfit::KalmanFitter::processTrackWithRep().
void genfit::FitStatus::Print (const Option_t * = "") const virtual
Reimplemented in genfit::KalmanFitStatus, and genfit::GblFitStatus.
Definition at line 88 of file FitStatus.cc.
View newest version in sPHENIX GitHub at line 88 of file FitStatus.cc
References charge_, isFitConvergedFully_, isFitConvergedPartially_, isFitted_, nFailedPoints_, genfit::PruneFlags::Print(), genfit::printOut, pruneFlags_, and trackHasChanged_.
Referenced by genfit::EventDisplay::drawEvent(), main(), and genfit::KalmanFitStatus::Print().
void genfit::FitStatus::setCharge (double charge) inline
Definition at line 135 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 135 of file FitStatus.h
References charge_.
Referenced by genfit::KalmanFitterRefTrack::processTrackWithRep(), genfit::KalmanFitter::processTrackWithRep(), genfit::GblFitter::processTrackWithRep(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
void genfit::FitStatus::setChi2 (const double & chi2) inline
Definition at line 139 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 139 of file FitStatus.h
References chi2_.
Referenced by genfit::GblFitter::processTrackWithRep(), genfit::KalmanFitStatus::setBackwardChi2(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
void genfit::FitStatus::setHasTrackChanged (bool trackChanged = true) inline
Definition at line 134 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 134 of file FitStatus.h
References trackHasChanged_.
Referenced by genfit::KalmanFitterRefTrack::processTrackWithRep().
void genfit::FitStatus::setIsFitConvergedFully (bool fitConverged = true) inline
Definition at line 131 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 131 of file FitStatus.h
References isFitConvergedFully_.
Referenced by genfit::KalmanFitterRefTrack::processTrackWithRep(), genfit::KalmanFitter::processTrackWithRep(), genfit::DAF::processTrackWithRep(), genfit::GblFitter::processTrackWithRep(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
void genfit::FitStatus::setIsFitConvergedPartially (bool fitConverged = true) inline
Definition at line 132 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 132 of file FitStatus.h
References isFitConvergedPartially_.
Referenced by genfit::KalmanFitterRefTrack::processTrackWithRep(), genfit::KalmanFitter::processTrackWithRep(), genfit::DAF::processTrackWithRep(), and genfit::GblFitter::processTrackWithRep().
void genfit::FitStatus::setIsFitted (bool fitted = true) inline
Definition at line 130 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 130 of file FitStatus.h
References isFitted_.
Referenced by genfit::KalmanFitterRefTrack::processTrackWithRep(), genfit::KalmanFitter::processTrackWithRep(), genfit::DAF::processTrackWithRep(), genfit::GblFitter::processTrackWithRep(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
void genfit::FitStatus::setNdf (const double & ndf) inline
Definition at line 140 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 140 of file FitStatus.h
References ndf_.
Referenced by genfit::GblFitter::processTrackWithRep(), genfit::KalmanFitStatus::setBackwardNdf(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
void genfit::FitStatus::setNFailedPoints (int nFailedPoints) inline
Definition at line 133 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 133 of file FitStatus.h
References nFailedPoints_.
Referenced by genfit::KalmanFitterRefTrack::processTrackWithRep(), genfit::KalmanFitter::processTrackWithRep(), and genfit::GblFitter::processTrackWithRep().
Member Data Documentation
double genfit::FitStatus::charge_ protected
fitted charge
Definition at line 159 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 159 of file FitStatus.h
Referenced by getCharge(), Print(), and setCharge().
double genfit::FitStatus::chi2_ protected
These are provided for the sake of the fitter, and their interpretation may vary. For the Kalman-derived fitters in particular, this corresponds to the backwards fit.
Definition at line 163 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 163 of file FitStatus.h
Referenced by getChi2(), getPVal(), and setChi2().
bool genfit::FitStatus::isFitConvergedFully_ protected
did the fit converge with all TrackPoints?
Definition at line 149 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 149 of file FitStatus.h
Referenced by isFitConverged(), isFitConvergedFully(), Print(), and setIsFitConvergedFully().
bool genfit::FitStatus::isFitConvergedPartially_ protected
did the fit converge with a subset of all TrackPoints?
Definition at line 151 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 151 of file FitStatus.h
Referenced by isFitConverged(), isFitConvergedPartially(), Print(), and setIsFitConvergedPartially().
bool genfit::FitStatus::isFitted_ protected
has the track been fitted?
Definition at line 147 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 147 of file FitStatus.h
Referenced by isFitted(), genfit::KalmanFitStatus::Print(), Print(), and setIsFitted().
double genfit::FitStatus::ndf_ protected
Definition at line 164 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 164 of file FitStatus.h
Referenced by getNdf(), getPVal(), and setNdf().
int genfit::FitStatus::nFailedPoints_ protected
Number of failed TrackPoints.
Definition at line 153 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 153 of file FitStatus.h
Referenced by getNFailedPoints(), Print(), and setNFailedPoints().
PruneFlags genfit::FitStatus::pruneFlags_ protected
Prune flags.
Definition at line 157 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 157 of file FitStatus.h
Referenced by getPruneFlags(), isTrackPruned(), and Print().
bool genfit::FitStatus::trackHasChanged_ protected
has anything in the Track been changed since the fit? -> fit isn't valid anymore
Definition at line 155 of file FitStatus.h.
View newest version in sPHENIX GitHub at line 155 of file FitStatus.h
Referenced by hasTrackChanged(), Print(), and setHasTrackChanged().
The documentation for this class was generated from the following files:
GenFit/blob/master/core/include/FitStatus.h
GenFit/blob/master/core/src/FitStatus.cc